### ISSUE TITLE
Features list and tags 

### ISSUE THREAD

**Issue by erigilg** [hackforla/food-oasis#1002]
### Overview
Make a glossary of all the product features of food oasis to then use those to organize the issues in the project board with feature labels. 

### Action Items

- [x] Make a list in a spreadsheet or document of all the product features of food oasis (food seeker side / food pantry side).
- [x] Review the list with other team member of FOLA
- [x] Write the definitions of the features 
- [x] Get it reviewed by a FOLA team member 
- [x] Use that list to label the issues in the project board. 

### Resources/Instructions
Add the spreadsheet or document link here.

**Comment by gigicobos** [comment]
@erigilg I're created an initial list [FOLA Features](https://docs.google.com/spreadsheets/d/1U-CnqTsqKGwPWWLs5oZET6mZD7H6spTr9DUDb1O6sO4/edit?usp=sharing). 
Please let me know if it looks ok.
