### ISSUE TITLE
Create complete site map of current FOLA website, showing screens for all user roles.

### ISSUE THREAD

**Issue by fancyham** [hackforla/food-oasis#1016]
### Overview

We could really use a comprehensive map of the website so that team members and collaborators can quickly see the structure and scope of the entire FOLA web app for both the public food-seeker interface (which everyone sees), as well as the private database administrator / data entry volunteer interface (which most don’t see).

We also need to show how the site works for different roles as not all pages or features are available to everyone.  

So this site map can allow all team members to see screens that they can’t normally see.

This site map / audit is essential to being able to understand what we currently have and to plan for the future.  

It will eventually be included in the onboarding documents.

### Goal

Site map that makes site easy to understand user journeys, with enough detail so that people can envision how the site works and looks.

Map will be used by designers, product managers, programmer for reference when discussing issues, projects, improvements.  So screenshots will be very helpful.  

Screenshots and user journey flows may also be copied out to be used in other documents and issues.

Because the site evolves, please put a date and your name on the site map (to take some credit, too!), or create a change log.

### Action Items

- [x] Create a comprehensive site map / audit of existing pages
- [x] Show how some pages/screens are available based on role (may need to get permissions, perhaps from @entrotech)   Highlight logic, if possible.
   - [x] Food Seeker
   - [x] Administrator
   - [x] Data validation volunteer
- [x] Stretch goal: Include screenshots of the pages (can be visible on extreme zoom-in) as reference.
- [ ] Stretch goal: Show separate user journeys (including off-line actions), perhaps as flowcharts.
- [x] Stretch goal: Highlight usability issues, and create issues about them in github.
- [x] Put date of site map audit on the document itself so that we know the date of the ‘snapshot’.

This can be done in stages. 

I suggest doing this in the FOLA Figma document (link below), with the side-goal of exporting to a big PDF in the future for easy reference.

Figma may allow for pasting screenshots and shrinking them to thumbnail size for placement on the map, but can be zoomed in for quick reference.

This is not meant to be a page-level logic breakout, but that can be a separate part of the map if so desired.

### Resources/Instructions
[Figma - Food Oasis Design System document](https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/Fola-Design-System?node-id=2935%3A0)

Every site map is different depending on what its of and how it’s used so feel free to ask here for suggestions, details, or examples.

**Comment by fancyham** [comment]
From @Benbaillou from Slack :
Hi Bryan - great job! I had a look at it and here are comments

**General Questions**
What is the Stakeholder Experience account?
Does LAWorks use the admin interface?

**Comment on red & green questions**
**Data Entry Volunteer Experience**
Tooltips
Problem identified with Touch Only devices: when scrolling with fingers it is easy to make changes by mistake on Organization settings => adding a tooltip could amplify this problem as user will scroll for instructions.

**Admin Expérience**
 => Criteria button => after 2+ attempts, the screen appeared - Figma - comment 55
 => Listing per alphabetical order and per category? - Figma - comment 56
=> [Export] items to a CSV (some fields don’t export well like Hours... that would be nice to fix => bug confirmed on my side - Figma - comment 57 

**Verifications**
 => [Save progress] Saves progress (otherwise not saved?) => Volunteers’s feedback - they asked for a dialog to confirm - Figma - comment 58
=> Others - agreed on checking what each button does
[Reassign] shows assignment dialogue 
[Needs Verification] does ?? 
[Request changes] does ?? [Approve] ... approves?? 
[Delete]... shows dialog to confirm delete?? =>=> Volunteers’s feedback - they asked for a dialog to confirm - Figma - comment 58

**Comment by fancyham** [comment]
Latest version with new screens/features added as of 2011-11-15

https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/Fola-Design-System?node-id=3598%3A89

PDF:
[2011-11-15 Food Oasis Volunteer and Admin UI Site Map.pdf](https://github.com/hackforla/food-oasis/files/7542896/2011-11-15.Food.Oasis.Volunteer.and.Admin.UI.Site.Map.pdf)
53

**Comment by fancyham** [comment]
Latest version adds Security Roles and what screens can be accessed via what role

https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/Fola-Design-System?node-id=3598%3A8953

**Comment by staceyrebekahscott** [comment]
@fancyham Can you provide a breakdown of your status on this issue:
- Current activity?
- Blockers?
- How close to completion?

**Comment by fancyham** [comment]
I’m about 90% done — the link above is the latest version.  I hope to complete it in the next week or so.

**Comment by staceyrebekahscott** [comment]
@fancyham Checking in on progress- is this ready for a PM review?

**Comment by fancyham** [comment]
Nope, not yet

**Comment by fancyham** [comment]
Link to PDF of Site Map (overview, public food-seeker site, private volunteer site)
https://drive.google.com/file/d/1-41kc0SY8AZjo8Qyg_UC5PFPYYP5uw9r/view?usp=sharing

Live link to site map in Figma is: 
https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/FOLA-Design-System?node-id=3940%3A8802

While reviewing the site, I also discovered that we have responsive page layouts with odd breakpoints?
Issue created to standardize them:
- #1354

**Comment by fancyham** [comment]
@staceyrebekahscott Did you want to review this before I close it out?

**Comment by staceyrebekahscott** [comment]
Thanks @fancyham, This looks great! I'll share it with the other PMs. Go ahead and close out the issue.

**Comment by fancyham** [comment]
Done!
