### ISSUE TITLE
Add video session recording to the volunteer and admin interface to check usability

### ISSUE THREAD

**Issue by fancyham** [hackforla/food-oasis#1017]
### Overview

Try adding session recording code to the volunteer and admin interface so that we can learn more about our users.

This MAY be useful to identify usability problems that people are having, as well as 'golden paths' through the UI.

This would potentially be used by user researchers, UX designers, product owners to better understand user behavior.

If these recordings end up being un-helpful, please remove the code.

Please make it so that 
- it is only turned on when needed, and with 
- a privacy notice to the user so that they know their keystrokes and mouse clicks are being recorded, along with the 
- ability to opt-out.

### Action Items

- [ ] Add session recording tools to the volunteer and admin pages
   - [ ] Can be turned on and off (default is off)
   - [ ] Privacy notice to user when active (perhaps at log-in?)
   - [ ] (optional) Ability to opt-out
- [ ] Store recording service's account log-in securely so only authorized project members will see it.
- [ ] If recordings are not helpful for further developing this project, make a note in github, and remove code from project to minimize risk to users.

**Comment by fancyham** [comment]
@pageignited, are we using hotjar.com now?  If so, is it something we can access results for?

**Comment by staceyrebekahscott** [comment]
Closing this issue as outdated. 

This issue was created in Aug 2021 but no work seems to have been done. The current UX researchers should develop their own process for testing usability.
