### ISSUE TITLE
Document Food Oasis team meeting times and who Must/Should/Can attend

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/food-oasis#1034]
### Overview 
The Civic Tech Jobs team needs accurate meeting time information from the Food Oasis team to help match your project with available volunteers.

### Action Items
- [x] provide details about the each meeting in a comment by using a copy of the check boxes below
- [x] post a link to this issue on https://github.com/hackforla/CivicTechJobs/issues/35 in a comment letting the civic tech jobs team know you are done.
```
  - [ ] day
   - [ ] start_time
      - [ ] AM
      - [ ] PM
   - [ ] duration_in_min
   - [ ] name_of_meeting
   - [ ] who_must_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend_lead
      - [ ] backend_lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
   - [ ] who_should_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend_lead
      - [ ] backend_lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
   - [ ] who_can_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend_lead
      - [ ] backend_lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
```
### Resources
- URL of the project's homepage on the HfLA website:  https://www.hackforla.org/projects/food-oasis
- Times that VRMS shows for your meetings: 
Tue 6:30 pm, 1 hour, Development
Thu 6:00 pm, 1 hour, Team
Mon 3:00 pm, 1 hour, Management

**Comment by gigicobos** [comment]
This meeting is no longer happening --> Mon 3:00 pm, 1 hour, Management

**Comment by gigicobos** [comment]
- [ ] day Tuesday
   - [ ] start_time 6:30 
      - [ ] AM
      - [ ] PM
   - [ ] duration_in_min 60
   - [ ] name_of_meeting development
   - [ ] who_must_attend 
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
   - [ ] who_should_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
   - [ ] who_can_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain

**Comment by gigicobos** [comment]
- [ ] day Thursday
   - [ ] start_time 6:00
      - [ ] AM
      - [ ] PM
   - [ ] duration_in_min 60
   - [ ] name_of_meeting Team
   - [ ] who_must_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend_lead
      - [ ] backend_lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
   - [ ] who_should_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend_lead
      - [ ] backend_lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
   - [ ] who_can_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend_lead
      - [ ] backend_lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
