### ISSUE TITLE
Migrate to version 5 of Material-UI

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#1045]
### Overview
There is a major upgrade of the Material-UI component library from version 4.* to 5.*. This is a BIG change involving re-naming the component NPM packages, changes to the theming structure, moving to emotion or styled components vs JSS for styling, moving some components out of the "lab" package and into the core.

### Action Items
- [ ] Study the below materials.
- [ ] Develop a migration plan
- [ ] Break up into incremental development issues.

### Resources/Instructions
https://mui.com/guides/migration-v4/
https://mui.com/blog/mui-core-v5/

**Comment by staceyrebekahscott** [comment]
@entrotech Checking in on the priority of this issue as it was opened in Oct 2021 and no movement has been made. Given the size of the issue, and current priorities discussed at the last team meeting, can this be moved to the Icebox for reassessment after the Impact Sprints?

**Comment by staceyrebekahscott** [comment]
None of the current milestone fit what this issue addresses. Once new milestones have been approved, will update accordingly.

**Comment by staceyrebekahscott** [comment]
Closing this issue as stale. Issue #1239 is more current.
