### ISSUE TITLE
Look into using Food Oasis Widget on Wordpress Sites

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#1057]
### Overview
Issue #962  Implemented a Food Oasis widget for embedding Food Oasis into third-party HTML web sites.  According to Bonnie, most of the Neighborhood Councils use Wordpress for their web sites, so we should probably create a Wordpress plugin for embedding Food Oasis in their sites for them.

### Action Items
- [ ] Determine options for including Food Oasis into a Wordpress site:
  - [ ] Maybe use an iframe plug-in
  - [ ] Possibly create a custom plugin for Food Oasis
- [ ] See if we can tailor the filtering for a web site based on, for example, neighborhood council, status, zip code, etc.

### Resources/Instructions
https://github.com/hackforla/food-oasis/wiki/Embedding-Food-Oasis-in-Your-Web-Site

**Comment by fancyham** [comment]
Bonnie suggested that once we get something up and running that we're happy with, she has three LA neighborhood councils that may be good pilot partners.

**Comment by entrotech** [comment]
This was completed and deployed to the Hack for LA and Food Cycle sites a while ago.
