### ISSUE TITLE
Fix Send Suggestion Feature

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#1069]
### Overview
If you attempt to Send a Suggestion (or Suggest a new Listing), when you Send the suggestion it fails with an HTTP 500 error.

### Action Items
- [ ] Debug and fix.

**Comment by entrotech** [comment]
@hanapotski I this @gigicobos created a wireframe for the Suggestion Admin page at one time - we should review to see if the implemented page matches, and consider creating a new feature for the new iteration on this feature.

**Comment by gigicobos** [comment]
@hanapotski Attached the wireframe for the Suggestions admin page. This wireframe includes the information we will need but as we discussed your layout looked cleaner and simpler. I do not have a the screenshot of the layout you shared with me. Hope this helps. Let me know if you have any questions.

[Food Oasis Suggestions Issue # 1069.pdf](https://github.com/hackforla/food-oasis/files/7480238/Food.Oasis.Suggestions.Issue.1069.pdf)

**Comment by entrotech** [comment]
I worked on this a bit to get it functioning. I'd like to give this issue back to @hanapotski  and @gigicobos to finalize the appearance and decide it we want to do another iteration on the feature. Here is what it looks like now:

![image](https://user-images.githubusercontent.com/9939032/140617160-0fd2f871-fb7e-408b-bf88-14e6a21c1757.png)
 A few things to think about:
The "Suggestions" com from two places, the Suggest New Listing feature on the Main Menu, which allows users to enter a bunch of details. If the suggested new listing is a good one, then the admin would want to create a new listing from the suggestions, so it might be good to have a button that the admin could press to start creating a new listing by going to the OrganizationEdit Screen, with the matching fields from the suggestion filled in.  The admin could then finish the listing or assign it to a volunteer to verify.
The other place suggestions come from is the Send Correction button on the Organization Detail panel.  In this case, if the admin decides the suggestion is good, would be to maybe attach the suggestion to the Organization Record in a new field for display in that Organization's Edit form, so the admin (or an assigned volunteer can see the suggestion and manually merge it with the existing information, save the changes, and "Close" the suggestion.
On the Suggestion Admin screen, it might be a good idea to show whether the suggestion is for a new listing or a correction to an existing listing..

**Comment by gigicobos** [comment]
@hanapotski @entrotech will get the feedback from Jordan (and the other admin volunteers) about the features for next iteration. I will have comments / revised mockup after their feedback. 
@entrotech would it be too much if we make sure the next iteration also includes the changes for issue #996 where pantries submit suggestions as well?
