### ISSUE TITLE
Visually indicate when user is on the dev site

### ISSUE THREAD

**Issue by fancyham** [hackforla/food-oasis#1096]
### Overview
Add some visual indicator to make it more obvious when a user / developer is working the dev site.  This was, it’s less likely to make the mistake of thinking that one is working on the prod server when one is working on the dev server.

One way to do this would be to change the color of the header or put some text at the top of the page.

### Action Items
- [x] Mockups for how this might look (or pull examples from other sites)
- [ ] Build it
- [ ] Stretch goal: Automatically include the current build number / release version in the indicator

### References

Something like:
<img src=https://user-images.githubusercontent.com/3376957/142058330-1c65194a-e4a0-49d9-90d0-cbfa519c7063.jpg height=400>
<img src=https://user-images.githubusercontent.com/3376957/142058338-1e3f24ce-161c-4940-890c-f8b1665ca5aa.jpg height=400>
<img src=https://user-images.githubusercontent.com/3376957/142058344-6a5bd1e1-fe4c-4865-abb9-537d1543dc9c.jpg height=400>

**Comment by staceyrebekahscott** [comment]
@entrotech @fancyham Moving this to the Icebox. No movement has been made on this since the issue was created in Nov 2021. Has this been identified as a major issue for the Devs?

**Comment by staceyrebekahscott** [comment]
There is currently no milestone that matches this type of issue. Once milestones are revised, issues will be reassessed.

**Comment by fancyham** [comment]
This is a usability thing (for the internal FOLA team).  

Created a new milestone to track FOLA internal team tools and usability.  This will be useful for analytics as well.
https://github.com/hackforla/food-oasis/milestone/17
