### ISSUE TITLE
Bug: Very tall toolbar when viewed on laptop

### ISSUE THREAD

**Issue by fancyham** [hackforla/food-oasis#1102]
### Overview
On iOS and Mac in Safari, the toolbar is sometimes very tall and usually taller than necessary.

This seems to be a recent change in the past month?

### How to replicate:
1. Go to foodoasis.la
2. Load map
3. Note extra-tall vertical toolbars:
<img width="1366" alt="Screenshot 2021-11-19 at 11 40 30 AM" src="https://user-images.githubusercontent.com/3376957/142695034-bbca4211-d266-4ed0-b8f5-724dae57728d.png">

### Platform
- iOS 15.1 iPad Pro 12.9 portrait orientation
- Mac Safari 15.1

### Action Items
- [ ] Reduce toolbar height to previous height so that it doesn’t take up more vertical space than necessary.

**Comment by fancyham** [comment]
Generally looks good!

In Firefox, the Food Oasis logo is missing?

Also, there now seems to be a blank footer at the bottom, (a quite tall one on Mac Safari) which I think shouldn’t be there?

![Screen Shot 2022-03-24 at 8 22 09 PM](https://user-images.githubusercontent.com/3376957/160048230-bfe9e432-b610-441d-b6d6-44a32c7c2873.jpg)

**Comment by sei1122** [comment]
I don't see the logo on Firefox either. 
The testing site, toolbar space is removed but maybe adding a bit of spacing would be nice.
Live site, map, and content cover till the end of the screen but test site has some spacing. 

<img width="1490" alt="Screen Shot 2022-03-25 at 10 40 27 AM" src="https://user-images.githubusercontent.com/19811032/160173384-022c1c7b-c703-452d-8fc3-8f226f0f8dc3.png">

**Comment by ryu-jieun** [comment]
Agree with @fancyham & @sei1122. There is a blank footer at the bottom both on the testing & public sites.

**Comment by fancyham** [comment]
Seems to be fixed
