### ISSUE TITLE
Add Search for specific name of organization in address field.

### ISSUE THREAD

**Issue by fancyham** [hackforla/food-oasis#1112]
### Overview
Potential feature:

It could be nice to be able to search for a specific pantry or meal program by name.  Currently that doesn’t seem to be possible.

Why?  If the food seeker knows the name of the org but doesn’t know where it’s located, it’s likely that the food seeker will enter the name into the address field because it looks like a search field.

Entering text there already displays an auto-complete showing business names (like Walmart) — might it be possible to include addresses and locations of pantries and meal programs in the auto-complete as well, as if they were businesses?

### Action Items

- [ ] Mockup
- [ ] Evaluate feasibility
- [ ] If not too hard, implement

### How it is now:

![Screen Shot 2021-11-22 at 4 13 57 PM](https://user-images.githubusercontent.com/3376957/142962183-9f1c2503-c3c2-4d09-befa-fb0887914d04.jpg)

### Mockup: (note the first autocomplete items)

![Screen Shot 2021-11-22 at 4 13 57 PM showing org name in auto-complete](https://user-images.githubusercontent.com/3376957/142962742-55dc79a3-4649-4592-9728-dcdada75eab9.jpg)

**Comment by entrotech** [comment]
This is a duplicate of issue #1115. See my comments there.

**Comment by Benbaillou** [comment]
@fancyham can we close this issue?

**Comment by fancyham** [comment]
Duplicate of #1115

**Comment by staceyrebekahscott** [comment]
@fancyham I am confused by this workflow- you closed it in Nov, but then it was moved to Prioritized Backlog then Icebox, but it remains closed. Is this something that still needs to be addressed, please add details as to your reasoning. 

Moving to Questions/ In Review.

**Comment by staceyrebekahscott** [comment]
@fancyham Following up on my comment from 08/12- please clarify if something still needs to be addressed on this issue.

**Comment by staceyrebekahscott** [comment]
Upon closer review, this issue reads as similar to issue #1115 , which is in the Prioritized Backlog. 

Moving this issue to Done column.

**Comment by fancyham** [comment]
This is a duplicate of #1115 so it should be closed as a duplicate, if that’s possible.
