### ISSUE TITLE
Perform a heuristic evaluation of the food seeker and volunteer desktop & mobile flows

### ISSUE THREAD

**Issue by gigicobos** [hackforla/food-oasis#1113]
### Overview
We need to perform a heuristic evaluation of the food seeker and volunteer user flow on both desktop & mobile devices.

### Action Items
- [x] Perform heuristic evaluation of food seeker desktop site - document observations
- [x] Perform heuristic evaluation of food seeker mobile site - document observations
- [x] Perform heuristic evaluation of volunteer desktop site - document observations
- [x] Perform heuristic evaluation of volunteer mobile site - document observations
- [x] Save document in the shared GDrive folder
- [x]  Merge and synthesize with Jieun's evaluations
- [x] Create presentation
- [x] Walk team through observations

### Resources/Instructions
Website: https://devla.foodoasis.net/
Shared document: https://docs.google.com/spreadsheets/d/1jQSoQ2X7P9IzUBEhlti4w9m2_FE2jT-9/edit#gid=204332786

**Comment by LIlinit** [comment]
I can't seem to drag this card into the "Actively Working" column. So I'll make a note here that I am actively working on this.

**Comment by LIlinit** [comment]
My heuristic evaluation has been saved to the shared drive: [GigiP_Heuristic Evaluation](https://drive.google.com/drive/u/2/folders/1dFiNdh-ZvmkmkGp4UKNhGKjbUrM2WNG_)

NOTE: this document is NOT the final product -- it will be merged with Jieun's evaluation to also provide a synthesized report next week.
