### ISSUE TITLE
Bug: stacking in the tab organization list-map view

### ISSUE THREAD

**Issue by Benbaillou** [hackforla/food-oasis#1116]
### **Overview**
Organization listings overlap each other in search results and appear stacked after landing on the map page or searching an organisation in the bar - recurring bugs

### Action Items

- [x] Fix

###  Screenshot
Device - Macbook Pro iOS 10.15.7 Catalina
Browser - Google Chrome

![Capture d’écran 2021-11-23 à 16 29 28](https://user-images.githubusercontent.com/91577998/143069201-ebb2f5f7-d17e-4158-855e-950024078909.png)
![Capture d’écran 2021-12-06 à 15 30 26](https://user-images.githubusercontent.com/91577998/144874604-9e9b3a04-ee64-407c-87db-3a48894a87c3.png)

**Comment by Benbaillou** [comment]
@entrotech - Hi John. I found a recurring stacking bug on the mapping interface. Let me know if you need more details.

**Comment by fancyham** [comment]
Looks good — haven’t seen the overlap during today’s QA testing of other issues.

**Comment by ryu-jieun** [comment]
looks good both on the computer and mobile!
