### ISSUE TITLE
Highlight pin when cursor hovers over a listing in organization list

### ISSUE THREAD

**Issue by fancyham** [hackforla/food-oasis#1120]
### Overview

This is a ’nice to have’ feature.

Highlight the location’s pin on the map when the user hovers (with cursor) over each listing in the organizations list.

Why?  Because this would help users browse organizations more efficiently.

This would only happen when viewing the list of organizations.

The ’selected’ pin from… ( #923 ) would be the pin to use as a highlight.

### Action Items

- [ ] Mockup (if needed)
- [ ] Implement 
- [ ] QA: Test that there are no foreseen issues
  - [ ] Please test on smaller screens, such as when the map isn’t visible (on medium and narrow screens).  This would be the case of small tablets what have mouse support (e.g. iPad mini) and embedded in iFrames on web pages.
- [ ] Stretch goal: 
    - [ ] Show organization name when hovering over pins on the map

### Resources/Instructions

Example from Yelp results

https://user-images.githubusercontent.com/3376957/143113967-22c47fe3-d6d9-4fa0-bf6c-f8af0900c868.mp4

- #1711 supersedes this

**Comment by fancyham** [comment]
Good question

When the user selects a location they enter organization-detail view.  And in that view, if the user hovers over other pins on the map with the cursor, I think nothing should happen. No pin highlighting — so basically like it is now. 

So this would be a change for the list-and-map view only.

**Comment by staceyrebekahscott** [comment]
Moved to Icebox, as this is a "nice to have" and issues with more priority should be addressed and completed before this is considered.

**Comment by fancyham** [comment]
Being addressed in this big UI design update
- #1874

**Comment by qiqicodes** [comment]
@fancyham can we close this as obsolete?

**Comment by fancyham** [comment]
I’d say 
- #1711 
supersedes this, and this one can be closed as long as #1711 stays around.

**Comment by fancyham** [comment]
- #1711 
is a duplicate of this and goes into more detail, so closing this one.
