### ISSUE TITLE
Hiring a new PM

### ISSUE THREAD

**Issue by Benbaillou** [hackforla/food-oasis#1126]
### Overview
A new PM will need to be hired to cover the following scope:

- Work with targeted organisations to embed FOLA on their website
- Integrate the management of Data Entry Volunteers (training, session, recruitment) under Hack For LA

### Action Items

- [x] Write a job desc
- [x] Make it approve by Bonnie and Leads
- [x] Post it

### Resources/Instructions
N/A

**Comment by Benbaillou** [comment]
@gigicobos 

Bonnie is totally fine for us to hire a new PM and agrees with Bryan and John's idea that he/she should be focus in growing the partnerships:
Embed our website on targeted organisations' 
Onboard the management of Data Entry Volunteers (training, session, recruitment) under Hack For LA

Her only requirement is to have someone living as close as possible to California, because the future PM will need to work with Bonnie on a regular basis to make connections with organisations.

**Comment by gigicobos** [comment]
**Project Name:** Food Oasis LA

**Volunteer Opportunity:** We are looking for a Product Manager preferably based in California with experience and/or connections in the Food Rescue Ecosystem. As a PM you'd be working on targeting organizations to embed our website and 
onboarding the management of Data Entry Volunteers (training, session, recruitment) under Hack For LA.

You will be joining the team who also has a Product Manager who is working on the strategy, vision and roadmap as well as final deliverables. 

**Duration:** ongoing / 10h week min

**Weekly Meeting**
Must attend: Team meeting - Thursdays 6:00pm- 7:00pm PST

**Slack channel:** #fola
Slack name of person to contact in the channel: Ben Baillou / Gigi Cobos
**Read more about the project:** https://github.com/hackforla/food-oasis/wiki

**Comment by Benbaillou** [comment]
@gigicobos - are we ok to post the job desc?

**Comment by gigicobos** [comment]
@Benbaillou completed already.
