### ISSUE TITLE
Bug - 'open' and 'Closing in x mins' tags are linked to device time setting rather than Los Angeles time zone

### ISSUE THREAD

**Issue by Benbaillou** [hackforla/food-oasis#1132]
### Overview
The 'open' and 'Closing in x mins' tags on the detail panel for each organisation are linked to the device time setting rather than to the Los Angeles time zone.

example:

- Computer in London time zone: + 8 hours PST
- London time: 5.24 pm
- LA time: 9.24 am
- Time set for tags: 5.24 pm rather than 9.24 am
![Capture d’écran 2021-12-08 à 17 26 41](https://user-images.githubusercontent.com/91577998/145421211-999cda69-fd00-4006-b70a-7e816c6832e8.png)

### Action Items

- [ ] To fix

**Comment by fancyham** [comment]
The changes worked for me.  I browsed with my computer set to to Hawaii time (3 hour difference from LA) and the warnings were correctly using LA time. (I’m a designer)

**Comment by sei1122** [comment]
Looks good to me.

**Comment by ryu-jieun** [comment]
All the opening hours are set in LA time.
