### ISSUE TITLE
Add history for verification notes and for organization edits

### ISSUE THREAD

**Issue by gigicobos** [hackforla/food-oasis#1139]
### Overview

Data entry volunteers and admins, refer to the "Verification Notes" field in the "Organizationedit" page to:
  - Review the notes from past the data entry volunteers who updated the organization to get a background of previous calls/edits.
  - Record notes after an organization is updated/verified.

 ?? question — How important are these to the administrator or database users? (so we can prioritize)
 
**Current issues:**
  - It is difficult to review the notes as there are too many records and the field is relatively small.
  - There is a risk of losing historical notes on the organization as any volunteer could edit or delete these notes because the field is editable.
 
**Proposed Changes:**
  - Redesign "Verification Notes", similar to a chat window where data entry volunteers will write their notes and click "Submit" to record their notes. This action will create a timestamped log.
  - Create a new tab on the "Organizationedit" page called "Status Change" to show the historical changes in an organization. This page will have the logs for "Verification Notes", "Changes in fields", "Changes of status" and also records from "Suggestions #1131 ".

### Action Items

- [ ] Create a prototype for the proposed changes
- [ ] Review prototype with Design and Engineering leads
- [ ] User test prototype with admin and data entry volunteers (new and experienced)
- [ ] Update prototype
- [ ] Change "Role" label to UX for design
- [ ] Change "Role" label to front end / back end
- [ ] QA devla
- [ ] Present changes to Volunteer Onboarding lead
- [ ] Deply to production
- [ ] Edit onboarding presentation
- [ ] Review any final feedback / bugs

### Resources/Instructions
[P1: Suggestions board - 12/02/21](https://github.com/hackforla/food-oasis/files/7646659/FOLA.Issue.1069.pdf)

### Related Issues
#1131 --> "Suggestions" logs will be displayed on the "Status Change" tab

**Comment by fancyham** [comment]
?? question — How important are these to the administrator or database users? (so we can prioritize)

**Comment by itserindean** [comment]
This seems very low priority and unnecessary work so closing as not planned
addressing the issues:

> It is difficult to review the notes as there are too many records and the field is relatively small.
I haven't found this to be an issue in my 6 months as an admin.

>There is a risk of losing historical notes on the organization as any volunteer could edit or delete these notes because the field is editable.
This is a risk but not one I've seen play out.
