### ISSUE TITLE
map: Show geographic regions: Development

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/food-oasis#1140]
### Dependency
- https://github.com/hackforla/food-oasis/issues/1129

### Overview
We need to have a food oasis interface that allows for searching by district boundary types so that we can get placement on official local sites such as Neighborhood councils, LA County Supervisors, LA City Council people, etc.

### Details
- Desired outcome: When user enters a geographic term like neighborhood or zip code (or one is specified in the URL), center the map on that location and display a highlighted boundary on the map so that the user can orient themselves to a familiar area, and zoom out to the level where the entire region is in-view on the map.
- URL: currently when you search a location the URL does not show that location.  For instance, searching Venice, CA will get you to the URL https://foodoasis.la/organizations (so we doing that map location behind the scenes).  However, we are adding arguments to the URL to allow people to bookmark food providers e.g., https://foodoasis.la/organizations?id=5221&org=st._joseph_center_-_bread_and_roses_cafe_-_rose_avenue .  We need to do the same for geographic regions, so it might look something like this: https://foodoasis.la/organizations?id=NC-Wilshire-Center-Koreatown or some other url arguments.  But it does need to be bookmarkable.

### Action Items
- [x] Talk to JD to find out size and role and if this needs multiple issues, etc.
- [x] See mockups from design #1129
- [x] Identify what will need to change in the way we provide the URL (see notes in details)
- [x] Discuss with Tech lead
- [x] Define course of action
- [x] If issue is too big and can be broken down into multiple issues, create them.
- [x] Implement #1165

### Resources/Instructions

- LA Neighborhood council pages: https://empowerla.org/councils/
- Example neighborhood council — Del Rey: https://empowerla.org/drnc/
- HfLA Data Science issue for district types https://github.com/hackforla/data-science/issues/118
- https://wcknc.la/boundary/

<details>
<summary>Example</summary>

Please note that when searching on google for koreatown, you are searching for a name of a location, not the NC boundaries. 
https://www.google.com/maps/place/Koreatown,+Los+Angeles,+CA  We are providing this example so you know generally what we are suggesting for the way it would work.  Here is the actual boundaries of this NC https://wcknc.la/boundary/

![Screen Shot 2021-11-29 at 5 59 45 PM](https://user-images.githubusercontent.com/3376957/143983461-f9bab0bb-57bf-4559-a980-9d15ba9c7a2f.jpg)
</details>

**Comment by fancyham** [comment]
- Development issue is #1165

**Comment by fancyham** [comment]
I believe this is completed with 
- #1129
- #1165
