### ISSUE TITLE
Create a mock-up of the Organization Edit Form

### ISSUE THREAD

**Issue by gigicobos** [hackforla/food-oasis#1141]
### Dependencies
#1142
#1143  

### Overview
As part of our effort to improve the design of the Organization Edit Form, we need to create an initial mock-up with the fields in the form and suggestions from the Heuristic Evaluation form.

### Action Items

- [ ] Create wireframes based on results from research #1143 
- [ ] Meeting with Design and Research to review wireframes
- [ ] Design new organization edit form
- [ ] Present design to the team and update changes
- [ ] Test with volunteers
- [ ] Design a final mockup

### Resources/Instructions
[Heuristic Evaluation to features - #1114 #1113](https://docs.google.com/spreadsheets/d/1UCoj5ecVQhOBAPNFvzOyySSeJFNtJ34Bx6Ti2cnLma0/edit#gid=983594560)
[Volunteer Feedback](https://docs.google.com/spreadsheets/d/1m2pKb5ZNvx1gYFKYP_ydG7ikdC0cg71VUPSUQn9J0Ik/edit#gid=388074418)
[Volunteer Dashboard](https://www.figma.com/file/KZbof1x83FOvw4Jfc99EIf/Food-Oasis-Dashboards?node-id=416%3A335) (Listing (Draft 2 - by Jordan Romanoff))
[Organization Edit Form](https://www.figma.com/file/9hPmNSsyaH2VMGNz5mffmI/Organization-Edit-Form?node-id=0%3A1)

### Related Issues
#320 
#1148

**Comment by Benbaillou** [comment]
I added in the resources the volunteer feedback we received from a survey last Q3/Q4 2021.
You can find interesting comments in the following tabs:
- Volunteer Sessions Feedback
- Volunteer Survey Form V1 - green cells

**Comment by gigicobos** [comment]
**Meeting 01/11/22**

_Attendees: Ning, Bryan, Ben, Gigi C._

Changes: 
- We updated the order of action items on this issue to complete #1143 before creating a design.
- Created issue #1148 to redesign tooltips.

**Comment by itserindean** [comment]
I can't find anything in any of these connected issues that explains why a redesign is needed/wanted or what the goal are so closing these as not-planned since the Organization Edit Form seems stable. But willing to reopen if there is a need.
