### ISSUE TITLE
Create a wiki of the Organization Edit Form fields

### ISSUE THREAD

**Issue by gigicobos** [hackforla/food-oasis#1142]
### Overview
As part of the effort to redesign the Organization Edit Form, we need to create a wiki with detailed information on the fields so the team can refer back to when making any changes.

### Action Items

- [ ] Create a wiki of the "Organization Edit Form" fields

### Resources/Instructions
[Heuristic Evaluation to Features](https://docs.google.com/spreadsheets/d/1UCoj5ecVQhOBAPNFvzOyySSeJFNtJ34Bx6Ti2cnLma0/edit#gid=983594560)

### Related Issues
#320

**Comment by itserindean** [comment]
I can't find anything in any of these connected issues that explains why a redesign is needed/wanted or what the goal are so closing these as not-planned since the Organization Edit Form seems stable. But willing to reopen if there is a need.
