### ISSUE TITLE
Bug: Data entry volunteer is logged out when updating Pantry

### ISSUE THREAD

**Issue by gigicobos** [hackforla/food-oasis#1151]
### Overview
As a data entry volunteer, I'm logged in and updating my assigned listing (organization edit form). After a few minutes, while updating the info of my listing, I'm logged out. The buttons to save progress do not show up and I can not save my listing. When I update the page, all the info is lost.

Desktop - Google Chrome

### Action Items
REPLACE THIS TEXT -If this is the beginning of the task this is most likely something to be researched and documented.

### Resources/Instructions
Reported during a training session on 01/15/22. Volunteer: Ryan Cassata / ryancassata@gmail.com. The organization is "The Dream Center"

**Comment by staceyrebekahscott** [comment]
@entrotech How can we determine if this is still a bug that needs to be worked out? I assume it would have been reported by a more recent data entry volunteer if the problem was critical and happening repeatedly.

**Comment by staceyrebekahscott** [comment]
Closing this issue as outdated. No issue like this has been reported since this was created.
