### ISSUE TITLE
HIRING: 1 Junior PM + 2 Partnership PMs

### ISSUE THREAD

**Issue by Benbaillou** [hackforla/food-oasis#1160]
### Overview
We need 3 new PMs to join our Project

## Details

- We need 1 junior PM to back Gigi C and Ben for the foodseeker website and volunteer Dashboard
- We need 2 PM to manage the partnership relationship in close collaboration with Bonnie

### Action Items

- [x] Post 2 adds on the Product Manager board - 1 for the Junior 1 for the 2 others.
- [x] Recruit the new PMs
- [x] Onboard them

### Resources/Instructions
https://github.com/hackforla/product-management/projects/8

**Comment by Benbaillou** [comment]
Posts created on the board

**Comment by itserindean** [comment]
Could this be moved to in progress?

**Comment by staceyrebekahscott** [comment]
@itserindean As per your comment from 2 weeks ago, I am determining that we can mark this issue as done. I will add comments and close it out.

**Comment by staceyrebekahscott** [comment]
Moved listings for PMs to Filled column on Product Open Roles board.
