### ISSUE TITLE
Neighborhood Council Support - Draw Neighborhood Boundary on Map

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#1165]
### Overview
To support embedding on a neighborhood council web site, we need to support a neighborhood_id query string parameter, and then retrieve the GeoJSON of the neighborhood (PostGIS) geometry from the neighborhood table, and render the region on MapBox. The default center of the map should be set to the geographic centroid of the neighborhood.

To use this, you will need to use a url like:

la.foodoasis.net/organizations?neighborhood_id=78

The number used should be the nc_id from the official Nieghborhood Council list referenced in the  Resources section. (e.g. 78 is "SOUTH CENTRAL NC").

### Action Items
- [x] Create a web api endpoint to retrieve a single neighborhood GeoJSON shape file from the database - include the calculated latitude, longitude of the region's centroid as part of this data for later use when we work on centering the map on the region.
- [x] retrieve any neighborhood_id query string parameter from the url to control which, if any, neighborhood is rendered.
- [x] When the neighborhood_id state value is present, call the above web api endpoint to retrieve the GeoJSON shape file, and render the region as a layer on the map, using the centroid of the neighborhood as the default centerpoint of the map
- [x] Update the embedding instructions with a lookup table(?) of neighborhoods to create the custom URL on the [wiki instructions page](https://github.com/hackforla/food-oasis/wiki/Embedding-Food-Oasis-in-Your-Web-Site)?
- [ ] QA!

**Comment by entrotech** [comment]
This is implemented to read the neighborhood_id from the url. As you move around in the application the query string currently gets re-written by code associated with OrganizationDetails, which does not preserve the neighborhood_id part of the queryString, and the region will no longer be rendered. We need a follow-up issue to modify the query string re-writing to maintain the neighborhood_id, if present. This cannot be done until issue 989 is resolved.

**Comment by fancyham** [comment]
@entrotech is there a list of URLs we could try for testing or a base URL to start with and try using different id numbers?

**Comment by fancyham** [comment]
Cool!

- [ ] When you @entrotech have a chance, could you list some test URLs so we can play with the regions?
- [ ] Maybe we shouldn put embedding instructions and a lookup table of neighborhoods for that custom URL on the wiki?

Once we can QA (@sei1122), I think we can close this and a bunch of other issues in the [Embeddable Widget milestone](https://github.com/hackforla/food-oasis/milestone/8)!

**Comment by fancyham** [comment]
Sorry, just realized we need this: added action items to revise instructions for the new neighborhood-displaying URLs

**Comment by entrotech** [comment]
I updated the wiki with instructions. Ready for QA.

**Comment by fancyham** [comment]
QA: Looks good!  

I followed the wiki instructions for one neighborhood and it worked as advertised.  Easy to follow instructions, too.

QA done — closing issue!
