### ISSUE TITLE
Improve Pantry and Meal programs filter buttons

### ISSUE THREAD

**Issue by fancyham** [hackforla/food-oasis#1173]
### Overview
What: Make it easier for food seekers to filter between Pantry and Meals by fixing confusing filter buttons above the map.

Why: Currently buttons are not color-coded, and they are confusing to toggle.

- Users can select a "Meals" or "Pantries", or both options by clicking the buttons. When users click or unclick both options, the results are the same. It is not clear to users if they selected the right option or not. Perhaps, adding a "View All" option and enabling users to select either "Meals", "Pantries", or "View All" option would help users better understand the choice. 

![Screen Shot 2022-03-10 at 6 52 36 PM](https://user-images.githubusercontent.com/3376957/157793312-18cd1840-5602-4733-bf0e-e6b4d2761bbe.jpg)

- Also, the colors of the "Meals" button and "Meals" icons on the map are different. It would help users identify the option more easily if the same color is used. 

![Screen Shot 2022-03-10 at 6 57 25 PM](https://user-images.githubusercontent.com/3376957/157794354-cbc68868-4ad2-4711-aff8-49c204692469.jpg)

Thoughts:
- When both buttons are ‘on’, it’s the same results as when both buttons are ‘off’.  It works but feels a little inelegant.  Consider alternatives like a checkbox rather than a button?  Considerations are size and what happens if we add a third category/button?

- Suggest matching up button colors to the pin buttons on the map.

- Also, consider changing order of buttons so pantries is on left — pantries seem like they’re a higher priority over meals.  Whatever is chosen, please ensure that button order matches the pin. (see how the pantry is on left on the map pin, but button order is different)
![Screen Shot 2022-03-10 at 7 00 47 PM](https://user-images.githubusercontent.com/3376957/157793988-a062d7b5-b304-4c4e-916c-dbd7a88fd698.jpg)

### How to replicate

Try clicking on the Meals and Pantries buttons — the colors don’t match the icons on the map.  For example, “Meals” button is enabled and highlights as blue, but the pins on the map are orange.
![Screen Shot 2022-03-10 at 6 57 25 PM](https://user-images.githubusercontent.com/3376957/157793606-17ca47fd-483a-42c1-bdd6-178098acca68.jpg)

### Action Items
- [x] Come up with design options
- [x] Review with team
- [x] Choose one
- [ ] Implement
- [ ] Test

### Resources/Instructions
See items # 11 and 12 in the Heuristic Evaluation from Dec 2021:
[Heuristic Evaluation Spreadsheet](https://docs.google.com/spreadsheets/d/1UCoj5ecVQhOBAPNFvzOyySSeJFNtJ34Bx6Ti2cnLma0/edit#gid=0)

**Comment by sei1122** [comment]
Meeting Note: March 17

Showed this design idea to the team. 
https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/FOLA-Design-System?node-id=4845%3A9271

<img width="1263" alt="Screen Shot 2022-03-24 at 10 40 47 AM" src="https://user-images.githubusercontent.com/19811032/159977421-fc884ce0-ace1-4df2-9a81-60b3cdd94cf3.png">


- The orange color used on the button looks lighter than the website orange -> Use the same color on the website (#E57109) 
- Button idea 3 can be a legend
- Toggle interaction is confusing. Use view all or radio buttons? 

Next steps: 
Explore the filter interaction

**Comment by sei1122** [comment]
https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/FOLA-Design-System?node-id=4883%3A9016

<img width="1559" alt="Screen Shot 2022-03-24 at 3 15 24 PM" src="https://user-images.githubusercontent.com/19811032/160019114-c00a5949-26ce-4e4a-9fa5-ee37572cb2ee.png">

**Comment by sei1122** [comment]
This is final designs of PANTRIES and MEALS buttons. 

https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/FOLA-Design-System?node-id=4902%3A8998

<img width="1220" alt="Screen Shot 2022-03-25 at 5 04 47 PM" src="https://user-images.githubusercontent.com/19811032/160216160-da09df9d-8a59-40a5-8632-9fa4e2d2e58a.png">

Next Steps: 
- [ ] @entrotech implement this design
- [ ] test this on testing url
- [ ] Update design if necessary
- [ ] launch

**Comment by ryu-jieun** [comment]
This issue has been solved and the new design has been updated on the public FOLA website.
