### ISSUE TITLE
Bug: On both sites "Suggest New Listing" page opens up mid-page 

### ISSUE THREAD

**Issue by GigiUxR** [hackforla/food-oasis#1183]
Both Mobile and Desktop Sites.   "Suggest New Listing" page  - This page opens up to the middle of the page/blank form and I had to scroll up  to the top of the page. 

To recreate:
1. https://foodoasis.la/suggestion
2. User ends up in middle of the page, needs to scroll to top to know where they are

Expectation:
- Arrives at suggestion page but at top of form.

**Comment by fancyham** [comment]
Related to #1208

**Comment by staceyrebekahscott** [comment]
This is identified as a bug in the title of the issue, so I am moving it to the Bugs column for immediate review.

**Comment by fancyham** [comment]
It looks like this may be a “focus” issue — the text entry focus is defaults to the email field (which is at the bottom), rather than starting in the organization field (which is the top field).

You can tell because when loading the page, the text entry cursor is in the email field.

**Comment by entrotech** [comment]
This was addressed by Issue #1208
