### ISSUE TITLE
Update landing page design

### ISSUE THREAD

**Issue by sei1122** [hackforla/food-oasis#1191]
### Overview
Page: https://www.foodoasis.la/
Update the design of the center square section. 
1. Currently, white and blue colors are used for the background. We should avoid using the blue color for the background because blue is the primary button color. If we overuse it, the button won't be stand out. 
2. Is the copywriting is clear enough for users? 
3. Green button color is intentionally selected? 

### Action Items

- [x] Design
- [x] Usability Testing
- [x] Development
- [x] Test
- [x] Launch

### Resources/Instructions
Current UI in Desktop and mobile
<img width="705" alt="Screen Shot 2022-04-06 at 2 30 42 PM" src="https://user-images.githubusercontent.com/19811032/162074774-76e4b36e-335f-4371-9786-4db17d02a038.png">

**Comment by sei1122** [comment]
Here is design ideas
https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/FOLA-Design-System?node-id=2936%3A781
<img width="1025" alt="Screen Shot 2022-04-07 at 11 11 19 AM" src="https://user-images.githubusercontent.com/19811032/162269070-c387ecb4-3e75-4d42-b10a-8bef76b0ccef.png">

**Comment by entrotech** [comment]
I converted this from a UI/UX issue to a dev issue, and moved back to the Prioritized Backlog for a developer to pick up.

**Comment by sei1122** [comment]
@LIlinit 
 I attached designs that we’d like to test.  You can access the design file from this link
https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/FOLA-Design-System?node-id=2936%3A7813

<img width="273" alt="Screen Shot 2022-05-26 at 10 24 46 PM" src="https://user-images.githubusercontent.com/19811032/170635212-ccf816b6-5b68-41b1-a3f4-7428fee726a1.png">

Here are some questions but feel free to add/modify
1.   Which design do you like the best? 
2. Which is a better description? 
- Locate free food in Los Angelas
- Search for free food in Los Angeles
- Find free food in Los Angelas


   I think we don’t need to test the desktop design. Based on the mobile design feedback, we can update the desktop design.
 
 <img width="429" alt="Screen Shot 2022-05-26 at 10 24 59 PM" src="https://user-images.githubusercontent.com/19811032/170635242-dedd7d77-8c0a-4fe3-8c1f-2c59e17c0a9e.png">

**Comment by devnikesh** [comment]
Hi team, Can I work on this issue I've done the desktop version. If yes, please assign me the issue and let me know which mobile design is selected. Here's the Screenshot of the Desktop version.

![Food-Oasis](https://user-images.githubusercontent.com/63302392/171606365-12e453c5-7de1-4464-9000-4c3d391e7537.png)

**Comment by sei1122** [comment]
@devnikesh, the User Researcher will conduct the A/B testing. 
So let you know when it is done.

**Comment by fancyham** [comment]
Recapping our team meeting, we are currently looking at comparing: 
current version, A-2, and B-2
![#1191 landing page variations](https://user-images.githubusercontent.com/3376957/174214021-7d87bffc-7271-46dd-a47c-ebf34e1d053e.jpg)

**Comment by sei1122** [comment]
UX research is done by @GigiUxR. 
Here is Gigi's presentation. 
https://stonybrook.voicethread.com/share/20395451/

Next step, based on the research we decide on the design.

**Comment by sei1122** [comment]
Meeting note July 28: 

We decided on these designs. 
Desktop: New design with map
Mobile: White background. 

Next design meeting, finalize the detail of the design.

**Comment by entrotech** [comment]
There is already a development issue for this #1223, we just need to update it once the design team finalizes the wording and designs for this issue.

**Comment by fancyham** [comment]
@sei1122 and @GigiUxR — any thoughts?

**Comment by fancyham** [comment]
@itserindean : says that 'Search' doesn't quite match our functionality, but Locate (what we use now) does.

Gigi may do some competitive analysis to see what other folks do if time allows.

Consensus from everyone weekly meeting: 
Let's stick with existing wording "Locate free food in Los Angeles" (or Hawaii, McKinney, etc.) for now and it's easy to change later if new data comes in.

**Comment by sei1122** [comment]
This is the final design
https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/FOLA-Design-System?node-id=6216%3A10697
<img width="758" alt="Screen Shot 2022-08-05 at 12 59 38 AM" src="https://user-images.githubusercontent.com/19811032/183030842-d4f7973c-0bc8-44f2-9e30-9fffd3ae8fa6.png">
