### ISSUE TITLE
Improve "Send Corrections" form - Cancel & Send buttons 

### ISSUE THREAD

**Issue by ryu-jieun** [hackforla/food-oasis#1200]
### Overview

"Cancel" and "Send" buttons in the "Send Corrections" form look very similar to each other and users could accidentally click the wrong button. It would be better to make the "Cancel" button less significant in a different color. 

You can find the "Cancel" and "Send" buttons in the "Send Corrections" form on each organization's detailed page. 

![Screen Shot 2021-12-07 at 13 55 59](https://user-images.githubusercontent.com/78619802/164555816-2b83c503-9f5e-4308-bf34-35f5405b9efb.png)

### Action Items

- [x]  Come up with design options
- [x]  Review with team
- [x]  Choose one
- [x]  Implement
- [ ]  Test

### Resources/Instructions
See item 17 in the Heuristic Evaluation from Dec 2021: https://docs.google.com/spreadsheets/d/1UCoj5ecVQhOBAPNFvzOyySSeJFNtJ34Bx6Ti2cnLma0/edit#gid=0

**Comment by sei1122** [comment]
Where are these CANCEL and SEND buttons located?

**Comment by ryu-jieun** [comment]
> 

They are in the "Send Corrections" form on each food pantry/meal program's detailed page.

**Comment by sei1122** [comment]
https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/FOLA-Design-System?node-id=2936%3A7814

Button idea

<img width="599" alt="Screen Shot 2022-04-21 at 5 27 15 PM" src="https://user-images.githubusercontent.com/19811032/164574046-5cd563cc-594d-4846-aa78-29c273cb4920.png">

**Comment by sei1122** [comment]
@entrotech,
This design is reviewed with team and good to go.
