### ISSUE TITLE
Resizing the hamburger menu on food seeker mobile site

### ISSUE THREAD

**Issue by ryu-jieun** [hackforla/food-oasis#1201]
### Overview
The hamburger menu on the top right does not fit the header. The image should be adjusted to fit the header. 
This issue appears on Food seeker Mobile Site (iPhone, Chrome, and Safari) 

![IMG_2175](https://user-images.githubusercontent.com/78619802/164556768-78991673-3295-4098-ae1d-2db357204d66.jpg)

### Action Items

- [ ] Resize the image 

### Resources/Instructions
See item #30 in the Heuristic Evaluation from Dec 2021:
https://docs.google.com/spreadsheets/d/1UCoj5ecVQhOBAPNFvzOyySSeJFNtJ34Bx6Ti2cnLma0/edit#gid=0

**Comment by staceyrebekahscott** [comment]
Making heuristics a priority for Impact Sprints 2022, moving to Prioritized Backlog.

**Comment by staceyrebekahscott** [comment]
@devnikesh Are you actively working on this? It's still in the Backlog column.

**Comment by devnikesh** [comment]
Hi, @staceyrebekahscott thanks for looking into it, #1342 here I've just made the PR for this issue, ready to be reviewed and deployed.

**Comment by devnikesh** [comment]
Hi @staceyrebekahscott, thanks for looking into it, #1342 here I've just made the PR for this issue, ready to be reviewed and deployed.

**Comment by staceyrebekahscott** [comment]
@devnikesh @entrotech Even though a PR was merged and closed for this issue, I checked on my iPhone and iPad via Safari and the Hamburger menu still appears as it does in the screenshot in the Overview. What is the next step needed in order to complete this issue?

**Comment by staceyrebekahscott** [comment]
@entrotech @devnikesh I just moved this over to the Dev project board to the Quality Assurance column- it was formerly in the Questions column on the main project board. 

Please see my comment from Oct 24 and advise what needs to be done here.

**Comment by devnikesh** [comment]
Hi @staceyrebekahscott, you can see the changes in [development](https://devla.foodoasis.net/), its not yet on production that's why you are still facing this issue. The changes will take place on next release for Production. Please let me know if you face this issue in development too.
