### ISSUE TITLE
Avoid using button color for background

### ISSUE THREAD

**Issue by sei1122** [hackforla/food-oasis#1207]
### Overview
Review the website interface and change the colors. Currently, button colors blue and orange are used for background color on the About Us, Donate, and FAQ  pages. Button colors should be used minimum so that users recognize buttons easily. 

### Action Items

- [x] Review pages
- [x] Design
- [x] Team's approval
- [ ] Frontend Development

### Resources/Instructions
Here are some examples
<img width="1222" alt="A4 - 1 (1)" src="https://user-images.githubusercontent.com/19811032/165855822-d05f921b-bd7e-4cbe-8f90-d2b313510e32.png">

**Comment by fancyham** [comment]
@sei1122 I think this might have been addressed by your recent design work on the static pages?

**Comment by sei1122** [comment]
yes, this issue is covered and currently development #1332. 
I close this issue.
