### ISSUE TITLE
Update Suggest a New Listing

### ISSUE THREAD

**Issue by sei1122** [hackforla/food-oasis#1208]
### Overview
Update Suggest a New Listing page
https://www.foodoasis.la/suggestion

1. Show the title when landing this page. 
-> To find the page title, need to scroll up to the top. 
2. Add validation.
-> Without filling out any info in the text field, we can send the form. Also, is anyone checking info after sending this?
3. Use the same title size and style as other pages to be consistant

### Action Items

- [ ] Design
- [ ] Review with dev team
- [ ] Implement

### Resources/Instructions
<img width="291" alt="Screen Shot 2022-04-28 at 3 28 45 PM" src="https://user-images.githubusercontent.com/19811032/165858141-5b4c3f07-604c-4ace-98db-3837ca531989.png">

**Comment by fancyham** [comment]
Issue 1 is also noted here: [#1183](https://github.com/hackforla/food-oasis/issues/1183)

**Comment by devnikesh** [comment]
**Overview**

1. Fixed the "Page opens up mid-air" issue
2. Implemented Validation for email, empty submission, required few information, min-max. 

**Suggestions**

- The form is longer vertically, we should split it in two columns
- Adding a Loading Spinner for "Send Suggestions" button, this will enhance the user experience

Is there any new design issued for the "Suggest a New Listing" page. For now I've checked in the Frontend and the submitted data seems to be as expected. I've attached a video  of the new changes, please have a look at it and let me know if any changes are required. 

P.S: need the `dotenv` file for database connection string, to fully test the form.

https://user-images.githubusercontent.com/63302392/173244253-a0cfbea8-e665-4ada-a80c-aaa7b39e6ba8.mp4

**Comment by devnikesh** [comment]
**Overview**

1. Fixed the "Page opens up mid-air" issue
2. Implemented Validation for email, empty submission, required few information, min-max. 

**Suggestions**

- The form is longer vertically, we should split it in two columns
- Adding a Loading Spinner for "Send Suggestions" button, this will enhance the user experience

Is there any new design issued for the "Suggest a New Listing" page. For now I've checked in the Frontend and the submitted data seems to be as expected. I've attached a video  of the new changes, please have a look at it and let me know if any changes are required. 

P.S: need the `dotenv` file for database connection string, to fully test the form.

https://user-images.githubusercontent.com/63302392/173244253-a0cfbea8-e665-4ada-a80c-aaa7b39e6ba8.mp4

**Comment by fancyham** [comment]
Nice!  Opening the window to the top is a great start.  

About the validation:

First, thanks for building this out, @devnikesh — seeing it in action is really helpful to me as a designer to see unexpected downstream effects.

I think the validation shown in the video above is too strict for our goals?

I could imagine someone not knowing the street address or zip code of a food pantry, or doesn’t know the phone number or email, but perhaps we should still allow them to start a listing by submitting the info they do have.  

So some options:

# 1)  Make all fields optional, but require at least one thing filled out?  If completely blank, reject submission and display “X fields need to be filled out” (if that’s actually the case)

OR

# 2) We could just continue to allow blank submissions — those submissions just go into the queue, and the administrator resolves it when they review new submissions?


# A) We could optionally validate the email and phone number fields to make sure they are valid if any text is entered, but also allow them to be blank.

Also, good question about fields:
- [ ] URL?

- [ ] Also, I think “Changes to hours” should probably be “Hours” only (since this is a new listing)?

**Comment by devnikesh** [comment]
@fancyham Thanks for reviewing it. I've made few changes. 

-  Made all fields optional, except the Organization Name and Category
- Added validation for Phone numbers
- Updated “Changes to hours” to "Hours"

Waiting for @entrotech's input on adding Url Field and review on the newly Updated Form. Also @fancyham and @sei1122 please let me know what needs to be updated or added. 

https://user-images.githubusercontent.com/63302392/173407037-7df41f40-14c6-40e6-9c24-dc56140da749.mp4

**Comment by fancyham** [comment]
Thanks!

Could you confirm that you can enter a phone number like this “+1 (121) 283-1833,1,2;3,# x923 (talk to Joanne)”?  (the command and semicolon are pauses) 

If not, perhaps better/easier to have no phone number format validation.  There’ll be a human reviewing and validating the information manually so we don’t have to worry about fields being ‘ready to publish’.

@sei1122 @entrotech what do you think about the category?  Is that necessary?  

I worry that it might be a combination program like meal, pantry, housing… or that people don’t know the terminology enough to enter something. 

Currently there’s no validation for that field, so I’d be inclined to continue to have no validation now that I’ve seen it in action. :)

**Comment by sei1122** [comment]
@devnikesh 
Thank you for the update :) 

I made a prototype to show the suggested design. 
https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/FOLA-Design-System?node-id=2936%3A7816

Here are changes

- Change the "Suggested New Listing"  Title style. Use the same phone size and the case to the About or Donate page. 

- Make form 2 columns for desktop and tablet screen ( As you suggest, if you can do 2 columns, it is great)

- Add icons to the required field so that the user knows which fields must fill out.

**Comment by sei1122** [comment]
@fancyham,
The category may not necessary but it would be good to check how the information is validated. 

I'd like to add validation to prevent keep sending empty data.

**Comment by sei1122** [comment]
Meeting note: 

Required filed is org name only. Having one required field prevents empty submission.

<img width="1084" alt="Screen Shot 2022-06-13 at 7 20 13 PM" src="https://user-images.githubusercontent.com/19811032/173479731-436bee96-5c0c-4703-b201-ef5db31de06b.png">

**Comment by devnikesh** [comment]
**Update:**

- Updated the "Suggested New Listing" Title style as in other pages.
- 2 columns for desktop and tablet screen.
- Added icon for required field (as implemented in other forms).
- Required only the Organization name.
- Successfully submitted the data and reviewed in the Suggestions Administration.

@sei1122 the two column design looks really good, it actually makes it more usable and accessible for users. Can we enhance the title and description area by aligning text for description(center), currently it's left aligned on desktop, or may be implementing it in a different way, just a thought :)

Also please add if anything needs to be updated or added.

https://user-images.githubusercontent.com/63302392/174352377-f2e27ee7-8926-493e-9149-ab3098090d4f.mp4

**Comment by sei1122** [comment]
@devnikesh, as you mention, we can center the description. The current description on the desktop is too narrow so it would be good to update. 

Also, when the required field is not filled and press the button, can you display the warning "Please enter the Organization Name" and the text field outline makes it red.

Here is a design
<img width="1759" alt="Screen Shot 2022-06-17 at 1 25 17 PM" src="https://user-images.githubusercontent.com/19811032/174396555-4feb5ade-2e02-4887-b873-fd3151fd54b7.png">

The Figma file is here
https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/FOLA-Design-System?node-id=2936%3A7816

**Comment by devnikesh** [comment]
**Update:**

- Spaced Full Width and Centered the Description on Desktop
- Updated the Warning text for Organization Name as "Please enter the Organization Name"


https://user-images.githubusercontent.com/63302392/174472312-8f375706-e02b-4f7d-a304-1615a25d102c.mp4

**Comment by sei1122** [comment]
Thank you for the video! 
Overall looks good. 
I will test once I can see this on https://devla.foodoasis.net/  and let you know.

**Comment by entrotech** [comment]
I did a subsequent PR #1249  to further relax most string validation rules.  Changed State filed to minimum of 2 characters, since US states have a two-character abbreviation. Omitted format validation for phone numbers to prevent user frustration at guessing the acceptable punctuation of the phone number.  This is merged to the development environment for @sei1122 to check out.

**Comment by sei1122** [comment]
I just tested it on the development site on desktop, tablet, and mobile. 
Looks good to me. 

One thing. Organization Name is required filed and currently one string validation. I wonder that is too short? 
How about set min 5 characters?
