### ISSUE TITLE
Update Landing Page Design

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#1223]
### Overview
The UI/UX team proposed some design modifications to the Landing page in Issue #1191. Need to implement these changes

### Action Items
- [x] Make changes to look like wireframe in Issue #1191.
- [ ] Review with UI/UX team.

**Comment by entrotech** [comment]
@GigiUxR Can you review this in devla.foodoasis.net and see if it has everything  you wanted?

**Comment by sei1122** [comment]
I tested on laptops, tablets, and mobile. 
Overall looks good. 

I have one suggestion about the hover state.
- hover button color: change to #0A3865 (This color is used in other buttons)
- hover link color: #31C658 (this green is better contrast)

Here is example
<img width="905" alt="Screen Shot 2022-08-08 at 5 00 24 PM" src="https://user-images.githubusercontent.com/19811032/183534497-db7d8bee-0692-4368-82b1-f6c0f923f1b9.png">

**Comment by yiminng** [comment]
looks good, we just need dev to update colours and main site

**Comment by entrotech** [comment]
The hover state change was implemented on Issue #1191
