### ISSUE TITLE
Clear the searched filter items from admin dashboard

### ISSUE THREAD

**Issue by sei1122** [hackforla/food-oasis#1232]
### Overview
When we use Search Criteria, we can't clear the filter items from the searched page. 
To clear the filter items, we need to open the Search Criteria page and clicked the buttons back to be original state. 

It would be great to clear the filtered items from the filtered view. 

### Action Items
- [x] Design 
- [ ] Implementation
- [ ] Test
- [ ] Launch

### Resources/Instructions
<img width="1099" alt="Screen Shot 2022-05-31 at 9 42 32 PM" src="https://user-images.githubusercontent.com/19811032/171329235-e143ddf5-2ce7-4779-87bd-1948705cd26c.png">

**Comment by sei1122** [comment]
Here is design 

Figma file
https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/FOLA-Design-System?node-id=2936%3A7815


<img width="786" alt="Screen Shot 2022-06-06 at 7 05 56 PM" src="https://user-images.githubusercontent.com/19811032/172280181-f071c516-1027-42b2-8927-e4b4dfd5ad7a.png">

**Comment by devnikesh** [comment]
**Update:**
- Added Clear Button for quick filtering to default
- Implemented the logic for Clear Button (Few bugs, working on it)

Please let me know if anything needs to be added or updated.

https://user-images.githubusercontent.com/63302392/175829047-cd762bb8-4abd-4f58-bcc5-29b0ec4ebce1.mp4

**Comment by staceyrebekahscott** [comment]
@sei1122 As you originally created this issue, based on the work that has been done, what are the next steps needed here? 

@devnikesh Has any work been done on this since your last comment on June 26? If so, please detail what has been done.

**Comment by sei1122** [comment]
@staceyrebekahscott, @devnikesh,
oh, I missed checking that @devnikesh sent. 

That looks good. After this goes to the dev environment site. I will test myself again. 
@devnikesh, let me when this merged with https://devla.foodoasis.net/

**Comment by devnikesh** [comment]
@staceyrebekahscott the visual part is done also the functional, but there are still some bugs. As discussed on meeting currently we are working on adding `typescript to backend`. Probably I will hop on to this after `types` has been added to backend or after this week. @staceyrebekahscott, @sei1122  I will update you if any progress has been made.

**Comment by staceyrebekahscott** [comment]
@devnikesh Checking in on an update- have you made any progress here?

**Comment by devnikesh** [comment]
@staceyrebekahscott  not much for now, I have some question regarding this, will communicate with other developers in the tomorrow's meeting.
