### ISSUE TITLE
Upgrade From React Data Grid 

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#1238]
### Overview
The react data grid is now on major version 7 ( https://github.com/adazzle/react-data-grid). The app currently uses version 6, and it is a significant upgrade that has may breaking changes.  We may want to take this opportunity to switch out for a completely different react grid - e.g. the new Material UI Data Grid.

### Action Items
- [ ] Evaluate the Material-UI Data Grid and see if it can replace the current react data grid.
- [ ] Define next steps to perform the transition...

### Resources/Instructions
https://github.com/adazzle/react-data-grid

**Comment by staceyrebekahscott** [comment]
@entrotech Same questions here as I asked in #1045 re: priority of this given the priorities of the Impact Sprints 2022. How will this impact those priorities?

**Comment by staceyrebekahscott** [comment]
None of the current milestone fit what this issue addresses. Once new milestones have been approved, will update accordingly.

**Comment by staceyrebekahscott** [comment]
Sent questions to Bryan and Seiko via Issue #1239.
