### ISSUE TITLE
Prevent sending empty data on Send Correction

### ISSUE THREAD

**Issue by sei1122** [hackforla/food-oasis#1242]
### Overview
Currently, users can submit the form without filling out any field. We need to set at least one required field to prevent sending empty data. 

### Action Items

- [x] Add star icon on Corrections field
- [x] Add verification on Correction field
- [x] Show the "Please enter corrections" Warning and change the stroke to red when a user presses SEND button without entering the Corrections field. 

### Resources/Instructions
Figma link
https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/FOLA-Design-System?node-id=5602%3A9454

<img width="892" alt="Screen Shot 2022-06-23 at 3 44 11 PM" src="https://user-images.githubusercontent.com/19811032/175427105-e362dd55-85bb-4992-9c69-9a0f4ab3c1a5.png">

**Comment by staceyrebekahscott** [comment]
@entrotech @Nechir-89 I see a PR in progress. What is the priority on this and when can we expect this to be resolved so we can close this issue?

**Comment by Nechir-89** [comment]
Well, thanks for commenting, I'm really close to have this done and I'm planning to have it done on tomorrow (Thursday, Aug 04).

**Comment by staceyrebekahscott** [comment]
As per the update, I am moving the issue back to In Progress until it needs further review.

**Comment by Nechir-89** [comment]
All changes have been added to Pull request #1257 and now it just needs a review and approval.
@entrotech @staceyrebekahscott @hanapotski

**Comment by staceyrebekahscott** [comment]
@entrotech @hanapotski Moving to QA and following up on @Nechir-89 request for review and approval. What are the next steps here?

**Comment by staceyrebekahscott** [comment]
@entrotech @hanapotski Following up on @Nechir-89 request- what are the next steps on this issue?

**Comment by entrotech** [comment]
This has been deployed to devla.foodoasis.net.  @staceyrebekahscott - Need to have PM and/or designer review to see if the user experience is satisfactory.

**Comment by staceyrebekahscott** [comment]
@entrotech I just sent 2 Send Corrections forms and both allowed me to send without filling anything in. No warning to fill in the Corrections field when sending it blank.

**Comment by sei1122** [comment]
I just tested. Looks good to me.

**Comment by staceyrebekahscott** [comment]
I just tested it again and it still allows me to send a blank form, no prompt to complete the correction field.

**Comment by staceyrebekahscott** [comment]
I misunderstood this approval process. I just tested on the Dev site and the process looks fine. 

@entrotech Approved. Please proceed with making this change live.

**Comment by staceyrebekahscott** [comment]
@entrotech Can this be moved to Done? What else is needed from the PM team?

**Comment by sei1122** [comment]
I found a bug. 

Please watch this
https://www.loom.com/share/3226523a6d1a42349331d14a36680f38
