### ISSUE TITLE
Bug: foodoasis.net goes to old site

### ISSUE THREAD

**Issue by fancyham** [hackforla/food-oasis#1245]
#### Describe the bug 

On my devices, http://foodoasis.net goes to the old site (the one from about a year ago with the fruit and veggies in the background)

#### Steps to reproduce the issue

(if applicable, please specify platform (iOS, Android, Windows, Mac version) and brower)

1. Go to http://foodoasis.net

#### What's the expected result?

The current site, which is http://la.foodoasis.net or http://foodoasis.la

#### What's the actual result?

The old site from over a year ago.  Or at least, the homepage.  The map doesn’t seem to be actually functional?

#### Device configuration
-  Both Mac and iPad, Safari, internet provider is “Spectrum”

**Comment by fancyham** [comment]
@sei1122 If you’re curious, here’s how the old site looked and how they used the blue color background on the map UI screen, and some other colors for buttons (like the chartreuse for the ‘search’ button)

**Comment by sei1122** [comment]
Nice :) 
Looks like the background image change every time. 
I didn't know the chartreuse and looked up. haha 
Nice yellow ish green. 

It might be nice to add a few more colors to our current website.

**Comment by staceyrebekahscott** [comment]
Found in Issues list but had not been added to the project for proper triage. Overview identifies this as a bug, so I triaged accordingly and added to Bugs column.

**Comment by entrotech** [comment]
Modifed the DNS record in AWS Route 53 for www.foodoasis.net.  This seemed to fix, though I was not able to figure out how to change the A record for the apex domain foodoasis.net.

**Comment by itserindean** [comment]
PM agrees this looks fixed on my devices

**Comment by fancyham** [comment]
Looks good and foodoasis.net and la.foodoasis.net now show the current site with the map of LA in the background, as expected.

So passes QA 👍

Thanks for fixing!
