### ISSUE TITLE
Add typescript to backend app

### ISSUE THREAD

**Issue by hanapotski** [hackforla/food-oasis#1248]
## Instructions
- pick files from the controllers, services and routes folders and add your initials to it along with a 🍔/🌭 icon so we'll know which files are currently being worked on
- checkout this [branch](https://github.com/hackforla/food-oasis/pull/1258)
- create a new branch - `1248-add-types-<filename>`
- change the file extensions to `.ts`
- add types
- create a PR pointing to [1248-install-typescript](https://github.com/hackforla/food-oasis/tree/1248-install-typescript)

## Note:
- don't push directly to the [feature branch](https://github.com/hackforla/food-oasis/pull/1258)
- when something gets merged in to the feature branch, you'll need to [update your branch](https://stackoverflow.com/questions/31881885/how-to-rebase-a-branch-off-a-rebased-branch/31882353#31882353)

🍔 - in progress 
🌭 - done

## controllers
- [x] account-controller.js 🌭 HZ, VW
- [x] category-controller.js 🌭 NS
- [ ] distance-controller.js 🍔 NS
- [x] email-controller.js 🌭 NA
- [ ] esri-controller.js  🍔 QZ
- [ ] export-controller.js 🍔 HZ
- [ ] faq-controller.js 🌭 QZ
- [ ] import-controller.js 🍔 HZ
- [ ] load-controller.js
- [x] logins-controller.js 🌭 VW
- [x] neighborhood-controller.js 🌭 JD
- [x] parent-organization-controller.js 🌭 HZ
- [ ] stakeholder-best-controller.js
- [ ] stakeholder-controller.js
- [ ] stakeholder-log-controller.js
- [x] suggestion-controller.js 🌭 NS
- [x] tag-controller.js 🌭 NA
- [x] tenant-router.js 🌭 VW

## import
- [ ] lapl-food-resources-scrape.js 🍔 HZ

## routes
- [x] account-router.js 🌭 HZ, VW
- [x] category-router.js 🌭 NS
- [ ] distance-router.js 🍔 NS
- [x] email-router.js 🌭 NA
- [ ] esri-router.js 🍔 QZ
- [ ] export-router.js 🍔 HZ
- [ ] faq-router.js 🌭 QZ
- [ ] import-router.js 🍔 HZ
- [x] index.js 🌭 NA
- [ ] load-router.js
- [x] logins-router.js 🌭 VW
- [x] neighborhood-router.js 🌭 JD
- [x] parent-organization-router.js 🌭 HZ
- [ ] stakeholder-best-router.js
- [ ] stakeholder-log-router.js
- [ ] stakeholder-router.js
- [x] suggestion-router.js 🌭 NS
- [x] tag-router.js 🌭 NA
- [x] tenant-router.js 🌭 VW

## service
- [x] account-service.js 🌭 HZ, VW
- [x] category-service.js  🌭 NS
- [ ] db.js
- [ ] distance-service.js 🍔 NS
- [ ] EmailTemplate.js  🌭 QZ
- [ ] esri-service.js  🍔 QZ
- [ ] faq-service.js 🌭 QZ
- [ ] import-constants.js  🌭 QZ
- [ ] import-service.js 🍔 HZ
- [ ] import-utils.js 🍔 QZ
- [ ] load_211.js
- [ ] load-lapl-food-resources-service.js 🍔 HZ
- [x] logins-service.js 🌭 VW
- [x] neighborhood-service.js 🌭 JD
- [x] parent-organization-service.js 🌭 HZ
- [ ] postgres-pool.js
- [ ] postgres-utils.js 🌭 QZ
- [x] sendgrid-service.js 🌭 NA
- [ ] stakeholder-best-service.js
- [ ] stakeholder-log-service.js
- [ ] stakeholder-service.js
- [x] suggestion-service.js 🌭 NS
- [x] tag-service.js 🌭 NA
- [x] tenant-service.js 🌭 VW

## middleware
- [ ] authenticate.js 🍔 QZ
- [ ] jwt-session.js

**Comment by Nechir-89** [comment]
Hi @hanapotski 
Please correct me if I'm wrong, by saying "installing typescript"  you mean installing typescript vscode extension, right

**Comment by hanapotski** [comment]
@Nechir-89 you can just branch off from this branch https://github.com/hackforla/food-oasis/pull/1258

That branch has typescript installed 👌

**Comment by Nechir-89** [comment]
Thanks for letting me know, 
I wasn't able to see the branch in the branch list at first, so here is what I did to see it:
- I ran ($git fetch origin)          // to get all remote branches
- and then ($git checkout 1248-install-typescript) to switch the branch

**Comment by qiqicodes** [comment]
@Nechir-89 did you get a chance to work on the `faq-controller.js`?

**Comment by Nechir-89** [comment]
@qiqicodes I think it has been assigned to RF, however the faq-router and faq-service are still available.

**Comment by qiqicodes** [comment]
@Nechir-89 afaik RF is not working on `faq-controller.js`, I will add types to all of the faq files in a PR.
