### ISSUE TITLE
Advisory Contacts

### ISSUE THREAD

**Issue by GigiUxR** [hackforla/food-oasis#1250]
Store names / contact info of any person who is a potential resource for FOLA

- [ ] Need to locate shared drive document for ongoing contact list to update
- [ ] How do we keep track of our engagement / information received with such contacts?

**Comment by staceyrebekahscott** [comment]
Added list above to issue #937 . Closed this issue as it overlaps with #937

**Comment by entrotech** [comment]
@staceyrebekahscott @GigiUxR @rylantalerico 

In [this folder](https://drive.google.com/drive/folders/1uFhAwa8dMbAT4jCwIefjKSEofBk54ho5) there is a spreadsheet called "Outreach Tracking" that has a partial listing of contacts. 

The same folder has a link to a deleted document that was much more comprehensive called "Food Oasis networking". This was what Jenny used to maintain that had many more connections (probably close to 100).  This might be recoverable from Jenny Mikesell, who is the listed document owner.
