### ISSUE TITLE
Change the navigation order

### ISSUE THREAD

**Issue by sei1122** [hackforla/food-oasis#1259]
### Overview
Change the navigation order to

1. Find Food 
2. About Us

We use the Find Food UI most so it would be good to start from Find Food navigation.

### Action Items

- [ ] Discuss this update with the team
- [ ] Send to dev team for update.

<img width="1080" alt="Screen Shot 2022-07-14 at 3 28 25 PM" src="https://user-images.githubusercontent.com/19811032/179099836-1713a325-7e72-4e68-81a1-34051596267a.png">

**Comment by lodenrogue** [comment]
I think this should do the trick: https://github.com/hackforla/food-oasis/pull/1260

**Comment by sei1122** [comment]
This is implemented and published live site
