### ISSUE TITLE
Adjust spacing for the Org detail view

### ISSUE THREAD

**Issue by sei1122** [hackforla/food-oasis#1261]
### Overview
Adjust spacing for org's detail view. In the current interface, information grouping is not clear. 
Data title H2 has the same margin both top and bottom and it is not clear whether the data belong to the top or bottom title. 

### Action Items
- [ ] Create sample design
- [ ] Review the design
- [ ] Development

### Resources/Instructions
Here is suggestions. 
<img width="960" alt="Screen Shot 2022-07-14 at 5 25 29 PM" src="https://user-images.githubusercontent.com/19811032/179122668-7830c2f5-7962-4732-a5b2-77311faea44c.png">

**Comment by staceyrebekahscott** [comment]
This appears to be related to Heuristics, adding Impact Sprints 2022 label, and to Prioritized Backlog.

**Comment by fancyham** [comment]
From our full-team meeting today: These are some designs that someone did (they didn't leave their name) over two years ago that had some interesting ideas and might be useful as a style reference or to bounce ideas off of / respond to:

https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/FOLA-Design-System?node-id=491%3A605

![Screen Shot 2022-09-01 at 8 20 09 PM](https://user-images.githubusercontent.com/3376957/188052835-c448b64e-29d0-445e-bcb8-9ae1a85ff1b4.jpg)

![Screen Shot 2022-09-01 at 8 20 28 PM](https://user-images.githubusercontent.com/3376957/188052831-3d2335fc-75cb-4c56-9235-85beb3b3d936.jpg)
(this highlighting is just like issue #1120)

![Screen Shot 2022-09-01 at 8 20 37 PM](https://user-images.githubusercontent.com/3376957/188052820-8d82bc22-4572-444a-97e0-266e088b6baa.jpg)

**Comment by fancyham** [comment]
Hey @nkiwan Just checking in — any recommendations / recent designs?

**Comment by fancyham** [comment]
@nkiwan, could you update the status on this, or un-assign yourself so someone else can pick it up?  Thanks!

**Comment by nkiwan** [comment]
<img width="682" alt="Screen Shot 2023-02-09 at 3 11 19 PM" src="https://user-images.githubusercontent.com/38304981/217972814-2503b2c3-421e-4710-a99e-577daf8f6907.png">
@fancyham I'm not sure what happened to my screens, but it looks like the formatting was affected by a font change or maybe someone accidentally edited something. Either way, I'm working on restoring them back to how I left them, then I can start the remaining work on the desktop and tablet views.

**Comment by fancyham** [comment]
Nooo — I hate when that happens. I just looked on my machine at it says the messed-up fonts changed to a font named "Inter", and weirdly, not all the text changed.  Some stayed Helvetica Neue

**Comment by fancyham** [comment]
Hi hi — @nkiwan  just checking in on this — I think this is about done, no?  Let's pick a version and send it to Dev since they have some time!

**Comment by fancyham** [comment]
Hi there — I'm gonna remove you from this issue so someone else can pick it up but also feel free to start working on it again!

**Comment by nkiwan** [comment]
Hi, apologies for the delay! I won't be able to pick back up on my issues until the first week of November so if someone wants to finish this up that's fine with me. Otherwise I'm happy to continue it when I'm back. Thanks!

**Comment by fancyham** [comment]
Being addressed in this UI update:
- #1874

**Comment by qiqicodes** [comment]
Closing this issue as it has been superseded by the new design implementation.
