### ISSUE TITLE
Improve consistency of hyperlink behavior on "Donate" page

### ISSUE THREAD

**Issue by GigiUxR** [hackforla/food-oasis#1266]
Problem:
Buttons on the Donate page are not consistent in its response. For instance,  "Donate" button responds to hover with change in color but the other buttons shown below with arrows do not respond to hovering at all.

Priority: 
3 - Nice to have

Heuristics Violated:
 #1 Visibility of system Status

Recommendations: 
Make all hyperlinks match the "Donate" button when cursor hovers above them.

**Comment by GigiUxR** [comment]
<img width="755" alt="Screen Shot 2022-07-29 at 9 44 58 PM" src="https://user-images.githubusercontent.com/31794055/181865502-81568029-dac1-4a94-a3d1-e1d45584947d.png">

**Comment by staceyrebekahscott** [comment]
Approved issue, added labels and milestone and moved to the Bugs column for Dev team action.

**Comment by staceyrebekahscott** [comment]
@sei1122 I am not sure if this falls into something UI-UX handles, but take a look and let me know if you can work on this.

**Comment by sei1122** [comment]
I can work on this issues.
