### ISSUE TITLE
Finalize text for recruiting designers and researchers and post ad

### ISSUE THREAD

**Issue by itserindean** [hackforla/food-oasis#1274]
### Overview
We need to recruit more designers and researchers to keep up with the 5 new PMs on our team. We need an ad on github so people in the H4LA onboarding funnel make it to us.

### Action Items

- [x]  find similar items from the past from our team even if a for a different discipline
- [x] find similar items from the past for same discipline even if from a different team
- [x] write initial draft
- [x] share draft with team for review
- [x] get reviews from other team members
     - [x] Design
     - [x] Research
- [x] write 2nd draft text based on feedback
- [x] review and edit text
     - [x] PM
     - [x] Design
     - [x] Research
- [x] write final text based on feedback
- [x] approve final text
     - [x] PM
     - [x] Design
     - [x] Research
- [x] post ad

**Comment by itserindean** [comment]
examples of posts from our team:
Could only find posts for PM
![image](https://user-images.githubusercontent.com/37763229/162998736-844482ea-4e3a-4e83-a704-5d8588b7fd4b.png)

**Project Name**: Food Oasis LA

**Volunteer Opportunity**: We are looking for Product Managers with experience and/or connections in the Food Rescue Ecosystem. As a PM you'd be working on targeting organizations to embed our website and
onboarding the management of Data Entry Volunteers (training, session, recruitment) under Hack For LA.

**Duration**: ongoing / 10h week min

**Weekly Meeting**:
- Team meeting - Thursdays 6:00pm- 7:00pm Pacific Time
- PM/Org meeting - To be negotiated with Bonnie

**Slack channel**: #fola
Slack name of person to contact in the channel: John Darragh

**Read more about the project**: https://github.com/hackforla/food-oasis/wiki

--------------

![image](https://user-images.githubusercontent.com/37763229/162998736-844482ea-4e3a-4e83-a704-5d8588b7fd4b.png)

**Project Name**: Food Oasis

**Volunteer Opportunity**: We're looking for 1 Product Manager who can help us drive our project to the next stage and build our new Roadmap. You'll be expected to attend and help run weekly meetings. We would also need your help with community partner outreach. Experience working with Non-profits or the government is a plus.

**Duration**: On-going

Team Meeting : 6-7 PM Pacific Time Thursdays

**Who to communicate your interest to**
- Slack channel link: #fola
- Slack name of the person to contact in the channel: John Darragh

[Read more about the project](https://www.hackforla.org/projects/food-oasis)

**Resources:**



-------------

**Comment by itserindean** [comment]
![image](https://user-images.githubusercontent.com/37763229/162992303-b0fae60e-1886-45ce-93c1-d1a27a909327.png)

**Project Name**: Hack for LA Website

**Volunteer Opportunity**: 
We are looking for designers to join our current team. Here you'll have the opportunity to work on the [hackforla.org](https://www.hackforla.org/) site, designing solutions that support both the needs of our users and the goals of the Hack for LA organization as a whole. 

We're currently working on a big redesign of the site and are looking for people with familiarity and interest in both visual design as well as larger UX/product design methods: 

**Duration:** 
Ongoing, 4-6 hours per week

**Meetings:**
Design team meetings: Wednesday 2:30 PM-3:30 PM PST
All team meeting (design, dev, PM): Sunday 10-11am PST

**Who to communicate your interest to**
Slack channel link: [hfla-site-ux](https://hackforla.slack.com/archives/C018FMQTWMT) 
```@Phuong Van```

------------
<img src="https://www.hackforla.org/assets/images/projects/civic-tech-index.png" />

**Project Name** : Civic Tech Index

**About the Project:** We are creating a continuously updated repository for all civic tech workers to find open source projects to model, connect with, and learn from. 

**Volunteer Opportunity:** We are looking for UX/UI designer to join our current team. 

**Responsibilities** helping us get launched!  We are sooooo close.  

**Duration:** Ongoing, 6 hours per week

**Meetings:**
- Monday 6-8pm PST (Mandatory)
- Thursday 6-7pm PST (Optional)

**Who to communicate your interest to**
Slack channel [#civic-tech-index](https://hackforla.slack.com/archives/CTYAKM0CW)
Contact Sean Sada, Chali, or Kevin Phan

**Comment by itserindean** [comment]
Example of researcher role description:
------
UX Researcher
This team member plays a critical role in the design process. They are responsible for providing answers to challenging and often unexplored questions about a product’s design. In order to do this, they will conduct research, collaborate with cross-functional teams, and assist the entire user experience team in ensuring that the consumer has an experience with a product that is fun, intuitive, accessible, and joyful.

Hack For LA brings together civic-minded technologists to build digital products, programs, and services with community partners and local government to address issues in the LA region. This is done by using the web as a platform for local government and community service.

Responsibilities
Conduct primary and secondary user research.
Conduct and evaluate quantitative and qualitative research.
Perform market and ethnographic research.
Work closely with cross-functional teams to identify and evaluate research topics.
Plan and implement user research strategies and methodologies.
Advocate research findings to diverse audiences through written and oral presentations.
Perform usability studies with consumers.
Ask questions, gather data, and analyze data.
Basic Qualifications
Experience or interest in human behavior
Ability to quickly and effectively share research results
Ability to perform all research-related tasks including research, planning, evaluating, and iteration
Ability to formulate specific, answerable, and practical questions
Ability to collaborate effectively with stakeholders and act as a strategic partner in product decisions

**Comment by itserindean** [comment]
Inital Draft text
---------
![image](https://user-images.githubusercontent.com/37763229/162998736-844482ea-4e3a-4e83-a704-5d8588b7fd4b.png)

**Project Name**: Food Oasis LA

**Volunteer Opportunity**: We are looking for a UI/UX researcher who can collaboratively work with stakeholders and conduct surveys and interviews for our initiatives.

**Duration**: ongoing  (~6 hrs week)

**Weekly Meeting**:
- Team meeting - Thursdays 6:00pm- 7:00pm Pacific Time

**Slack channel**: #fola
Slack name of person to contact in the channel: John Darragh (should we direct it to an active researcher-- Gigi?)

**Read more about the project**: https://github.com/hackforla/food-oasis/wiki

--------------

![image](https://user-images.githubusercontent.com/37763229/162998736-844482ea-4e3a-4e83-a704-5d8588b7fd4b.png)

**Project Name**: Food Oasis LA

**Volunteer Opportunity**: We are looking for designers to join our current team. Here you'll have the opportunity to work on the [foodoasis.la](https://www.foodoasis.la/) site, designing solutions that support both the needs of our foodseekers and the goals of the volunteers who keep the site up-to-date.

We're currently looking for people with familiarity and interest in both visual design as well as larger UX/product design methods:

**Duration**:ongoing  (~6 hrs week)

**Weekly Meeting**:
- Team meeting - Thursdays 6:00pm- 7:00pm Pacific Time
- Design Team meeting - Thursdays 7:00pm - 7:30pm Pacific time (Is this an ongoing meeting?)
- 
**Slack channel**: #fola
Slack name of person to contact in the channel: John Darragh (should we direct it to an active Designer-- Bryan?)

**Read more about the project**: https://github.com/hackforla/food-oasis/wiki

--------------

**Comment by sei1122** [comment]
- Design Team meeting - Thursdays 7:00pm - 7:30pm Pacific time  ---> yes this is ongoing
- Slack name of person to contact in the channel: John Darragh (should we direct it to an active Designer-- Bryan?) ---> candidate contact to Bryan or me.

**Comment by fancyham** [comment]
@itserindean Both research and designer looks good!

For researcher candidates, they can reach out to me — (@GigiUxR let us know if you'd like to be an alternative contact, also)

**Comment by itserindean** [comment]
from @GigiUxR on slack
[Gigi P]I won't be in front of my computer for awhile. It's easier for me to answer here for now. For UX researcher, they will be helping with user flow maps, guerilla style research, competitive analysis, usability studies, and benchmarking
Someone with a research background is ideal

**Comment by staceyrebekahscott** [comment]
I'll also draft a version of these positions for the Food Oasis page on Democracy Lab. As per Impact Sprints 2022, we are going to be using Democracy Lab as an additional recruiting tool to the HfLA process. We will need to develop an explainer for the on boarding process, as DLab adds an additional layer to an already complicated process.

**Comment by itserindean** [comment]
---------
### Final text for approval RESEARCHER

---------
![image](https://user-images.githubusercontent.com/37763229/162998736-844482ea-4e3a-4e83-a704-5d8588b7fd4b.png)

**Project Name**: Food Oasis LA

**Volunteer Opportunity**: We are looking for a UI/UX researcher who can collaboratively work with stakeholders and conduct surveys and interviews for our initiatives. You will be helping with user flow maps, guerilla style research, competitive analysis, usability studies, and benchmarking
Someone with a research background is ideal, but not necessary and we will help train anyone who is interested.

**Duration**: ongoing  (~6 hrs week)

**Weekly Meeting**:
- Team meeting - Thursdays 6:00pm- 7:00pm Pacific Time

**Slack channel**: #fola
Slack name of person to contact in the channel: @Bryan Wu or @Gigi Patel

**Read more about the project**: https://github.com/hackforla/food-oasis/wiki

---------
### Final text for approval DESIGNER
-----------------------

![image](https://user-images.githubusercontent.com/37763229/162998736-844482ea-4e3a-4e83-a704-5d8588b7fd4b.png)

**Project Name**: Food Oasis LA

**Volunteer Opportunity**: We are looking for designers to join our current team. Here you'll have the opportunity to work on the [foodoasis.la](https://www.foodoasis.la/) site, designing solutions that support both the needs of food seekers using the site and the goals of the volunteers who keep the site up-to-date.

We're currently looking for people with familiarity and interest in both visual design as well as larger UX/product design methods:

**Duration**:ongoing  (~6 hrs week)

**Weekly Meeting**:
- All Hands Team meeting - Thursdays 6:00pm- 7:00pm Pacific Time
- Design Team meeting - Thursdays 7:00pm - 7:30pm Pacific time
- 
**Slack channel**: #fola
Slack name of person to contact in the channel: @Bryan Wu or @Seiko Igi

**Read more about the project**: https://github.com/hackforla/food-oasis/wiki

--------------

**Comment by fancyham** [comment]
Both look good to go with my one change for the researcher:

Someone with a research **or food security or systems** background is ideal, but not necessary and we will help train anyone who is interested.

Thanks!

**Comment by sei1122** [comment]
Looks good! 

Thank you!

**Comment by itserindean** [comment]
@fancyham "food security" or "food insecurity"?

**Comment by gigi** [comment]
> Slack name of person to contact in the channel: @bryan Wu or @gigi Patel

Hi guys. Id like to help but I dont live in LA...
It seems you invited the wrong nickname)

**Comment by itserindean** [comment]
Apologies for that, Alexey. I was trying to indicate the Slack aliases and forgot that github would interpret the first name as a github handle.

**Comment by fancyham** [comment]
@itserindean yup, “food security” — that’s how it’s used in the world (e.g. “annual food security conference”, not “annual food insecurity conference”)

**Comment by itserindean** [comment]
@fancyham updated above. Thank you for the clarification and education.

**Comment by staceyrebekahscott** [comment]
@itserindean @fancyham I believe the terms Food Security and Food Insecurity are both correct depending on what the subject is. 

The goal to achieve Food Security for populations might be the work of large organizations, such as what the Global Food Security Conference is about. 

But individuals experience Food Insecurity, and there are researchers and organizations, such as Food Banks, that work to help people experiencing Food Insecurity directly. 

So the role of the researcher could be someone who has worked with individuals experiencing Food Insecurity or who has done research on food insecure populations, such as people who live in areas considered "food deserts". 

I would say we would be looking more for the latter, someone who is experienced working with, or has an interest in working with, people experiencing Food Insecurity. From a User Experience perspective, I would imagine this is the more important consideration, given the Food Oasis tool's intended user is someone who is experiencing Food Insecurity and needs access to a food resource such as a Food Pantry. 

However, if the listing is already posted, the wording of Food Security is fine. And I hope I interpreted the question of which one is proper correctly, and that this explanation is useful.

**Comment by staceyrebekahscott** [comment]
@itserindean If you haven't posted these yet, can we see what one looks like with the Food Oasis Logo, instead of the photo of the pile of beets? We have discussed that photos of fresh vegetables is not an accurate depiction of what goes on at food pantries, which is why the main page design was changed from the fresh fruits and veggies to the Map. I think the simple Food Oasis logo would look nicer, if there's time to make changes. 

Also, I think a PM should also be listed as a contact for someone the potential team member should contact. Like the issues, the new team members should be reviewed by the PMs as well. I am happy to be listed, or you can list yourself since you took the lead in making these listings.

**Comment by itserindean** [comment]
@staceyrebekahscott I like the Food Oasis logo (Added above.) I haven't posted yet because i'm waiting to hear from @gigicobos from Research.

**Comment by itserindean** [comment]
@fancyham @sei1122-- @staceyrebekahscott hadn't had a chance to weigh in previously so I added a 2nd review to the process and am rebranding this phase as that. I made some tweaks to the researcher text based on her feedback here and offline to say: "Someone with a research background or who has experience working with individuals experiencing food insecurity is ideal, but we will train anyone who has an interest in learning how to help food insecure populations." Is this okay for you guys?

**Comment by sei1122** [comment]
Looks good.

**Comment by GigiUxR** [comment]
@fancyham @itserindean @sei1122 @staceyrebekahscott:  Erin, thanks for your suggestion with "but we will train.." but I am hesitant in placing that sort of emphasis especially since we already state "Ideal".   I suggest something like the following:

"Experience is not required and anyone interested helping people having trouble finding food is welcome to apply."  This way people may assume rightfully so that a huge part of this role is taking the initiative to self-learn and no rely on a training program. Everything else regarding the descriptions of the ideal candidate is fine with me. However, I have one note on "Food systems" mentioned by @fancyham's comment -- I believe we want to go with someone with even more micro level research than that. I, for instance, have some background in food systems both at the mess and macro level and still find myself lacking in the actual day-to-day experience of a food seeker.

**Comment by itserindean** [comment]
@GigiUxR  Does this capture what you were thinking or were you imaging your suggested text alongside "Someone with a research background or who has experience working with individuals experiencing food insecurity is ideal"

**Volunteer Opportunity**: We are looking for a UI/UX researcher who can collaboratively work with stakeholders and conduct surveys and interviews for our initiatives. You will be helping with user flow maps, guerilla style research, competitive analysis, usability studies, and benchmarking. Experience is not required and anyone interested helping people having trouble finding food is welcome to apply.

**Comment by fancyham** [comment]
Researchers familiar with food insecurity populations and issues would be nice, though hard to find, I bet.  I think if you know what food security is, you'll also know what food insecure means.

For the record, while the beets photo above looks like a farmer's market with items stacked for sale, a lot of food distributions (not necessarily pantries, BTW) do have fresh fruits and veggies, but they'll probably be in grocery bags with other veggies rather than a ton of one type. Not just dried or canned goods.

(Though sometimes…  in Hawaii, early in the pandemic, sometimes we'd have so much of one thing that that we'd be giving huge boxes of, say, onions or sweet potatoes or ginger to people — totally unreasonable amounts that I hope they passed to their friends and family)

**Comment by itserindean** [comment]
---------
### Final text for RESEARCHER

---------
![LOGO food oasis horizontal 2](https://user-images.githubusercontent.com/107142453/186766499-656225b9-9878-4932-b4cf-3a92e6621e93.png)


**Project Name**: Food Oasis LA

**Volunteer Opportunity**: We are looking for a UI/UX researcher who can collaboratively work with stakeholders and conduct surveys and interviews for our initiatives. You will be helping with user flow maps, guerilla style research, competitive analysis, usability studies, and benchmarking. Experience is not required and anyone interested helping people having trouble finding food is welcome to apply.

**Duration**: ongoing  (~6 hrs week)

**Weekly Meeting**:
- Team meeting - Thursdays 6:00pm- 7:00pm Pacific Time

**Slack channel**: #fola
Slack name of person to contact in the channel: @Bryan Wu or @Gigi Patel

**Read more about the project**: https://github.com/hackforla/food-oasis/wiki

---------
### Final text for DESIGNER
-----------------------

![LOGO food oasis horizontal 2](https://user-images.githubusercontent.com/107142453/186766499-656225b9-9878-4932-b4cf-3a92e6621e93.png)

**Project Name**: Food Oasis LA

**Volunteer Opportunity**: We are looking for designers to join our current team. Here you'll have the opportunity to work on the [foodoasis.la](https://www.foodoasis.la/) site, designing solutions that support both the needs of food seekers using the site and the goals of the volunteers who keep the site up-to-date.

We're currently looking for people with familiarity and interest in both visual design as well as larger UX/product design methods:

**Duration**:ongoing  (~6 hrs week)

**Weekly Meeting**:
- All Hands Team meeting - Thursdays 6:00pm- 7:00pm Pacific Time
- Design Team meeting - Thursdays 7:00pm - 7:30pm Pacific time
- 
**Slack channel**: #fola
Slack name of person to contact in the channel: @Bryan Wu or @Seiko Igi

**Read more about the project**: https://github.com/hackforla/food-oasis/wiki

--------------

**Comment by itserindean** [comment]
@fancyham @sei1122 @GigiUxR @staceyrebekahscott  Please confirm if you approve this final text for posting.

**Comment by fancyham** [comment]
That looks good to me.  If there's space, I'd add a one-sentence description of the project near the beginning.

Something like "Food Oasis (http://foodoasis.la) is a website that helps food seekers find food pantries and meal programs near them."

**Comment by sei1122** [comment]
Design team meeting, we'd like to have one hour 
Thursday  7:00 - 8:00 pm Pacific Time

**Comment by itserindean** [comment]
@fancyham I think that's good idea and I made that changes since you're the first to review, but I think that's the extent of changes I can make to this text without adding another round of review to the process which has already taken more than  a month and missed 2 onboarding opportunities to get volunteers for these roles.

**Comment by sei1122** [comment]
Thank you looks good

**Comment by staceyrebekahscott** [comment]
I concur, they look ready for posting.

**Comment by fancyham** [comment]
Looks good to me!  Thanks for doing this!

**Comment by itserindean** [comment]
@GigiUxR communicated by slack "Not in front of a computer so can't comment in GitHub... I've had a look via mobile and it looks great

**Comment by itserindean** [comment]
ads have been posted ahead of the 9/12 onboarding meeting
