### ISSUE TITLE
"Your Phone" field allows users to type in any characters other than numbers

### ISSUE THREAD

**Issue by itserindean** [hackforla/food-oasis#1280]
Problem:
"Your Phone" field allows users to type in any characters other than numbers and "-" or ".". It means it doesn't let users know when they accidentally put wrong or unnecessary information. 
![Screen Shot 2022-08-10 at 12 18 05 PM](https://user-images.githubusercontent.com/107142453/184002226-216056f1-75a1-447d-9a9a-f89de6bda2d6.png)

Step to repro:
goto foodoasis.la
goto map view by entering an address or using current location
Click on "details" for any listing
Click "send correction"
type characters into "Your Phone" field.

Severity 1 - Cosmetic problem only: need not be fixed unless extra time is available on project

Heuristics Violated:
5:  Error prevention
8:  Aesthetic and minimalist design

Recommendations:
This field could limit users type in numbers (and "-" or "." if necessary). It is also possible to show a sample phone number format under the label depends how we would like to organize the contact information (eg., 123-456-7890 / 1234567890). 

### Action Items
- [ ] Design mocks up how it would look
- [ ] make change as designed

Note: the issue in [the heuristics spreadsheet](https://docs.google.com/spreadsheets/d/1UCoj5ecVQhOBAPNFvzOyySSeJFNtJ34Bx6Ti2cnLma0/edit#gid=0) (item no. 31) asks to link this to #1131 

This is issue was created from a list of food seeker [issues identified](https://docs.google.com/spreadsheets/d/1UCoj5ecVQhOBAPNFvzOyySSeJFNtJ34Bx6Ti2cnLma0/edit?usp=sharing) by a [heuristic evaluation](https://docs.google.com/presentation/d/1mAQV8V9y1ZoQAgBb_mflU8UAGcRogsVfEgZU-hKVvQ0/edit?usp=sharing) completed by 
[@Gigi P](https://hackforla.slack.com/team/U02KZ8WSHHV) & @ryu-jieun  at the end of last year.

**Comment by itserindean** [comment]
I created this with severity 1, as described in [the heuristics spreadsheet](https://docs.google.com/spreadsheets/d/1UCoj5ecVQhOBAPNFvzOyySSeJFNtJ34Bx6Ti2cnLma0/edit#gid=0)
but I think the severity should be:
0 = I don’t agree that this is a usability problem at all

I don't think this will practically help users catch errors who are legitimately trying to enter a phone number. My guess is that most phone number errors are transposing numbers, not inputting erroneous letters.

**Comment by entrotech** [comment]
We had to create the phone number field as free-form entry, because some of the existing data had other information crammed into the phone field. For example, it might have something like `(310) 901-5994 (ask for Martha)` or `(310) 901-5944 (mobile)`. In some cases there were multiple phone numbers in the single field.

**Comment by staceyrebekahscott** [comment]
@GigiUxR Can you advise on how we should proceed here, given the comments from @entrotech and @itserindean ? 

Moving to Questions/ In Review.

**Comment by staceyrebekahscott** [comment]
@GigiUxR Following up on John and Erin's comments- please advise if this is still a usability issue that should be addressed. If no response by this week's meeting, we will go with their assessment and close this issue.

**Comment by itserindean** [comment]
Noting for posterity that it was @ryu-jieun rather than @GigiUxR who identified this as an issue in the Heuristics exercises, but as Gigi is our only active researcher at the moment, it will have to be her who weighs in...

**Comment by GigiUxR** [comment]
@staceyrebekahscott @entrotech @itserindean It seems that this would impact us more on the back end than the front user end and therefore not such a major usability concern. Are we ending up making extra efforts on the back end to clean the data  from erroneous / miscellaneous info such as parentheses, dashes, letter , etc.?

**Comment by itserindean** [comment]
From @entrotech's comment I don't believe we're doing anything to clean this up. Let's close as won't fix since it's not really a usability concern.

**Comment by staceyrebekahscott** [comment]
Agreed. Closing issue as won't fix.
