### ISSUE TITLE
Update FAQs content

### ISSUE THREAD

**Issue by itserindean** [hackforla/food-oasis#1281]
### Problem:
No FAQs content for 
-  food seekers, 
- partners who want to embed our site
- social workers who want to help clients
- food pantry site that wants to add themselves to database

also
- FAQ for volunteers doesn't cover what the volunteer work is
- FAQ for donors does't cover where to donate/who you're donating to/that it's about financial donations not food donations.
- our glossary doesn't seem necessary and "Meal programs" aren't necessarily cooked. (not sure on accuracy of others just caught that one...

<details> <summary>CLICK HERE TO VIEW SCREENSHOT OF CURRENT FAQ</summary>

![Screen Shot 2022-08-10 at 12 29 16 PM](https://user-images.githubusercontent.com/107142453/184003716-6980a580-f4b4-4162-bddf-b701988dbc7f.png)
</details>

### Steps to reproduce
goto foodoasis.la
goto map view by entering an address or using current location
Click on "details" for any listing

Severity 2 - Minor usability problem: fixing this should be given low priority

## Heuristics Violated:
 #10 Help and Documentation

## Recommendations:
check for suitable, common questions that have been emailed to general inquiries email or asked at pantries. 

### Action Items
- [x] research FAQs on similar sites
- [x] PM check foodoasisinfo@hackforla.org email account for common questions
- [x] Author FAQ content
Language clean up ideation: https://docs.google.com/document/d/15S6ApvAydqan0esH7WALr2QwSKl_BLe8UJxHo0kSs5I/edit
Final updated language: https://docs.google.com/document/d/18fXCo7UwfxhzV1mwFruJFstiNz5CLeUqKhaZofRk3qQ/edit
- [x] Design mocks up how it would look: Mockups for updated language (frame 319): https://www.figma.com/file/GnvrOCZiWBKOMxjKTFcq4w/FOLA-Content-team-library?node-id=411%3A2&t=e9BE7VCcFqkbTPsu-0hKVvQ0/edit?usp=sharing) 

- [x] add FAQ content to site

This is issue was originally created from a list of  [issues identified](https://docs.google.com/spreadsheets/d/1UCoj5ecVQhOBAPNFvzOyySSeJFNtJ34Bx6Ti2cnLma0/edit?usp=sharing) by a [heuristic evaluation](https://docs.google.com/presentation/d/1mAQV8V9y1ZoQAgBb_mflU8UAGcRogsVfEgZU-hKVvQ0/edit?usp=sharing) completed by 
[@Gigi P](https://hackforla.slack.com/team/U02KZ8WSHHV) & @ryu-jieun  at the end of last year. 

### Resources
Design requested Content initially work in Google Docs. Google doc Research and content audit lives here: https://docs.google.com/document/d/1taXVLsGdkAPhEBA8-KzO2TrBClUc7EPf98iDTNvpaT8/edit#heading=h.8h1xplviyjun

**Comment by itserindean** [comment]
I created this with severity 1, as described in [the heuristics spreadsheet](https://docs.google.com/spreadsheets/d/1UCoj5ecVQhOBAPNFvzOyySSeJFNtJ34Bx6Ti2cnLma0/edit#gid=0)
but I think the severity should be:
2- Minor usability problem: fixing this should be given low priority

I think we should have FAQ addressing questions for the primary users of our site (which i'm assuming is foodseekers.)

**Comment by staceyrebekahscott** [comment]
Moving to Prioritized Backlog, as Heuristics are an Impact Sprints 2022 Priority.

**Comment by GigiUxR** [comment]
@staceyrebekahscott @itserindean I agree with raising the severity to 2.

**Comment by itserindean** [comment]
This could also consider FAQs from:

- partners who want to embed our site
- social workers who want to help clients
- food pantry site that wants to add themselves to database

**Comment by entrotech** [comment]
Here is a link to the Stakeholder version of the proposed content from Emily: 
https://docs.google.com/document/d/1M6ejOzg07wTAz8Y1FXckq6e6NUAz36HKyGRJDn3DBms/edit#heading=h.y28zcafxg4u5

**Comment by fancyham** [comment]
This might require some research but let’s try to out what questions food seekers actually have when they come to our site!

Terminology question: do we want to consider orgs who embed our site ‘partners’?  That might be a too-strong word since partners usually implies actually working together.  We may need another term for that group or goal — perhaps a heading like “Help people find free food” -> instructions for embedding, etc.

**Comment by staceyrebekahscott** [comment]
I would like us to hold off on including any instructions on embedding to our website, until we can do a complete evaluation of the value of using the embed. 

Questions to consider here would be: 
- How does the embed affect the host's website? (is the embed slow to load? does it slow down their site overall?)
- How can we measure if the embed is actually helpful to food seekers? 
- Do we want traffic to be pushed to our website and does the embed do this? 

There are more questions to consider, but this is a longer term priority that I don't want to discuss too much now, to avoid it being a distraction of our more immediate priorities.

**Comment by ShruthiVen28** [comment]
Updated language: https://docs.google.com/document/d/15S6ApvAydqan0esH7WALr2QwSKl_BLe8UJxHo0kSs5I/edit
Mockups for updated language : https://www.figma.com/file/GnvrOCZiWBKOMxjKTFcq4w/FOLA-Content-team-library?node-id=411%3A2&t=e9BE7VCcFqkbTPsu-0

Content will be passing this to Design on 2/9/23

**Comment by ShruthiVen28** [comment]
To streamline Content passing over files to Design, we ask the PMs and Leads to please check against their name as a sign of approval for our FAQ changes  (as discussed during the PM and Leads meeting on 2/9): 

- [ ] @staceyrebekahscott 
- [ ] @itserindean 
- [ ] @entrotech 
- [ ] @fancyham 
- [ ] @sei1122 
- [ ] @GigiUxR 

Thanks!

**Comment by fancyham** [comment]
Thanks!  FAQ is much-improved!

As discussed during the design meeting for future versions: would be nice to have screenshots (marked up with instructions) or even video.  If either are appropriate in the future, please put right in the manuscript and we'll figure out how to get it on the website or help with layout mockups.

**Comment by GigiUxR** [comment]
@ShruthiVen28 @bduhe I signed off but I made comments and raised questions in the Figma doc. Hope it helps.
