### ISSUE TITLE
"Food Pantry" category is not really visible as it is located at the bottom of the address area. I

### ISSUE THREAD

**Issue by itserindean** [hackforla/food-oasis#1282]
Problem:
"Food Pantry" category is not really visible as it is located at the bottom of the address area. It could be moved to the top as this category is one of the key information that users want to see. 

![Screen Shot 2022-08-10 at 12 35 08 PM](https://user-images.githubusercontent.com/107142453/184004721-e2fd2327-9787-422b-b5d7-6e3ff1b2942f.png)

Step to repro:
goto foodoasis.la
goto map view by entering an address or using current location
Click on "details" for any listing

Severity 1 - Cosmetic problem only: need not be fixed unless extra time is available on project

Heuristics Violated:
1 Visibility of system status

Recommendations:
It could be moved to the top as this category is one of the key information that users want to see. 

### Action Items
- [ ] Design mocks up how it would look
- [ ] make change as designed

This is issue was created from a list of food seeker [issues identified](https://docs.google.com/spreadsheets/d/1UCoj5ecVQhOBAPNFvzOyySSeJFNtJ34Bx6Ti2cnLma0/edit?usp=sharing) by a [heuristic evaluation](https://docs.google.com/presentation/d/1mAQV8V9y1ZoQAgBb_mflU8UAGcRogsVfEgZU-hKVvQ0/edit?usp=sharing) completed by 
[@Gigi P](https://hackforla.slack.com/team/U02KZ8WSHHV) & @ryu-jieun  at the end of last year.

**Comment by itserindean** [comment]
I created this with severity 1, as described in [the heuristics spreadsheet](https://docs.google.com/spreadsheets/d/1UCoj5ecVQhOBAPNFvzOyySSeJFNtJ34Bx6Ti2cnLma0/edit#gid=0)
but I think the severity should be:
0 = I don’t agree that this is a usability problem at all

The food pantry label does show up at the top of the listing in the list of results which I think it's more useful when distinguishing between multiple listings. In the detail view I'm not sure this is key information.
![Screen Shot 2022-08-10 at 4 35 39 PM](https://user-images.githubusercontent.com/107142453/184040898-be1a82ec-1ee4-48b8-8396-43e7e7287888.png)

**Comment by sei1122** [comment]
We discussed the team and we decided to remove the icon because it isn't useful. 
You can see the updated version at
https://devla.foodoasis.net/ 

Next release and it should be updated. 

<img width="472" alt="Screen Shot 2022-08-10 at 5 26 31 PM" src="https://user-images.githubusercontent.com/19811032/184045165-f56e98d3-a71c-4d04-8ef9-e252a67eebb0.png">

I think this issue can be closed.

**Comment by staceyrebekahscott** [comment]
@GigiUxR As per Erin's comments, do you still think this is a usability issue? If so, please explain. 

Moving to Questions/ In Review.

**Comment by staceyrebekahscott** [comment]
@GigiUxR Following up on Erin's comments- please advise if this is still a usability issue that should be addressed. If no response by this week's meeting, we will go with Erin's assessment and close this issue.

**Comment by itserindean** [comment]
Noting for posterity that it was @ryu-jieun rather than @GigiUxR who identified this as an issue in the Heuristics exercises, but as Gigi is our only active researcher at the moment, it will have to be her who weighs in...

**Comment by GigiUxR** [comment]
This is no longer a usability issue.

**Comment by itserindean** [comment]
closing per @GigiUxR comment that this is no longer a usability issue
