### ISSUE TITLE
Fields in "Send Correction" should have input constraints

### ISSUE THREAD

**Issue by itserindean** [hackforla/food-oasis#1283]
Problem:
All the fields in the "Send Correction" do not have input constraints. Input constraints help both organizations and users as it prevents organizations from reading an extremely long message and users from spending long time writing a long message. 

![Screen Shot 2022-08-10 at 12 42 47 PM](https://user-images.githubusercontent.com/107142453/184006012-789da3d2-8642-4f1c-b6d8-c7dd06d33b8e.png)

Step to repro:
goto foodoasis.la
goto map view by entering an address or using current location
Click on "details" for any listing
Click "send correction"

Severity 2 - Minor usability problem: fixing this should be given low priority

Heuristics Violated:
5 Error prevention
9 Help users recognize, diagnose, and recover from errors

Recommendations:
It would be helpful to add input constraints (eg., 200 words) under the field especially for "Corrections".

### Action Items
- [ ] detail exact constraints desired
- [ ] make change as designed

Note: the issue in [the heuristics spreadsheet](https://docs.google.com/spreadsheets/d/1UCoj5ecVQhOBAPNFvzOyySSeJFNtJ34Bx6Ti2cnLma0/edit#gid=0) (item no. 31) asks to link this to #1131 

This is issue was created from a list of food seeker [issues identified](https://docs.google.com/spreadsheets/d/1UCoj5ecVQhOBAPNFvzOyySSeJFNtJ34Bx6Ti2cnLma0/edit?usp=sharing) by a [heuristic evaluation](https://docs.google.com/presentation/d/1mAQV8V9y1ZoQAgBb_mflU8UAGcRogsVfEgZU-hKVvQ0/edit?usp=sharing) completed by 
[@Gigi P](https://hackforla.slack.com/team/U02KZ8WSHHV) & @ryu-jieun  at the end of last year.

**Comment by itserindean** [comment]
I created this with severity 2, as described in [the heuristics spreadsheet](https://docs.google.com/spreadsheets/d/1UCoj5ecVQhOBAPNFvzOyySSeJFNtJ34Bx6Ti2cnLma0/edit#gid=0)
but I think the severity should be:
0 = I don’t agree that this is a usability problem at all

Do we have any evidence this is a real problem for organizations? As  a user on other sites I"ve ben frustrated when trying to provided detailed information to hit an arbitrary character limit. This feels arbitrary to me.

**Comment by entrotech** [comment]
Can anyone describe what kind of constraint would be at all helpful? About all you can do with a single-field free-form text entry is put a minimum and/or maximum number of characters constraint, which strikes me as pretty arbitrary and not helpful.

**Comment by staceyrebekahscott** [comment]
@GigiUxR As per the comments above from @itserindean and @entrotech , can you advise on the reasoning for the constraints given the concerns they expressed?

Moving to Question/ In Review.

**Comment by staceyrebekahscott** [comment]
@GigiUxR Following up on John and Erin's comments- please advise if this is still a usability issue that should be addressed. If no response by this week's meeting, we will go with their assessment and close this issue.

**Comment by itserindean** [comment]
Noting for posterity that it was @ryu-jieun rather than @GigiUxR who identified this as an issue in the Heuristics exercises, but as Gigi is our only active researcher at the moment, it will have to be her who weighs in...

**Comment by staceyrebekahscott** [comment]
Going with assessment given by @itserindean and closing this issue.
