### ISSUE TITLE
 Blue color for just one word in the About heading makes it seem like a hyperlink but it is not.

### ISSUE THREAD

**Issue by itserindean** [hackforla/food-oasis#1284]
Problem:
“ABOUT…” The blue color for just one word in the heading makes it seem like a hyperlink but it is not. Mobile & Desktop.

![Screen Shot 2022-08-10 at 12 53 11 PM](https://user-images.githubusercontent.com/107142453/184008033-6291d3dc-949d-4f92-99eb-d2fc591e9ab3.png)

Step to repro:
goto foodoasis.la
click on hamburger menu
Click on "About"

Severity 2- Minor usability problem: fixing this should be given low priority

Heuristics Violated:
4 Consistency and Standards
8 Aesthetics and Minimalist Design

Recommendations:
Use non blue color and consistent styling of all words in header

### Action Items
- [x] Design mocks up how it would look
- [ ] make change as designed

This is related/could be fixed at same time as https://github.com/hackforla/food-oasis/issues/1285 & https://github.com/hackforla/food-oasis/issues/1286

This is issue was created from a list of food seeker [issues identified](https://docs.google.com/spreadsheets/d/1UCoj5ecVQhOBAPNFvzOyySSeJFNtJ34Bx6Ti2cnLma0/edit?usp=sharing) by a [heuristic evaluation](https://docs.google.com/presentation/d/1mAQV8V9y1ZoQAgBb_mflU8UAGcRogsVfEgZU-hKVvQ0/edit?usp=sharing) completed by 
[@Gigi P](https://hackforla.slack.com/team/U02KZ8WSHHV) & @ryu-jieun  at the end of last year.

**Comment by staceyrebekahscott** [comment]
Making heuristics a priority for Impact Sprints 2022, moving to Prioritized Backlog.

**Comment by staceyrebekahscott** [comment]
@sei1122 Assigned to you.

**Comment by fancyham** [comment]
https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/FOLA-Design-System?node-id=6467%3A10939

**Comment by sei1122** [comment]
This issue is sent to development #1332
