### ISSUE TITLE
Blue headers on FAQ/About/Donate erroneously suggest they are hyperlinks 

### ISSUE THREAD

**Issue by itserindean** [hackforla/food-oasis#1286]
Problem:
Headers on FAQ/About/Donate are confusing because blue color suggests they are hyperlinks which they are not

![Screen Shot 2022-08-10 at 5 53 31 PM](https://user-images.githubusercontent.com/107142453/184047583-1ee47a69-3286-402c-b164-f415f9e95e27.png)

Step to repro:
goto foodoasis.la
click on hamburger menu
Click on "About" or "FAQ" or "Donate"

Severity 1 - Cosmetic problem only: need not be fixed unless extra time is available on project

Heuristics Violated:
4 Consistency and Standards
8 Aesthetics and Minimalist Design

Recommendations:
Use non blue color and consistent styling of all words in header

### Action Items
- [ ] Design mocks up how it would look
- [ ] make change as designed

This is related/could be fixed at same time as #1285 & #1284

This is issue was created from a list of food seeker [issues identified](https://docs.google.com/spreadsheets/d/1UCoj5ecVQhOBAPNFvzOyySSeJFNtJ34Bx6Ti2cnLma0/edit?usp=sharing) by a [heuristic evaluation](https://docs.google.com/presentation/d/1mAQV8V9y1ZoQAgBb_mflU8UAGcRogsVfEgZU-hKVvQ0/edit?usp=sharing) completed by 
[@Gigi P](https://hackforla.slack.com/team/U02KZ8WSHHV) & @ryu-jieun  at the end of last year.

**Comment by staceyrebekahscott** [comment]
Making heuristics a priority for Impact Sprints 2022, moving to Prioritized Backlog.

**Comment by itserindean** [comment]
assigned to Seiko because also related to  https://github.com/hackforla/food-oasis/issues/1285 & https://github.com/hackforla/food-oasis/issues/1284

**Comment by fancyham** [comment]
https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/FOLA-Design-System?node-id=6467%3A10939

**Comment by sei1122** [comment]
This is sent to development #1332
