### ISSUE TITLE
There should be "(Currently) Closed" and "Open Soon" tags in addition to  "Open Now" & "Closing in xx minutes",

### ISSUE THREAD

**Issue by itserindean** [hackforla/food-oasis#1287]
Problem:
There are tags "Open Now", "Closing in xx minutes", and "Temporarily Closed", but not "(Currently) Closed" and "Open Soon". 
![Screen Shot 2022-08-10 at 3 56 46 PM](https://user-images.githubusercontent.com/107142453/184037528-98bc9379-7ab9-4a5c-a193-f88ae26a907d.png)

Severity 2- Minor usability problem: fixing this should be given low priority

Heuristics Violated:
2 Match between system and the real world
4 Consistency and standards

Recommendations:
It would provide more information that users need if these tags can be added. 

### Action Items

- [ ] Design mocks up how it would look with these tags and finalizes wording of tagsz
- [ ] make change as designed

This is issue was created from a list of food seeker [issues identified](https://docs.google.com/spreadsheets/d/1UCoj5ecVQhOBAPNFvzOyySSeJFNtJ34Bx6Ti2cnLma0/edit?usp=sharing) by a [heuristic evaluation](https://docs.google.com/presentation/d/1mAQV8V9y1ZoQAgBb_mflU8UAGcRogsVfEgZU-hKVvQ0/edit?usp=sharing) completed by 
[@Gigi P](https://hackforla.slack.com/team/U02KZ8WSHHV) & @ryu-jieun  at the end of last year.

**Comment by staceyrebekahscott** [comment]
Making heuristics a priority for Impact Sprints 2022, moving to Prioritized Backlog.

**Comment by itserindean** [comment]
Upon reviewing this further I think there could be a value add in adding an "opening soon" tag, but not in adding a "currently closed" tag. As currently implemented the "Open Now" & "Closing in xx minutes" tags call attention to the locations currently open. If everything is tagged, it will only clutter the screen and will no longer effectively call attention to the open locations. @GigiUxR if you agree I will update this issue to reflect that we should only add an 'opening soon' tag

**Comment by GigiUxR** [comment]
@itserindean I personally think that having "Opening in XXX.." is quite valuable ( I imagine we only have this tag showing if it is within a short amount of time - yes?) and not mentally cluttering. Rather, I see myself weighing together  options that are Open Now, with places Opening in 15 minutes, etc.  To move this forward, we could do a quick design preference test with food seeker like-minded respondents to determine what  would be preferred by seekers.

**Comment by qiqicodes** [comment]
Closing this issue as it has been superseded by the new design implementation.
