### ISSUE TITLE
Footer of Main Site 

### ISSUE THREAD

**Issue by yiminng** [hackforla/food-oasis#1289]
### Overview
1. Both Desktop and Mobile Sites
“Food Oasis” in the footer indicates clickable text when hovering above it by responding with a lighter shade of green. But it is not.  

![Screen Shot 2022-08-10 at 9 18 39 PM](https://user-images.githubusercontent.com/109191409/184064132-46c13576-fa53-42bd-8a26-93c3707d8aa5.png)

2. Do we need a footer? - Currently the hamburger bar disappears after scrolling to the end of page.
3. Hamburger bar disappearing in pages is not consistent in mobile/desktop/web browsers 

Heuristics Violated:
 #1 Visibility of system Status

Severity Level 2 as described in [the heuristics spreadsheet](https://docs.google.com/spreadsheets/d/1UCoj5ecVQhOBAPNFvzOyySSeJFNtJ34Bx6Ti2cnLma0/edit#gid=0)

### Action Items

- [ ] Team to decide if we want to keep footer or just make hamburger present consistently on all pages and remove footer 
If we keep footer 
- [ ] make "Food Oasis" in footer link to home page 
- [ ] Have changes be consistent across mobile/desktop/web browsers 

Part of this is issue was created from a list of food seeker [issues identified](https://docs.google.com/spreadsheets/d/1UCoj5ecVQhOBAPNFvzOyySSeJFNtJ34Bx6Ti2cnLma0/edit?usp=sharing) by a [heuristic evaluation](https://docs.google.com/presentation/d/1mAQV8V9y1ZoQAgBb_mflU8UAGcRogsVfEgZU-hKVvQ0/edit?usp=sharing) completed by
[@Gigi P](https://hackforla.slack.com/team/U02KZ8WSHHV) & @ryu-jieun at the end of 2021

**Comment by yiminng** [comment]
I think this can be a Level 1 = Cosmetic problem only: need not be fixed unless extra time is available on project as it currently does not affect how users mainly use the app.

**Comment by staceyrebekahscott** [comment]
Issue #1302 was created as per the team meeting discussion, addressing the concerns of this issue. Closing as not planned as issue is now a duplicate.
