### ISSUE TITLE
Visual changes to indicate hyperlinks in "About Us" and "FAQ" 

### ISSUE THREAD

**Issue by yiminng** [hackforla/food-oasis#1290]
### Overview
Hyperlinks in About and FAQ page does not change colour when hovering over hence not conveying that they are links that can be clicked on. 

Steps to repro:
goto foodoasis.la
goto FAQs - For Volunteers 
goto About Us - Our Team 

Heuristics Violated:
#1 Visibility of system status

Severity Level 2 as described in [the heuristics spreadsheet](https://docs.google.com/spreadsheets/d/1UCoj5ecVQhOBAPNFvzOyySSeJFNtJ34Bx6Ti2cnLma0/edit#gid=0)

### Action Items
- [ ] change responsiveness/look of link to convey that they are clickable 

This is issue was created from a list of food seeker [issues identified](https://docs.google.com/spreadsheets/d/1UCoj5ecVQhOBAPNFvzOyySSeJFNtJ34Bx6Ti2cnLma0/edit?usp=sharing) by a [heuristic evaluation](https://docs.google.com/presentation/d/1mAQV8V9y1ZoQAgBb_mflU8UAGcRogsVfEgZU-hKVvQ0/edit?usp=sharing) completed by
[@Gigi P](https://hackforla.slack.com/team/U02KZ8WSHHV) & @ryu-jieun at the end of 2021

**Comment by yiminng** [comment]
1. I think it can be Severity Level 1 = Cosmetic problem only: need not be fixed unless extra time is available on project as it is currently underlined (indicating it is something different than regular text) 
2. Adding PM Volunteers as it pertains to volunteer information in static page

**Comment by staceyrebekahscott** [comment]
Making heuristics a priority for Impact Sprints 2022, moving to Prioritized Backlog.

**Comment by fancyham** [comment]
@sei1122 Is this issue solved by the work on you did on the static pages?  #1286 

Development issue:
#1332

If so, I think we can close this one out!

**Comment by sei1122** [comment]
No I haven't included this issue. 
We need to review this.

**Comment by Nechir-89** [comment]
@yiminng if this is still open I can work on it!

**Comment by staceyrebekahscott** [comment]
@fancyham @sei1122 Please advise if there is anything @Nechir-89 needs to know, as they have expressed interest in working on this issue. Thanks!

**Comment by fancyham** [comment]
@Nechir-89, I believe @sei1122 is working on standardizing the link colors that we'll be using site-wide (we currently have some colors that are close but non-standard), so keep an eye out for that. ;)

This is the issue for the colors:
- #991

**Comment by Nechir-89** [comment]
@fancyham thanks for letting me know it, since this issue is more for designers I think it would be better if I remove my name from this task and see if I can do another task.

**Comment by sei1122** [comment]
This is link colors
https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/FOLA-Design-%231?type=design&node-id=11065-18199&t=ncDx9b64V4dzH43Q-4

<img width="492" alt="Screen Shot 2023-05-29 at 11 49 21 PM" src="https://github.com/hackforla/food-oasis/assets/19811032/aa399106-e71b-4d95-842b-ba4973ca2ec6">

I talked to @entrotech  on May 16, and all the link colors will be changed to #1976D2.

**Comment by Nechir-89** [comment]
@sei1122 Thank you for letting me know it
