### ISSUE TITLE
Partnership Engagement: Los Feliz Neighborhood Council

### ISSUE THREAD

**Issue by staceyrebekahscott** [hackforla/food-oasis#1291]
### Overview
We would like to establish a partnership with the Los Feliz Neighborhood Council and have them embed Food Oasis onto their website. This is a goal identified for Impact Sprints 2022. 

**Epic Issue**
#1341 Empower LA Data

Los Feliz NC has expressed interest in the Food Oasis tool in the past. We need to reengage with them and find out more of their current priorities regarding food insecurity and their constituents. 

URL: [Los Feliz NC](https://www.losfeliznc.org/)
Website Platform: Wix [Wix Editor: Embedding a site or widget](https://support.wix.com/en/article/wix-editor-embedding-a-site-or-a-widget)
Webmaster: Orlando Valente

Executive Committee:
Jon Deutsch: President
Dan McNamara: VP of Administration
Misty LeGrande: VP of Communication
Amanda Blide: Secretary
Erica Vilardi-Espinosa: Treasurer

- See questions in the comment from 08/31/22

**Comment by staceyrebekahscott** [comment]
I had a meeting with Mellina Stoney- Partnership Manager at Code for America, and we discussed a new approach to partnerships for FOLA. Moving this to Icebox, as the neighborhood council engagement may become a medium to long term goal. Partnerships with our more current partners, such as Food Cycle LA, are being pushed to priority.

**Comment by staceyrebekahscott** [comment]
For Bonnie: 

- When was the most recent conversation with John regarding a partnership with Food Oasis?
- What other HfLA projects have a partnership with the Los Feliz council? 
  - What is the context of those partnerships?
- What is the main reason that a partnership with Los Feliz would benefit Food Oasis? 
- What info should I know about John that would be helpful when engaging with him? 
- Was there any particular reason John was interested in the Food Oasis tool for the Los Feliz constituents?

**Comment by staceyrebekahscott** [comment]
Met with Mellina from CfA, discussed strategy for reaching out to Jon. Draft of email is in progress.

**Comment by staceyrebekahscott** [comment]
[Draft of email to Jon Deutsch- President of Los Feliz NC](https://docs.google.com/document/d/1yqaK4ucf_1B_f43QoCq9qgggLTTaukxHAhBVuEGe78w/edit#)

Sent draft to Mellina from CfA for feedback. 
Sent message to Devs in Slack asking about how well the embed works on Wix.

**Comment by staceyrebekahscott** [comment]
Sent draft to Bonnie via her request form.

**Comment by staceyrebekahscott** [comment]
Moving to Prioritized Backlog, as the current strategy is to prioritize NCs that have food resources already mentioned on their websites.

**Comment by kcoronel** [comment]
Hi @staceyrebekahscott, Bonnie drafted an update to the email you wrote, [here](https://docs.google.com/document/d/1yqaK4ucf_1B_f43QoCq9qgggLTTaukxHAhBVuEGe78w/edit#) and she sent the message and copied the food oasis email address

**Comment by staceyrebekahscott** [comment]
Sent message to Karen via Slack to see if there has been any response to Bonnie's email. We have not received any response in the FOLA email.

**Comment by staceyrebekahscott** [comment]
Karen informed me that Bonnie has not mentioned receiving any response to this email. Closing this issue, and will add further notes re: NCs to #1341 Empower LA Data.
