### ISSUE TITLE
Bug: Link to "Attend a Training Session" in the For Volunteers section of website leads to an Error 404

### ISSUE THREAD

**Issue by staceyrebekahscott** [hackforla/food-oasis#1297]
#### Describe the bug 

In the For Volunteers section on the FAQ page of the website, the link to "Attend a training session" leads to an Error 404 page. 

#### Steps to reproduce the issue

1. Go to [Food Oasis FAQ](https://la.foodoasis.net/faqs)
2. Click on Attend a training session link in the For Volunteers section 
3. See error 

#### What's the expected result?

The link should lead to LA Works: [Help the hungry with phone calls and research](https://volunteer.laworks.com/opportunity/a0C3l00000r3wLvEAI/%E2%9A%99-help-the-hungry-with-phone-calls-and-research)

#### What's the actual result?

<img width="801" alt="Screen Shot 2022-08-17 at 11 12 43 PM" src="https://user-images.githubusercontent.com/98001560/185307858-7a586c91-d922-46b4-8b4b-2c8f0ece5e2e.png">

#### Device configuration
- Device: iMac 
- OS version: 10.14.4
- Browser: Chrome
- Browser version: 104.0.5112.101

**Comment by staceyrebekahscott** [comment]
Moved to Bugs column for immediate review.

**Comment by entrotech** [comment]
The correct link should be https://volunteer.laworks.com/opportunity/a0C3l00000r3wLvEAI
The old one was  https://www.laworks.com/opportunity/a0C3l00000iCS6GEAW

This link is referenced on the Los Angeles, McKinney, Santa Barbara and Portland sites by the 
"VOLUNTEER" and "BECOME A VOLUNTEER" buttons on the Donate page, and
"Attend a training Session" link on the FAQs page.
"
