### ISSUE TITLE
 "Meals" and "Pantries" buttons "Details" page of a meal program/pantry

### ISSUE THREAD

**Issue by yiminng** [hackforla/food-oasis#1298]
### Overview
Mobile and Desktop Sites (iPhone, Chrome & Safari)
1. "Meals" and "Pantries" buttons do not work when users are on "Details" page of a meal program/pantry. 
2. If users click “List”, it closes the “Details” page without letting users know and goes back to the list. 

[Food Oasis.pdf](https://github.com/hackforla/food-oasis/files/9368189/Food.Oasis.pdf)

Steps to repro: 
go on a "Details" page of any Listing 

Heuristics Violated:
#4 Consistency and standards

Recommendations: 
Remove the functions on "Details" page (only enable “Back to List” option) or enable them working. 

### Action Items
- [ ] design team to make changes 
- [ ] dev to update 

This is issue was created from a list of food seeker [issues identified](https://docs.google.com/spreadsheets/d/1UCoj5ecVQhOBAPNFvzOyySSeJFNtJ34Bx6Ti2cnLma0/edit?usp=sharing) by a [heuristic evaluation](https://docs.google.com/presentation/d/1mAQV8V9y1ZoQAgBb_mflU8UAGcRogsVfEgZU-hKVvQ0/edit?usp=sharing) completed by
[@Gigi P](https://hackforla.slack.com/team/U02KZ8WSHHV) & @ryu-jieun at the end of 2021

**Comment by staceyrebekahscott** [comment]
@itserindean I just found this in the Issues list, but it had not been added to the project. Can you check this and evaluate that this is an problem that still needs to be addressed?

**Comment by itserindean** [comment]
Technically yes it would be better if this went away in this case, but I don't think this should be a priority for engineering hours at this point. When the user is in detoured they've explicitly taken action to get there so I don't think they will get confused by this because they are presumably there to find details about a listing.
