### ISSUE TITLE
Consider design changes to the application header for mobile devices.

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#1304]
### Overview
John Huang suggested that the mobile header as shown in the Resources below might be better if we used the normal Food Oasis logo, instead of the "stacked" one, and possibly eliminate the "Locate Free Food In Los Angeles" text as well.

- The logo in this view doesn’t match the logo used elsewhere on the site 
- This version of logo (white text knocked out of green background) saves horizontal space, but is rather illegible at this small size.
- The text looks clumsy with awkward line breaks.  Competes with logo.

We should make this header feel in-line with headers on the desktop version and on the landing page.

### Action Items
- [x] Consider these suggestions and propose a new design

### Resources/Instructions
Current mobile header
![image](https://user-images.githubusercontent.com/9939032/185526031-3fe89a8f-782f-4727-b076-77126ac7894c.png)

Desktop header
![Food Oasis desktop header](https://user-images.githubusercontent.com/3376957/185540249-9d467163-f62a-49e9-bd25-275e3bfd3bd7.png)

**Comment by fancyham** [comment]
Thanks everyone for the discussion.

- The logo is different from the desktop, so confusing branding. Looks like a mistake.
- The problem with the existing is that the logo is so small that it’s pretty illegible.
- The text looks clumsy, often with a weird line break, and a bit like an ad.

Based on our conversation, I put together four variations (please feel free to add more)

I tried to find a balance between the logo, feeling modern with some whitespace, and if possible, explaining/hinting what the site is about.  

Take a look!
@sei1122 @JohnHaoHuang @entrotech @staceyrebekahscott @itserindean @rylantalerico 

![Comparison array - Round 1 (2022-08-18)](https://user-images.githubusercontent.com/3376957/185534518-42b25a45-50c7-474c-8730-0ab37c474dcd.png)

My favorites in order are: C, A, B, D — I currently think that the text is helpful for first-time viewers, and may be helpful for when we’re embedded in other people’s websites.

**Comment by staceyrebekahscott** [comment]
I like B, A, C, D. 

The carrot alone looks too much like Instacart's logo. Not sure if that might become a problem.

**Comment by staceyrebekahscott** [comment]
Approved and moved to Prioritized Backlog, pending assignment by UI-UX team.

**Comment by itserindean** [comment]
In order, I prefer:  B, C, A, D.

**Comment by sei1122** [comment]
I like B, C, A, D

C could be good if we were scandalized by each location have own area name beside logo like in Hawaii and Santa Barbara.

**Comment by fancyham** [comment]
Thanks, keep ‘em coming!
@entrotech @rylantalerico @JohnHaoHuang @GigiUxR and anyone else I missed

**Comment by nkiwan** [comment]
I'm late to this but B is also my top choice. My ranking: B, A, C, D.

**Comment by fancyham** [comment]
@entrotech, The design is done here — we're removing the descriptive text and using the standard Food Oasis logo.  

Not sure if this should be marked done or what, so please close out once you've created a new task for it?  Thanks!

**Comment by staceyrebekahscott** [comment]
Moved back to Questions/ In Review, awaiting response from John D. re: dev tasks.
