### ISSUE TITLE
Fix links to LA Works Volunteer Opportunity

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#1305]
### Overview
The link to volunteer with LA Works for Food Oasis has changed to https://volunteer.laworks.com/opportunity/a0C3l00000r3wLvEAI

### Action Items
Modify the LA Works links wherever they appear in the application

### Resources/Instructions

The old link was https://www.laworks.com/opportunity/a0C3l00000iCS6GEAW

**Comment by prasanta10** [comment]
I would like to contribute to this issue.

**Comment by staceyrebekahscott** [comment]
Moving to Bugs column. This is a duplicate of #1297 and it appears as if PRs have been created on both issues. Sending a message on Dev Slack channel for clarification.

**Comment by entrotech** [comment]
Dupllicate of Issue #1297
