### ISSUE TITLE
Volunteer Options on Donate page are redundant

### ISSUE THREAD

**Issue by staceyrebekahscott** [hackforla/food-oasis#1315]
### Overview
There are 2 Volunteer options on the Donate page that link to the same page on LA Works website. One of the should be removed as they are redundant (the orange has less information and should be removed from the site). 

<img width="1142" alt="Screen Shot 2022-08-21 at 10 05 45 PM" src="https://user-images.githubusercontent.com/98001560/185843543-4b246c44-4f57-471b-b006-b9115e91440d.png">

### Action Items

- Consult with the PM and Dev team on removing the volunteer option in orange.

**Comment by staceyrebekahscott** [comment]
@entrotech @itserindean @rylantalerico @yiminng I think the Volunteer option in orange should be removed, as it is a redundant feature on the Donate Page. Please advise if you agree/ disagree. 

Moving to Questions/ In Review.

**Comment by itserindean** [comment]
I agree. I like the "Want to give your time instead?" phrasing that justifies this button on the donate page. What if we did something like this: (Rough mockup by PM not designer for illustration only...)  also, i was on the fence about making teh button "volunteer" instead of "become a volunteer"

![Screen Shot 2022-08-21 at 11 21 30 PM](https://user-images.githubusercontent.com/107142453/185852868-e1f908f0-341e-4709-ad55-0ffe0cb1c708.png)

**Comment by staceyrebekahscott** [comment]
I like this mockup. And I think just "Volunteer" for the button works best.

**Comment by itserindean** [comment]
@staceyrebekahscott @sei1122  should we roll this into the updates for #1284 , #1285 & #1286 ?

**Comment by staceyrebekahscott** [comment]
That makes sense to me if it is not too much work for Seiko.

**Comment by itserindean** [comment]
Also I agree with @staceyrebekahscott that it should just say "volunteer"

**Comment by sei1122** [comment]
I will include this update to #1284, #1285 & #1286

**Comment by staceyrebekahscott** [comment]
@sei1122 If it makes sense with your workflow, please see if you can consolidate these issues so we don't have so many open. If you think you're close to having them completed, then wait and close out all 4. In other words, don't do more work to consolidate if you are almost done. Issue has been assigned to you.

**Comment by sei1122** [comment]
The design is close to finalization. 
After this week's review and I need to do more iterations, I will consolidate the issue.

**Comment by sei1122** [comment]
This is sent to development #1332.
