### ISSUE TITLE
Remove Food Oasis site for Oregon

### ISSUE THREAD

**Issue by staceyrebekahscott** [hackforla/food-oasis#1317]
### Overview
We were working with the Code for Portland brigade of CfA for a while, but they determined that the Oregon Food Bank has a comprehensive pantry/ meal program listing [here](https://www.oregonfoodbank.org/find-support), and decided that a Food Oasis site for Oregon would be redundant. I think this site can be dropped.

### Action Items

- Consult with PM team to confirm this site can be removed.

**Comment by staceyrebekahscott** [comment]
@itserindean @rylantalerico @yiminng The details in the Overview were provided by @entrotech . I concur with his assessment that this site can be dropped. Please advise if you concur or not.

**Comment by itserindean** [comment]
I concur.

**Comment by staceyrebekahscott** [comment]
@entrotech We confirmed as a PM team that this site can be removed. Please proceed.

**Comment by staceyrebekahscott** [comment]
@entrotech A reminder to proceed with removing this site.

**Comment by staceyrebekahscott** [comment]
@entrotech A reminder to proceed with removing this site.
