### ISSUE TITLE
Remove Food Oasis Site for Northern CA

### ISSUE THREAD

**Issue by staceyrebekahscott** [hackforla/food-oasis#1318]
### Overview
The California site was proposed by Joel Parker-Henderson (a former member of HfLA) during 2019, specifically to address food insecurity in Northern California due to the wildfires that year, but the scope was pretty large, and we were never able to collect comprehensive data across the state. We also ran into some resistance from food banks (i.e. the Redwood Food Bank) that did not want us publishing the data for their outlets, out of concern that we would not be able to keep our listings current on an ongoing basis. I think this site can be dropped.

### Action Items

- Consult with the PM Team to confirm this site can be removed.

**Comment by staceyrebekahscott** [comment]
@itserindean @rylantalerico @yiminng The details in the Overview were provided by @entrotech . I concur with his assessment that this site can be dropped. Please advise if you concur or not.

**Comment by itserindean** [comment]
I concur.

**Comment by staceyrebekahscott** [comment]
@entrotech We confirmed as a PM team that this site can be removed. Please proceed.

**Comment by staceyrebekahscott** [comment]
@entrotech A reminder to proceed with removing this site.

**Comment by staceyrebekahscott** [comment]
@entrotech A reminder to proceed with removing this site.
