### ISSUE TITLE
Build a Slide Deck for an introduction to Food Oasis / Presentation at Brigade Congress 2022

### ISSUE THREAD

**Issue by staceyrebekahscott** [hackforla/food-oasis#1321]
### Overview
We need a slide deck that we can use to introduce Food Oasis to new team members, new partnerships, etc. It should be about 6-8 slides. If more specifics are needed, ex: for a presentation to a potential new partner, we can add slides to customize. 

### Action Items
Slides should include:

- Overview of Food Oasis (why it was created, how long has it been in effect, who is it for)
- Why Food Oasis is different from other Food pantry directories? 
- Stats on Food Insecurity nationwide and in Los Angeles 
- Tour of the website (an explanation of the ideal user journey)
- Ways to get involved (volunteer, donation and partnership opportunities)

**Comment by staceyrebekahscott** [comment]
@itserindean Assigned to you.

**Comment by itserindean** [comment]
I created an initial draft in powerpoint and converted it to google slides so anyone could make changes/comment. It's particularly lacking in details about:
-Why Food Oasis is different from other Food pantry directories
-How to get involved through partnering

Open to notes/suggestions on ANYTHING
https://docs.google.com/presentation/d/1lZfIqgZEHGBZiUUgQzu1G0oh2JGR-aMzZPby-NE4zZ0/edit?usp=sharing

**Comment by staceyrebekahscott** [comment]
@itserindean The link is giving me an Access Denied message. Is it located in the FOLA Shared Drive?

**Comment by itserindean** [comment]
It is in the FOLA Shared Drive: Food Oasis > 00_PMO > PM Documents. I'll change permissions to anyone with link

**Comment by itserindean** [comment]
@rylantalerico 
Open to notes/suggestions on ANYTHING. I mentioned above a few things in particular it's lacking...
https://docs.google.com/presentation/d/1lZfIqgZEHGBZiUUgQzu1G0oh2JGR-aMzZPby-NE4zZ0/edit?usp=sharing

**Comment by staceyrebekahscott** [comment]
FOLA needs to build a Communications Guide. This is a set of collateral that we can use to make slide decks and with our logo and consistent branding. Upon searching in the Drive, most of the slide decks about FOLA are different. This guide will make it so we can have consistency going forward. 

See link to Code for America's guide for their Get Your Refund Project: [Get Your Refund Communications Guide](https://docs.google.com/presentation/d/1b67e6ubqqKgFTf7l1A9srHDrCEIk5kprRf9JldS5RNI/edit#slide=id.g8078b36bb8_0_35)

We should have one of the new designers work on this before we continue building this slide deck. 

@itserindean Removing you from this issue and moving to the Backlog. We will get one of the designers to pick it up once we have a Communications Guide.

**Comment by staceyrebekahscott** [comment]
Assigning this to myself. Seiko is going to help with this. [Hack for LA: Food Oasis - Brigade Congress 2022 Deck](https://docs.google.com/presentation/d/17WWB4gsCWZuW8mcS6KAfomixbmpuUJUKCd7PBvQ9Mwk/edit?usp=sharing)

@sei1122 I have added you as an editor to the Slide deck. It is currently in my Code for America Drive, but will be moved to our Drive after Brigade Congress.

**Comment by sei1122** [comment]
Here is the process
1. Find templates
2. Pick a template
3. Change the template to the Food Oasis theme
4. Format content
5. Add illustration based on content if you'd like

**Comment by staceyrebekahscott** [comment]
Slide Deck template: [Food Oasis](https://docs.google.com/presentation/d/1w-RUsEY88Dp8hPE9nd1U878lx8CVwF-UUMvrSH6V71s/edit#slide=id.g35f391192_00)

**Comment by staceyrebekahscott** [comment]
[Hack for LA | Food Oasis Overview Slide Deck](https://docs.google.com/presentation/d/13YcAKGS84X9B4rmqS1Ah98kpsDRtpJjk4izbBDYv3iA/edit#slide=id.g173838d392e_0_0)

This slide deck does not include stats on Food Insecurity as mentioned in the Overview. That slide can be added later if needed. 

This slide deck currently resides in the Impact Sprints 2022 folder in Drive.
