### ISSUE TITLE
agenda: how to transfer domain registration for foodoasis.la

### ISSUE THREAD

**Issue by itserindean** [hackforla/food-oasis#1326]
### Overview
- [ ] Bring Bonnie up to speed on #1310.
- [ ] Present[ research on alternative sites for registration](https://docs.google.com/spreadsheets/d/1pyiPueqeJlfBopJOZDYBxR-2s_8JCwQKqgLgkFljZzU/edit?usp=sharing)
- [ ]questions
   - [ ] How do domain purchases work with Hack for LA? 
   - [ ] How do we spend money/get reimbursed?)
   - [ ] Are there any best practices for choosing a registrar?
- [ ] RISKS/urgency
   - Domain transfers are often limited within 7 days of expiration 
   - which means we must initiate a transfer by 8/31. 
   - If we fail to do this, we risk being unable to transfer our domain to a new site 
   -  *extreme case* we risk losing the stie all together. 
      - (we could likely find *Some* place to register but may pay a premium. 

- [ ] Document the process we follow for transferring the domain.
- [ ] Make sure we record on the Food Oasis calendar when the domain expires. 
- [ ] Find out what is going on with foodoasis.net and develop a plan for what to do when that is set to expire. 

### Action Items
Add comment to this issue with your proposed agenda item. if item warrants an issue of its own please start a [new issue](https://github.com/hackforla/tdm-calculator/issues)

**Comment by ExperimentsInHonesty** [comment]
I left a note on  https://github.com/hackforla/food-oasis/issues/1310


Q:  How do domain purchases work with Hack for LA? 
A: I register them, I expense them

Q: How do we spend money/get reimbursed?) 
A: Code for America only allows three people on the expense account, and I am one of them.  So I can buy things and expense them against funds we have from donations.  Mostly I just pay for stuff out of pocket.

Q:  Are there any best practices for choosing a registrar?
A: I don't buy domains that are not .net, .com, .org and I register them at google domains.  The domains we have that are not those, are either legacy or someone well meaning on a team registered them, and its always a pain or expensive to maintain them.

**Comment by entrotech** [comment]
FoodOasis.net domain is already under Hack for LA control, and expires 7/18/23.  Most of the rest of this is taken care of under Issue #1310. Now that both foodoasis.la and foodoasis.net are under Hack for LA admin control, it would be a good idea to have a calendar of expiring domain registrations, though it might be at the Hack for LA organization level.
