### ISSUE TITLE
Bug: Volunteer Portal: Button to pass listing along does not appear

### ISSUE THREAD

**Issue by staceyrebekahscott** [hackforla/food-oasis#1328]
#### Describe the bug 

On the page to update the listing, there should be a button to pass the issue along to another volunteer, and on my screen there was no button option. Screenshot is of the Identification page, but I checked all pages and there is no button. 

What is the user’s goal?: To be able to pass the issue along to another volunteer.

#### Additional details / screenshot

<img width="1392" alt="Screen Shot 2022-08-31 at 8 53 27 PM" src="https://user-images.githubusercontent.com/98001560/187828702-4b2242ff-35b4-4d8c-b154-9f597cb44823.png">

#### Device configuration
- Device: iMac
- OS version: 10.14.4
- Browser: Chrome
- Browser version: 104.0.5112.101
- Tried in regular and incognito mode, same result.

**Comment by sei1122** [comment]
I joined a volunteer session and this is an organization I validated.
There are 3 buttons at the button.

Once volunteers sign up for the Food Oasis account and Jordan can assign organizations to volunteers.
The organization's data interface is basically the same but the buttons are different between admin and volunteer.

<img width="703" alt="Screen Shot 2022-08-31 at 9 27 11 PM" src="https://user-images.githubusercontent.com/19811032/187831431-f734c652-d823-4f21-bd62-586f0caa7b71.png">

**Comment by entrotech** [comment]
@staceyrebekahscott When you took that screenshot, were you logged in?  You would not see buttons if you are not logged in or logged in with an account that does not have the "Data Entry", "Coordinator", or "Admin" role.

**Comment by staceyrebekahscott** [comment]
Closing this issue as resolved. I have since been given the Admin role.
