### ISSUE TITLE
Try out and possibly migrate to new github Projects kanban

### ISSUE THREAD

**Issue by fancyham** [hackforla/food-oasis#1329]
Github has a new "Project Management" kanban board that can also be viewed as a spreadsheet — seems quite powerful and could add a lot of features that we'd like to use for project management and sorting issues.
https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/about-projects

So we're going to try it out and switch if it feels good

- [x] Make a copy of our current kanban in the new system to play with
- [x] Test it out for a week or so
- [x] x If it seems useful and works for us then: delete playground copy, make actual migration, close/archive previous kanban.
- [x] If we're not ready, delete this beta test project

**Comment by fancyham** [comment]
I've created a copy of our kanban — new link is here:

https://github.com/orgs/hackforla/projects/17/views/1

Beware: I think that moving things between columns actually changes the issue permanently, so be careful.

Please try creating new views!  They seem quite powerful.

- I noticed the our "text notes" in the references column are no longer visible the way they used to be.

I believe the two automations we had have been migrated over automatically (they were the standard github ones)
Previous 'automations':
![Screen Shot 2022-09-01 at 8 56 15 PM](https://user-images.githubusercontent.com/3376957/188056185-cfd1b051-a54d-4def-accf-b0b7324e5b96.jpg)
![Screen Shot 2022-09-01 at 8 56 59 PM](https://user-images.githubusercontent.com/3376957/188056188-27573752-1e55-4c8e-9b3a-2cc14f764c72.jpg)

New 'workflows': (these seem to be default workflows)
![Screen Shot 2022-09-01 at 8 57 27 PM](https://user-images.githubusercontent.com/3376957/188056194-77f88cba-17b8-4a5d-b297-b89d0065f104.jpg)
![Screen Shot 2022-09-01 at 8 57 31 PM](https://user-images.githubusercontent.com/3376957/188056201-9789f351-7674-4033-89ca-5f8557cd0111.jpg)

Paging PMs and senior folks: @entrotech @staceyrebekahscott @itserindean @rylantalerico @sei1122 @GigiUxR   — please add anyone I missed

**Comment by fancyham** [comment]
Please continue using the old kanban for actual work.

Play with views and navigation — be aware that while we're working with 'live' issues, it seems I can move items between columns in the playground version and that does not affect the old kanban.  

![image](https://user-images.githubusercontent.com/3376957/188057899-df02e79d-1b72-4f7a-a25d-b0da2df86272.png)

![image](https://user-images.githubusercontent.com/3376957/188057921-24327ddf-4914-4259-8d72-e8093ebef06e.png)

![image](https://user-images.githubusercontent.com/3376957/188057948-9615c393-103a-4067-9aad-37584912993a.png)

Give it a spin and let's discuss at our next meeting and take a temperature about how folks feel about this new version.

**Comment by staceyrebekahscott** [comment]
We need to get permission from Bonnie before we do this. There may be reasons this has not been recommended across HfLA if some projects are in this new format and some are in the old. 

Also, I am not seeing the same options as the ones in the screenshots above. I wonder if different browsers / browser versions accounts for this difference.

**Comment by fancyham** [comment]
Those screenshots are from the github instructions as examples, but I created a new spreadsheet view of my own that shows items in milestones that are prioritized or in progress: https://github.com/orgs/hackforla/projects/17/views/3

The spreadsheet view seems more compact than the kanban, so that's a plus.

**Comment by fancyham** [comment]
At our recent meeting, we found that the new interface was nice though it was missing some things that we were used to like milestones and some other metadata.  The spreadsheet view seemed well received by our team.

My gut feeling is that this is the 1.0.  We'll want to balance the lack of certain features for the availability of new ones (like the spreadsheet view)

We wanted to get feedback from Hack for LA's admin team so I sent in a request for their opinion.  Will update when that arrives.

@entrotech @itserindean @staceyrebekahscott

**Comment by fancyham** [comment]
Got an update from Bonnie — she’d like us all to hold off for now:

Bonnie: 
“Hi PMs  -- You may have noticed that GitHub has launched a new type of project board.  Please hold off on using them for now.  Read the thread for more details

The website team had a 2 hour meeting with GitHub and here is why we want everyone to hold off
1. When you make the board it will have to have your project name, unlike the current boards, because they will all be in one place, so having multiple project boards be called "project board" or project management" will make it impossible to know which one is yours. 
    a. Please add your project initials to your project board now.  (e.g., https://github.com/hackforla/food-oasis/projects/8 would be called FOLA: Project Management)
2. Currently, they will be changing this hopefully soon, when you go to one of the new boards, you leave the menu for your project repo.  So moving from board to issues to wiki tabs is impossible. You have to navigate back to your repo and the menu of how to do that has changed to a new placement that is not intuitive.
3. Many projects have links in their wiki to the current boards.  Each project will need to write up a migration plan for what links will need to be changed to make sure there are not out of date links on their project
4. Many projects have cards on their project board.  These will be automatically converted to draft issues and they don't work the same way as cards, so that information will need to be part of the projects migration plan.  Probably these links will need to be moved to the wiki.

See also this wiki page with details
https://github.com/hackforla/admin/wiki/GitHub:-Project-Boards
“

https://hackforla.slack.com/archives/C01Q24YF56J/p1664037427096299?thread_ts=1662850839.250869&channel=C01Q24YF56J&message_ts=1664037427.096299


So sounds like HfLA is holding off for now which is fine — they’re aware of it so let’s wait for when they say it’s ready for us.

In the meantime, how about we delete the ‘playground’ version we created as a test (as planned) so that we don’t have any confusions going forward?  I’ll post a poll to the leads in slack to confirm.

**Comment by itserindean** [comment]
Sounds good. yes let's delete the playground now as planned.

**Comment by itserindean** [comment]
@fancyham I still see the playground, it doesn't seem deleted.

**Comment by fancyham** [comment]
Just deleted the playground project.

Reading over the 'hold off for now' reply from the HfLA admins, the issues holding them back see to be relatively minor UI issues (from my perspective) vs the benefits so PMs, could you keep your ears open in the #PM channels?

Let's keep an eye on this feature and check in with admins again in a month or two and keep pushing for it — I think the spreadsheet views could be really powerful for a birds-eye view of what's happening in the project.

For us, we'd just have to move card/note items out of our 'reference' column and into a wiki, and that's about it.

**Comment by fancyham** [comment]
If anyone has suggestions, I'd love for us to have a way to make sure we revisit this kanban issue periodically until we can start using it.

**Comment by staceyrebekahscott** [comment]
Either a calendar reminder or a note on our Leads/PM meeting agenda to check in Nov 1, and then monthly until we can do it. I'll add a reminder for myself on my personal calendar. 

Also, I've been thinking about the reference stuff for a while. A lot is outdated and doesn't need to be there, but much of it should be in the Wiki. We will start that conversation amongst the PMs and get it organized.

**Comment by staceyrebekahscott** [comment]
@fancyham Are there any more notes you want to add? Or can this issue be marked as closed?

**Comment by fancyham** [comment]
I followed up and good news: we got confirmation from Karen on the Hack for LA admin team that we can now use the new GitHub Projects format, whenever we like. 

They just ask that we label our boards like this:
 FOLA : Dev
 FOLA : PM 
 so that it works with their own processes.

Once we start using it, let the admin team know so that they can update the boards they’re following.

**Comment by fancyham** [comment]
(late update) Last month, at the leads meeting, we collectively decided that the dev team should pilot migration to this new system. 

Why? Becuase the team that most-needed a tool that allowed them to have different custom views, custom tags, and kanban was the dev team, so if it works for them, it would work for all of us.

So with this is mind, dev team, please give it a try!  The goal is to get all the teams onto a single “Projects” board, but also allow each of the teams to have their own custom views that make sense for their needs.

Please contact me with any questions or if you’d like help setting it up — it’s all new to me but I think should be doable and rewarding.

**Comment by fancyham** [comment]
2024-06 - we have successfully migrated to the new GitHub Project /Kanban boards. Thanks Qiqi who did the work!
