### ISSUE TITLE
Make changes to the Header appearance on Mobile devices

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#1331]
### Overview
Design Issue #1304 contains discussion and decisions to make changes to the application header (on map page for example). Need to implement these changes.

### Action Items
- [ ] Change from "stacked header on small width devices to using the standard desktop log on all width devices.
- [x] Remove the tag line from the center of the header on narrow devices (it's not there on wider devices).

### Resources/Instructions
See Issue #1304 for wireframe.

**Comment by staceyrebekahscott** [comment]
@entrotech Issue approved for work. Updated labels and milestone, moved to prioritized backlog for dev assignment.
