### ISSUE TITLE
### Resources

### ISSUE THREAD

**Issue by sei1122** [hackforla/food-oasis#1334]
### Resources

[Volunteer Presentation Recording](https://us02web.zoom.us/rec/share/PgZO63p4R4DtFwWHTOsjv08vmo8VMmMsdEe1hhdyuIrGXprJeY6fnoU2ZjZ1TK60.3WwhwDzq-eWhEjtf) (Passcode: 94?za&U+ )
[Articles and News](https://docs.google.com/spreadsheets/d/1XAXtN0Z1Q68TiuvAXFComCVj1LcWzcqXetNyK433WZA/edit?usp=sharing)

**Comment by staceyrebekahscott** [comment]
@sei1122 This issue appears as if it was added to the test project. Is that what you intended? The issue will disappear if we do not end up transitioning to the new project format.

**Comment by sei1122** [comment]
I think I edit this on the testing Kanban board. 
I will close this.
