### ISSUE TITLE
link for tonight's onboarding in meetup doesn't seem to be working.

### ISSUE THREAD

**Issue by itserindean** [hackforla/food-oasis#1337]
### Overview

- https://us02web.zoom.us/meeting/register/tZUtdeGvrTMoHtKkRwm7R8Kl8r9TXL73-UY9 takes you to a zoom webpage that says "Uh oh!- You seem to have lost your way."
- Thread of people asking for help in [#new-joiner-orientation](https://hackforla.slack.com/archives/C04S7PNCU)
- how do we get people the  correct link ASAP?

### Action Items
Add comment to this issue with your proposed agenda item. if item warrants an issue of its own please start a [new issue](https://github.com/hackforla/tdm-calculator/issues)

**Comment by itserindean** [comment]
![Screen Shot 2022-09-12 at 5 15 46 PM](https://user-images.githubusercontent.com/107142453/189781596-e39b2258-1ee1-4b5e-8983-650769ddec17.png)
is where the link takes you

**Comment by staceyrebekahscott** [comment]
@itserindean Does this still need to be an issue in our project?

**Comment by itserindean** [comment]
closed because underlying issue was fixed wehn @ExperimentsInHonesty  updated the zoom link
