### ISSUE TITLE
#### Onboard Sarah Chee @cheesarah 9-18-22

### ISSUE THREAD

**Issue by cheesarah** [hackforla/food-oasis#1346]
#### Onboard Sarah Chee @cheesarah 9-18-22

**New member, do these and check off as you complete them:**
- [ X] Join Slack channels
  - [x] ```#fola```
  - [x] ```#fola-devs```
  - [ ] Note that our Slack only keeps chat history for two weeks!  Use GitHub comments for issue discussion or to record/summarize Slack discussions so that future readers can understand how decisions were made.
- [x] Write your info on the [Roster](https://docs.google.com/spreadsheets/d/1--JQ5WTLpQcBkSC5wbvQKFZ3Mw8OoHK9ToyXrymVGnM/edit?usp=sharing)
- [x] Access [Figma Team file](https://www.figma.com/team_invite/redeem/VntY2vYvcg5jHhRouZjOf9)
- [x] Read [Food Oasis Wiki](https://github.com/hackforla/food-oasis/wiki)
- [x] Join the [Volunteer session](https://www.laworks.com/opportunity/a0C3l00000ohIRxEAM/%E2%9A%99-help-the-hungry-with-phone-calls-and-research) if you can. Work LA organizes volunteer sessions every Sat. volunteers contact to organizations to verify information so that site info is up to date.  Good to learn how volunteers use our site.
- [x] Check Git Kanban board. We use this to track tasks.
https://github.com/hackforla/food-oasis/projects/8
- [x] Visit the [Resources column](https://github.com/hackforla/food-oasis/projects/8#column-8946444) Check out cards: 
  - [x] Functional Figma files (which is where we do our designs)
  - [x] Design Assets
  - [x] User Research 
- [x] Bookmark https://www.foodoasis.la/  (This is the live main site)
- [x] Bookmark https://devla.foodoasis.net/  (This is our development / testing site)

**FOLA team**
- [x] GitHub
     - [x] Add to appropriate team ('read'?)
- [x] Figma
  - [x] Send invite main
  - [x] Send invite research
- [x] Google Drive
   - [x] Add to shared HFLA drive as Contributor
- [x] Add to Google calendar invites
   - [x] [Thursday at 6pm PT - All-team meeting]

_Originally posted by @itserindean in https://github.com/hackforla/food-oasis/issues/1246#issuecomment-1250349820_

**Comment by itserindean** [comment]
closing since you've checked these off

**Comment by cheesarah** [comment]
thank you! 

Sarah Eunkyung Chee

“Love is the bridge between you and everything”  Rumi
