### ISSUE TITLE
Food-seeker site : responsive layouts have inconsistent breakpoints

### ISSUE THREAD

**Issue by fancyham** [hackforla/food-oasis#1354]
### Overview
The public site http://la.foodoasis.net is a responsive website, meaning that the layout of the UI changes based on the screen size.  This allows the UI to optimize itself for different device sizes — smartphone, tablet, computer.

Our site currently has inconsistent breakpoints (when a new layout kicks in), with odd breaks like 607 px-wide (see attached)

[Site Map - Food Seeker - Public Site - Responsive Layouts.pdf](https://github.com/hackforla/food-oasis/files/9679431/Site.Map.-.Food.Seeker.-.Public.Site.-.Responsive.Layouts.pdf)

### Action Items
- [x] Make breakpoints more consistent.  
  - [x] Contact design team if new new breakpoints needed or questions.
  - [x] If there are reasons for unusual breakpoints, bring up with design team

**Comment by junjun107** [comment]
I updated the following breakpoints in global theme with screen width : (https://v4.mui.com/customization/breakpoints/#breakpoints)

    xs, extra-small: 0px
    sm, small: 600px 
    md, medium: 960px
    lg, large: 1280px
    xl, extra-large: 1920px

If there is a breakpoints value design team wants to change, just let me know.
