### ISSUE TITLE
Update content in About US static page to be more current.

### ISSUE THREAD

**Issue by itserindean** [hackforla/food-oasis#1365]
### Overview
When a user clicks on the "[About Us](https://foodoasis.la/about)" page they expects to learn current information, but our page is about 2 years old in content. The current page references Covid A LOT and most recent date listed in 2020. Should reflect current number of organizations in the data base.

### Action Items

- [x] research latest statistics
- [x] Language clean up ideation: https://docs.google.com/document/d/15S6ApvAydqan0esH7WALr2QwSKl_BLe8UJxHo0kSs5I/edit
- [x] author new text: Final updated language: https://docs.google.com/document/d/18fXCo7UwfxhzV1mwFruJFstiNz5CLeUqKhaZofRk3qQ/edit
- [x] Mockups for updated language (frame 319): https://www.figma.com/file/GnvrOCZiWBKOMxjKTFcq4w/FOLA-Content-team-library?node-id=411%3A2&t=e9BE7VCcFqkbTPsu-0
- [x] update the site

### Resources
Design requested Content work initially in gdocs. Research and content audit lives here https://docs.google.com/document/d/1U_l9p1DHYPHzSpS4sonEDCpmJ3r6YHgi_C17rgN3vnM/edit#

**Comment by staceyrebekahscott** [comment]
@itserindean You added this to In Progress but no one is assigned. Should this be assigned to Sam?

**Comment by ShruthiVen28** [comment]
Updated language: https://docs.google.com/document/d/15S6ApvAydqan0esH7WALr2QwSKl_BLe8UJxHo0kSs5I/edit
Mockups for updated language : https://www.figma.com/file/GnvrOCZiWBKOMxjKTFcq4w/FOLA-Content-team-library?node-id=411%3A2&t=e9BE7VCcFqkbTPsu-0

Content will be passing this to Design on 2/9/23

**Comment by ShruthiVen28** [comment]
To streamline Content passing over files to Design, we ask the PMs and Leads to please check against their name as a sign of approval for our About Us changes (as discussed during the PM and Leads meeting on 2/9):

- [ ]  @staceyrebekahscott
- [ ]  @itserindean
- [ ]  @entrotech
- [ ]  @fancyham
- [ ]  @sei1122
- [ ]  @GigiUxR

Thanks!

**Comment by fancyham** [comment]
Design team reviewed and gave the thumbs-up. 

In future versions, I'd personally love to bring back some of that righteous fire 🔥 but also totally understand that's not (yet) in our voice and style creative brief/goals (per your earlier survey of team leads). 

(BTW, please add link or summary of that list of priorities to this issue as context and background)

**Comment by itserindean** [comment]
Everything looks good to me except for a SUPER minor thing, it looks like there are 2 spaces in "regularly  to" 
**Context:** 
Proposed “Our Team” Updates
Food Oasis is a 100% volunteer-run project. We are part of [Hack for LA](https://hackforla.org/). Our team includes product managers, researchers, designers, developers, writers and data validators who maintain this web-based directory. We verify each listing in our directory regularly  to ensure the contact information, hours of operation, and services provided are accurate.

**Comment by staceyrebekahscott** [comment]
@ShruthiVen28 @bduhe Since issue #1552 has been created and the work handed off to the Design team, can we mark this and issue #1281 as Done?

**Comment by GigiUxR** [comment]
@ShruthiVen28 @bduhe I signed off but made my comments and raised some questions in the figma doc. Hope it helps!
