### ISSUE TITLE
get Oportun paperwork to receive $500 donation

### ISSUE THREAD

**Issue by itserindean** [hackforla/food-oasis#1366]
### Overview
The FOLA team received an email from LA Works that one of their corporate partners (Oportun) would like to donate $500 to us! They have requested 3 pieces of documentation

### Action Items
They have requested:
- [x] W-9 Form
- [x] IRS Determination Letter
- [x] ~~Grant Invoice for $500 that references “Oportun Volunteer Week 2022”~~ 
- [x]  donation acknowledgment letter 500 that references “Oportun Volunteer Week 2022”
- [x] Similar but unrelated question: we have some students volunteering through UCLA working on data validation and one has asked to see our “form 990" for an assignment. Do we fill out one annually?

**Comment by itserindean** [comment]
w

**Comment by itserindean** [comment]
On 10/11: Received IRS Determination Letter from @ExperimentsInHonesty & form 990 from Karen.
still need:
- [ ] W-9 Form
- [ ] Grant Invoice for $500 that references “Oportun Volunteer Week 2022”

Karen shared in slack #admin "Bonnie was checking with CFA regarding W-9 and grant invoice. From personal experience, CFA didn’t have a template MOU for me to use with Code for Hawaii. So I googled some stuff and created my own template. I hope they come back with a grant invoice but plan b might be creating a template internally."

**Comment by staceyrebekahscott** [comment]
@itserindean Any response on whether Oportun can/ will make a donation via Code for America? [Donate to Code for America](https://codeforamerica.org/donate/?utm_source=website&utm_medium=header_donate_button)

**Comment by itserindean** [comment]
My contact at LAWorks (Kelsey) forwarded the request on Friday but has not sent an update yet. I checked in again today.

**Comment by staceyrebekahscott** [comment]
@itserindean Checking in- what is the status on this? Have you heard from Kelsey?

**Comment by itserindean** [comment]
Finally heard back this afternoon! Kelsey looped in Rachel McMahan from her team who was supposed to connect with Oportun. She says: "Thanks for following up. I lagged on passing this message to Oportun so we're waiting to hear back from them. My apologies for the delay here!"

**Comment by itserindean** [comment]
heard back this morning! 
Unfortunately, Oportun cannot pay the grant online via the link you sent along. They have to process the grant with an invoice & W9. Please let me know if you're able to get these things. The invoice can be addressed to Oportun & if you need a contact person to include on there it would be Elinore Robey, Director of Community Relations, [elinore.robey@oportun.com](mailto:elinore.robey@oportun.com).

Thanks for working with us and Oportun to get this grant issued even though it's outside of your typical process.

**Comment by staceyrebekahscott** [comment]
Note that I am working with my colleagues at CfA to find out more about how we can apply for and accept grants. It is a complicated and somewhat tedious process.

**Comment by staceyrebekahscott** [comment]
Communicated with Gabrielle at CfA, and she said the Finance and Contracts team can help us with an invoice, but they will need a grant agreement. Communicated this with Erin via Slack, and she will follow up with Oportun.

**Comment by itserindean** [comment]
on 11/1, @ExperimentsInHonesty sent an email to Elinor Robey and as far as I know, we have not yet heard back.
on 11/8 I emailed LA Works asking if there was someone else we should be talking to.

the email Bonnie sent:

> Hi Elinore,
> 
> Erin from our Food Oasis project told me that Oportun would like to give $500 to Hack for LA.
> 
> Erin shared with the following requirements
> 1. W-9 Form 
> 2. IRS Determination Letter
> 3. Grant Invoice for $500 that references “Oportun Volunteer Week 2022” 
> 
> I believe that we can get you everything your organization needs, here is where we are on each of the items
> 
> 1. I have attached the IRS determination letter
> 
> 2. We are talking to Code for America about issuing a W-9 
> 
> 3. Code for America is seeing the word Grant to mean a contract for specific services rendered.  Essentially restricted funds that come with contractual conditions that must be met to consider the grant satisfied (which then has to go through legal).    
> 
> From all the conversations I have had with Erin from the Food Oasis project about the monies that you want to give us, it sounds like it is not a grant (by Code for America's definition).  Meaning, there is no service or report or anything else we need to provide other than a W-9.
> 
> I understand that your accounts payable department is looking for an invoice.
> 
> If my understanding is correct, would a letter with the following text suffice.  If it will not, please provide what information the Invoice must contain in order to be considered an "invoice" given that no services are being rendered.
> 
> Thank you for your generous commitment to support Hack for LA and its Food Oasis project.  Please find the W-9 and Determination Letter attached.
>  
> Donation Instructions
>  
> If sending by check 
> Code for America
> 972 Mission St, 5th floor
> San Francisco, CA 94103
> please include Hack for LA on the memo line of your check 
>  
>  
> Or send via wire transfer
> Bank Name: Mechanics Bank
> Branch Name: Berkeley
> Address: 2301 Shattuck Ave. Berkeley, CA 94703
> Branch Phone: (510) 647-0720
> Bank routing #: 121-102-036
> Checking account #: 041300300
> SWIFT code: MEBKUS66
> Once the wire transfer is initiated, please email [giving@codeforamerica.org](mailto:giving@codeforamerica.org) with the donor name, email, address, date of transfer, and that its for Hack for LA so that we can identify and acknowledge your gift promptly.
>  
> 
> Looking forward to hearing back from you,
> 
> Best,
> 
> Bonnie

**Comment by itserindean** [comment]
Rachel from LA works got in touch with Elinor from Oportun who somehow didn’t receive Bonnie’s email. I resent it today and heard back already. Elinor rephrased the “Grant invoice” as an “Acknowledgement letter on letterhead” and confirmed that the sample text Bonnie provided would work (see below) she reiterated their need for a w-9.

> Thank you for your generous commitment to support Hack for LA and its Food Oasis project. Please find the W-9 and Determination Letter attached.
> Donation Instructions:
> If sending by check
> Code for America
> 972 Mission St, 5th floor
> San Francisco, CA 94103
> please include Hack for LA on the memo line of your check
> Or send via wire transfer
> Bank Name: Mechanics Bank
> Branch Name: Berkeley
> Address: 2301 Shattuck Ave. Berkeley, CA 94703
> Branch Phone: [(510) 647-0720](tel:5106470720)
> Bank routing #: 121-102-036
> Checking account #: 041300300
> SWIFT code: MEBKUS66
> Once the wire transfer is initiated, please email [giving@codeforamerica.org](mailto:giving@codeforamerica.org) with the donor name, email, address, date of transfer, and that its for Hack for LA so that we can identify and acknowledge your gift promptly.
> 
> 

I followed up agin with Jess from C4A about the W9

**Comment by itserindean** [comment]
Jess Manapul from C4A is checking with their finance team about getting a w-9 and I put the approved text into this letter so we can submit as soon as we have the w9
[Oportun donation acknowledgement letter.pdf](https://github.com/hackforla/food-oasis/files/10017456/Oportun.donation.acknowledgement.letter.pdf)

**Comment by itserindean** [comment]
update from C4A (Jess Manapul):
CfA is closed this week for fall break.
Status update from Friday: It looks like it would be a donation to a restricted program (Food Oasis); however, it would also qualify as a grant as well, so they’re reviewing the agreement letter you sent to see if we need to add anything or get additional info from Oportun. We’ll be in touch next week!

**Comment by itserindean** [comment]
update from C4A (Jess Manapul): Recieved W9 and was told we can send the acknowledgment letter _after_ we receive the donation.
[CfA w-9  prepared 09.08.2021 - signed.pdf](https://github.com/hackforla/food-oasis/files/10147856/CfA.w-9.prepared.09.08.2021.-.signed.pdf)

I emailed Oportun with this info to see if this can work.

**Comment by itserindean** [comment]
Was able to connect C4A directly to Oportun and they came to an agreement over paperwork ("An invoice with the description: Oportun will donate $500.00 to Hack for LA in support of its Food Oasis Project") that would work for both sides. I'm following up with C4A to get said paperwork created and delivered.

**Comment by itserindean** [comment]
donation has been received

**Comment by staceyrebekahscott** [comment]
@itserindean A note for when you close out issues on the new project boards- there is no automation on the Product Management board, so you have to manually move this to the Done column. I just did it for this issue, so just a reminder for future issues.

**Comment by itserindean** [comment]
@staceyrebekahscott thanks for letting me know!!
