### ISSUE TITLE
Reduce the size of images on static pages (about us, donate, FAQ) so they load quickly and use less data

### ISSUE THREAD

**Issue by fancyham** [hackforla/food-oasis#1394]
### Overview
Based on research from #928 , we found some easy ways to increase the performance of our website.

One of the things found was that we are using unnecessarily large and high-resolution images on our static pages (About Us, Donate, FAQ), leading to 42-second(!) load times for those pages over 3G connections.

We should reduce the size of those image files so that the pages load more quickly and require less data.

The images should still look nice, but they don't need to be such high quality / low compression / large.

![Screenshot 2022-10-25 at 9 49 53 PM](https://user-images.githubusercontent.com/3376957/197938793-049780c7-980d-40bd-ba60-1b65b163ad85.jpg)

![Screenshot 2022-10-25 at 9 56 40 PM](https://user-images.githubusercontent.com/3376957/197938522-7dc3ad69-1122-4b22-b7be-c23d96ec5849.jpg)

### Action Items
- [ ] Reduce the resolution/size/quality of the images used on these pages

**Comment by Athi223** [comment]
Hey, I'd like to contribute to this if its available

**Comment by khanhtranngoccva** [comment]
Hi there! I would like to contribute to this issue as well.

**Comment by staceyrebekahscott** [comment]
Moving to Prioritized Backlog, to be assessed once current Dev workload is completed.

**Comment by entrotech** [comment]
Image size is already pretty good. Here are the images loaded for the landing page:
![image](https://user-images.githubusercontent.com/9939032/199152930-708e958f-5c51-47a9-be8a-f40f085c5bc4.png)

The About page could use a smaller about-bg image:
![image](https://user-images.githubusercontent.com/9939032/199153818-d489e872-4a37-402b-8c4f-ec5b46836064.png)

Likewise, the background image for thee Donate Page is too large:
![image](https://user-images.githubusercontent.com/9939032/199153612-f098dfdf-4930-4a97-95ca-bf1a8a439d9d.png)

The FAQ page also has a background image that is much too large.

For this issue, find all the images that are over 100KB-200KB and further compress them to a smaller size (in bytes)

**Comment by Athi223** [comment]
@entrotech So, it is up for grab?

**Comment by entrotech** [comment]
@Athi223 @khanhtranngoccva Thanks for your interest in the Food Oasis repo.  We manage assignment of issues to developers through our project board and developer stand-up meetings.  This is a project of Hack for LA, the Los Angeles brigade of Code for America, and we have an on-boarding process for volunteers who want to contribute to our projects. Please see[ hackforla.org ](https://www.hackforla.org/join) for the steps to join the project and make contributions.

**Comment by fancyham** [comment]
Okay, so something’s strange here — if the images aren’t that big, what’s slowing down these page loads?

According to the Total Load Time table showing load times for each page, as seen in 
- #928
the About Us page takes about 19(!) seconds to load on DSL?  

If it’s not the images, why is it so slow?  That’s the real goal for this issue — faster load times.

**Comment by junjun107** [comment]
I compressed the about page image to 267 KB and tested: 

![267](https://user-images.githubusercontent.com/60997220/204362506-6ce0a986-b234-4582-9057-bcbad5e40023.png)

This is what hosting reduced about image on Cloudinary. The difference isn't very significant 
![267-cloudinary](https://user-images.githubusercontent.com/60997220/204362763-677b39e8-8d05-4400-b69b-2d70a01616c4.png)

**Comment by fancyham** [comment]
@junjun107, Any idea what the long blue line here is?  That seems like the real reason the page loads so slowly — is there perhaps a way to reduce the time needed for that item?  

This page has very little functionality on it, so it's surprising it takes so long to load.

![markup](https://user-images.githubusercontent.com/3376957/207996297-4922d735-b9ed-42ae-8a9c-fad32da4a2bf.jpg)
