### ISSUE TITLE
If possible, display 'loading' progress indicator during initial page load

### ISSUE THREAD

**Issue by fancyham** [hackforla/food-oasis#1395]
#### Describe the bug 

Currently, there is a long delay when loading our page for the first time, perhaps 19 seconds on a 3G connection.  

This is likely due to loading and initialization of React and other javascript components.

Because users are used to low-latency webpage loads, many will abort their page-load if it takes more than around 4 seconds.  

So since our page often takes longer, we should show a 'loading' indicator so that they stick around.

This loading indicator can be an 'indeterminate load indicator' animated gif such as a spinner, or it could be a cute branded animation.

This is particularly important when our tool is embedded on other people's sites as the page loads will be even slower, and there will be a large blank box while our components load.

### Action items

- [ ] Determine if we can have a 'loading' animation on the initial load and if not, what alternatives are possible
- [ ] Design or select a page loading animation, and how it should look/appear
- [ ] Implement

### Related issue / Supporting details

- #928 

![Screenshot 2022-10-25 at 10 15 54 PM copy](https://user-images.githubusercontent.com/3376957/197940971-6aa9761f-7363-494c-a712-0f081f169abb.jpg)

**Comment by staceyrebekahscott** [comment]
Moving to Prioritized Backlog, to be assessed once current Dev workload is completed.
