### ISSUE TITLE
Change Background behind "Back to List" Link on StakeholderDetails Component to White

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#1419]
### Overview
Change Background behind "Back to List" Link on StakeholderDetails Component to White

### Action Items
- [x] Create a named color in the Client Palette of palette.background.main and set it to white.
- [x] Apply this color to the background behind the "Back to List" link on the StakeholderDetails panel.

### Resources/Instructions

This is per @sei1122 observation on Issue #991 
 
![image](https://user-images.githubusercontent.com/9939032/200437487-fa0ce360-b65b-4ba1-8ab9-3f62652b2ba6.png)

**Comment by sei1122** [comment]
Looks good.
