### ISSUE TITLE
Permanently Closed and Temporary Closed locations should not show up in our list of organizations

### ISSUE THREAD

**Issue by itserindean** [hackforla/food-oasis#1427]
### Overview
When a food seeker is looking for food, showing them locations that are temporarily/permanently closed doesn't help them find food. Thus we shouldn't include them in the list.
![Screen Shot 2022-11-08 at 3 20 07 PM](https://user-images.githubusercontent.com/107142453/200698119-375c15f4-befc-4298-b3c6-869ad76003ff.png)

note: The current behavior is to show them all at the very bottom of the list of organizations

### Action Items
- [ ] hide any location marked as temporarily/permanently closed

**Comment by fancyham** [comment]
This is an interesting one — there’s some benefit (perhaps in the future) to be able to show pantries/meal programs that are closed, but our current UI doesn’t really support this well…

This would be similar to going to Google Maps or Yelp and seeing a ‘location has permanently closed” message — the listing still exists… the question is when or if we should show these temporarily and/or permanently closed locations.

In the future, if/when we support “search for organization name’ (#1115), showing temporarily and permanently closed orgs would be useful for food seekers who used to go to a pantry or know the name of an org, but not their location.

Related issue:
- #1115

**Comment by staceyrebekahscott** [comment]
This issue is related to #905 in that the dev work required to removed listings that do not want to be published on Food Oasis is likely the same as removing closed locations. Once these are ready to be addressed it should be considered whether these issue can be merged.

**Comment by qiqicodes** [comment]
Closing this issue, Permanently Closed and Temporary Closed locations do not show up in our list of organizations.
