### ISSUE TITLE
Conduct Surveys with UCLA Students to improve Volunteer Engagement

### ISSUE THREAD

**Issue by bkobak33** [hackforla/food-oasis#1431]
### Overview
As part of our effort to improve volunteer engagement and redesign our Organization Edit Form, the UXR team would like to distribute two rounds of surveys to the UCLA students volunteering with Food Oasis as part of their "Engaging LA" course in Fall 2022. The goal is to assess primary pain points at the beginning and end of their 8 week experience and to note significant changes over time.

### Action Items
- [x] UX researchers meet to discuss plan
- [x] Create a Research Plan
- [ ] Confirm Research Plan
- [x] Write Email Message for Survey 1
- [x] Write Survey 1
- [ ] Write Email Message for Survey 2
- [ ] Write Survey 2
- [ ] Data Collection
- [ ] Data Analysis
- [ ] Share Findings

### Resources/Instructions
[Research Plan](https://docs.google.com/document/d/1zlRgkTsRpe6kq-L1LqO1-QCMmBlFyowm3l1GYe0wrWU/edit)
[Data Collection](https://docs.google.com/spreadsheets/d/1ySRK41E6jFRss3DCbF44AId6c4T2dw-6NwJhysQeMQk/edit#gid=0)
Survey 1

- What could be improved or clarified about the orientation session?
- What outstanding questions do you have about the validation forms?
- Do you feel prepared to begin validating the data after the orientation?
- Would you recommend this volunteering to a friend?
- What could be improved or clarified about the validation process?
- Did any new questions arise after beginning your first validation?

[Survey 2](https://docs.google.com/forms/d/1E0-mCA99eZMdQJKHp-19Sz-Ty02ec-Ji-7r6mlLwRaw/edit)

**Comment by staceyrebekahscott** [comment]
Added Volunteer Engagement Milestone and moved to In progress. 

I'd like to note a connection between this research, and our partnership with LA Works. We are in the process of training a new Project Lead for Food Oasis at LA Works, and with this we have the opportunity to change the way those trainings are conducted. See more details on this in issue #1296 Partnership with LA Works.

**Comment by staceyrebekahscott** [comment]
We are now considering working with college students instead of recruiting volunteers via LA Works. Noting that here since my last comment on 11/11/22 referenced creating a new role for working with LA Works- this is no longer something we will be pursuing.

**Comment by fancyham** [comment]
For future reference, the UCLA class listing was this:
https://catalog.registrar.ucla.edu/course/2022/CESC50XP

[2022 Fall - UCLA - Engaging Los Angeles.pdf](https://github.com/hackforla/food-oasis/files/10369711/2022.Fall.-.UCLA.-.Engaging.Los.Angeles.pdf)

**Comment by staceyrebekahscott** [comment]
@bkobak33 @GigiUxR Is this issue now completed, as per Briel's presentation at the All Hands meeting? Is there anything you need from a PM in order to move forward or close the issue?

**Comment by GigiUxR** [comment]
This can be closed out.
I will create another issue for ongoing UCLA surveying.

**Comment by staceyrebekahscott** [comment]
Issue closed as completed as per Gigi's notes.
