### ISSUE TITLE
Make Link Colors Consistent

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#1452]
### Overview
Standardize Link colors to #1976D2 for normal links and #551A8B for "visited" links throughout the Food Seeker and Volunteer and Admin themes and make sure the themes are applied to all instances of links.  If there are links that appear on non-white backgrounds that have insufficient contrast, make a note of them and we will discuss.

### Action Items
- [x] Define the colors in the /client/src/theme/clientTheme and /client//src/theme/adminTheme theme files and then modify react components that have links to use the styles from the Material-UI themes.
- [x] The most important point is to make sure that all links get their style from the theme, rather than having hard-coding styling unique to different links in the site, We expect the Design Team to change their mind about what exact color should be used, but it should be the case that we change a color in one (or maybe two - one for food Seeker (clientTheme) and one for admin (adminTheme) places).

### Resources/Instructions
(https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/FOLA-Design-System?node-id=2943%3A7817&t=W0esMVtJzkzGG3TE-0)

**Comment by entrotech** [comment]
I also set the :hover color to "#004ba0"

**Comment by entrotech** [comment]
@Seiko I'm putting this back to "In Progress", cause we need to know what the colors should be for each of the following states:
normal link: "#1976D2";
visited link:  "#551A8B";
hovered link: ??
disabled link: ??

**Comment by sei1122** [comment]
Can you set the link color to these? 
We may need to adjust later but I'd like to try this
Normal link: "#1976D2";
Visited link: "#551A8B";
Hovered link: #004BA0
Disabled link: #4D4D4D

<img width="323" alt="Screen Shot 2023-02-26 at 11 10 17 PM" src="https://user-images.githubusercontent.com/19811032/221497415-384267f7-913b-4834-bf24-33b355897801.png">

**Comment by entrotech** [comment]
Here is a link that talks about styling links: https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Styling_links

Apparently, there is no such thing as a "disabled" link, but there an additional state called "active" for when the link is clicked on, and only the normal and visited states are mutually exclusive.  For example, a link can be visited and focused and active at the same time.  I just styles the focused and active states with bolder text, and uses a color of primary.light = "#6693CA" for the active state.

**Comment by sei1122** [comment]
Hi John, 

I changed Disable gray to Secondary link. 

https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/FOLA-Design-%231?node-id=10336-17624&t=GchKTlaug1NNGW6R-4
<img width="498" alt="Screen Shot 2023-03-19 at 8 18 05 PM" src="https://user-images.githubusercontent.com/19811032/226238725-46215306-84ca-4f31-b7b5-ae877f2f79cc.png">

We use this secondary link on the static pages. This is used in blocks of text. 

<img width="809" alt="Screen Shot 2023-03-19 at 8 19 50 PM" src="https://user-images.githubusercontent.com/19811032/226238921-3e2a14bf-9c13-4982-b7b5-f86e70d6e727.png">

**Comment by sei1122** [comment]
I checked [dev site](https://devla.foodoasis.net/) and have several requests. 

1. Can you remove this green when hovering the link
<img width="523" alt="Screen Shot 2023-03-19 at 8 22 37 PM" src="https://user-images.githubusercontent.com/19811032/226239209-76fd3505-8fe9-481b-acc2-3fa2c9c6a526.png">

2. Underline should be the same as the phone number
3. Remove underlines from social media icons
<img width="715" alt="Screen Shot 2023-03-19 at 8 28 28 PM" src="https://user-images.githubusercontent.com/19811032/226239854-ab69fd3b-4578-492c-80cb-122fbacd751b.png">

**Comment by entrotech** [comment]
@sei1122 It wasn't clear to me exactly what behavior you want with the "secondary" link, but I used the color you specified for the normal state, and took out any color changes, etc. for the other states (hover, click, visited, etc.) So for the secondary link the only thing that changes with the link state is that the cursor changes to a finger when it is hovered.

Similarly, for the link to be used with images or icons, the only state-driven behavior should be the cursor change.

**Comment by sei1122** [comment]
Hi @entrotech, sorry it has been a while to reply this issue. 
I checked the links, and I'd like to update this secondary link to the primary link so that the links are consistent. 
Since our site is not big, maybe link is one color is ok for now. 

<img width="513" alt="Screen Shot 2023-05-04 at 3 26 33 PM" src="https://user-images.githubusercontent.com/19811032/236342804-5c159e01-920d-4b77-86fd-99e785236ac8.png">

**Comment by sei1122** [comment]
Create the development issue to get rid of the secondary link color.

**Comment by entrotech** [comment]
- Created Issue #1682 
This removes the secondary link style.
