### ISSUE TITLE
Make Heading and Body Text Colors Consistent

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#1453]
### Overview
All Headings should be #1B1B1B and Body Text should be #313233

### Action Items
- [x] Define the colors in the /client/src/theme/clientTheme and /client//src/theme/adminTheme theme files and then modify react components that have Headings and Body Text to use the styles from the Material-UI themes.
- [x] The most important point is to make sure that all text gets get its style from the theme, rather than having hard-coding styling unique to different components in the site, We expect the Design Team to change their mind about what exact color and maybe font familty, weight, etc. should be used, but it should be the case that we change a color in one (or maybe two - one for food Seeker (clientTheme) and one for admin (adminTheme) places).

### Resources/Instructions
(https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/FOLA-Design-System?node-id=2943%3A7817&t=W0esMVtJzkzGG3TE-0)

**Comment by entrotech** [comment]
The <Typography /> element has several variants. I'm setting all the h* and subtitle variants to the heading color #1B1B1B,mm and both body* variants to the "Body Text" color #313233.

**Comment by entrotech** [comment]
As mentioned on Jan 4, the colors are set based on the design tokens associated with each piece of text, though it would be good if @sei1122 or one of the other designers could review all the pages to make sure that each text element is categorized as they wish.  That is, we may have some text that uses the subtitle1 style, when the designers expect it to use the "body" style.

**Comment by sei1122** [comment]
@entrotech 
I did QA. Please check the google doc
https://docs.google.com/document/d/1BL1czXVKT2f-4hjlIrwDOULKIp3cUKHjml7A625YN7s/edit?usp=sharing

Are admin pages going to change the text colors?
I checked the admin interface, but the text color was the same as before. 
Let me know if I need to check the Admin pages too.

**Comment by sei1122** [comment]
@entrotech, I check the update! 
Please close the issue.
