### ISSUE TITLE
Reach Bonnie form Agenda

### ISSUE THREAD

**Issue by itserindean** [hackforla/food-oasis#1463]
### Overview

Padma Gopalan attended the 10/31 onboarding where she expressed interest in joining as a UX writer. Bonnie suggested the website team and instructed her to email for more info.
Padma emailed on 11/2 & 11/8 but never herad back (Subject "UX Writer for Hack for LA website")
She followed up with me to ask if I could help get her in touch.
We risk losing this volunteer.

### Action Items
Add comment to this issue with your proposed agenda item. if item warrants an issue of its own please start a [new issue](https://github.com/hackforla/tdm-calculator/issues)

**Comment by staceyrebekahscott** [comment]
@itserindean I put this on the Product board in Backlog, although I am wondering why this is an issue on our board that we need to address. Has Padma reached out on Slack? They can also wait until January when things are back in full swing.

**Comment by itserindean** [comment]
Padma is newly onboarded to H4LA and not onboarded  to a team so she doesn't have a write privileges on any projects to make an issue herself. She asked about reaching out via slack but I haven't found that to b any more effective to reach Bonnie and since I was part of the initial conversation with her and Bonnie, I said I would help fill out the form. Regarding timing, to be transparent. Padma asked me in early Nov and I forgot which is why I did it now.

**Comment by staceyrebekahscott** [comment]
@itserindean Have you advised Padma to connect with Bonnie now that HfLA has started up again?

**Comment by staceyrebekahscott** [comment]
Closing this issue. I did a quick search on Slack and saw her name so she looks to still be involved. Bonnie has been more responsive on the channels, Padma should be able to reach her. There is no need for us to keep this open.
