### ISSUE TITLE
Enhancement: Make it easier to type zip code on landing page

### ISSUE THREAD

**Issue by jelenaUX** [hackforla/food-oasis#1470]
**Overview**
The landing FO page asks the user to type in the zip code or press a button, but it doesn't have the Zip code field in focus automatically. The pointer seems to be somewhere else by default (perhaps undefined?). So upon landing, user has to manually move the pointer to the zip code field so that they can type in the zip code. This adds unnecessary scrolling and the potential to confuse food seekers. Let’s make it easier by automatically focusing the pointer on the zip code field.

**Steps to reproduce the issue**
   Go to 'https://www.foodoasis.la/'
   The pointer is not visible until you move it. Then the user has to guide the pointer with their finger across the screen to the "Use my current location" button or the zip code field. 

**What's the desired result?**
    The desired result would prioritize food seekers by visually indicating a clear course of action to the food seeker. This can be achieved by automatically setting the pointer focus on one of the commonly chosen options on the landing page. For example, upon landing to FO website, the zip code field or the "Use my current location" button could be automatically set as the focus. Or, at least the pointer could be placed visually near the center of the screen, to minimize scrolling.

**Device configuration**
    Device: laptop computer MacBook Air
    OS version: MacOS
    Browser: Firefox
    Browser version: 102.4.0esr

**Comment by staceyrebekahscott** [comment]
@entrotech @hanapotski Adding this to the Dev Icebox. This is marked as an Enhancement, which is not something we have defined as a team. But it looks like the issue was created in the format of a Bug so I am wondering if this needs to be evaluated as such first. Please advise.

**Comment by fancyham** [comment]
In the current version of the site (single text field and GPS-locate-me button only), it would make sense to default keyboard focus into the address-entry field.

Now that we’re moving to a longer, scrolling landing page with content below the fold, this option may not make as much sense, as users may want to use keyboard to scroll down.

Let’s revisit when new homepage is launched.
