### ISSUE TITLE
Bug: In admin dashboard can not make changes to organization 4023, 4868, 5187

### ISSUE THREAD

**Issue by itserindean** [hackforla/food-oasis#1471]
#### Describe the bug 

Neither the volunteer this is assigned to, nor myself (an admin) has been able to make change to org [4023](https://foodoasis.la/organizationedit/4023) (Saint Columban Catholic Church -  St. Vincent de Paul Food Distribution Center)
 (need to be logged in as admin for link to be helpful)
Click Criteria.
In name field enter Saint Columban 

**this is also happening for org [4868](https://foodoasis.la/organizationedit/4868) Lakeview ADHC
**this is also happening for org [5187](https://foodoasis.la/organizationedit/5187) Willing 2 Move Forward
#### Steps to reproduce the issue

log in as admin to dashboard
Click Criteria.
In name field enter "Saint Columban"

1) make a change
click save progress
progress is not saved if you come back to it

or
2) click reassign (enter any name, i used my own)
nothing happens, it is not reassigned

or
3) confirm email. confirm Food Types
click approve
nothing happens, it is not approved

### Acceptance Criteria
- The save button should be disabled if anything is missing from the business hour inputs
- Show the validation error on the ui
- Show the error below the input and add a red border on the input

**Comment by entrotech** [comment]
The problem here is that the start and/or end times were not entered for one or more intervals on the Business Hours.  This is not obvious to users, because no validation error messages are displayed. Need to fix so validation errors are displayed in a way that is hard for users to ignore.
