### ISSUE TITLE
Bug: The Re-Center button on the Map page doesn't handle disabled location well

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#1489]
### Overview
If the user has not allowed the browser to report the device location, or has explicitly disallowed it, the re-center button on the map page is still enabled, but doesn't do anything when pressed.

### Action Items
- [x] Decide on the correct behavior. It should probably behave like the "Use My Location" button on the home page, which is disabled if the user has explicitly denied the location service, or prompts the user to allow location services if the location service has not yet been allowed or denied.

**Comment by andyarensman** [comment]
Hey @entrotech, I think this issue can be closed since it is the same as issue #1205 that I committed during our last meeting.
