### ISSUE TITLE
Get an example MapBox map working in React

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#15]

**Comment by lucas-homer** [comment]
so... I'm just going to keep working against this issue, though we've made some progress beyond 'get an example working' -- http://food-oasis.herokuapp.com/ -- that reflects the work up to Nov. 19, 2019. Things I'm going to work on now:

- Make filter options collapsible
- remove title (takes too much space)
- implement search bar to take text input for name/address and return lat/long
- rethink the UX flow so it's super obvious what button to click and when (kind of vague, but basically the existing 'Edit' button is a little oblique as to what it does)
