### ISSUE TITLE
Decide on a Design for Standard Text Fields

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#1519]
[Food Oasis Development Site](https://devla.foodoasis.net/login/)

### Overview
The design of TextFields in the application is quite varied. Decide on a standard design and behavior. Identify specific instances where the standard TextField is not appropriate and define what deviations from the standard are desired.

### Background
The development team is in the process of organizing the code such that the design of various components is consistent across the  application. This should provide a more consistent user experience in terms of control appearance and behavior. Should we decide to change the behavior or appearance of a control, we should theoretically only need to change it in one place in the code, and all instances of that control will be updated throughout the application.

This issue addresses the standardization of TextFields on forms. To get started, we will look at the TextFields on the Login Form:

![image](https://user-images.githubusercontent.com/9939032/213554133-f6a96830-61cf-493b-8828-9a06edcb8b5f.png)

If you play with this form, you will note that:

- The Email TextField is in a normal state, with a (blue?) , rounded border and the label overlapping the upper-left part of the border.
- The password TextField has a validation error, changing the border to red and adding error text below the TextField. It also has the Password "eye" button embedded in the TextField that allows the user to view the TextField contents.
- If you hover over a TextField, the border turns black (unless it is already red because of a validation error).
- If a TextField receives keyboard focus, the border becomes thicker, regardless of its color.

Most TextFields in the application currently look more or less like those on the Login Form, but, for example, the Query dialog on the Verification Admin screen have a different style: 

![image](https://user-images.githubusercontent.com/9939032/213596499-39e97697-6c90-47b6-810d-0d13441b5a33.png)

Designating Required fields is implemented in different ways in different parts of the application:
- On the Login form, there is no visual indication of required fields. 
- On the OrganizationEdit form and Suggest a New Listing form, the label by the TextField is followed by a small asterisk.  
- On the Correction form, the required TextField has a large asterisk inside the TextField as an adornment on the right:

![image](https://user-images.githubusercontent.com/9939032/213556668-00133ffc-c932-48d3-ac7c-437a88f2bf74.png)

### Action Items
- [x] Review the behavior of the TextField on the Login form and decide if all of the detailed behavior is what we want as a "Standard" TextField behavior and appearance.  Create a development issue to implement any desired changes.
- [x] Document the standard TextField in the Design System (e.g., Figma and any realted documentation). A complete design spec would include designs for each state (normal, hover, keyboard focus, disabled, invalid input). Also include a standardized way of indicating required fields and perhaps explanatory text (placeholder text inside the TextField input or perhaps text located elsewhere. Of course, exact colors from the standard application color palette, border corner radius, text font family and font size, etc. should also derive from the Design System.
- [x] Review all the other TextFields in the application to identify situations where it is appropriate to deviate from the standard. If there are such situations that occur repeatedly, define any "alternate" standards that we might need.

**Comment by staceyrebekahscott** [comment]
@itserindean Added this to In Progress on Product board, as John D wants this to be a priority. 

@jnaito777 @nkiwan Adding you to this issue and adding this to In Progress on Project management board. 

See notes on Design team agenda: [Design Team Meeting Agenda](https://docs.google.com/document/d/1oLPGqa2DX0tvGLc2F3mN1xqmMjZurUYd4-AKkMj4bWI/edit#) and Leads/PM Meeting: [Leads/PM Meeting](https://docs.google.com/document/d/1uPO0_AJ1zn3IZXrhHBXub-ZfakIsx34jKHK3LIB8VmM/edit#)

**Comment by staceyrebekahscott** [comment]
@jnaito777 @nkiwan I assigned this issue to you both as per notes from the Design meeting on 01/19. 

Are you still wanting/ able to work on this issue?

**Comment by fnkdesign** [comment]
3/23/23
Feedback received from the design team. 
Next step would be asking around for more feedback from other team.

**Comment by fancyham** [comment]
@fnkdesign Good discussion yesterday — thanks for putting that together.  

Please post a link and PDF of in this issue for posterity :)  

Also, when you are working in FOLA Figma file, please copy these FigJam discussions over to the Figma file for posterity (so future FOLA folks have permanent access to documents/sketches so future people can understand /lear from what happened)

**Comment by fancyham** [comment]
Also, please do ask research and dev for help with identifying problems (if any) and finding non-standard stuff with existing text fields throughout the site.  

You can ask in their respective channels or ask the leads Gigi P (research lead) and with Hannah (dev lead) and they can send over people who might be able to help with your request.

Research may be able to help audit and do a heuristic usability review, and devs might be able to search the codebase and find instances of non-standard text fields.  

Also be sure to discuss with devs for what’s easiest to build and what different changes might cost as far as dev-difficulty (my guess is that ‘standard’ Material UI behavior is the easiest for them) — doesn’t mean we go the easiest-for-dev direction but it’s useful to know what the problems are from the user side and how difficult different options are for the devs and maintaining them.  

This is some fancy CSS stuff, so while devs will absolutely try to create anything we give them, some designs end up being super complicated unbeknownst to us — and I’d like to make sure we make product development a dialog between disciplines and I think they’re interested in that, too. ;)

**Comment by fancyham** [comment]
FYI: Found an interesting write up about the evolution of the Material UI-style text fields and how they got to the animated label vs their previous iteration (which used an underline)

https://medium.com/google-design/the-evolution-of-material-designs-text-fields-603688b3fe03

@fnkdesign what’s the status on this issue — looks like some has been sent to development #1660, but I think you mentioned updating the drop-down style, also?

Also, check out the landing page foodoasis.la and the map screen’s text fields — might be tight to have a label, so would it have just the hint text inside the text field?

**Comment by fancyham** [comment]
Also, please post links to your figma designs here as a comment as they’re progressing (and even better, drag a screenshot into this comment field for even quicker and easier access :)

**Comment by fnkdesign** [comment]
➤ Here’s the FigJam file from our design meeting on 3/23/23

[Text Field Style Votes_Comments.pdf](https://github.com/hackforla/food-oasis/files/11456969/Text.Field.Style.Votes_Comments.pdf)

➤ I reached out to Hannah on 3/29/23, I updated her with some feedback from the design team meeting, and discussed about the feasibility and maintenance. From dev point of view, it is obvious that the current design that we’re using Material UI is the easiest choice in terms of implement and maintain, but it is understandable why version A is a popular choice among the team (considering adding tool tip).

We also discussed about “standard” and “non-standard” text fields. We wasn’t sure about the terms of “standard” and “non-standard” text fields but if anything the dev team can always adjust the code/style case by case. 

➤ 4/13/23 The dev team adopted "Version A" to implement on the dev environment.

<img width="1676" alt="form1_devla" src="https://github.com/hackforla/food-oasis/assets/113713802/feee0c39-033c-462c-89b5-28dbef698bd6">
<img width="1677" alt="form2_devla" src="https://github.com/hackforla/food-oasis/assets/113713802/a7ff071f-60e8-44ed-b4d7-c8d9ebb2ad00">

➤ It is interesting to see how MUI evolved. It is always interesting to see what others think about the design in the discussion. I saw a lot of people mentioned that gray-fill might be mistaken for a disabled text-field, especially when the text inside the text field is almost blend in with the grey-fill. 
<img width="617" alt="MUI" src="https://github.com/hackforla/food-oasis/assets/113713802/2bf96246-150c-4203-a33d-aaf234b8214e">
As much as I like how the text field from MUI looks, I think it could be challenging to work with tool tip and check box unlike the traditional text field where you can place tool tip right next to the label on the top.
<img width="684" alt="textfield-traditional" src="https://github.com/hackforla/food-oasis/assets/113713802/52d721d5-57c1-4d19-a03a-86046ac6ddc8">

➤ Currently, I'm working on updating comments from the team, regarding text field on the dev environment to Hannah. I also created a “draft version of text field guide” on [Figma](https://www.figma.com/file/9hPmNSsyaH2VMGNz5mffmI/FOLA-Design-%232?type=design&node-id=3331%3A4596&t=rH9ioJvEi20s5Q0d-1), any feedback are always welcome :)
 
<img width="807" alt="textfield draft1" src="https://github.com/hackforla/food-oasis/assets/113713802/31c1f9aa-154b-46db-a7cf-ff4c4061685f">
<img width="808" alt="textfield draft2" src="https://github.com/hackforla/food-oasis/assets/113713802/e6a6aee0-becf-4210-8d99-359483add433">

**Comment by fnkdesign** [comment]
Final update: I’ve worked with the dev team to test out the design of text fields. Some related issues are #1678, #1696 and #1747. All of the components turns out great, and it works as expected on the dev environment. 

Here’s the final design, and it can be access [here](https://www.figma.com/file/9hPmNSsyaH2VMGNz5mffmI/FOLA-Design-%232?type=design&node-id=5265%3A1676&mode=design&t=iRW5ya8iV6wnjwOy-1).
<img width="833" alt="completed text fields" src="https://github.com/hackforla/food-oasis/assets/113713802/2c54b727-0555-4346-afba-332736681373">
Thank you everyone that involved in this project, you guys are awesome! 👏👏👏

**Comment by fancyham** [comment]
Thank you Fern for your great work!!  Thank you devs for making it happen!  Woohoo!
