### ISSUE TITLE
Create Primary and Secondary Button components

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#1527]
### Overview
When migrating to V5 of Material-UI / MUI, I standardized the theme on a single button style, but @sei1122 suggested that we have two different "standards", one for the "primary", i.e., most common or most important Call to Action on a panel or page, and a "secondary" standard button design for less important or common actions.

### Action Items
- Decide whether the second standard should be a styled component or somehow integrated with the theme (e.g., maybe selecting the "filled" variant will be Primary and the "outlined" variant will be Secondary?)
- Work with UI team to implement the desired behavior from Design Issue #1518

**Comment by entrotech** [comment]
@narae-ux  and @sei1122 have refined the expected behavior of the two button styles, so I'm moving this issue bak to "In Progress to incorporate their changes under this issue.

**Comment by entrotech** [comment]
From Design Issue #1518, per Button Guide V4.3 on 2/3/23:
Both styles:
Change corner radius on all button to 12px.
Font Size should be 16px/1rem
Padding should be 8px 16px

Primary Only:
Normal State: background color: #336699 color: #FFFFFF no border
Disabled state: background color: #2D5B88 Border: 1px solid #6C6C6c 
Hover State: background: 2D5B88 no border
Focused State: color: #336699 color: #FFFFFF - Two borders?? inner 2px solid transparent, outer 2px solid #336699
Pressed State: #264A79, color #FFFFFF no border

Secondary:
Normal State: background: white, border: 2px solid #336699 color: #336699
Disabled: background white; border: 2px 6C6C6C, color #949494
Hovered: background: ESF1F7 border: 2px #336699, color #336699
Focused: background: white, border: 2px solid #336699 color:  #336699 Two borders: inner: transparent 2px? outer: 2px solid #336699
Pressed: background: CBE3F1, border: 2px solid #336699, color: #336699

**Comment by entrotech** [comment]
AFAIK, the PRs above implemented the primary and secondary buttons pretty well.  I also created a demo page for UI components that you can get to by adding "/muidemo" to the url, like this:
https://ladev.foodoasis.net/muidemo. For example:

![image](https://user-images.githubusercontent.com/9939032/219524962-887a4137-8229-4d28-8589-a61b7b1561c1.png)

There are two problems with the implementation that I noticed:
1. In situations where a set of buttons are stacked together horizontally, the buttons shift slightly to the right when one of the buttons is hovered. Though we don't have buttons that are stacked vertically anywhere in the app - there may be a downward shift on hover in that scenario as well.  This seems to be a subtle change in the size of a button when it is hovered, but I yet know why that is happening.
2. On at least one screen, when the Primary Buttons has extra space around it and the button has keyboard focus, the outermost border pulls away from the button, rather than having a 2px gap to the button itself:

![image](https://user-images.githubusercontent.com/9939032/219525751-7077fd52-3fa4-4a28-b0bb-b179dcc6e623.png)


Developers will keep working on these issues, but It would be good for @narae-ux @jnaito777 and @sei1122 to see if we are on-track with the implementation.  I think the design itself is pretty good, though the buttons do end up being significantly larger that they were before. I think it's partly a larger font, partly the margin inside button, and partly the two extra borders to achieve the "focus" state effect.

**Comment by narae-ux** [comment]
This is amazing and very helpful - thank you @entrotech! 

Btw I think this is [the link for the demo page for UI components](https://devla.foodoasis.net/muidemo): https://devla.foodoasis.net/muidemo.

Thank you for noting problems with the implementation as well! 

Follow-up:
- I will review the current button styles, make some changes (i.e. remove extra borders and potentially reduce size of buttons too), and follow up then.

**Comment by entrotech** [comment]
At this point, the implementation should be consistent with Version 6.2 of the Button Design.  If additional changes are needed, we should open a new development issue with the exact changes requested.

**Comment by sei1122** [comment]
@entrotech, the Button looks good to me! 
Please close the issue.
