### ISSUE TITLE
Create Discussion for LA Works to test Change Log documentation process

### ISSUE THREAD

**Issue by staceyrebekahscott** [hackforla/food-oasis#1530]
### Overview
During the Leads/PM meeting on 01/19 we discussed how to document the progression of an issue or process. John D suggested we use the Discussions feature. I will test out if this works by using the LA Works partnership as an example. #1296 

### Action Items
- [x] Finish adding notes to issue #1296 
- [ ] Add New Discussion and share learnings with the Leads/PM team.

**Comment by qiqicodes** [comment]
Closing this issue, currently no working partnership with LA Works.
