### ISSUE TITLE
Design System (Audit-Logos, Icons, Images)

### ISSUE THREAD

**Issue by jnaito777** [hackforla/food-oasis#1531]
We need to update the Design System to design more efficiently. When I’m designing, I refer to the design system color, font, button, and components. Some of the items are not the latest so I need to back and forth website and design system. 

### Action Items
- [x] Audit logos, icons, images on Food Oasis website (both food seeker and admin side)
- [x] Document existing logos, icons, images (existing style guide)
- [x] Create written documentation of the audit
- [x] Review with design team
- [ ] Remove redundant/out-of-use/non-accessible logos, icons, or images
- [ ] Approval by team

### Resources/Instructions
This is related to the main issue #1204

Currently, there are 2 versions of the design system.

Design System version 1
https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/FOLA-Design-System?node-id=0%3A1

<img width="683" alt="164845894-7f8cf921-d339-4db9-b3b2-196fe1cd7404" src="https://user-images.githubusercontent.com/114040198/214707526-dc8a964b-3dce-41c5-a7b3-a1ad35652586.png">

Design System version 2
https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/FOLA-Design-System?node-id=0%3A1
<img width="628" alt="164845980-6a93686d-c6bf-49b7-8b3c-e661b132f5db" src="https://user-images.githubusercontent.com/114040198/214707559-ab5606ea-10db-450c-b514-0dfe1397bcc3.png">

Material UI (React library) is used Food Oasis site. This is helpful when we design.
Material UI
https://www.figma.com/community/file/912837788133317724

**Comment by staceyrebekahscott** [comment]
Updated labels, added to Project Management board, and moved to In Progress column.

**Comment by jnaito777** [comment]
Material UI icons in use per John:
https://docs.google.com/document/d/1cO8M4PjEEinmgiyqlTAULyxu7m_x80BbT1TVu41oznE/edit

In addition to these, there are a few custom svg files that we use for the Meal Program (fork) icon, Pantry (apple) icon and the Food Oasis logo.

**Comment by jnaito777** [comment]
![Screenshot 2023-04-13 at 7 07 27 PM](https://user-images.githubusercontent.com/114040198/231923521-70adb2f1-2a4a-4218-a717-773c3ce28f6f.png)

Results from preference test

**Comment by jnaito777** [comment]
Based on the A/B test (above) and review of the design team, we will be using the check marked icons. I have included the SVGs. 

For the social media icons, removing the old Facebook and Instagram icons, and replacing it with the new set.
For the you are here icon, removing the old red icon and replacing with Google's "current location" icon/You are here Icon.
For the center yourself icon, removing the cross hairs next to the search button and replacing with Google's "my location" icon/Center yourself icon. 

![Screenshot 2023-05-04 at 12 55 06 PM](https://user-images.githubusercontent.com/114040198/236315225-0358f15c-9960-46b0-8eb7-3ac46bae1ba2.png)


![Uploading Screenshot 2023-05-04 at 12.53.15 PM.png…]()

![My location](https://user-images.githubusercontent.com/114040198/236313881-c2cef21d-2f35-4a3c-8dcb-7d4b6f9d6889.svg)
![Current Location](https://user-images.githubusercontent.com/114040198/236313886-f2818461-6768-4167-9eab-cdea2fb311aa.svg)
![Instagram](https://user-images.githubusercontent.com/114040198/236313888-95e75a23-5cee-4651-8017-74e17b5b612c.svg)
![Facebook](https://user-images.githubusercontent.com/114040198/236313891-63a1ba39-791f-471e-8782-71fbca232071.svg)
![Youtube](https://user-images.githubusercontent.com/114040198/236313894-4bc8bb37-da69-428a-90a1-fd0669f967fa.svg)
![Linkedin](https://user-images.githubusercontent.com/114040198/236313896-987d294a-49bf-44e1-a9e5-4bc3fb238b94.svg)
![Twitter](https://user-images.githubusercontent.com/114040198/236313899-fee74ac5-cb59-4ec3-86c1-4f4140a127b0.svg)

Please let me know if you have any questions. Thank you!

**Comment by fancyham** [comment]
Some of the recommendations from this is being incorporated in new design being released in early 2024
