### ISSUE TITLE
Place new content for the static page’s design - About Us, Donate, and FAQ

### ISSUE THREAD

**Issue by sei1122** [hackforla/food-oasis#1552]
### Overview
The content team wrote new content for the About us, Donate, and FAQ pages. 
Place the latest content for the static page designs to make it easier for the developers when they update the pages. 

### Action Items

- [x]  Place content to design file (Figma file link place holder)
- [x] Review by the design team
- [x] Review by the content team
- [x] Handoff to the Dev team
- [ ] QA
- [ ] Launch

### Resources
- [#1365 Update content in About US static page to be more current.](https://github.com/hackforla/food-oasis/issues/1365)
- [#1281 Update FAQs content](https://github.com/hackforla/food-oasis/issues/1281)
- [Content Figma file file](https://www.figma.com/file/GnvrOCZiWBKOMxjKTFcq4w/FOLA-Content-team-library?node-id=488%3A489&t=pQ1ywbfcfsYezXYk-4)
- [Content Google doc](https://docs.google.com/document/d/15S6ApvAydqan0esH7WALr2QwSKl_BLe8UJxHo0kSs5I/edit?usp=sharing)

**Comment by sei1122** [comment]
@fancyham, @ShruthiVen28
 
 I placed content. Please check the pages and let me know if I need to update anything. 

https://www.figma.com/file/9hPmNSsyaH2VMGNz5mffmI/FOLA-Design-%232?node-id=640%3A110&t=HBBxp1fCHO8wKZhY-1

<img width="610" alt="Screen Shot 2023-02-15 at 9 00 08 PM" src="https://user-images.githubusercontent.com/19811032/219272847-8ffd9513-af26-4421-bc6a-eb542c76fc5c.png">

**Comment by staceyrebekahscott** [comment]
Updated labels, added milestone and added to In Progress.

**Comment by sei1122** [comment]
@John, 

I’d like to handoff to the dev team.  
Content team updated the static page content, and I placed new content on static page design.
 The main thing for the dev is to place content, but there is a minor design update from the last version. 

1. FAQ Page / Additional Questions section 
 Please add this section after Contact Us page is created on the site (issue #1288).  Until then, we can hide this section.

2. About Page / There is numerous free food….  to these resources.
  Can you set the font size for the desktop - 24 px and mobile - 20px
  
3. About Page / Our Partners 
Please use the new logo for [Farm2people.org](http://farm2people.org/)  

I left comments for dev on the Figma file as well.   Let me know if you have any questions!

**Comment by fancyham** [comment]
@entrotech :)

**Comment by fancyham** [comment]
Tagged as 'ready for dev review' and sent to devs!

**Comment by sei1122** [comment]
Content feedback for Dev: 

- About Us page: **missing link for Hack for LA**
- FAQ: 
  - Does this web-based directory include every resource where I can get free food in Los Angeles County? ( **missing link for Hack for LA**) 
  - What is the difference between a food bank, food pantry and meal program?
    - Generally, food banks collect donated food and distribute items to food pantries. Food pantries provide free groceries to food seekers. Meal programs provide free cooked meals to food seekers. Many locations provide multiple services. Our updated directory indicates which services are available at each location. (missing period)
  -   Food Providers: How can I add our food pantry to your directory?
      -   Change to “How can I add our food **resource** to your directory?”

- Donate : **missing link for Hack for LA**
