### ISSUE TITLE
Upgrade react-router to v 6.*

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#1568]
### Overview
We are currently on version 5.3.0, but did not make adjustments to the code that were supposed to be made in version 5.1, and now the current version is v6.8.1  This should be a two-step upgrade as described it the linked instructions below. I've read in at least one place that version 5 has issues with React 18, so this may be important.

### Action Items
REPLACE THIS TEXT -If this is the beginning of the task this is most likely something to be researched and documented.

REPLACE THIS TEXT -If the issue has already been researched, and the course of action is clear, this will describe the steps.  However, if the steps can be divided into tasks for more than one person, we recommend dividing it up into separate issues, or assigning it as a pair programming task.

### Resources/Instructions
(https://github.com/remix-run/react-router/blob/main/docs/upgrading/v5.md)
https://reactrouter.com/en/main/upgrading/v5

**Comment by junjun107** [comment]
React-router-dom is now at 6.10.0
