### ISSUE TITLE
If Request Assignment Fails, Show user a message explaining what to do.

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#1569]
### Overview
When Volunteers press the Request Assignment button on "My Dashboard", they should be assigned a listing to re-verify.  The rule is that from the listings that are Meal Programs or Food Pantries, are not permanently closed and have the current status of "Needs Verification" they will be assigned the one that has the earliest "last modified" date.  However, if there are no listings that meet this criteria, the request assignment feature does not assign them a listing to work on.  In this case, we need to show them a message explaining what happened, and what to do about it.

### Action Items
- [ ] Display an error message:“Error : Couldn’t find listings to verify.  Please contact your volunteer coordinator and let them know.”— a pop-up would be fine, or if you want to be fancy, a message that appears after pressing the button.  Contact design if you need a sketch/directions, but the important thing is the message.
- [ ] Implement the feature.

**Comment by fancyham** [comment]
Added error text to the issue description
“Error : Couldn’t find listings to verify.  Please contact volunteer coordinator and let them know.”
