### ISSUE TITLE
Implement Standard Buttons, Version 6

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#1599]
### Overview
Another update to the button styles, per Issue #1518 comments for version 6.

### Action Items
- [ ]  Implement changes.

### Resources/Instructions

https://www.figma.com/file/9hPmNSsyaH2VMGNz5mffmI/FOLA-Design-%232?node-id=2469-3499&t=FwTPipJwXGrtGcSL-0

**Comment by fancyham** [comment]
Hi, not sure how to handle this but we’d like to beta test these new button styles on the dev site and have team members review it this live version and give feedback to designer, who will quickly iterate the design (and give to the dev working on this issue) till we get to a version that works well. 

Not sure how we could arrange this with git — Would we want to create a new dev issues each iteration, or perhaps keep this one open till it’s fully done?
