### ISSUE TITLE
Conduct heuristic evaluation of buttons standardization

### ISSUE THREAD

**Issue by GigiUxR** [hackforla/food-oasis#1618]
### Overview

Buttons standardization on the dev site need to be evaluated for usability.  

### Action items

- [ ] Complete heuristic evaluation of the buttons on the dev site
- [ ] Determine next steps for beta testing

**Comment by fancyham** [comment]
Design and dev teams have standardized buttons across the public and intranet sites.

If there are problems, let’s address them as they come up with the philosophy of “no news is good news”.
