### ISSUE TITLE
Create new Map and filter page design

### ISSUE THREAD

**Issue by chombus** [hackforla/food-oasis#162]
### Overview
Define the design of the map/filter page and create a rough wireframe 

### Action Items
- [x] Gather existing wireframes from @lucas-homer 
- [x] Create updated low fidelity wireframes
- [ ] Determine interaction behavior of auto complete functionality
- [ ] Review with team and iterate on design

### Resources
- latest design [Draft_01_07.pdf](https://github.com/hackforla/food-oasis/files/4035785/Draft_01_07.pdf)

- [existing page](https://foodoasis.la/locations/?type=&deserts=1&open=&address=)

**Comment by lucas-homer** [comment]
https://xd.adobe.com/view/b1876808-5f77-461e-61f3-cecc6fd2bde9-c7b6/

**Comment by chombus** [comment]
**Design Ideas**
- https://carto.com/demo/reveal-demo/
- https://www.mapbox.com/showcase/facebook
- https://gis.halotrust.org/kssurveymap/

**Comment by chombus** [comment]
@lucas-homer @tina-moh 

Rough idea for this page.  "Borrowed" heavily from Google, Yelp, Zillow, Airbnb etc. 
![Details_map](https://user-images.githubusercontent.com/49743179/71019027-78204300-20ae-11ea-85da-b01f1ea514c0.png)

**Comment by lvl3jose** [comment]
@chombus Here is what I have so far.
![fola_mappage_wireframe_v1-1](https://user-images.githubusercontent.com/58757647/72395971-08729780-36f0-11ea-9391-748b0047b6db.png)
![fola_mappage_wireframe_v2-1](https://user-images.githubusercontent.com/58757647/72395972-08729780-36f0-11ea-8696-3b9a710b791f.png)

**Comment by tina-moh** [comment]
Hi Jose, 
Thanks the layout looks cool, focusing on functions: could you please tell what does filter 1 and filter 2 refer to?

**Comment by lvl3jose** [comment]
@tina-moh Filter 1 will be "Distance". However, I wasn't sure if it made sense to add "Near Me" as the second filter, or rather if we even needed a second filter so I made it a placeholder.

**Comment by chombus** [comment]
ETA Friday for draft design

**Comment by lvl3jose** [comment]
@chombus Here is the draft design v2
https://www.figma.com/file/Qs2zKdqZFLyPxc5qaaFCBk/FOLA-v1?node-id=0%3A1
![fola_map_v2](https://user-images.githubusercontent.com/58757647/73038004-bfb09200-3e05-11ea-807f-216d1009fd01.jpg)
![fola_location selection_v2](https://user-images.githubusercontent.com/58757647/73038009-c3441900-3e05-11ea-9d4e-f9312ca8cdc1.jpg)
![fola_results 1_v2](https://user-images.githubusercontent.com/58757647/73038016-c6d7a000-3e05-11ea-8238-cc6e10302a63.jpg)
![fola_results 2_v2](https://user-images.githubusercontent.com/58757647/73038021-c939fa00-3e05-11ea-9d1d-716710724c6e.jpg)
![fola_filter select 1_v2](https://user-images.githubusercontent.com/58757647/73038035-d35bf880-3e05-11ea-979e-aca48917a742.jpg)
![fola_filter select 2a_v2](https://user-images.githubusercontent.com/58757647/73038046-db1b9d00-3e05-11ea-9e20-642e27aa8213.jpg)
![fola_filter select 2b_v2](https://user-images.githubusercontent.com/58757647/73038051-deaf2400-3e05-11ea-8695-8da78c753d20.jpg)
![fola_results 3_v2](https://user-images.githubusercontent.com/58757647/73038053-e1117e00-3e05-11ea-8ee0-3fea7fec08b3.jpg)

**Comment by ExperimentsInHonesty** [comment]
@lvl3jose Please add a copy of the existing homepage to the figma and change the resulting screen to  reflect that we have their address from the first page.

**Comment by lvl3jose** [comment]
@ExperimentsInHonesty Here are the update screens with the address.
https://www.figma.com/file/Qs2zKdqZFLyPxc5qaaFCBk/FOLA-v1?node-id=0%3A1
![fola_home_v1](https://user-images.githubusercontent.com/58757647/73314868-6ec4e300-41e3-11ea-8f02-72ca5ffb3dda.jpg)
![fola_results 1_v3](https://user-images.githubusercontent.com/58757647/73314888-784e4b00-41e3-11ea-8fa9-cae6004fc005.jpg)
![fola_results 2_v3](https://user-images.githubusercontent.com/58757647/73314889-784e4b00-41e3-11ea-8822-55099523477a.jpg)
![fola_filter select 1_v3](https://user-images.githubusercontent.com/58757647/73314902-813f1c80-41e3-11ea-88ff-5417b087b0da.jpg)
![fola_filter select 2a_v3](https://user-images.githubusercontent.com/58757647/73314903-813f1c80-41e3-11ea-993a-3f9b2ca50ac0.jpg)
![fola_filter select 2b_v3](https://user-images.githubusercontent.com/58757647/73314904-813f1c80-41e3-11ea-9df2-2b98ef1667b6.jpg)
![fola_map_v3](https://user-images.githubusercontent.com/58757647/73314918-8ac88480-41e3-11ea-896c-1cf465910cc0.jpg)

**Comment by lucas-homer** [comment]
@lvl3jose looks great. One note -- do we want an actual button to initiate the search? We can also allow for triggering the search function and going to results view via 'enter' or 'on select' of one of the autocomplete's results list, but I wonder if it's also more accessible to include a 'Search' button?

**Comment by tina-moh** [comment]
thanks Jose, we may discuss on functions just a note on UI :
 Green for background is not suggested  due to visibility ( the logo has green inside so putting it over a green background creates visibility issue especially for color blind people) and secondly less color is suggested to concentrate more on content and avoid color sensibility and disruption.
Thanks

**Comment by lvl3jose** [comment]
@tina-moh I'll make the necessary changes and update asap.

**Comment by lvl3jose** [comment]
@tina-moh I'm having trouble not just making the UI greyscale, which feels like a step backward. Do you have any suggestions?

**Comment by tina-moh** [comment]
Hi Jose, 
Don’t worry we can discuss it on Tuesday, any way you could lighten the background where the logo is (ex. white, really light grey) or any other way that could have visible contrast . Now the rush is to refine the existing website for the deadline without any specific changes regarding to layout.
The new layout would be for further phases.
Thanks

**Comment by ExperimentsInHonesty** [comment]
@lvl3jose the top bar should be the current gray, not the green for visibility
![Screen Shot 2020-02-02 at 4 34 39 PM](https://user-images.githubusercontent.com/37763229/73618103-ee82f100-45d9-11ea-877e-531a7670d1ea.png)


The icons should remain the same for food pantry
![Screen Shot 2020-02-02 at 4 33 13 PM](https://user-images.githubusercontent.com/37763229/73618080-bd0a2580-45d9-11ea-9fa6-d1ca074997fe.png)
but we need a new one for hot meals (maybe a bowl, with steam coming off).

Please give us an update:
1. Progress
2. Blocks
3. Availability
4. ETA

**Comment by lvl3jose** [comment]
@ExperimentsInHonesty @chombus @tina-moh 

**Progress:** I have changed all the screens' top bar to match. I have recreated the Food Pantries icon in Figma, it just needs some minor details. Currently working on the icon for Hot Meals.

<img width="676" alt="186a9f8a1d37bb316095ae7a6c071272" src="https://user-images.githubusercontent.com/58757647/73703086-aa5c2300-46a3-11ea-8976-ad5c3dda787c.png">

**Blocks:** I'm thinking about whether the bottom bar of this screen needs to be changed as well? What about the dark green selected filter buttons?

<img width="388" alt="bfad1ccc9253a38798f905b66e1b362b" src="https://user-images.githubusercontent.com/58757647/73703198-03c45200-46a4-11ea-926a-3bfe99ae55be.png">

**Availability:** I will be at our meeting tomorrow and will also be available online all day tomorrow, Wednesday 2/5, and most of the day Friday 2/7.

**ETA:** 2/4 Tuesday morning.

**Comment by tina-moh** [comment]
@lvl3jose filters would be “Meals” ( instead of Hot meals)and “Food Pantries “ thanks 
@lucas-homer Distance not for V1?

**Comment by lvl3jose** [comment]
@ExperimentsInHonesty @tina-moh Here are the changes.

https://www.figma.com/file/Qs2zKdqZFLyPxc5qaaFCBk/FOLA-v1?node-id=0%3A1

<img width="782" alt="362f5f3651ee9bf50633c5ad99613b48" src="https://user-images.githubusercontent.com/58757647/73784322-2315ba80-474a-11ea-90af-123b6b7aa1ce.png">

**Comment by tina-moh** [comment]
<img width="124" alt="Meal" src="https://user-images.githubusercontent.com/56663382/73789873-69701700-4754-11ea-8133-193aae73e527.png">
@ Jose can use this icon for "Meals" since as decided to use  TERM "Meals" instead of" Hot meals" to cover a wider range. Thanks

**Comment by lvl3jose** [comment]
@ExperimentsInHonesty @tina-moh Here is what it looks like with the new icon.

https://www.figma.com/file/Qs2zKdqZFLyPxc5qaaFCBk/FOLA-v2?node-id=0%3A1

<img width="854" alt="80868143a621d395675cd4229640e371" src="https://user-images.githubusercontent.com/58757647/73798823-e73e1d80-4768-11ea-885b-27d42b5f6206.png">

**Comment by ExperimentsInHonesty** [comment]
snipit from slack
Bonnie  10:44 AM
Do you have an update for this issue:
https://github.com/hackforla/food-oasis/issues/162 (edited) 
There is a action item in the top part of issue: Determine interaction behavior of auto complete functionality
Have you done that?

**Comment by lvl3jose** [comment]
Here is my update on button size and contrast.
https://www.figma.com/file/Qs2zKdqZFLyPxc5qaaFCBk/FOLA-v2?node-id=0%3A1
<img width="696" alt="9134cddaa216360b6c42b3f658876b44" src="https://user-images.githubusercontent.com/58757647/74298615-1b808380-4cff-11ea-99ed-d678b9e6109f.png">

**Comment by lvl3jose** [comment]
Updated with new icons, better color contrast, and button sizes.
https://www.figma.com/file/Qs2zKdqZFLyPxc5qaaFCBk/FOLA-v2?node-id=0%3A1
<img width="895" alt="d772d3931ca5ec3a95508992dd9a6ae8" src="https://user-images.githubusercontent.com/58757647/74686492-85c57800-5186-11ea-869b-57270ad605ea.png">

**Comment by jpmikesell** [comment]
This is great Jose. Let's call this done!

**Comment by tina-moh** [comment]
UI, @lvl3jose  could you please use the same line thickness for plate and shelves .( in meal icon and food pantry icon- they should follow somehow same style) and personally I vote for four object for food pantry icon, the one with three seems empty , Thanks

**Comment by lvl3jose** [comment]
Here is the latest update.
https://www.figma.com/file/Qs2zKdqZFLyPxc5qaaFCBk/FOLA-v2?node-id=0%3A1
<img width="928" alt="6639ff97f871eda789d881226b7945bd" src="https://user-images.githubusercontent.com/58757647/74787189-68b2a700-5263-11ea-9679-d7131d01fe8e.png">

**Comment by lvl3jose** [comment]
Here is the final for v1
https://www.figma.com/file/Qs2zKdqZFLyPxc5qaaFCBk/FOLA-v4?node-id=0%3A1
![9094cc6a38ef7ca336aba291931243d0](https://user-images.githubusercontent.com/58757647/75119676-e5fe6300-5639-11ea-92b6-1c9147382d12.jpg)
<img width="818" alt="e38014c6770d74d0e0218464bdc4432a" src="https://user-images.githubusercontent.com/58757647/75119680-edbe0780-5639-11ea-8498-488f15d7f352.png">
<img width="806" alt="65e44b5572f3dfd7f127e9e623c0ed86" src="https://user-images.githubusercontent.com/58757647/75119685-f4e51580-5639-11ea-8eea-52503ba34870.png">
<img width="798" alt="da5ea9fbdf06cf33c72b9514128401f8" src="https://user-images.githubusercontent.com/58757647/75119689-f9a9c980-5639-11ea-9bb5-e9c449301da0.png">
<img width="381" alt="404635b5f87504ea5c65f0285ca34a9e" src="https://user-images.githubusercontent.com/58757647/75119690-fdd5e700-5639-11ea-8a3a-617f7549f9ed.png">

**Comment by royceduong** [comment]
@lucas-homer will provide comments by Tuesday, 2/25

**Comment by ExperimentsInHonesty** [comment]
@lucas-homer can you provide an update on this?  see comment above.

**Comment by lucas-homer** [comment]
With the exception of the below view, which I think is unnecessary, this all looks good to me. 
![image](https://user-images.githubusercontent.com/33523751/75833568-4b570000-5d6e-11ea-8290-1e782e2afabc.png)
