### ISSUE TITLE
Bug: Export button on Verification Administration doesn't work

### ISSUE THREAD

**Issue by itserindean** [hackforla/food-oasis#1632]
#### Describe the bug 

I'm trying to export the validation database so I can get some metric on thruput before/after my admin takeover.

#### Steps to reproduce the issue
go to foodoasis.net
click hamburger menu
click volunteer login.
log in with admin credentials
check 1/some/all checkboxes (Export button will become enabled)
Click export

#### What's the expected result?
i expect it to download a .cvs file

#### What's the actual result?
absolutely nothing happens.

**Comment by entrotech** [comment]
I'm not sure exactly why this was broken in production, but many changes have been made to the Verification Admin screen, including replacing react-data-grid with mui x-data-grid.  The bug was causing a 503 error in the axios request to the back-end.
