### ISSUE TITLE
Bug: Freeform text fields are missing line breaks, making them illegible

### ISSUE THREAD

**Issue by fancyham** [hackforla/food-oasis#1651]
#### Describe the bug 

Some of our listings are missing line breaks in the description, making the text very hard to read.

the linebreaks are in the database field, so it looks like it may be stripped out when displayed on the food-seeker website

#### Steps to reproduce the issue

1. Go to: https://foodoasis.la/organizations?latitude=33.8601968981324&longitude=-117.874101526717&org=neighborhood_services&id=4408
2. Look at Note field — no line breaks
3. Go to database entry https://foodoasis.la/organizationedit/4408 and look at Notes for Public.  There are line breaks in that text/  (You will need to log in as an admin to see this page.)

#### Solution

Please reproduce line breaks in org text entry fields — the breaks are important for readability. 

Please ensure this works for other freeform text fields and other orgs don’t have the same issue.

**Comment by entrotech** [comment]
Since the line breaks are stored in the database, the problem is with the panel on the organizations screen shown to food seekers on the organization detail panel.  Modified the labels to make this a dev issue.

**Comment by andyarensman** [comment]
"The listing for St. Joseph Center - Hampton Drive has the issue. The Notes for Public, Description and Covid Notes (and maybe other fields) all have some formatting in the data entered by the volunteer."
