### ISSUE TITLE
Update / Align Checkboxes with design

### ISSUE THREAD

**Issue by VirginiaWu11** [hackforla/food-oasis#1663]
### Overview
Update / Align Checkboxes with design.

### Resources/Instructions
Checkboxes Figma from design issue #1148 .

**Comment by fancyham** [comment]
The checkboxes are a bit high right now — could they be lowered?  The text baseline should match up with the text field contents, and the checkbox will probably descend a bit below that baseline:

<img width="449" alt="image" src="https://github.com/hackforla/food-oasis/assets/3376957/f25dc789-1952-4355-b99c-f10559c68794">

**Comment by junjun107** [comment]
Updated checkboxes alignment with textfields #1664 
Before:
![Screen Shot 2023-06-10 at 3 18 08 PM](https://github.com/hackforla/food-oasis/assets/60997220/c525cd24-a130-4f32-8e26-a4ab77d4fdcb)

After:
![Screen Shot 2023-06-10 at 3 17 54 PM](https://github.com/hackforla/food-oasis/assets/60997220/c10a50bb-1e18-4082-b037-c9e19e8e998e)

**Comment by junjun107** [comment]
@fancyham I moved confirm checkboxes. Can you check ?

**Comment by fnkdesign** [comment]
Hi @junjun107, the alignment for checkboxes looks great! But I believe there's one checkbox that misaligned when entering an error state (the one next to 'Name' text field): 
<img width="1680" alt="org edit form error state alightment" src="https://github.com/hackforla/food-oasis/assets/113713802/14806143-10cf-4055-81ad-6283bf8dd9c7">

Also, is it possible to change the color of checkboxes when activated to match the primary/radio button?
Here's [the link](https://www.figma.com/file/9hPmNSsyaH2VMGNz5mffmI/FOLA-Design-%232?type=design&node-id=3331%3A4596&mode=design&t=M4Ona4NgssRHe0Lg-1 ) to my Figma for more information.

Please feel free to slack me if you have any questions/update. Thank you!

**Comment by junjun107** [comment]
@fnkdesign I updated the checkbox alignment plz check.

**Comment by fnkdesign** [comment]
@junjun107 That's perfect! Thank you June!
