### ISSUE TITLE
Marketing: FOLA posters / flyers

### ISSUE THREAD

**Issue by fancyham** [hackforla/food-oasis#1667]
### Overview
We want flyer(s) that can be posted on a bulletin board or around town that sends people to the Food Oasis website.

This would be used for bulletin boards at community centers, churches, as handouts.

Our audience will be food seekers or their friends/allies who may see this poster in public settings, or may be given one by a volunteer / service provider.

### Action Items

Let’s create a library of posters that we feel comfortable sharing and using.  These may eventually be available on the website as PDFs.

### Content

Want it to be easy to read, eye-catching, trustworthy… success if if people visit or successfully tell their friends (and ultimately find food).

Definitions:
* **Poster:** We need some to catch someone’s eye from 4-8 feet away.  
* **Flyer:** These may be a stack of flyers on a table that people take, it might also be given out by volunteers.  It might also be sent via internet as a PDF.  This type of marketing might have more details, but again, easy to read and take action is very important. Simpler is better.

Some items that probably should be part of both:
* Headline
* URL
* Call to action
* Easy to read, 8th grade reading level(? even lower would be better).
* Ideally, translate these into popular languages
* (optional) Things that show why we’re trustworthy like partner logos
* (optional) Screenshot
* (optional) QR Code

### Action Items
- [x] Create posters and flyers
- [ ] (optional) Create repository of posters and flyers for future use on Google Drive (and list them here)

### Resources/Instructions
If there are similar flyers that we can use as reference, please collect links to them here or make a folder on the Google Drive.

**Comment by fancyham** [comment]
I’m expecting that we’ll have a small collection of flyers of that we can pull from for different situations.  

I created a first draft of a flyer. This one is aimed at posting around the UCLA campus and around community centers and neighborhoods as part of issue #1666.

https://docs.google.com/document/d/11WQ1RsDyQf1Uuel5csGt5lBZ4dd0LGlJXGlnM2wmD5g/edit#

![](https://files.slack.com/files-pri/T04502KQX-F056P2J8C80/image.png)

**Comment by itserindean** [comment]
i like it! I Think the white space and simple drawing draws the attention nicely.
i think we should probably include a hack for LA logo (And maybe ours too?)

I think a "flyer" optimized for social media might be useful as well... i could always ask the students to design some in canava...

**Comment by fancyham** [comment]
I think having the students try their hand at it is a great idea, too.  Would also be interested in their social media ideas.  

I put together a version with our logo and HfLA’s and you can check it out in the deck but I think their awkward shape and placement actually distract from the call to action because neither of those logos are recognizable, so in this case, I think our logos are additional friction to taking action (also the HfLA logo is illegible at that small size)… 

I think it’d be better to highlight our recognizable partners, and let the reader see our logo when they arrive at the site.

**Comment by fancyham** [comment]
@cheesarah , checking in will the current versions work for your project (and what's the deadline for the posters)?  

Once these are approved, I (or someone else) will have to manually insert the individual QR codes, before these are sent to the students.

**Comment by cheesarah** [comment]
Hi Bryan,Sorry for the late reply. These all look good and I’m wondering if I can leave it to your discretion? Or, if it’s not too much trouble we can have two versions and let the students pick? Sent from my iPhoneOn May 5, 2023, at 1:33 PM, Bryan Wu ***@***.***> wrote:﻿
@cheesarah , checking in will the current versions work for your project (and what's the deadline for the posters)?
Once these are approved, I (or someone else) will have to manually insert the individual QR codes, before these are sent to the students.

**Comment by itserindean** [comment]
I let the UCLA students know they could create social media posts for us to use for extra volunteer hours. I limited them ton2 submissions each, but if anyone is especially talented I may extend additional opportunities to them. I'll share whatever I receive!

**Comment by fancyham** [comment]
@cheesarah cool, in that case, let’s call this first version “done”!  And you can use the first two pages to crest the individual  student ones.  Am interested in hearing what the students think or get as feedback.

**Comment by fancyham** [comment]
I've also started a Figma board for folks to add their sketches, concepts and ideas (please annotate your work so we know what you're going for): https://www.figma.com/file/9hPmNSsyaH2VMGNz5mffmI/FOLA-Design-%232?type=design&node-id=3343-4599&t=T65BXQB88RsZelYW-4
