### ISSUE TITLE
Usability: No ‘enter’ button on location search field

### ISSUE THREAD

**Issue by fancyham** [hackforla/food-oasis#1668]
### Overview
On search fields, there is usually an on-screen ‘search’ button that submits the text entry to the search engine.  However, our landing page does not have this, so we are breaking with a popular UI pattern.

We basically require a user to press the ‘enter’ button on their on-screen keyboard to submit a text field — but this isn’t obvious, especially if the user selects an auto-complete item.

![IMG_2804](https://user-images.githubusercontent.com/3376957/236696276-adcbcf31-3710-4e91-87d3-f34c74c33577.jpeg)

This happens on both desktop and mobile landing pages, but it’s worse on mobile since users may not know they have to hit the ‘enter’ key on their on-screen keyboard.

### Discussion and possible Solution(s)
Suggest: 
- [x] Make the magnifying glass into a more obvious button by changing its color (it’s actually a button — try it — it goes to Los Angeles)  
- [x] Keep the magnifying glass button in the text field visible while the user enters text. 

#### Quick mockup of current the suggested solution
<img width="750" alt="image" src="https://github.com/hackforla/food-oasis/assets/3376957/661d52b0-f939-471b-b79e-43a7d9cedd55">

### Action Items

- [x] Confirm that this is a problem worth fixing (research, design teams)
- [x] Investigate problem
- [ ] Problems seem to be:
  - [ ] No ‘submit’ button, which we can fix by adding one (easy to fix - see above sketch)
  - [x] #1691
  - [ ] #1692
- [ ] Design and specify changes (design)
- [ ] Implement changes (devs)
- [ ] Beta test / QA (design, research)

**Comment by fancyham** [comment]
<img width="591" alt="image" src="https://github.com/hackforla/food-oasis/assets/3376957/6ab741e1-964c-4d2a-ba0b-14d8752760e6">

**Comment by fancyham** [comment]
Added mockup to description above

Discussion on Slack was that these proposed changes (colorizing the search button and keeping it visible while entering text) would help the user interface part of the problem.

However, there's also some weirdness when typing in a zip code and pressing return — sometimes the search returns empty, even though the zip code entered should be valid.  

Question: Does the user **have** to use one of the auto-completes to get a search result?  If the user enters free-form text, does it get geolocated properly?

**Comment by Sage-2001** [comment]
So, what I have understood by far is that the issue at hand is the landing page lacks a visible "search" button, which goes against the common user interface (UI) pattern where users expect to see a button to submit their search queries. Instead, the current implementation requires users to press the "enter" key on their keyboard to initiate the search, but this behavior may not be intuitive, especially if the user selects an auto-complete suggestion.

**Comment by fancyham** [comment]
I think there are three separate issues at play here:
1. No ‘submit’ button, which we can fix by adding one (easy to fix - see above sketch)
3. the autocomplete sometimes disappears even when there are matches (bug?)
4. It seems like even if we add a submit button, a user submitted piece of text doesn’t properly resolve into an address or GPS, even for zip codes that should work, and the search engine returns zero results. (Bug?)

**Comment by Sage-2001** [comment]
I don't know how to solve 2 and 3 issues. Any heads-up?

**Comment by Sage-2001** [comment]
@fancyham Adding the search button did not cause any issues, and it appears that the problem mentioned in #1692 is a separate bug. When attempting to enter a custom user input for an address, it seems that the application is not accepting any values unless they are selected from the dropdown autocomplete section. This behavior results in failed results for any address that is not chosen from the autocomplete options. Can you checkout my pull request by the way? Thanks

**Comment by Sage-2001** [comment]
@fancyham can you please review my pull request

**Comment by fancyham** [comment]
Being addressed in this UI update
- #1874

**Comment by qiqicodes** [comment]
Closing this issue as it has been superseded by the new design implementation.

**Comment by fancyham** [comment]
Adding screenshot from upcoming design — it has an ‘enter’ button now :)
<img width="828" alt="image" src="https://github.com/hackforla/food-oasis/assets/3376957/371d7e6b-2d5c-40d3-b126-fd23ab941cdd">
