### ISSUE TITLE
OpenTimeInput TextField Update

### ISSUE THREAD

**Issue by andyarensman** [hackforla/food-oasis#1678]
### Overview
As part of the UI standardization we want to update the OpenTimeInput. The design is being worked on [here](https://www.figma.com/file/9hPmNSsyaH2VMGNz5mffmI/FOLA-Design-%232?type=design&node-id=3331-4596&t=y5GnWF34YIccudVw-0).

### Action Items
- [x] Talk to the design team
- [x] The first line of text fields should have a label
  - [x] The custom Label component we made should be used if possible
- [x] Any subsequent lines should not have a label
- [x] Change the time selection from analog to digital if possible. ([Here is the MUI info](https://mui.com/x/react-date-pickers/digital-clock/))
- [x] Implement new error message design
- [x] Implement any other style changes
- [x] Center the placeholder text (if needed)
- [x] Add screenshots when finished for designer to see

### Resources/Instructions
- See the ["Text Field with No Label for Date Time Input concept and version B"](https://www.figma.com/file/9hPmNSsyaH2VMGNz5mffmI/FOLA-Design-%232?type=design&node-id=3796-4674&t=VNw3hkCtLFogpHfH-0) for more details
- Reference the Figma textfield designs [here](https://www.figma.com/file/9hPmNSsyaH2VMGNz5mffmI/FOLA-Design-%232?type=design&node-id=3331-4596&t=y5GnWF34YIccudVw-0)
- Reference the text field and select code on OrganzationEdit.js
- Fern K. is the designer for the new text fields
- [MUI Digital Clock](https://mui.com/x/react-date-pickers/digital-clock/)

This is how the OpenTimeInput currently looks:
![chrome_Nrv2w5Kfy8](https://github.com/hackforla/food-oasis/assets/86622025/4ff2fc3a-f328-45f9-9a82-22f4ecade552)

**Comment by fancyham** [comment]
Hi, is there something specific that needs to to be updated or is this a general query for the design team asking if there are any changes we might like?  

Please add a link and/or screenshots to the page or screen in question… but I think this is the interaction you’re talking about talking about?
https://github.com/hackforla/food-oasis/assets/3376957/8d1ff088-e8e5-453b-8c9a-555775d2965b

Could you describe or point us to a list of options? 

For example, if we wanted, could we be able to get rid of the clock dial dialog and just have people type in a time?

**Comment by andyarensman** [comment]
Hey Brian - apologies for the lack of details on this issue. The non-centered text refers to the placeholder text, which we do not need the design team's input on.

I've updated the issue slightly and added a screenshot, but I'm going to reach out to Fern with a few questions before proceeding any further.

**Comment by jenny-alexander** [comment]
Hi @fnkdesign - Is there a figma design to follow for the mobile view for this issue? I believe the reference in the resource/instructions section of this card (["Text Field with No Label for Date Time Input concept and version B"](https://www.figma.com/file/9hPmNSsyaH2VMGNz5mffmI/FOLA-Design-%232?type=design&node-id=3796-4674&t=VNw3hkCtLFogpHfH-0)) shows only desktop view.

**Comment by jenny-alexander** [comment]
Changed the size from 2pt to 5pt to better reflect required changes.

**Comment by jenny-alexander** [comment]
Update:
I am 75% complete with this issue. 
TODO: Implement the new error message design (whereby each field is highlighted in red and error message appears as helper text - instead of current design with error messages displayed in a box below). I'm going to use the Formik validation schema to do this (to keep it consistent with the form validation done in OrganizationEdit.js).

**Comment by jenny-alexander** [comment]
Update: I informed @hanapotski that I have to step away from this issue for 4-6 weeks. I will resume when I return. Or I can return the issue to the backlog if it's urgent and someone else should work on it.

**Comment by jenny-alexander** [comment]
@fnkdesign - Here are the screenshots of changes made. Can you please review and provide feedback?

<img width="1404" alt="FOLA_default_view" src="https://github.com/hackforla/food-oasis/assets/80556079/09f63aae-8991-45c9-9b71-9a4e482ac45f">
<img width="1203" alt="hours_active_state" src="https://github.com/hackforla/food-oasis/assets/80556079/d35c9af5-8710-4972-be02-7d0c9a625143">
![hours_error_state](https://github.com/hackforla/food-oasis/assets/80556079/2b303bb4-ca64-4400-bad6-ed3723853cf9)
![hours_copy_icon](https://github.com/hackforla/food-oasis/assets/80556079/2c709b69-f613-4971-9541-233b69b1f4cc)
![desktop_timepicker](https://github.com/hackforla/food-oasis/assets/80556079/91b2aeeb-5bef-46e3-a503-69b8f430cb07)
![mobile_timepicker](https://github.com/hackforla/food-oasis/assets/80556079/e4d3299c-6876-4c27-b1b7-40d9515c4e32)
![hours_mobile_view](https://github.com/hackforla/food-oasis/assets/80556079/5d9efaac-45ec-4ec9-9b4f-c1577a057e4f)

**Comment by jenny-alexander** [comment]
<img width="1404" alt="FOLA_default_view" src="https://github.com/hackforla/food-oasis/assets/80556079/bc7c9980-de4e-4ee5-a394-74ed020c0dc3">
<img width="1203" alt="hours_active_state" src="https://github.com/hackforla/food-oasis/assets/80556079/ad60ddcc-783e-45af-8df1-3254d13311b4">
![hours_error_state](https://github.com/hackforla/food-oasis/assets/80556079/569e6327-f7b8-464b-a465-397c0a3e24b7)
![hours_copy_icon](https://github.com/hackforla/food-oasis/assets/80556079/9faf8e1b-01d6-4ce5-9c8e-71d2c3c760c0)
![desktop_timepicker](https://github.com/hackforla/food-oasis/assets/80556079/9ef15ac1-0bc0-493e-b0c4-43dc532d548b)
![hours_mobile_view](https://github.com/hackforla/food-oasis/assets/80556079/e8bb965c-8cb9-4c1e-931a-da4dd7b14ea8)
![mobile_timepicker](https://github.com/hackforla/food-oasis/assets/80556079/28c207b9-3ce9-4f1b-a9ba-83a2a8cda903)

**Comment by jenny-alexander** [comment]
<img width="1404" alt="FOLA_default_view" src="https://github.com/hackforla/food-oasis/assets/80556079/4f53ba28-a2bc-412c-9c06-377f6ffc3278">

**Comment by fnkdesign** [comment]
Hi Jen, thank you for an update! Here's my feedback for a couple adjustments:
- I wonder if you incorporated hover state for text fields as well?
- Is it possible to apply the new time picker for mobile version? (for consistency experience)
- Could you please change the text 'inside' the text field to 'red' for error state? Here's an example:
<img width="384" alt="time inpu-error state" src="https://github.com/hackforla/food-oasis/assets/113713802/16c36339-a473-4fa5-bf0d-fb8900af65b2">

- I wonder how text fields would look like next to each other in rows (when users clicked 'add hours')? They look fine on the mobile version though!

Also, I don't see changes on our [development site](https://devla.foodoasis.net/) yet? Are you able to make your changes accessible? If you could, that would be great for us to test it out and provide any additional feedback.

**Comment by jenny-alexander** [comment]
@fnkdesign, thank you for the feedback. Yes, I can make those adjustments.
 
I'm on vacation for the next 3 weeks so will most likely won't have anything on the dev site until mid-to-end of August (pending a code review by FOLA devs).

**Comment by jenny-alexander** [comment]
@fnkdesign Here are screenshots of the changes you requested. I'll do my best to attend the Monday evening dev meeting and ask for a review (if you approve the latest changes).

![FOLA_hover_state](https://github.com/hackforla/food-oasis/assets/80556079/bd7fb4b0-d3b0-48f2-9898-a654636eb7f1)

![mobile_view_updated](https://github.com/hackforla/food-oasis/assets/80556079/f4250c7e-8f74-4f93-832c-48755d422488)

![red_placeholder_text](https://github.com/hackforla/food-oasis/assets/80556079/274512de-0ccb-47cb-915a-8378e022383f)

![multiple_rows_desktop](https://github.com/hackforla/food-oasis/assets/80556079/2fcc68a9-28e0-4acd-ba6d-1475b9f894e3)

**Comment by fnkdesign** [comment]
@jenny-alexander These screenshots looks great! I think the last adjustment that needs to be done is to change the font weight of "Business Hours" (label) to 'Medium' instead of 'Regular':

<img width="720" alt="label medium weight" src="https://github.com/hackforla/food-oasis/assets/113713802/24b87b9c-1b6e-4066-9151-df5f7c86715a">

**Comment by jenny-alexander** [comment]
@fnkdesign Here is the screenshot with modified label:
<img width="1290" alt="Screenshot 2023-07-31 at 1 55 14 PM" src="https://github.com/hackforla/food-oasis/assets/80556079/1b7ce03e-cce9-458d-9abc-ccf0e29c5525">


==> Also, I reviewed the action items listed above and is it correct to only show the "Business Hours" label once...even if there are multiple rows of business hours?

**Comment by fnkdesign** [comment]
@jenny-alexander You are correct about the label - the screen shot above looks awesome! Thank you for a quick update!

**Comment by jenny-alexander** [comment]
@fnkdesign - The changes are now reflected on the [dev site](https://devla.foodoasis.net/).

**Comment by fnkdesign** [comment]
@jenny-alexander I checked it out and it looks great, works great! Thank you for putting this together.
