### ISSUE TITLE
Eliminate Secondary Link Design Style

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#1682]
### Overview
Per Issue #1452 latest revision, Seiko decided to get rid of the secondary link color design for use with in-line text, and revert to using a single link style.

### Action Items
- [x] Change links that currently use the secondary link style back to using the primary link style.
- [x] Remove code that implements the secondary link style from the theme.

**Comment by amauryplayero** [comment]
Hi! I would like to be assigned to this issue. Read the instructions to contribute, but am unable to assign myself the issue. Does this mean I'd have to join hack for LA formally?

Thank you :)

**Comment by amauryplayero** [comment]
@entrotech Hi! just double checking to see if you had read my comment
