### ISSUE TITLE
Reorder the footer on smaller screens

### ISSUE THREAD

**Issue by hanapotski** [hackforla/food-oasis#1686]
### Action Items
- Reorder the footer on smaller screens so that the order goes from Find Food > About Us > Donate > FAQs > Suggest New Listing

### Resources/Instructions
[context](https://github.com/hackforla/food-oasis/issues/1520)

**Comment by victorchrollo14** [comment]
hey, I would to like to work on this issue, but there doesn't seem to be any footer.
![Screenshot from 2023-05-17 13-01-23](https://github.com/hackforla/food-oasis/assets/89346667/9e43283a-9079-4c1d-ad1c-590f5858204c)

**Comment by elsa-linu** [comment]
@hanapotski Hey, I would like to work on this issue.

**Comment by junjun107** [comment]
Updated Footer list order 
<img width="495" alt="Screen Shot 2023-06-10 at 12 38 05 PM" src="https://github.com/hackforla/food-oasis/assets/60997220/bb3bb759-53be-4846-8f27-5b0d5ad912d1">
