### ISSUE TITLE
Static pages: Currently no way to contact us — missing contact info / email / form

### ISSUE THREAD

**Issue by fancyham** [hackforla/food-oasis#1687]
### Overview
During the last ‘about us’ page update, we accidentally dropped the ‘contact us’ instructions from our site.

We need a way for folks to reach us — a simple email address is fine, but we also designed a web-based email form for anonymous and easy messages to our team. (#1288) which is currently in the development backlog, so I think waiting to be worked on.

While that contact form is being developed, we should probably put the email instructions back on the website.

### How it’s used

In the past we didn’t have that many people reaching out to us, but this link will likely be used for:
- Food seekers with additional questions, requests, comments
- Contacting us as an organization by partners, press, government, other orgs - to ask questions, to learn about us and our system, for possible partnerships, etc.
- People emailing us about things that don’t fit into the ‘[suggest a new listing](https://foodoasis.la/suggestion)’ form.

### Action Items
- [ ] Get something up now on the public website now so people can contact us
- [ ] Implement new version (i.e. a form)

Please look at these related issues and see what makes the most sense for right now.  

- #1288 - (contact form options)
- #1365 - (text revisions)

If it requires a new ‘Contact us’ page, then please build it and add the link to the footer:

I believe that we Ideally, a form would be great, but the development might take a while.  In that case or while that’s being developed, please push our contact email address to the live website now while that’s being worked on.

Archive.org snapshot:
> <img width="368" alt="image" src="https://github.com/hackforla/food-oasis/assets/3376957/879d527d-c5d0-42ec-9b1d-636a5ed740c5"> 
https://web.archive.org/web/20220628020827/https://foodoasis.la/about

CONTACT US

Questions about our project?
Updates to the listings?
General inquiries?

Please contact our Support Team
foodoasisinfo@hackforla.org

**Comment by sei1122** [comment]
The dev team updated and we can see it on the dev environment.
https://devla.foodoasis.net/about
