### ISSUE TITLE
Feature: Implement contact us form

### ISSUE THREAD

**Issue by kurikurichan** [hackforla/food-oasis#1718]
### Overview
- Implement the contact us form as described in Issue #1288 

### Action Items
- [x] Figure out whether or not we need a new web API endpoint to send email
- [x] Design form 
- [ ] Review with design team after it is completed

### Resources/Instructions
Please refer to Issue #1288 

Note: On FAQ page but not actually static

**Comment by shefali12-ab** [comment]
Hii @kurikurichan , is somebody working on this issue.

**Comment by kurikurichan** [comment]
Hi @shefali12-ab, sorry for not replying sooner, but yes, I am working on it!

**Comment by shefali12-ab** [comment]
no problem @kurikurichan.
