### ISSUE TITLE
Change Walk-in Allowed tag color

### ISSUE THREAD

**Issue by sei1122** [hackforla/food-oasis#1728]
### Overview
Currently, we use button blue for the Walk-ins Allowed tag color on the org data info section. Looks clickable because the color is the same as the button.

### Action Items
Designer selects a different color for the tag. 

### Resources

<img width="1202" alt="Screen Shot 2023-06-27 at 8 45 40 PM" src="https://github.com/hackforla/food-oasis/assets/19811032/024e90de-8a4f-42a1-8dba-533a7e472597">

**Comment by hirentimbadiya** [comment]
we can use purple color for "Walk-ins Allowed" ?? , I would like to work on this issue, Please assign me. @sei1122

**Comment by sei1122** [comment]
Hi @hirentimbadiya, did you do an onboarding Hack for LA and Food Oasis?

**Comment by hirentimbadiya** [comment]
Yes I attended onboarding session of Hack For LA

**Comment by sei1122** [comment]
Nice, you attended the onboarding of Hack For LA. 
If you decided to join the Food Oasis, there is onboarding too. Please join the #fola channel and contact us. We will connect you to the team lead.

**Comment by andyarensman** [comment]
This issue is resolved in #2074
