### ISSUE TITLE
Align logo with the baseline of the nav links in Footer

### ISSUE THREAD

**Issue by junjun107** [hackforla/food-oasis#1731]
### Action Items
* Align the base of logo with the base of the last list item when on mobile view 

On large screen:
![image](https://github.com/hackforla/food-oasis/assets/60997220/adef1065-5874-4628-ac26-e0689301b1f7)

on mobile screen:
![image](https://github.com/hackforla/food-oasis/assets/60997220/0c1fdd62-eb96-4857-83c0-0ce84ca0025b)

Resources: 
[Reorder footer nav list order on small screen](https://github.com/hackforla/food-oasis/issues/1686)

**Comment by karenhernandeze** [comment]
Can I be assigned this one?

**Comment by junjun107** [comment]
![Screen Shot 2023-07-24 at 5 10 06 PM](https://github.com/hackforla/food-oasis/assets/60997220/92cf660a-a208-440a-a88a-d8b48385a4c9)

**Comment by junjun107** [comment]
@fancyham can you review this ?
