### ISSUE TITLE
Upgrade the AWS SDK for Javascript to V3.

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#1740]
### Overview
When I run the server in the dev environment, I get the following message in the terminal:
```
(node:22324) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
```
### Action Items
I believe this is only used by the AWS geolocation feature, so it might make sense for Matt to work on it, if he is available.

- [ ] Update the AWS SDK package.
- [ ] Regression test.

**Comment by Nechir-89** [comment]
I tested and I upgraded  AWS SDK for JavaScript (v2) to newer version but it seems the message is primarily talking about changing code format and syntax to newer version and not just upgrading version number of AWS SDK.

what I found is, currently there is still v2 (2.1446.0) on NPM registry "[aws-sdk NPM package](https://www.npmjs.com/package/aws-sdk)" however on GitHub the version number is different story "[aws-sdk-js-v3](https://github.com/aws/aws-sdk-js-v3)"

Maybe this task need to be assigned to someone who worked on it before.
