### ISSUE TITLE
Fix "Get Coordinates" Button Position

### ISSUE THREAD

**Issue by andyarensman** [hackforla/food-oasis#1747]
### Overview

On the Organization Edit Form in the Admin Dashboard, the "Get Coordinates" button should be aligned with the Lat/Long fields

![chrome_nzSIpsQo7r](https://github.com/hackforla/food-oasis/assets/86622025/a5a8a6ee-8494-46f3-bb16-10745abc0c07)

**Comment by jenny-alexander** [comment]
@fnkdesign Changes done as per requested. Here are 3 screenshots showing different breakpoint sizes.

Please confirm it looks good or if changes are needed!

![Screenshot 2023-08-29 at 12 07 33 PM](https://github.com/hackforla/food-oasis/assets/80556079/75998671-ea51-40bc-9c08-26ff8a8aaf34)

![Screenshot 2023-08-29 at 12 08 49 PM](https://github.com/hackforla/food-oasis/assets/80556079/a57d2496-ac78-4842-a02b-b1b89612b093)

![Screenshot 2023-08-29 at 12 09 31 PM](https://github.com/hackforla/food-oasis/assets/80556079/77f6156f-8f39-4e9f-b04f-eae99b995edf)

**Comment by fnkdesign** [comment]
This looks awesome! Thank you @jenny-alexander!

**Comment by jenny-alexander** [comment]
@fnkdesign - the changes are now on the [dev fola](https://devla.foodoasis.net) site. Please check to make sure it is as expected.

**Comment by fnkdesign** [comment]
@jenny-alexander It is as expected. Thank you for the update!
