### ISSUE TITLE
Add Microsoft Clarity to the project 

### ISSUE THREAD

**Issue by sisi-in-tech** [hackforla/food-oasis#1753]
### Overview 
The PM team is working to get more data from our users and have signed up for a Microsoft Clarity account to get the data the instructions are to Copy and paste the Clarity code into the app.

### Action Items 
- [ ] Add this code snippet to the index.html file.
``` 
<script type="text/javascript">
    (function(c,l,a,r,i,t,y){
        c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
        t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
        y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
    })(window, document, "clarity", "script", "icb9dr54qj");
</script>
```

### Resources/Instructions
[context](https://hackforla.slack.com/archives/CP86PUF9N/p1691440769358959)

**Comment by fancyham** [comment]
Just putting this here for future searchers: Microsoft Clarity is a user behavior and website debugging analytics tool
