### ISSUE TITLE
Create draft design of stakeholder details

### ISSUE THREAD

**Issue by chombus** [hackforla/food-oasis#178]
### Overview
Define the design of the stakeholder details page and create a rough wireframe 

### Action Items
- [x] Create updated low fidelity wireframes
- [x] Determine interaction behavior
- [x] Review with team and iterate on design

### Resources
Existing pages
 - https://foodoasis.la/farmers-market/l-a-city-hall-little-tokyo-cfm/?deserts=1
 - https://foodoasis.la/food-pantry/san-gabriel-mission/?deserts=1

**Comment by chombus** [comment]
**Existing interface**
1) 
![image](https://user-images.githubusercontent.com/49743179/70876125-45bafc80-1f6d-11ea-9c46-b4d4cbcbd5d4.png)




2) 
![image](https://user-images.githubusercontent.com/49743179/70876089-23c17a00-1f6d-11ea-8334-c76255241870.png)

**Comment by chombus** [comment]
The info we want to show:
![image](https://user-images.githubusercontent.com/49743179/70876180-74d16e00-1f6d-11ea-9a4e-6f7a524d7962.png)

**Comment by chombus** [comment]
@tina-moh can you post a link to your latest designs in the issue description?

**Comment by tina-moh** [comment]
Hi Chait, SORRY yes Asap.
could you please assign me in group 12 in progress, it seems 
I unassigned myself!!!

**Comment by tina-moh** [comment]
<img width="423" alt="Screen Shot 2020-01-14 at 10 55 11 AM" src="https://user-images.githubusercontent.com/56663382/72373135-8321bf80-36bc-11ea-8617-d8a9a60ce927.png">

**Comment by tina-moh** [comment]
<img width="289" alt="Screen Shot 2020-01-14 at 11 16 49 AM" src="https://user-images.githubusercontent.com/56663382/72374589-6e92f680-36bf-11ea-8843-8912647b37bd.png">

**Comment by ExperimentsInHonesty** [comment]
Please provide update:
1. Progress
2. Blocks
3. Availability
4. ETA

**Comment by ExperimentsInHonesty** [comment]
@tina-moh please mock up the existing layout for stakeholder detail to show all the fields that Chait has identified above.  - Tina says eta 2/4/2020.

**Comment by tina-moh** [comment]
https://www.figma.com/file/QgM5vS8NhDNXhknnFpu2Hn/Prototyping-in-Figma?node-id=26%3A394

**Comment by tina-moh** [comment]
<img width="744" alt="Stakeholders List" src="https://user-images.githubusercontent.com/56663382/73801802-769aff00-4770-11ea-8df0-aaf4e1f8fb5e.png">

**Comment by tina-moh** [comment]
<img width="827" alt="Meal Detail" src="https://user-images.githubusercontent.com/56663382/73801852-a3e7ad00-4770-11ea-8551-0e58efe72a75.png">

**Comment by tina-moh** [comment]
<img width="827" alt="Food Pantry Details" src="https://user-images.githubusercontent.com/56663382/73801953-e6a98500-4770-11ea-9e38-5e89ca6c6da0.png">

**Comment by tina-moh** [comment]
<img width="895" alt="Food Pantry Detail" src="https://user-images.githubusercontent.com/56663382/73806755-3abb6600-477f-11ea-9b28-10b809e33c1a.png">

**Comment by ExperimentsInHonesty** [comment]
@tina-moh are you done with this issue?  Can you hit the check boxes at the top to indicate areas where it is complete.  

@lucas-homer is there a issue that this is a dependancy for.  If yes, please indicated here, if no, please create a new issue (throw it in the icebox) and indicate that it is dependent on this issue.
```yaml
### Dependency
Issue #178
```

**Comment by lucas-homer** [comment]
@tina-moh as we just discussed, these designs need one more item -- the search input (for current location OR a user's typed input). It should probably live in the same row as the filter buttons.

**Comment by tina-moh** [comment]
ETA Tuesday 02/18

**Comment by tina-moh** [comment]
<img width="750" alt="Stakeholders detaiL B1" src="https://user-images.githubusercontent.com/56663382/74786026-9c400200-5260-11ea-8525-aecd54422fe3.png">
<img width="751" alt="stakeholders details B2" src="https://user-images.githubusercontent.com/56663382/74786050-a82bc400-5260-11ea-8134-0ae2fee5437f.png">
<img width="750" alt="Stakeholders detail B3" src="https://user-images.githubusercontent.com/56663382/74786066-b083ff00-5260-11ea-895e-048b1c2c2df0.png">

**Comment by tina-moh** [comment]
https://www.figma.com/file/QgM5vS8NhDNXhknnFpu2Hn/Prototyping-in-Figma?node-id=26%3A394

**Comment by tina-moh** [comment]
<img width="750" alt="Stakeholders detaiL B1" src="https://user-images.githubusercontent.com/56663382/74786216-fd67d580-5260-11ea-9050-f02a80a017ad.png">

**Comment by tina-moh** [comment]
<img width="751" alt="stakeholder details B2" src="https://user-images.githubusercontent.com/56663382/74786501-b75f4180-5261-11ea-97d3-27e4364310c4.png">

**Comment by tina-moh** [comment]
<img width="913" alt="Stakeholder Details b3" src="https://user-images.githubusercontent.com/56663382/74786520-c34b0380-5261-11ea-96aa-f47aba1011ef.png">

**Comment by tina-moh** [comment]
<img width="247" alt="Screen Shot 2020-02-18 at 4 11 45 PM" src="https://user-images.githubusercontent.com/56663382/74789395-7d923900-5269-11ea-9c92-d590f883b5b9.png">

**Comment by tina-moh** [comment]
<img width="530" alt="B01" src="https://user-images.githubusercontent.com/56663382/74789550-ed082880-5269-11ea-9af4-a6ac0c2d7e8e.png">

**Comment by tina-moh** [comment]
<img width="714" alt="B02" src="https://user-images.githubusercontent.com/56663382/74789562-f5606380-5269-11ea-80fd-a838676cc3f2.png">

**Comment by tina-moh** [comment]
<img width="714" alt="B03" src="https://user-images.githubusercontent.com/56663382/74789581-ff826200-5269-11ea-9afa-d13fd094453e.png">

**Comment by tina-moh** [comment]
<img width="1095" alt="P2" src="https://user-images.githubusercontent.com/56663382/75060872-7733d500-5494-11ea-9bfe-4792ad9e3767.png">

**Comment by tina-moh** [comment]
<img width="1054" alt="P3" src="https://user-images.githubusercontent.com/56663382/75060937-9468a380-5494-11ea-882d-f6faf12727cd.png">

**Comment by tina-moh** [comment]
<img width="1058" alt="P4" src="https://user-images.githubusercontent.com/56663382/75061133-f2958680-5494-11ea-94b8-a5cff0daecab.png">

**Comment by tina-moh** [comment]
https://www.figma.com/file/QgM5vS8NhDNXhknnFpu2Hn/Prototyping-in-Figma?node-id=26%3A394

**Comment by tina-moh** [comment]
<img width="998" alt="P2" src="https://user-images.githubusercontent.com/56663382/75062748-448bdb80-5498-11ea-8fd6-245fd4e8e10c.png">

**Comment by tina-moh** [comment]
<img width="998" alt="P4" src="https://user-images.githubusercontent.com/56663382/75063009-c4b24100-5498-11ea-9432-fc84fd09332e.png">

**Comment by tina-moh** [comment]
<img width="999" alt="P3" src="https://user-images.githubusercontent.com/56663382/75064005-f4624880-549a-11ea-8c12-ee8bdfe4115b.png">

**Comment by lucas-homer** [comment]
Thanks @tina-moh for these! They look good to me.

**Comment by royceduong** [comment]
@ExperimentsInHonesty signed off on this, 2/23/20 during Sunday meeting. It is now closed.
