### ISSUE TITLE
Update Styling System to Use xs Prop in Material-UI Components in Desktop.js

### ISSUE THREAD

**Issue by 93Belen** [hackforla/food-oasis#1781]
### Overview
Our project currently utilizes the makeStyles function for styling Material-UI components. However, with the updates in Material-UI version 5, it is recommended to transition to using the sx prop for styling. 
Additionally, once we don't use the makeStyles function, we will be able to remove the `mui/styles` dependency, which has conflicts with React v.18 recently added to our project. 
This GitHub issue is part of a series of Issues aiming to update the styling system in our project. In this issue, we are going to update Update Styling System to Use xs Prop in Material-UI Components in `/components/FoodSeeker/SearchResults/layouts/Desktop.js` 

### Action Items
- [x] Replace HTML elements with Material Ui components
- [x] Replace the existing makeStyles implementation with the xs prop for styling.
- [x] Ensure that the changes do not impact the styling overrides in the theme folder.
- [x] Make sure you don't lose accessibility when replacing semantic HTML for Material UI Components

### Resources/Instructions
https://mui.com/material-ui/getting-started/overview/
https://mui.com/material-ui/migration/migration-v4/

**Comment by jenny-alexander** [comment]
Changes made.

**Before:**
![Screenshot 2023-09-29 at 10 47 23 AM](https://github.com/hackforla/food-oasis/assets/80556079/c6badea3-3925-41d0-a4c1-9d2bf4faa45e)

**After:**
![Screenshot 2023-09-29 at 10 47 54 AM](https://github.com/hackforla/food-oasis/assets/80556079/05358a99-e4e8-451e-80fc-4241c029a98e)
