### ISSUE TITLE
Advanced Filtering: Days

### ISSUE THREAD

**Issue by andyarensman** [hackforla/food-oasis#1806]
### Overview
This is part of the advanced filtering feature. The days button will allow the user to specify what day/time the locations are open.

### Action Items
- [ ] Look at the design
- [ ] Implement it

### Resources/Instructions
- Checkout the Figma file https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/FOLA-Design-%231?node-id=12002%3A33590&mode=dev
- Click on the Deafult Page and press play to see the prototype

![chrome_9cMH0esZ16](https://github.com/hackforla/food-oasis/assets/86622025/95b1e5a7-2c11-4847-81a3-7f07a1802ba5)

**Comment by VirginiaWu11** [comment]
Note-
link to figma button on map: https://www.figma.com/file/9hPmNSsyaH2VMGNz5mffmI/FOLA-Design-%232?type=design&node-id=5719-20618&mode=design&t=VrqyidVJFNQVbEY5-4

link to figma filter panel: https://www.figma.com/file/9hPmNSsyaH2VMGNz5mffmI/FOLA-Design-%232?type=design&node-id=5719-24255&mode=design&t=VrqyidVJFNQVbEY5-4
