### ISSUE TITLE
Advanced Filtering: Remove the "Search this area" button

### ISSUE THREAD

**Issue by SAUMILDHANKAR** [hackforla/food-oasis#1807]
### Overview
This is part of the advanced filtering feature. The "search this area" button should be removed.

### Action Items
- [x] Look at the design
- [x] Implement it

### Resources/Instructions
- Checkout the Figma file https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/FOLA-Design-%231?node-id=12002%3A33590&mode=dev
- Click on the Deafult Page and press play to see the prototype

![chrome_9cMH0esZ16](https://github.com/hackforla/food-oasis/assets/86622025/95b1e5a7-2c11-4847-81a3-7f07a1802ba5)

**Comment by junjun107** [comment]
Closing this addressed in  https://github.com/hackforla/food-oasis/issues/1824

**Comment by SAUMILDHANKAR** [comment]
As discussed in the team meeting yesterday, we have decided to completely remove the "Search this area" button. So, reopening this issue. Additional action item:
 - [ ] Remove unused code introduced as part of issue #1824.
