### ISSUE TITLE
Migrate makeStyles styling system to sx props styling in TagAdmin.js

### ISSUE THREAD

**Issue by lateral-neck-stretch** [hackforla/food-oasis#1840]
### Overview
Our project currently uses `makeStyles` (which uses [JSS](https://mui.com/system/styles/basics/) under the hood) to style Material UI components. JSS is now deprecated in Material UI v5, and the new default styling engine ([Emotion](https://emotion.sh/docs/introduction)) requires a shift to `styled` or `sx` API. Material UI recommends `sx` API for creating responsive styles, and we will be using `sx` API to replace instances of `makeStyles`.

This issue is for the the TagAdmin component in `components/Admin/TagAdmin.js`.

### Action Items

- [ ] Replace the existing `makeStyles` implementation with use of the `sx` prop in the TagAdmin component.
- [ ] Ensure that the changes do not impact the styling overrides in the theme folder.
- [ ] Make sure you don't lose accessibility when replacing semantic HTML for Material UI Components.
- [ ] Resolve dependency conflicts (if any).

### Resources/Instructions
https://mui.com/material-ui/migration/migrating-from-jss/
https://mui.com/material-ui/migration/migration-v4/
Issue #1705 (refer to for an example of how these changes were applied to the FAQ page)

**Comment by junjun107** [comment]
duplicate ticket #1832
