### ISSUE TITLE
Add feature flag information to the dev wiki

### ISSUE THREAD

**Issue by SAUMILDHANKAR** [hackforla/food-oasis#1876]
### Overview
We are planning to use feature flags while developing "Advanced filters" feature. In this issue, we will add the required information to the wiki.

### Action Items
- [x] Add steps for using feature flags in this issue.
- [x] Explore if additional relevant information can be added.
- [x] Reach out to the team for feedback.
- [x] Add the final information to a new page in the developer wiki.

**Comment by SAUMILDHANKAR** [comment]
Implementing feature flags is a way to deploy a piece of code in production while restricting access to only a subset of users. <sup>(1)</sup>

Next few points are a discussion on how this was implemented in our project to selectively remove the "Search this area" button:

- To implement feature flags, we created a custom react hook [useFeatureFlag](https://github.com/hackforla/food-oasis/blob/develop/client/src/hooks/useFeatureFlag.js) which returns a boolean, based on if the environment variable ```REACT_APP_FEATURE_FLAGS``` is present in the ```.env.local``` file (the .env.local file was added to the local environment with the aforementioned environment variable). 
- The ```/client/.env.local``` path was also added to the [.gitignore](https://github.com/hackforla/food-oasis/blob/develop/.gitignore) file so the file is not part of the repo, however, .env.local file can be added in another environment, to use the environment variables as required.
- Finally, we passed the ```advancedFilter``` parameter in the custom hook function within the [resultmap.js](https://github.com/hackforla/food-oasis/blob/develop/client/src/components/FoodSeeker/SearchResults/ResultsMap/ResultsMap.js) file as follows. https://github.com/hackforla/food-oasis/blob/779c5e5d3221faf207258a6d079c557ef461f8bd/client/src/components/FoodSeeker/SearchResults/ResultsMap/ResultsMap.js#L78 The boolean value thus returned (depending on if the env variable is present in .env.local file) was then used with the "search this area" button (in [this](https://github.com/hackforla/food-oasis/blob/779c5e5d3221faf207258a6d079c557ef461f8bd/client/src/components/FoodSeeker/SearchResults/ResultsMap/ResultsMap.js#L205) line) to turn on or off its visibility.

Similarly, this custom hook can be used while developing other features.

**Reference**

1. https://www.oreilly.com/library/view/managing-feature-flags/9781492028598/ch01.html

**Comment by hanapotski** [comment]
@entrotech does this look good to you?🙃 this implementation is just temporary as this doesn't allow other people aside from devs to enable feature flags. We just added it so we can start working on the advanced filters 😅

**Comment by SAUMILDHANKAR** [comment]
Thank you @hanapotski. I just added the link to the PR in the references. Also, wondering if we should add a copy of ```.env.local``` file in the dev folder of the Google drive. Please let me know if that would be helpful.

**Comment by SAUMILDHANKAR** [comment]
Thank you @entrotech @junjun107 for your review and feedback. I have added the information to the wiki page [here](https://github.com/hackforla/food-oasis/wiki/Feature-Flags).
