### ISSUE TITLE
Attribution hidden in map's mobile view 

### ISSUE THREAD

**Issue by SAUMILDHANKAR** [hackforla/food-oasis#1930]
### Overview
Currently, attribution image, links, icons of mapbox, openstreetmap etc get hidden behind the draggable component. In this issue, we will implement an optimal solution to address this.

Please see the video below for reference. [This line](https://github.com/hackforla/food-oasis/pull/1893/files#diff-ca154e224b396e2f5a75697c0cc83cd7bea4221ca3ebf675e952b3a96d805322R45) can be edited to reproduce the behavior in the video.

https://github.com/hackforla/food-oasis/assets/843538/5b315d16-d4e4-4437-b61e-4161464c862c

### Action Items
- [ ] Explore ways to solve this problem.
- [ ] Discuss with team if required.
- [ ] Implement the solution.
- [ ] Make sure existing functionalities are not impacted.

### Resources/Instructions
- [Mobile.js](https://github.com/hackforla/food-oasis/blob/develop/client/src/components/FoodSeeker/SearchResults/layouts/Mobile.js)

**Comment by SAUMILDHANKAR** [comment]
@JohnHaoHuang Hi John, Hope you are doing well. I am reaching out for your help on the design part of this issue. Currently, in mobile view, the attribution gets hidden behind the draggable list component. We need to make sure the attribution is always visible as per https://docs.mapbox.com/help/getting-started/attribution/. It would be very helpful if you can suggest a way to incorporate this in our [design wireframe](https://www.figma.com/file/9hPmNSsyaH2VMGNz5mffmI/FOLA-Design-%232?type=design&node-id=640-125&mode=design). Looking forward to your suggestions. Thank you.

**Comment by JohnHaoHuang** [comment]
Please have elements ( image, links, icons ) attached on on top of the sliding card component. Please look at my sketch in figma for further reference. Let me know if you have more question or if this solution does not work. Thank you.

https://www.figma.com/file/9hPmNSsyaH2VMGNz5mffmI/FOLA-Design-%232?type=design&node-id=640%3A125&mode=design&t=EE9R10rW1eli3HqE-1

**Comment by SAUMILDHANKAR** [comment]
> Please have elements ( image, links, icons ) attached on on top of the sliding card component. Please look at my sketch in figma for further reference. Let me know if you have more question or if this solution does not work. Thank you.
> 
> https://www.figma.com/file/9hPmNSsyaH2VMGNz5mffmI/FOLA-Design-%232?type=design&node-id=640%3A125&mode=design&t=EE9R10rW1eli3HqE-1

Thank you for creating the sketch on Figma and explaining the expectation.
