### ISSUE TITLE
Bug - Remove autofocus on AddressDropDown in ResultsFilters

### ISSUE THREAD

**Issue by junjun107** [hackforla/food-oasis#1936]
### Overview
We have autofocus on address input bars on Home and ResultsFilters. When visiting ResultsFilters page on mobile, the autofocus triggers the keyboard on mobile devices. User have to exit input first to continue with search. 
<img src="https://github.com/hackforla/food-oasis/assets/60997220/42ee8460-2945-478a-b46c-0067a042adca" width="200" alt="IMG_9127">

### Action Items
- [ ] only keep autofocus on Home page
- [ ] remove autofocus on ResultsFilters

**Comment by Aend23** [comment]
hello as per your 
Action Items
 only keep autofocus on Home page
 remove autofocus on ResultsFilters 

i created an solution can it would be great if you review it , looking forward for any to your review.

**Comment by junjun107** [comment]
> hello as per your Action Items only keep autofocus on Home page remove autofocus on ResultsFilters
> 
> i created an solution can it would be great if you review it , looking forward for any to your review.

Hello, to participant in Food Oasis - HackForLA please visit [HackforLA](https://www.hackforla.org/getting-started) for details.
