### ISSUE TITLE
Change color of email templates on contact form

### ISSUE THREAD

**Issue by kurikurichan** [hackforla/food-oasis#1954]
### Overview
We are working on an overhaul of the FOLA website design, and are also changing the colors. The light green color we used previously as a staple will be dark green and the FOLA logo has also changed. The email templates should change colors and logo to reflect the new styles we are using. 

### Resources/Instructions
[New styles](https://www.figma.com/file/9hPmNSsyaH2VMGNz5mffmI/FOLA-Design-%232?type=design&node-id=5721-25429&mode=design)

**Comment by SAUMILDHANKAR** [comment]
@JohnHaoHuang Hi John, requesting your help on the green color that should be used in the background of the food oasis logo as shown in the email template image below. I am going to replace the logo but not sure which shade of dark green should be used in the background.  Please let me know. Thank you.

<img width="390" alt="Email template" src="https://github.com/hackforla/food-oasis/assets/843538/f741bc1e-0389-4961-ac2b-afb965e62e47">

**Comment by SAUMILDHANKAR** [comment]
@JohnHaoHuang Thank you for your feedback. Adding your comments from May 4th below:
