### ISSUE TITLE
Update StakeholderDetails Icon to new ones without white border 

### ISSUE THREAD

**Issue by junjun107** [hackforla/food-oasis#1966]
### Overview
Old map icons reused as map marker, marker on click and stakeholder detail icons. However, new design has its own each for each state. Update the codes accordingly 

old icon ![image](https://github.com/hackforla/food-oasis/assets/60997220/ea0cab86-f277-47f5-b7cd-85896196441c) 
new icon ![image](https://github.com/hackforla/food-oasis/assets/60997220/1b71ebad-d016-4913-90ed-baccea52bcad)

### Action Items
Use the following Figma links to locate correct icons needed under lcons on Panel 
https://www.figma.com/file/9hPmNSsyaH2VMGNz5mffmI/FOLA-Design-%232?type=design&node-id=640-125&mode=design&t=mkQ8pAJGRjTkm6PV-0 
![image](https://github.com/hackforla/food-oasis/assets/60997220/a6ffcb1b-f17c-4468-9774-f9dd836f24d3)

**Comment by andyarensman** [comment]
Old: 
![chrome_IdvQ7L0hVP](https://github.com/hackforla/food-oasis/assets/86622025/91d10a2f-1f31-47a8-a5a2-ffc7fdd670ee)

New (Icons are supposed to be bigger according to the figma file):
![chrome_Z1bPGFSSCk](https://github.com/hackforla/food-oasis/assets/86622025/ab8ccbc2-a435-4302-8ee1-dca34b90b835)

Closed Location:
![chrome_DGHcfUGV6Q](https://github.com/hackforla/food-oasis/assets/86622025/d1f9ac64-d58a-408b-8903-f2e4de987433)
