### ISSUE TITLE
Bug: Identical Text Across All Google Sitelinks for FOLA 

### ISSUE THREAD

**Issue by junjun107** [hackforla/food-oasis#1976]
When search Food Oasis on Google, this is what comes up. Small text under each title are all same.
![Screenshot 2024-01-19 at 3 03 14 PM](https://github.com/hackforla/food-oasis/assets/60997220/155ddad0-0d8f-4b13-9598-8f7238c26127)

Virginia mentioned this could be related to the SEO.js in client. 

Example what it should look like: 
![image](https://github.com/hackforla/food-oasis/assets/60997220/ee657b0d-0c26-4ab6-8eff-1ec9c2f0bab9)

## To do

- [ ] Research how Google populates those subheads
- [ ] Come up with something more meaningful and helpful
- [ ] Put that text onto the pages so Google uses them

**Comment by VirginiaWu11** [comment]
Was looking at the first few sentences of the page and I don't think they are concise enough to be the SEO description. 
Can we pass this ticket to someone who can help with the copy? @entrotech
