### ISSUE TITLE
Gray variant Button needs Disabled State Styling

### ISSUE THREAD

**Issue by 93Belen** [hackforla/food-oasis#1982]
### Overview
To address #1965 we created a new Button variant called gray. This variant needs to specify the styling for the disabled state.

Figma file:
https://www.figma.com/file/9hPmNSsyaH2VMGNz5mffmI/FOLA-Design-%232?type=design&node-id=640-125&mode=design&t=xdwtmisCgWb93Pp4-0

**Comment by kurikurichan** [comment]
I spoke to John the designer and it sounds like there is no special disabled state he wants to add
