### ISSUE TITLE
Research: Investigate Options to Reduce Heroku Hosting Costs

### ISSUE THREAD

**Issue by qiqicodes** [hackforla/food-oasis#1995]
Explore strategies to lower the ongoing monthly hosting expenses of the Food Oasis project.

Currently, the project relies on Heroku dynos, specifically the Basic Tier, for both production and development staging, resulting in a total monthly cost of $14.

Consider investigating alternative hosting solutions, such as AWS products or similar platforms, to assess potential cost savings.

**Comment by farahrobleh** [comment]
@entrotech are we still currently using this technology, or have we already completed migrated to AWS?

**Comment by ExperimentsInHonesty** [comment]
Final reduction achieved.
