### ISSUE TITLE
Investigate MUI Out-Of-Range Console Warnings

### ISSUE THREAD

**Issue by andyarensman** [hackforla/food-oasis#2021]
### Overview
When running locally, we are getting several MUI warnings that make it difficult to trouble shoot any other errors or warnings from the console.

The warnings are:
- MUI: You have provided an out-of-range value `false` for the select (name="day") component. Consider providing a value that matches one of the available options or ''. The available values are `SUN`, `MON`, `TUE`, `WED`, `THU`, `FRI`, `SAT` 
- MUI: You have provided an out-of-range value `false` for the select (name="time") component. Consider providing a value that matches one of the available options or ''. The available values are `12:00AM`, `01:00AM`, `02:00AM`, `03:00AM`, `04:00AM`, `05:00AM`, `06:00AM`, `07:00AM`, `08:00AM`, `09:00AM`, `10:00AM`, `11:00AM`, `12:00PM`, `01:00PM`, `02:00PM`, `03:00PM`, `04:00PM`, `05:00PM`, `06:00PM`, `07:00PM`, `08:00PM`, `09:00PM`, `10:00PM`, `11:00PM`
- etc.

### Action Items
- [ ] Investigate how to fix this issue
- [ ] Make changes

**Comment by andyarensman** [comment]
This might just be on my machine

**Comment by junjun107** [comment]
![image](https://github.com/hackforla/food-oasis/assets/60997220/1dc6e9ff-7d98-4d25-a7a2-94bdf51f1dfc)
