### ISSUE TITLE
Bug: Website search result is zoomed in

### ISSUE THREAD

**Issue by ihorng** [hackforla/food-oasis#2027]
#### Describe the bug 

When viewing the search result on the mobile device (after typing in the location in the search box), the entire page is zoomed in. It makes it look the page is cut off and requires the user to scroll horizontally to view the rest of the page.  To view the page in it's actual size, the user would need to double tap on the screen to zoom out. 

#### Steps to reproduce the issue

(if applicable, please specify platform (iOS, Android, Windows, Mac version) and browser)
iOS, Safari 

1. Go to http://foodoasis.la
2. Click on the search box and type in "Los Angeles" 
3. The problem: search result page is zoomed in which makes it look like the page is cut off

#### What's the expected result?

All the information on the search result page should be displayed to fit in the mobile view and not zoomed in.

(if you have a suggested solution, you can add it here)

It looks like the zoom setting was applied because of the previous interaction (when entering the text in the search box, it automatically zooms in a bit). Possibly removed the zoom setting for the search result page.

#### Additional details / screenshot

Video recording 
[https://drive.google.com/file/d/18ksMs6YgQnrfw4oC0MJSxuhX-vKuRhOh/view](https://drive.google.com/file/d/18ksMs6YgQnrfw4oC0MJSxuhX-vKuRhOh/view)

<img width="547" alt="image" src="https://github.com/hackforla/food-oasis/assets/3376957/e298c1bc-a3f7-46c6-b7f1-d6c7b0765cc7">

**Comment by fancyham** [comment]
Looks good.  Added two screenshots from your video for easy reference.

Looking at the video, I notice the window zooms-in a bit as soon as you bring up the keyboard to enter an address.  That might be a hint for us to figure out what’s going on.
