### ISSUE TITLE
Bug: inconsistency with icon size in detail list view

### ISSUE THREAD

**Issue by qiqicodes** [hackforla/food-oasis#2048]
Bug: inconsistency with icon size in detail list view, set fixed width for icon

<details>
<summary>Click to see the icon size inconsistency</summary>
<img src="https://github.com/hackforla/food-oasis/assets/68657634/2d0ca229-fac4-4fdf-b549-d823fcf79928">
<img src="https://github.com/hackforla/food-oasis/assets/68657634/2333fcc0-27dd-4278-a454-af442b2436ec">
</details>

**Comment by andyarensman** [comment]
This was fixed with the redesigns of the panel
