### ISSUE TITLE
Feature: Enhance Search Experience

### ISSUE THREAD

**Issue by qiqicodes** [hackforla/food-oasis#2049]
When clicking on "Back to List" button from detail list view, the user will be back at the top of the list. 

What should be the expected behavior when the user clicks on the back to list button?

**Current Behavior**

https://github.com/hackforla/food-oasis/assets/68657634/2e53225c-f4f5-4344-8567-aaa2278d3f20

**Comment by fancyham** [comment]
This is a duplicate of
- #2056

**Comment by fancyham** [comment]
Also renamed this issue to be more descriptive and to highlight that this was a regression (and so a bug)

was: "Feature: Enhance Search Experience"
