### ISSUE TITLE
Serious Bug: Returning to list from an org detail loses place in the list

### ISSUE THREAD

**Issue by fancyham** [hackforla/food-oasis#2056]
#### Describe the bug 

When viewing an org's details, then clicking on Back to List or using the browser 'back' button, my place is not held in the scrolled list as it restarts the list back from the top and forces me to rescroll down to pick up where I left off. 

This makes it very difficult to browse and penalizes the user who gets more information about an organization.

The goal of a user is to find an organization… typically they start at a long list, scroll down to something that looks interesting, get more details, exit back to the list and continue scrolling the list from where they left off.  But our site now prevents this.

#### Steps to reproduce the issue

1. Do a search and view a list of organizations
2. Scroll down list to the 10th organization in the list, which is off-screen at first
3. Click on "Details"
4. View the organization's details.  Click "Back to List" or use the browser's "Back" button
5. View the list of organizations, but unfortunately, list has scrolled back to the top item, and now it's a pain to try finding the 11th item in the list to continue your research

#### What's the expected result?

The list should be exactly as it was when the user last interacted with it, so if the 10th item was in the middle of the screen, then it should again be there.

I would also suggest: consider using an animated yellow-beige highlight of the org's tile in the list for a few seconds of org's tile when returning from it, for example, will also make it easier to track that this is the org page that you've just returned from.

#### What's the actual result?

The list as scrolled to the beginning, which means I've lost my place.  This also makes it very difficult to browse org details.

#### Additional details / screenshot / video

https://github.com/hackforla/food-oasis/assets/3376957/f4e47477-08b4-4f3c-9a34-adae486af024

#### Device configuration
- Device: Desktop (and probably mobile, too)
- OS version: Mac
- Browser Safari

**Comment by fancyham** [comment]
Hi @GigiUxR - Could you check the new behavior on the devla.foodoasis.net website?

@hanapotski , I think this new fix broke the back button?

1. I'm on an org detail screen
2. Hit browser's "back" (in Safari on desktop)
3. I get a blank screen now

**Comment by qiqicodes** [comment]
@fancyham 

Thanks for highlighting this area for improvement. To address the back button functionality and prevent the blank screen issue when navigating back from the org detail screen, could you kindly open a new issue for this feature? This will allow us to enhance the user experience more effectively.
