### ISSUE TITLE
Bug: Query for Listing Fetches Listings from All Tenants.

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#2061]
#### Describe the bug 

The application fetches all listings from all tenants, when it should only get listings for the current tenant. E.g for la.foodoasis.net, the application should only download listings for tenantId = 1.  This violates the segregation of listings by tenantId, and also significantly impacts performance, since many listings are retrieved that aren't needed.

#### Steps to reproduce the issue

(if applicable, please specify platform (iOS, Android, Windows, Mac version) and browser)

1. Go to map page.  You can look at Developer console Network tab to see that too many listings are downloaded or scroll the map to McKinney TX, or Oahu and see that listings from other regions ar appearing on the map and list.

#### What's the expected result?
Only listings for the current tenant (i.e., region) should be retrieved.

(if you have a suggested solution, you can add it here)
Add tenantId to the stakeholderbest search criteria.

#### What's the actual result?

-

#### Additional details / screenshot

- Screenshot (drag in)
- Video recording (drag in)

#### Device configuration
- Device: [e.g. type of smartphone, tablet, desktop computer]
- OS version: [e.g. iOS, Android version #]
- Browser [e.g. Chrome, Firefox, Safari, etc.]
- Browser version [e.g. 22]

**Comment by fancyham** [comment]
Please also check solution against (and possibly close out) this UI-focused bug report for what sounds like the same issue: 
- #2067

**Comment by qiqicodes** [comment]
the pull request #2062 also addresses issue #2067
