### ISSUE TITLE
Serious Bug: GPS button doesn’t re-center on current location

### ISSUE THREAD

**Issue by fancyham** [hackforla/food-oasis#2065]
#### Describe the bug 

Severity: 5/5 (where 5 is worst)

Using the “GPS” button in the map view correctly gets the user’s location and correctly places a marker, but it doesn’t update the map to match, so the user’s marked location is far off-screen.

This is unexpected behavior from the user, and I think a regression.

#### Steps to reproduce the issue

1. Go to any location on the map far from where you are located
2. Click on GPS button (upper right corner, next to the address field)
3. Error > your marked location on the map is not centered, and may be completely off-screen, especially if you are zoomed in.

#### What's the expected result?

- Map should scroll or jump to your current location and marker on the map (assuming we were able to get a location for you)

A smooth scroll might be a nice bonus, but is not necessary.

#### What's the actual result?

- Marker is indeed on map, but often off-screen.

#### Device configuration
- Device: Desktop 
- OS version: Mac
- Browser: Safari

**Comment by entrotech** [comment]
PR #2147 did not seem to fix, so I re-opened the issue.

**Comment by qiqicodes** [comment]
@entrotech I've tested the dev staging site, the fix works for Brave, Chrome, and Safari. Try restarting browser application and updating the browser if prompted.
