### ISSUE TITLE
Bug: icons from verification email not displayed

### ISSUE THREAD

**Issue by qiqicodes** [hackforla/food-oasis#2101]
Figure out why these logos are not loading in email, and fix the bug
- [ ] Food Oasis Logo
- [ ] Icon Spacer

<img width="665" alt="Screen Shot 2024-04-08 at 4 16 18 PM" src="https://github.com/hackforla/food-oasis/assets/68657634/5712b5f7-b6bb-4530-b7db-e0b8b75226cd">

**Comment by SAUMILDHANKAR** [comment]
After merging PR #2145, logos loading in gmail. Will bring up for discussion in next team meeting if we need to test this for other email services.

**Comment by SAUMILDHANKAR** [comment]
Progress update 
During last week's team meeting we discussed that I would be working on this issue. Would explore testing this for different email services. Unfortunately was not able to spend time on this last week due to reduced time availability.
Availability next week: 1 hr

**Comment by SAUMILDHANKAR** [comment]
Unassigning from this issue since I am taking time off for the next couple of weeks. I haven't made much progress on this issue. I will come back to this once settled down and if this is still available.

**Comment by longhairshortcode** [comment]
Tested in production mode and on first try if you wanted to see images you had to click on "Show images" button, yet when tried again, images just appeared automatically. 

![Image](https://github.com/user-attachments/assets/4d020435-0e1f-40b2-a197-37b4b60e2c6b)

**Comment by junjun107** [comment]
Also working for me. No longer a bug

![Image](https://github.com/user-attachments/assets/d2839dbe-1019-4624-a067-0b7fc675f68a)

**Comment by longhairshortcode** [comment]
Thanks everyone who checked this out! Will close this ticket because the images are showing depending on the user email/images settings. Images do show in email so there isn't a bug. Woo hoo!
