### ISSUE TITLE
Add additional column to admin suggestion page for correction or suggestion, add 4 additional fields to suggestion details page

### ISSUE THREAD

**Issue by kurikurichan** [hackforla/food-oasis#2121]
### Overview
Right now when a user submits a correction or suggestion, they both go to the Admin's suggestions dashboard with no distinction between which was a suggestion and which was a correction. 

Also, a lot of information that the user inputs on the Suggest New Listings page does not populate in the Admin's suggestions dashboard. 

### Action Items
- [ ] Add a new column to the Suggestions dashboard with C or S labels
- [x] Add the missing categories, state, zip, email, and hours fields to the Suggestions details page

### Resources/Instructions
* http://foodoasis.la/admin/suggestions  < - suggestions dashboard
* http://foodoasis.la/suggestion < - new suggestion page

**Comment by fancyham** [comment]
Related to
- #1131 

Which shows proposed designs for updated “Corrections” and “Suggestions” pages.  

Basically, it would be ideal if we could have users make corrections based on the existing listing, where possible, by showing them what we have, then letting them make their corrections atop or next to it.

And for suggestions, to allow them to fill out the fields (as much as they can) as if it was a listing on our site.

I’m not sure what fields are actually in the ‘suggestions’ database, but perhaps those fields should be the same ones we are actually displaying on our site.
