### ISSUE TITLE
Bug: Can’t search for Rancho Cucamonga, CA 91739 (which is in LA)

### ISSUE THREAD

**Issue by fancyham** [hackforla/food-oasis#2127]
#### Describe the bug 

Can’t search for or find the location: “Rancho Cucamonga” (a town in LA) or zip code 91739

I was looking for this listing: “God’s Pantry - Rancho” and couldn’t find it on the map because it wouldn’t accept the address
https://foodoasis.la/organizations?latitude=34.1168289790474&longitude=-117.52592800069877&org=god%27s_pantry_-_rancho&id=4771

We seem to be unable to go to some addresses?  Can we also check that all the towns in LA can be found?

Also note that there are some phantom zip codes that the post office doesn’t use — 91736 and 91738, for example, are unused by Zip Code, but 91739 is definitely used.

#### Steps to reproduce the issue

1. Try searching for “91739” or “Rancho Cucamonga” — the autocomplete will fail and pressing return won’t find it on map

#### What's the expected result?

Put pin on map in this location:
<img width="953" alt="image" src="https://github.com/hackforla/food-oasis/assets/3376957/a26898b4-698d-4b01-948d-279d6aa63296">

#### What's the actual result?

- Failed search

- [ ] Are there other missing addresses?

#### Device configuration
- Device: iPad
- OS version: 17.6
- Browser: Safari

#### Action Item:
- update the backend to return only organizations belonging to the tenant
- use the tenant configuration longitude/latitude

**Comment by junjun107** [comment]
To my understanding,FOLA is only targeting LA county and Rancho Cucamonga is in San Bernardino county.  Here is a picture to show what LA county covers.
<img src="https://github.com/hackforla/food-oasis/assets/60997220/c6ca3322-1ded-44a4-8173-697b98cddaf5" width="200">

**Comment by fancyham** [comment]
Oh my, I’d never considered that (also, not from LA).  Haha. 

So, we actually have a fair number of listings outside of LA county on our map: and wondering how we approach and handle that as far as our goals and how users think of us. 

<img width="580" alt="image" src="https://github.com/hackforla/food-oasis/assets/3376957/c38cbb0d-51f2-49a1-8aa5-89e560df9a7a">

In the user case above, I entered a San Bernardino zip code — feel like we should give some feedback about why we can’t resolve that address. 

Any thoughts about how we could handle that gracefully?  Perhaps some sort of error message?

**Comment by fancyham** [comment]
Closing this because of explanation above - Rancho Cucamonga is outside our official service area. We just happen to have a few listings in that area. “Works as intended”

in the future we should consider showing beyond LA County.
