### ISSUE TITLE
Allow creation of new stakeholder by a person with stakeholder role. The login should be automatically associated with the stakeholder as a stakeholder administrator.

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#214]

**Comment by entrotech** [comment]
As of 12/17/19, only Admins can create new stakeholders, and the stakeholer role is just any registered user.  Do we need to differentiate between registered users and user with a stakeholder role for this purpose, so we don't have unverified people registering and creating new stakeholders?

**Comment by ExperimentsInHonesty** [comment]
Yes we do need to differentiate classes of user.

Also copied from an old note I found of mine: Create an admin screen for administering users, allowing them to be granted or denied "stakeholder" and/or "administrator" role, and to view the stakeholders associated with a stakeholder user.
