### ISSUE TITLE
Feature: Toast prompt for user feedback form

### ISSUE THREAD

**Issue by danvgar** [hackforla/food-oasis#2165]
### Context
- Need to create a toast prompt at lower right side of screen that links users to Google Form feedback survey.

<img width="1125" alt="Screenshot 2024-06-30 at 9 33 02 AM" src="https://github.com/hackforla/food-oasis/assets/124107401/7b229da1-67fe-426d-b553-3dcedba6f830">

### Key Features
- Needs to be collapsible 
- Link to external Google Form survey (to be provided by Research team shortly)
- Allow user to stop prompt from showing again.
  - (Can be local storage for now to confirm if user requested not to show again)
  - Refer to Figma page linked below for grayscale hex codes. 
 
### Discussion
- Design+Dev teams considered embedded third-party survey services (e.g. Qualaroo), but for the sake of time and simplicity, it was agreed to stick to free Google Forms link as a start. 

### References:
- Design Team Ticket: #1769 
- 8/17/23 Meeting Notes (Under PM Team): https://docs.google.com/document/d/1uPO0_AJ1zn3IZXrhHBXub-ZfakIsx34jKHK3LIB8VmM/edit.  
- Survey PRD - https://docs.google.com/document/d/1mFbh3-30JjwguLOc-3cHZTyFI-TSsTduvJXeMKKHSH4/edit
- [Research Plan for Pop-Up Surveys](https://docs.google.com/document/d/18pzn3OMbDqXKmiTlO9EVS0zUQuadPtharKjMuyacvlU/edit)

### Figma whiteboard:
- UI sketches
- Survey comparisons
- Competitive / Industry audit (seeing other people's examples)
- UI designs
https://www.figma.com/file/9hPmNSsyaH2VMGNz5mffmI/FOLA-Design-%232?type=design&node-id=640-122&mode=design

### Acceptance Criteria:
- [ ] Add a snackbar with the google form link - 
        link : https://docs.google.com/forms/d/1iMhqormFjimqhVtJKiFbQPmkFJcf1L-9inImEPcxg7E/viewform?edit_requested=true
- [ ] Should be rendered at the bottom right of the page
- [ ] Should be dismissible - use localStorage to keep track of whether the user has seen it and keep track of what form they've seen
- [ ] Should appear after a certain amount of time

**Comment by fancyham** [comment]
Hi there — what’s the current status / ETA for this?  Any blockers need cleared / clarifications / or simplifications needed?  We’d love to start running surveys ASAP as we need that data to make some roadmap plans!

**Comment by danvgar** [comment]
@fancyham We are back from the HFLA July break and working on this! Do you know if a Google Form link is ready yet? @neom500

**Comment by fancyham** [comment]
@GigiUxR @neom500 Hey Gigi, Nate -- could you connect with @danvgar about the google link?  I'll slack you all together

**Comment by monicakrystal** [comment]
@fancyham  I think someone mentioned this was the correct form?  Not 100% sure though. https://docs.google.com/forms/d/1iMhqormFjimqhVtJKiFbQPmkFJcf1L-9inImEPcxg7E/viewform?edit_requested=true

**Comment by fancyham** [comment]
@monicakrystal , That looks like an old one -- please use this one instead:

The survey URL:
https://docs.google.com/forms/d/e/1FAIpQLSdAhi_nMKQfWVHjfpl1ZkmymBTt8BW7YNqVIOJ4JKYgSL4O3g/viewform?usp=sf_link

and code for embedding:
<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSdAhi_nMKQfWVHjfpl1ZkmymBTt8BW7YNqVIOJ4JKYgSL4O3g/viewform?embedded=true" width="640" height="921" frameborder="0" marginheight="0" marginwidth="0">Loading…</iframe>

(you should be able to replace the width and height or, I think, even remove it)
