### ISSUE TITLE
Text panel obscures map and pin on mobile, off-center on desktop

### ISSUE THREAD

**Issue by Shienny1** [hackforla/food-oasis#2168]
severity 5/5
Near impossible to see location on map on mobile devices
Maps are centered as if text panel doesn’t exist leading to obscured or weird alignments. Map should center using its visible area, not the entire screen. 

### Problem:
On mobile, tapping a result to get details loads org detail view, but layout of split screen obscures map and pin, and pin is off-screen. 

Desktop has a similar problem.

To reproduce the desktop version of this bug:
1. From landing page, enter an address. On desktop, map Pin appears in the correct place at first.
![IMG_1253](https://github.com/user-attachments/assets/cf8cc736-3d32-4d47-b1df-c11b90211b6e)

2. Do a search again from the map page and the map now re-centers in the wrong place.
![IMG_1252](https://github.com/user-attachments/assets/8f2c2963-54e4-4f92-8cde-400a22217782)

To it might have something to do with loading the page for the first time vs going to a new location

### User goal: 
to get see the cross streets of the location indicated on the map so i tap on the icon

### my expectation: 
To zoom in to that specific location and see more information of the name and hours of operation (maybe covering maximum bottom half, and leave the upper half of the screen on the map  showing the selected location zoomed in.

### actual result:
80% screen covered by TEXT on location's information etc. Covering the map.
So I swipe down to open the window to map again.
BUT the map window has migrated to a different location, no where close to the selected location.

### screenshots and video 

https://github.com/hackforla/food-oasis/assets/3376957/87062398-06a2-4bcd-99bf-9ecd2cce789f

https://github.com/user-attachments/assets/be6ff243-2863-43cc-b2f1-d940acb4e386

![image](https://github.com/hackforla/food-oasis/assets/3376957/11c2d360-90b7-4ef6-ba09-4ecc0d3532d8)

### possible solutions

make map larger - see figma designs - I believe it’s supposed to be 50% text at first? — Bryan

Ensure that with new split-screen view that pin is centered in map viewport at first load.  This might mean calculating visible map and centering it as text panel is resized.

for example if text is 80% of screen, map is remaining 20% and pin should be at approx 10%.

Ideally the selected pin and the user’s location are both visible on the map at the same time.  This will give them a sense of location relative to where they are now.

Stretch goal: if pin is centered, then keep it centered as user resizes text panel. 

### related issues
-  #2028

**Comment by fancyham** [comment]
Changed title, added some text, added formatting (using markdown https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) and inserted the screenshot and video into the issue itself (better for easy reference - drag and drop or attach those media files). Also tagged it for devs to look at.

**Comment by fancyham** [comment]
Related issue 
-  #2028

**Comment by Shienny1** [comment]
Hi Guys. I checked the devla.foodoasis.net site : this is what I am experiencing still: The icons are nonresponsive at times. And they are still NOT CENTERED in the selected location in the mobile version. Please the clip attached

https://github.com/user-attachments/assets/e5079976-b59d-45bc-a108-d78453eba21e

**Comment by fancyham** [comment]
@Shienny1 could you add add that comment to 
- #2028  please?  I think they’re still working on the weird map centering issue there. 

I’ve reopened this issue so we don’t lose track of it but I believe it’s the same problem as
- #2028
