### ISSUE TITLE
Add missing 'use my current location' button on mobile screen

### ISSUE THREAD

**Issue by fancyham** [hackforla/food-oasis#2187]
#### Describe the bug 

There is no "use my current location" option at the map view on the mobile layout, but a user will want one there to re-center themselves or to use it for the firs time.

This seems to have disappeared during the big redesign, but it's available on other screen sizes, so this should be easy to re-add.

Please insert it between the address field and the map button

<img width="786" alt="image" src="https://github.com/user-attachments/assets/69e3a404-9215-46f8-aff7-eb214b60074c">

**Comment by fancyham** [comment]
@Shienny1 , this is the usability problem you found on row 24 of the [design team's usability review matrix](https://docs.google.com/spreadsheets/d/1dDZzrwRvulR-TyGP2Gj_NWhS5AzK_drQ5X3xpnuqOFY/edit?gid=0#gid=0).  Thanks!

**Comment by MuthamilselvanG** [comment]
@JmJenna Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again
