### ISSUE TITLE
Change "Back to Search" link to "< Back to Results" and change color

### ISSUE THREAD

**Issue by fancyham** [hackforla/food-oasis#2189]
### Context
Currently, it's hard to see the "Back to Results"-type link on our organization detail screen. 

This small design change should make this breadcrumb more prominent and help users have a better sense of their location on the site.

### For reference, here's the current version
<img width="858" alt="image" src="https://github.com/user-attachments/assets/b69471da-96db-40ed-ba23-5bf0dcdb61bf">

The light grey text makes it hard to understand that it's a breadcrumb.  The low contrast also makes it hard to read for people with clouded vision (i.e. seniors)

### Proposed change

<img width="858" alt="image" src="https://github.com/user-attachments/assets/77daae1f-72fd-4978-8661-760a47267d3f"> 

Change the text a little (note that it's worded differently on Desktop for some reason):
- Change text to read "< Back to Results" (this is more common terminology)
- Change the color to be a darker/higher contrast color... dark gray rather than the current light gray.

**Comment by fancyham** [comment]
This is from row 20 of the [design team's usability issues spreadsheet](https://docs.google.com/spreadsheets/d/1dDZzrwRvulR-TyGP2Gj_NWhS5AzK_drQ5X3xpnuqOFY/edit?gid=0#gid=0)

**Comment by prashantrai-30** [comment]
Hey @fancyham  can you assign this issue to me,I have a potential solution for this.

**Comment by fancyham** [comment]
HI, @prashantrai-30, you must be a Hack for LA member and Food Oasis volunteer to work on these issues and I don't see you our our developer group -- check out hackforla.org to learn more, or contact your team lead please!
