### ISSUE TITLE
Change CSS for organization name links to be more obvious

### ISSUE THREAD

**Issue by fancyham** [hackforla/food-oasis#2190]
### Overview

It's not obvious that each organization has a detail screen because links to it aren't obvious.

Many other food pantry websites have the same information that we have on the search results screen but nothing more.

Our site has much, much more than those sites, but people won't know this unless there are obvious links to bring them deeper in.

To fix this, we should make the organization names on the search results very obvious links.

To start, let's change the Org Name Links so that they underline all the time.  

Why all the time and not just on hover?  Because there's no hover effect on mobile screens.  Things need to look clickable right off the bat.

<img width="1271" alt="image" src="https://github.com/user-attachments/assets/29fa5ac6-126a-4245-a908-a99dd71f69dc">

Note that on the org detail screen, the name of the org is not a link and will look like just a header, which it is.

If this is too jarring, we can try other methods via simple CSS changes and the dev and designer can try out things together -- the point is that there needs to be some obvious differentiation between what's a link and what's a label.

### Discussion

I think this should be a simple CSS update.

**Comment by fancyham** [comment]
Created from [usability review in June](https://docs.google.com/spreadsheets/d/1dDZzrwRvulR-TyGP2Gj_NWhS5AzK_drQ5X3xpnuqOFY/edit?gid=0#gid=0)

**Comment by monicakrystal** [comment]
Hi ! What do you think of this? this only happens on mobile. I feel like the blue seems more user friendly/ "clickable". 
<img width="596" alt="Screenshot 2024-08-15 at 8 47 09 PM" src="https://github.com/user-attachments/assets/4070762d-a724-405c-9aa8-74b5376c9ee6">

**Comment by fancyham** [comment]
While very clickable and obvious, I think that the color doesn't go well with the other colors we have :) 

Could you make it the same color as before but with an underline, and let's see how that feels?

**Comment by monicakrystal** [comment]
Sure, just had to change the color. Here it is in black. Let me know your thoughts. Thank you!
![Screenshot 2024-08-17 at 9 40 42 AM](https://github.com/user-attachments/assets/42a14239-01b9-4c72-8789-8b95a8b612be)

**Comment by fancyham** [comment]
Nice!  Is there somewhere I can see it?  I basically want to QA and check that it feels right — this is pretty minor so perhaps can be pushed to Devla for testing but before acceptance? (A design on paper sometimes feels wrong when actually using it)

I feel like we could use a virtual machine that can be spun up for QA testing specific bug fixes :)

**Comment by fancyham** [comment]
If not easy to use it live, could you post a short video or screenshots of using them on desktop, portrait iPad (768 wide), and mobile?

**Comment by monicakrystal** [comment]
Which virtual machine? Docker? Do you want it only underlined on desktop, ipad, and mobile?

**Comment by fancyham** [comment]
Yup, the underlined org title URL on desktop, iPad and Mobile — a (short) video of searching, scrolling and going into the org is what I’m looking for to see how it looks and feels.  

I’m a little technical so another option is you could send me / point me to the new css and I can try using it as a custom CSS here though not sure if that’d work.  (I’ve not actually done code review on github or ever, actually, I’m more of a hack)

Bigger picture:
I’m out of my depth here about what’s possible but what I’d love is for designers or creators of issues to be able to review a live version of the fix while it’s in development so that there can be cycles of back-and-forth checking of how things work and feel, as well as QA — but before it goes into the formal check-in/pull into the actual code base.  

That might require talking to the leads and asking if this might be possible but one possibility I can imagine might be a collection of temporary staging/prototype dev servers — like devla1, devla2, etc. that a dev can publish their in-progress work so that the folks working on a specific issue can work on it together.
(feel free to share this ^^^ with the dev leads)

**Comment by fancyham** [comment]
Hey hey -- checking in on this

The screenshots from 3 weeks ago with the black links look good -- if you can post a video showing hover effects, etc., that would also work.   

If it helps any, FYI, I'll be at Sep 9th's (tomorrow's) dev meeting.

**Comment by monicakrystal** [comment]
Hi! What kind of hover effects do you want?

**Comment by fancyham** [comment]
If you're at tonight's meeting, maybe you can show it to me there!

**Comment by ExperimentsInHonesty** [comment]
left monicakrystal a message on the pr to resolve merge conflict.
