### ISSUE TITLE
Add client-side validation, tooltip, go to link and design for Instagram contact field

### ISSUE THREAD

**Issue by monicakrystal** [hackforla/food-oasis#2201]
**Overview**

We would like for the instagram contact field to match the twitter contact field.

To do List:

- [ ] add design to the contact field
- [x] add tooltip
- [ ] add go to link when user enters text into the field
- [x] add validation to the field 

**EXAMPLE***

![Screenshot 2024-09-06 at 1 01 46 PM](https://github.com/user-attachments/assets/83bfd54c-ff15-40d8-8406-b6d1645e0389)

*Need to change Instragram to match the twitter one

**Comment by SAUMILDHANKAR** [comment]
Closing this since it should have been closed with #2203
