### ISSUE TITLE
FOLA: Open Role for: Front End Developer using Mapbox

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/food-oasis#2220]
<img src="https://tinyurl.com/picfoodoasis" width=400px>

**Project Name**: Food Oasis

**Name of Role**: Front End Developer

**Volunteer Opportunity**: We are looking for a developer to help solve a problem we are having with our site

> When viewing a list of organizations, and tapping one to get details about it, the map does not update show or highlight the organization’s pin. Often the pin is way off-screen.
> 
> The map should re-center (ideally with a smooth scroll/pan) on the highlighted pin automatically, ideally showing both the user’s current location and the pin so that they can determine the relative location.

**Skills:** Mapbox, React, JavaScript

**Duration**: 2 or more months (we also have other Mapbox issues)

**Meeting Times**: 6pm PST Mondays

**Who to communicate your interest to**
- Slack channel link: [#fola](https://hackforla.slack.com/archives/CMER3R1RD)
- Slack name of person to contact in the channel: see who this issue is assigned to and @ message them in the channel above

[Read more about the project](https://www.hackforla.org/projects/food-oasis)

**Comment by whitneywind** [comment]
I'm a developer and am also studying GIS, so I'd be happy to help out with Mapbox in this project! I'll message the assignee as well @sumit-sharma92
