### ISSUE TITLE
Research and document food-seeker needs — what do they need?

### ISSUE THREAD

**Issue by fancyham** [hackforla/food-oasis#2222]
### Overview

Starting with the questions:
* How do users determine which food assistance program will best meet their needs?
* What are the challenges users face when looking for food assistance?

and how can we better help food-seekers?

To better design features, we need to better understand food-seekers and people who help them.

### Methods

**Some goals**
- Learn more about food-seekers
- Research the context in which they're seeking food
- Research the resources available to them (what's the assistance landscape?)

**Some methods**
- Research secondary sources
- Interviews
- Turn those findings into a user-needs 'mind map' identifying groups of people and their tasks: what they need, why and when they need them, the context / mental state when they're doing these tasks, and other related info.
- Priority should be given to things that are backed up by first-or second-hand data

**This info would be used…**
- By FOLA team members, in particular, the design team, to better understand our users and their needs.
- To help prioritize features -- and to find 'low-hanging fruit' features that we may be able to easily accomplish
- To identify gaps that we would like to research more
- To identify opportunities.  This might mean opportunities for intervention... for example, might this tell us that we should reach out to teachers or churches?

(Note: I created this issue after-the-fact to help us track, record, and to link to work that @ihorng designer/researcher been doing since July 2024 —Bryan)

### About food seekers, the food-assistance landscape, and their context
[**Secondary Research: Food Seekers**](https://docs.google.com/document/d/1fN-LOpCr72Tyu4JNqIkD23vS0dqP0v5J4kHOzQnTcMk/edit?usp=sharing) by @ihorng  (14-page Google Doc)
Overview
- Understand the broader landscape of food insecurity 
  - Understand the larger context, including definitions, demographic, and systemic issues that impact food access 
  - Provide background information on food seekers
- Understand food seekers personal experience facing food insecurity 
  - Learn about volunteers’ experience volunteering at food banks/pantry and how they are providing access to food for food seekers

- Identifies user needs and decision making process
- Identifies user pain points

### Food-Seeker Needs 'Mind Map'
[**Food-Seeker Needs 'Mind Map'**](https://docs.google.com/document/d/1oIP9mGy3gJVGBDLC1549l3Rc_cqC0UQEotOxwpBCnKE/edit) by @ihorng  (8-page Google Doc)
Overview
- To think about the food seekers’ problems that needs to be solve and whether or not the product being designed solves the problem

Objective
- To organize topics and research findings into an arrangement for clarity 
- Untangle complexity to make things more understandable 
- Find connections between different findings and insights

Methodology
- Based on findings from [Secondary research findings](https://docs.google.com/document/u/0/d/1fN-LOpCr72Tyu4JNqIkD23vS0dqP0v5J4kHOzQnTcMk/edit) (above)
- Additional sources (texts marked in blue marked with * have sources located at bottom of each section)

Goal
- A better understanding of food seekers and their requirements, which informs design decisions
- Explore recommendations that can be further developed or evaluated

**Comment by fancyham** [comment]
Adding this for posterity: 
**Tools and techniques answering 'what, why, and how'-type questions**

**Question:**
I'm interested in finding out:

* How do users determine which food assistance program will best meet their needs?
* What are the challenges users face when looking for food assistance?


**Discussion and Recommendations**

The research team might have some interviews with subject matter experts (academics and social workers), and I don’t think they’ve done much talking with food-seekers directly (yet)..

So in the meantime, while they’re on break, let’s both look for studies that other people have done — perhaps academic, or even news articles or interviews profiling what people go through when they start needing food. It won’t be the same as a direct interview, but it’s a start.  If you find a good one, share it here in this thread.

Also, another technique we can do is:

Role Play (not perfect but it’s a start) — what would you do if you started running out of money and needed food, and to actually start pursuing it. That is, literally write down what you do, do it, and see what barriers or discoveries you come across.  Also, note your emotional state as you go - frustrated?  Sad?  worried? angry?

You might pretend you’re in LA county, but I’d suggest doing it for your area. It’ll be similar to LA. and what you write up becomes a walkthrough if what one person has gone through. 

Or pretend you’re helping a friend or friend’s family find food.

Sometimes drawing it as a mind map or flowchart as you do things can be useful.

I’ve done this when I evaluate sites or try to get to know a subject I’m not familiar with but need to design for. It’s far from perfect - perhaps we’re actually housed, have food (acting is far different from living it), are too tech savvy or are too young or lack connections (to church, friends in similar situations, etc.), but it’s a great way to peek into the experience.

interview - Lots of people have needed food at one time or another - even our friends and relatives. So asking what those people did can be really useful. The one downside of this is that it often lacks details and emotions and time, as our memories often collapse and simplify what really happened.

Asking them how they’d help a friend is another way of getting to that information.

I just talked to someone who’s done research like this and she recommends looking into:

Newspaper and magazine deep dives into food insecurity and perhaps homelessness (though many/most food insecure people are housed) — there have been some Pulitzer-winning ones that might be helpful:

[(Pulizter prize) Eli Saslow of The Washington Post](https://www.pulitzer.org/winners/eli-saslow)
“For his unsettling and nuanced reporting on the prevalence of food stamps in post-recession America, forcing readers to grapple with issues of poverty and dependency.”

Documentaries

Books about how people survive when they don’t have money

What to look for: profiles of what its like to be food insecure

Reddit or discussion groups by and for food-insecure folks (if such a thing exists) — sharing strategies, knowledge.

https://www.reddit.com/r/findareddit/comments/yhvrrj/is_there_a_reddit_for_people_down_on_their_luck/

Part of the challenge here is that you may be looking for info about people experiencing food insecurity for the first time, and what do they go through - for example, someone who has just been laid off from their job — … that’s kind of a different experience than someone who has already figured out a system that works for them (or works as best it can) 

[r/findareddit on Reddit: is there a reddit for people down on their luck that are hungry and need a food donation or anything along those lines?](https://www.reddit.com/r/findareddit/comments/yhvrrj/is_there_a_reddit_for_people_down_on_their_luck/)

Also, volunteer at a food pantry or social service where you interact with folks looking for food. This is harder, but talking to someone who does this and asking those questions would be the next best thing.

There are academic papers that might also be helpful but also hard to read

But here’s one I found by googling for “that is profiling people in the UK - skim past the Methods section and read the parts with quotes from interviews:
[Understanding Lived Experiences of Food Insecurity through a Paraliminality Lens](https://journals.sagepub.com/doi/10.1177/00380385211003450?icid=int.sj-full-text.similar-articles.9)

—Bryan

**Comment by fancyham** [comment]
@GigiUxR FYI, documenting the work Ingrid did on food-seekers, their needs, and the food-assistance landscape

**Comment by ihorng** [comment]
This has been completed from my end
