### ISSUE TITLE
Feature Flag Survey and Update Mobile Survey Button

### ISSUE THREAD

**Issue by junjun107** [hackforla/food-oasis#2262]
### Overview
Objective 1: Right now survey is always visible on homepage. We want be be able to toggle survey on and off. 
Objective 2: Survey button is cut off on mobile view
![Screenshot 2024-10-24 at 7 35 56 PM](https://github.com/user-attachments/assets/ecda2511-b36f-4240-b21b-0f3ca67659e8)

### Action Items
- [x] Fix feature not auto fetch after update 
- [x] Refactor useFeatureFlag hook to add a user-specific fallback
- [x] Adjust survey container size on mobile  
- [ ] Put survey behind a feature flag and turn it on

**Comment by MuthamilselvanG** [comment]
@junjun107 Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again
