### ISSUE TITLE
Create Landing Page

### ISSUE THREAD

**Issue by Telos8840** [hackforla/food-oasis#234]
### Overview
Build out Landing Page based on latest wireframes

### Latest design
https://www.figma.com/file/QgM5vS8NhDNXhknnFpu2Hn/Prototyping-in-Figma?node-id=26%3A394

**Comment by ExperimentsInHonesty** [comment]
@Telos8840 Please provide update:
1. Progress
2. Blocks
3. Availability
4. ETA

**Comment by ExperimentsInHonesty** [comment]
The purpose of this is to copy the current foodoasis.la homepage as closely as possible, while changing out the fake search bar with a real one that takes in the address.

**Comment by ExperimentsInHonesty** [comment]
To be clear, what we are looking for in the mockup is:
1. staying close to the existing design. 
2. Changing the search box to actually be a search box, with the word "Enter an address, neighborhood or zip code"
3. see Tina image in next comment for how current location works
4. Replace the text under the search that currently says 
 - "Food Oasis LA (FOLA) shows you places to find healthy food in Los Angeles – whether you are looking to buy, grow, or need access to free food. 
- "Food Oasis LA (FOLA) has links to food pantries and hot meals" 
5. Leave the "Learn more" link

**Comment by tina-moh** [comment]
![47C405B1-DBAA-46CD-B9EE-AE127AE81B96](https://user-images.githubusercontent.com/56663382/73618602-a2d24680-45dd-11ea-9221-a786dc821880.jpeg)

**Comment by Telos8840** [comment]
This is nearly done. I had some issues initially with Material UI giving me some errors but I just got that resolved today. I'm hoping to have this done by the time we meet next week.

**Comment by ExperimentsInHonesty** [comment]
ETA by next meeting.  Progress going well.

**Comment by tina-moh** [comment]
<img width="675" alt="Landing page 1" src="https://user-images.githubusercontent.com/56663382/74777739-f932bc80-524e-11ea-8d41-7ce85e25dc2a.png">

**Comment by tina-moh** [comment]
<img width="546" alt="Landing Page1" src="https://user-images.githubusercontent.com/56663382/74778347-3b103280-5250-11ea-9f81-079e27565729.png">
<img width="541" alt="Landing page2" src="https://user-images.githubusercontent.com/56663382/74778355-3f3c5000-5250-11ea-8fd3-3927f4831812.png">
  @lucas-homer @Telos8840  please let me know if you have any  comments

**Comment by tina-moh** [comment]
we can have it either in blue or red 
! (the blue and red comes from logo nad have passed accessibility test)
So can vote for the color too
<img width="496" alt="landing page R1" src="https://user-images.githubusercontent.com/56663382/74780647-e4f1be00-5254-11ea-99de-b4943ada9e4c.png">
![Uploading landing page R2.png…]()

**Comment by tina-moh** [comment]
<img width="670" alt="Screen Shot 2020-02-18 at 2 08 14 PM" src="https://user-images.githubusercontent.com/56663382/74782455-5717d200-5258-11ea-879b-7eec5d4b7ab4.png">
![Uploading Screen Shot 2020-02-18 at 2.09.40 PM.png…]()

**Comment by tina-moh** [comment]
<img width="669" alt="Screen Shot 2020-02-18 at 2 09 40 PM" src="https://user-images.githubusercontent.com/56663382/74782481-63039400-5258-11ea-9a8e-be2c6f9d77d9.png">

**Comment by tina-moh** [comment]
<img width="668" alt="Screen Shot 2020-02-18 at 3 37 56 PM" src="https://user-images.githubusercontent.com/56663382/74787716-b976cf80-5264-11ea-8460-b04376845c17.png">

**Comment by tina-moh** [comment]
Final Result
<img width="1047" alt="P1" src="https://user-images.githubusercontent.com/56663382/75064042-07751880-549b-11ea-9375-27706a1b1ab5.png">

**Comment by tina-moh** [comment]
<img width="1072" alt="P01" src="https://user-images.githubusercontent.com/56663382/75064392-b7e31c80-549b-11ea-9942-78ea2084b798.png">

**Comment by royceduong** [comment]
See #252 for all designs.

**Comment by jpmikesell** [comment]
@lucas-homer -- When you have a chance we need to officially approve this design so we can move on to implementation.

**Comment by lucas-homer** [comment]
approved!

**Comment by Telos8840** [comment]
I'll start working on updated this to reflect the new designs. Thanks @tina-moh for the hard work!

**Comment by Telos8840** [comment]
@lucas-homer I pushed up the branch to `/feature/234-search-landing-page` if you want to take a look. The last issue I had was connecting the search input to the results page. I was trying to implement a global state as well as an easier local storage solution but quickly realized I was digging myself into a bigger hole that is out of this scope. 

I think what needs to be done is just creating a route with the lat and long and passing that to the  results page but I believe you'll have a better idea of what needs to be done.

You'll also need to add a `.env` file into the client root and add this `NODE_PATH=src`. This is so we can slowly migrate to importing files absolutely rather than the long file imports we currently have. Let me know if you have any questions or find a better way to pass the results to the stakeholders page.

cc: @ExperimentsInHonesty
