### ISSUE TITLE
Verfiy data for soup kitchens

### ISSUE THREAD

**Issue by jpmikesell** [hackforla/food-oasis#237]
### Overview
Update and verify current stakeholder data for Soup Kitchens
### Action Items
- [ ] Familiarize yourself with the data for this group. The data is located in a CSV table [here](https://docs.google.com/spreadsheets/d/1M1pqck4GM79aJ32czVzi8pIudQBIk8q9dcnESn61jRc/edit#gid=0)
- [ ] Familiarize yourself with the [script](https://docs.google.com/document/d/1cD_CXGyLK9KF87FyIZ4hP9xz75Oun21mvF8o1LM6AOU/edit?usp=sharing) 
- [ ] Following instructions below, make phone calls to update the data using the herokuapp 
### Instructions

1) Log in to [herokuapp](http://food-oasis.herokuapp.com)
  - if you're not registered, follow instructions [here](https://github.com/hackforla/food-oasis/wiki/How-to-Register-and-Edit-stakeholder-data#register) to register

2) Open the CSV table for Group 1 located [here](https://drive.google.com/file/d/1my7ZaTTDBBaTh9_iwX6QD_gpXKXY_DrA/view?usp=sharing)

3) For each row in the table, familiarize yourself with the data we have about them. Learn about them before you pick up the phone. Find a description about them and get context so you understand who you’re calling. 

4) Make the phone call and gather the data you need

5) Find and edit the corresponding item in the herokuapp. More detailed instructions [here](https://github.com/hackforla/food-oasis/wiki/How-to-Register-and-Edit-stakeholder-data#edit-stakeholder-data)

**Comment by chombus** [comment]
@jpmikesell can you update description?

**Comment by ExperimentsInHonesty** [comment]
@jpmikesell says will start working on this Monday 27th.

**Comment by jpmikesell** [comment]
**1. Progress** - I was only able to make a few phone calls for the soup kitchen database. I did create 2 infographics to explain our process for the presentation and a video to help new people get onboard with calls. 
[how to make calls.pdf](https://github.com/hackforla/food-oasis/files/4145648/how.to.make.calls.pdf)
Video link: https://drive.google.com/file/d/1JD3MzCbc4rKuQt3A2YzXxFYB6kEs30K_/view?usp=drivesdk
![1 copy 2](https://user-images.githubusercontent.com/54608811/73616860-9cd46980-45cd-11ea-9f07-9f4cb6eec9c6.png)

**2. Blocks** - I started a job this week that took up all of my time. 
**3. Availability** - This coming week I have organized myself again to make call for 30 min a day. 
**4. ETA** - Data will be verified by 2/17
