### ISSUE TITLE
Create an educational video for new people to call

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/food-oasis#239]
### Overview
We need an educational video for volunteer callers.

### Action Items
- [x] Write a script 
- [x] Edit the google form to be verbatim
- [x] Send script to Bonnie, Jenny, and Jabari to validate
- [ ] Once approved, make the video.

### Resources/Instructions
Google Form for volunteers to fill out for [data collection](https://docs.google.com/forms/d/14-EE3xfzaWD4QVhBKUwIUBxQI9OgQeJE2au5T4tCmuo/edit )

**Comment by ExperimentsInHonesty** [comment]
@gcohen02 will send script by 2/11 morning

**Comment by gcohen02** [comment]
sent the script to bonnie, Jabari and Jenny. The preliminary script exists in the drive in the PHONE CALLS folder. We plan to make a preliminary video by tonight.

**Comment by ExperimentsInHonesty** [comment]
@melodylaishram can you provide an update if you were able to test this on your roommates?  And what the feedback was or if you will be able to write that up here or in the google doc by using the comments feature by Tuesday 2/ 18?

**Comment by melodylaishram** [comment]
Hi Bonnie,

Sorry it’s been a busy weekend. Plan on testing it out on a few people tomorrow and I’ll post it on the google drive.

Melody Laishram
UX Designer
(408) 315-5481
www.melodylaishram.com

**Comment by gcohen02** [comment]
https://docs.google.com/document/d/1HrMxwXyjybtv6tpXjlQbztZ581G6FsehEhcYg2Zcdeo/edit?ts=5e4c41c7

**Comment by gcohen02** [comment]
Questions from data verification survey: https://docs.google.com/document/d/1q_DNiO5w84N_UBGCcPOBv_MYhDohujEaQcfnySUp0dA/edit

**Comment by jpmikesell** [comment]
1. Progress - Reviewed notes from Melody's testing. Rewrote introduction. Made a list of questions so the volunteer can have context. 
2. Blocks - Confusion on how to present the questions in the verification form.
3. Availability - Have 1-2 hours this week to work on a simple presentation for the video and practice creating the video.
4. ETA - Aim to have both completed by Sunday.

**Comment by gcohen02** [comment]
https://drive.google.com/file/d/17KIspDDJvHxeiOMZTVeO5UHMHvmkoFik/view first draft of the video. There is a weird sound and I don't know where it's coming from. It might just be from my typing. I also said a couple of things out of order and it was a bit redundant. I'll shoot at least one more try but it's somewhere to start.

**Comment by gcohen02** [comment]
Here was the document with some of my criticisms of the first draft: https://docs.google.com/document/d/1XWIfewLNxinYsBEFg1okXBMuf9Cc6RV4jkRUnCESrGQ/edit You can find the video in the bubble before this.
@ExperimentsInHonesty @jpmikesell @melodylaishram

**Comment by gcohen02** [comment]
@royceduong ^ (bonnie wanted you copied on this too)

**Comment by gcohen02** [comment]
FOLA video take #2 https://drive.google.com/file/d/1YXwQSgnQlN7-dm_hv9PvNReU4M6UV5fO/view it's shorter and the progression is better. There was one bug with the form and I could be more eloquent so I'll probably do another draft. Please watch it and let me know what you think. You can use the doc I made above to add your feedback just make a distinction between what was for the first and second video. @ExperimentsInHonesty @melodylaishram @jpmikesell @royceduong

**Comment by gcohen02** [comment]
^Also that weird clicking is gone for the most part. I did forget to make sure to stress reading the questions verbatim.

**Comment by jpmikesell** [comment]
I think this video works well and serves the needs we have. @ExperimentsInHonesty will need to approve.

**Comment by melodylaishram** [comment]
I agree, this video is much clearer that the previous one. I will try and test it this week and let you know if I encounter any issues.

Melody Laishram
UX Designer
(408) 315-5481
www.melodylaishram.com

**Comment by gcohen02** [comment]
Great. I’ll probably do one more because I personally identified some things I missed out on (which can be found on the doc of criticism from before) but I’ll wait until I hear from Melody. Melody if you could just email this chain when you made those adjustments, that would be much appreciated!

Thanks for all your help! 
Gaby

**Comment by melodylaishram** [comment]
I’ll test it this week and email you my insights!

**Comment by gcohen02** [comment]
version 3:
https://drive.google.com/file/d/1088wJjrP8dSRY2iod__ALG37oRlQRJd0/view
