### ISSUE TITLE
Create a google sheet for remote volunteers to signup for call sets.

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/food-oasis#240]
### Overview
We need to make it easier to select places to call for remote volunteers and note their progress.

### Action Items
Create new google sheet

### Resources/Instructions
[Data Verification board](https://github.com/hackforla/food-oasis/projects/8)

**Comment by jpmikesell** [comment]
1. Progress - completed
https://docs.google.com/spreadsheets/d/102PL-9DCXEuKVF7Wv036hCTnm0d6q37bAwiJ-oDDdVo/edit#gid=0
