### ISSUE TITLE
Create an email script to the non profits

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/food-oasis#241]
### Overview
We need an email template for sending to targets that asks them to fill out the form, when they don't want to talk to us on the phone.

### Resources/Instructions
[From food oasis to donor form](https://docs.google.com/forms/d/1RcpZp1n3_pPrKvBjmekDryk6hNB2sqfuPpieopEeKy8)

**Comment by gcohen02** [comment]
Jenny has looked it over. The link is below. It is in the phone calls folder in the google drive

https://docs.google.com/document/d/1z1ernVR-X877qpweSkmTa3vKVK5ezSHsDxGGfEjgWKU/edit

**Comment by ExperimentsInHonesty** [comment]
Link to https://docs.google.com/document/d/1z1ernVR-X877qpweSkmTa3vKVK5ezSHsDxGGfEjgWKU/edit in the resources section.
