### ISSUE TITLE
Review all scraped data to determine if we can normalize it

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/food-oasis#242]
### Overview
We have scraped a lot of data from various website.  We need to see if it's possible to normalize it into one data set, from which to verify the listings

### Action Items
Please add your availability for a zoom meeting to the comments.

### Resources/Instructions
[Scraped resources google drive folder](https://drive.google.com/drive/u/0/folders/15V2rV3aTLiA16juUUPlUmfsi-t2zW-vc)

**Comment by chrislopez28** [comment]
I'm tied up this week until Feb 2, but after that I'm pretty open.

I'm available Mondays 9AM-4PM; and weekday nights 8:30PM-10:30PM.

**Comment by ExperimentsInHonesty** [comment]
@chrislopez28 I can do Monday at 10am if that works for you.  But I think @chombus is not available during the day.  But I think we can review this without him for now.  I'll reach out to you on slack to confirm your availability for this Monday.

**Comment by chrislopez28** [comment]
Experimenting with matching potential duplicate entries between scraped files.

**Pantries**
Food Finders and LMS. Closest entry by haversine ("as the crow flies") distance in meters:
https://github.com/chrislopez28/fola-data-normalization/blob/master/export/pantries_dist.csv

**Farmers Markets**
CalFresh and LMS. Most similar name string by finding entry with minimum levenshtein distance:
https://github.com/chrislopez28/fola-data-normalization/blob/master/export/markets_stringdist.csv

**Comment by ExperimentsInHonesty** [comment]
See these links for references about what type of information we are collecting
stakeholder details - part of current design efforts:
https://github.com/hackforla/food-oasis/issues/178#issuecomment-565886143

AIRS
https://github.com/hackforla/food-oasis/projects/6

**Comment by ExperimentsInHonesty** [comment]
see jobs-for-hope repo backend for scraper examples

**Comment by ExperimentsInHonesty** [comment]
Discussion between @chrislopez28and @ExperimentsInHonesty on, determined that we need more data for him to work with.  So he is going to get some scrapers working, starting with issue #95.   We will come back to this issue, once more of the scrapers are active.

**Comment by chrislopez28** [comment]
Progress: 
* Started spreadsheet to track scraping process: https://drive.google.com/drive/u/0/folders/15V2rV3aTLiA16juUUPlUmfsi-t2zW-vc
* Started working with new team members on scrapes
* Started getting an idea of the database tables

To Do:
* Experiment normalizing the data between foodpantries.org and LA LMS
