### ISSUE TITLE
Stakeholder form field requirements gathering

### ISSUE THREAD

**Issue by jpmikesell** [hackforla/food-oasis#244]
These two fields need to be able to be a list: services and items.

<img width="354" alt="Screen Shot 2020-01-28 at 20 32 40" src="https://user-images.githubusercontent.com/54608811/73328144-844f0280-420d-11ea-895c-d553d6beef71.png">

<img width="491" alt="Screen Shot 2020-01-28 at 20 32 22" src="https://user-images.githubusercontent.com/54608811/73328228-ca0bcb00-420d-11ea-888f-a4860c3de668.png">

The "verify" button may need to change it's name to something like: "Data is finalized". ???

**Comment by jpmikesell** [comment]
Also this field needs to be a list
![Screen Shot 2020-01-04 at 15 20 33](https://user-images.githubusercontent.com/54608811/73617229-28032e80-45d1-11ea-970b-e0cd0b238dc5.png)

**Comment by ExperimentsInHonesty** [comment]
@lucas-homer please provide an update.
1. Progress
2. Blocks
3. Availability
4. ETA

**Comment by lucas-homer** [comment]
Update:
1. 
-- "Inactive" button bug -- 
I spent some time on the 'Inactive' button bug, but unfortunately didn't make much progress. From what I can tell, it's some sort of issue with how we're using a particular JS library that powers this form. For a quick and dirty fix, I may actually separate this "Deactivate" feature code to be separate from the rest of the form. I want to style it with more of "Hey be careful before pressing this button" intent. 

-- other fields in the form needing lists per @jpmikesell --
When you say "list" you mean like a <textarea> effect where you can return a new line? Or do you mean something else?

**Comment by lucas-homer** [comment]
moved the "Inactive" button bug info to its own ticket --> #261

**Comment by lucas-homer** [comment]
Did some research on how ubiquitous these fields are, and went over everything with Jenny. For now I am going to add language in the "services" and "items" fields for users to separate each "item" or "service" with a comma so we can a little more efficiently get a better idea of how to normalize those two fields and eventually make them searchable.
