### ISSUE TITLE
Outreach for External Volunteers

### ISSUE THREAD

**Issue by jpmikesell** [hackforla/food-oasis#246]
### Overview
Steps to reach out to volunteers outside of Hack for LA.

### Action Items
1. Write script for educational video.
2. Write step by step guide that can help revise the attached pdf to help educate new volunteers (instead of Hack for LA members).

[how to make calls.pdf](https://github.com/hackforla/food-oasis/files/4145823/how.to.make.calls.pdf)

**Comment by ExperimentsInHonesty** [comment]
Screen shot of pdf
![Screen Shot 2020-02-02 at 5 18 46 PM](https://user-images.githubusercontent.com/37763229/73619021-2ab95000-45e0-11ea-9070-7a230e5f425f.png)

@gcohen02 and @jpmikesell let's talk about how this is different from how external volunteers are going to make the calls.
From our conversation two weeks ago, there was a plan to simply the process.  i.e. no heroku, using spreadsheets, etc.   Please define what we decided on.
