### ISSUE TITLE
Create Pitch Deck

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/food-oasis#247]
### Overview
We need a showcase deck, that explains the history, current status, and where we are going.

### Action Items
- [x] Create an outline
  - [x] Make history slides
     - [x] Get pictures from our facebook and other social media channels, as well as from the website.
    - [x] Look at the website for our written history
  - [ ] Make current project explanation slides
  - [ ] Make Future Direction slides
     - [x] Talk to Bonnie to about future direction

### Resources/Instructions
[current website] https://foodoasis.la/
Facebook
[Hack for LA facebook](https://www.facebook.com/hackforla/)
[Food Oasis facebook](https://www.facebook.com/foodoasisla/)

![1 copy 2](https://user-images.githubusercontent.com/54608811/73619999-c51b9280-45e4-11ea-86a0-fd7de078f8e4.png)

May be some useful direction also on my website that I just updated: https://www.mikeselldesign.com/work/food-oasis-website-for-food-seekers-in-los-angeles

**Comment by Jbarib** [comment]
In Progress - https://docs.google.com/presentation/d/1Jz77EMqhsG3b1wq-RP7kWfDIIsLGFpSZChY38rrxEUE/edit#slide=id.g6e92fb47a2_0_26

**Comment by Jbarib** [comment]
Still in Progress - https://docs.google.com/presentation/d/1Jz77EMqhsG3b1wq-RP7kWfDIIsLGFpSZChY38rrxEUE/edit#slide=id.g7d9e390c05_0_9

**Comment by ExperimentsInHonesty** [comment]
@Jbarib , can you give us an update on this.  It looks like the last edit was made 5 days ago.
1.  Progress
2. Blocks
3. Availability
4. ETA

**Comment by Jbarib** [comment]
1. Want to ensure sources for cites are linked or available
2. Need more information on future direction
3. Available
4. Sunday

**Comment by Jbarib** [comment]
2 - notes from Bonnie on today's meeting - resolve after the rest of the deck is completed
4 - will update and sync with the team Tuesday

**Comment by Jbarib** [comment]
Current Project Explanation as of 3/3/2020 we are:

- scraping data from open online resources to merge with the original data set
- the design enhancements are close to completion
- developing training tools [recording/informational to show new volunteers the process to update data
- a subset of the original data has been updated using this process

**Comment by lizagarrison** [comment]
The [deck for the Rapid Response Workshop](https://docs.google.com/presentation/d/16UJa8cO5qZ1Rx7Tr3g7Gp19eVMvosNwz0F4ytlG2k3c/edit?usp=sharing) can be used / tweaked prior to V2 launched (which is when the project background will be provided on-site)
