### ISSUE TITLE
Create Full User Flow from Search -> Results -> Stakeholder details

### ISSUE THREAD

**Issue by lucas-homer** [hackforla/food-oasis#252]
### Overview
We want to clearly outline each view of the primary feature of the app, and this issue serves as a reference for that. From the landing page's search input, to the results page (including the map of results and the list of results), to the stakeholder details. 

### Action Items
- [x] search page
- [x] results page
- [x] stakeholder details

### Resources/Instructions
Please paste in screenshots and/or urls for figma designs

**Comment by lucas-homer** [comment]
I should add the "Stakeholder Details" view is just another part of the results page really. Hopefully I didn't confuse anyone with that

**Comment by tina-moh** [comment]
Hi ,  The landing page and stakeholders details are updated in related issues, and the same with map search, once they are confirmed will update here the flow, thanks

**Comment by tina-moh** [comment]
<img width="1095" alt="P1" src="https://user-images.githubusercontent.com/56663382/75061075-d2fe5e00-5494-11ea-858a-9a763f371bfa.png">

**Comment by tina-moh** [comment]
<img width="1095" alt="P2" src="https://user-images.githubusercontent.com/56663382/75061187-0e992800-5495-11ea-9f00-93e828ad1665.png">

**Comment by tina-moh** [comment]
<img width="1054" alt="P3" src="https://user-images.githubusercontent.com/56663382/75061257-35575e80-5495-11ea-842c-cc3bee563efa.png">

**Comment by tina-moh** [comment]
<img width="1058" alt="P4" src="https://user-images.githubusercontent.com/56663382/75061303-4dc77900-5495-11ea-9958-f5aac95d1297.png">

**Comment by tina-moh** [comment]
https://www.figma.com/file/QgM5vS8NhDNXhknnFpu2Hn/Prototyping-in-Figma?node-id=26%3A394

**Comment by tina-moh** [comment]
<img width="1047" alt="P1" src="https://user-images.githubusercontent.com/56663382/75062591-f8d93200-5497-11ea-9c8f-a4574709e88e.png">

**Comment by tina-moh** [comment]
<img width="998" alt="P2" src="https://user-images.githubusercontent.com/56663382/75062684-2aea9400-5498-11ea-9b0b-4a2ae3b8819e.png">

**Comment by tina-moh** [comment]
<img width="1056" alt="P3" src="https://user-images.githubusercontent.com/56663382/75062754-4bb2e980-5498-11ea-9f98-998abc97cac7.png">

**Comment by tina-moh** [comment]
<img width="998" alt="P4" src="https://user-images.githubusercontent.com/56663382/75062806-6d13d580-5498-11ea-917f-3c7259f8d7bf.png">

**Comment by tina-moh** [comment]
<img width="999" alt="P3" src="https://user-images.githubusercontent.com/56663382/75063840-95043880-549a-11ea-93db-5c68c9a8c81c.png">

**Comment by tina-moh** [comment]
<img width="952" alt="P5" src="https://user-images.githubusercontent.com/56663382/75064076-18258e80-549b-11ea-9aa6-4f62ea9da855.png">

**Comment by tina-moh** [comment]
<img width="954" alt="P7" src="https://user-images.githubusercontent.com/56663382/75064140-2f647c00-549b-11ea-9e58-e93eb8b0725d.png">

**Comment by tina-moh** [comment]
<img width="952" alt="P6" src="https://user-images.githubusercontent.com/56663382/75064362-a69a1000-549b-11ea-9dae-c4cfd42d133d.png">

**Comment by tina-moh** [comment]
Landing page:
- Updating landing text
"Food Oasis LA (FOLA) has links to Food Pantries and Meals"

- Functional search button on landing page (enter an address, neighborhood, or zip)
- Choosing Current location as option to start the search

Search result/Stakeholders:
- Result three main filters:
Distance ( Any Dis, 0.3 miles, 1.2 miles, 3.1 miles, 9.3 miles -taken from "yelp" )
Food pantries
Meals

- Updating text on top right corner on stakeholder details
   "Hunger Free Los Angeles"

- Updating stakeholder details information
Address , Hours, Phone, Website, Eligibility /Requirement, Services Offered, Item Availability, Social Media

- Blue as main body color (replacing green with blue because of accessibility issues)

- Using just two color loctors on map Blue( Food pantries) and Red (meals)

Color Pantone codes:

 Red 
 Hex: CC3333
 CSS:  rgba(204, 51, 51, 1) 

 Blue
 Hex: 336699
CSS: rgba(51, 102, 153, 1)

Light Grey:
Hex: F1F1F1
CSS: rgba(241, 241, 241, 1)

Dark Grey:
Hex: 545454
CSS: rgba(84, 84, 84, 1)

Light green on search button:
Hex: BCE76D
CSS: 188, 231, 109

Black:
Hex: 000000
CSS: rgba(0, 0, 0, 1)

White:
Hex: FFFFFF
CSS: rgba(255, 255, 255, 1)
 Thanks
Please let me know if I can help by anything ! 
@lucas-homer @Telos8840

**Comment by lucas-homer** [comment]
Thank you so much @tina-moh for documenting this so well! My only question is around this one -- https://github.com/hackforla/food-oasis/issues/252#issuecomment-589794122

Right now we don't have this in v2 (food-oasis.herokuapp.com), but we have the hamburger icon that slides the sidebar into the window from the left. This is one difference between v1 (foodoasis.la) and v2 that I think is okay. The hamburger menu in foodoasis.la doesn't really "open" any "menu" it actually just moves you down the page. It's... kind of weird. 

Anyway, I guess I'm proposing we ignore that particular design as we don't need it. Thoughts? cc @lvl3jose

**Comment by tina-moh** [comment]
Hi Lucas, you are  right. In existing website reaching to this part is possible in two ways :
Scrolling down on landing page or the hamburger icon, so if possible we leave it as it is 
( already updated the landing page with hamburger icon)
<img width="1388" alt="Screen Shot 2020-02-22 at 11 41 20 AM" src="https://user-images.githubusercontent.com/56663382/75098211-4fae3c80-5568-11ea-92eb-10604f030a88.png">

**Comment by lvl3jose** [comment]
https://www.figma.com/file/Qs2zKdqZFLyPxc5qaaFCBk/FOLA-v4?node-id=0%3A1
![9094cc6a38ef7ca336aba291931243d0](https://user-images.githubusercontent.com/58757647/75119772-c3b91500-563a-11ea-93dc-236dab9b44ba.jpg)
<img width="818" alt="e38014c6770d74d0e0218464bdc4432a" src="https://user-images.githubusercontent.com/58757647/75119746-8fddef80-563a-11ea-9580-134d08f44361.png">
<img width="806" alt="65e44b5572f3dfd7f127e9e623c0ed86" src="https://user-images.githubusercontent.com/58757647/75119750-953b3a00-563a-11ea-9c4c-a341a60e64c6.png">
<img width="798" alt="da5ea9fbdf06cf33c72b9514128401f8" src="https://user-images.githubusercontent.com/58757647/75119752-98cec100-563a-11ea-8c91-be8da1ded6ce.png">
<img width="381" alt="404635b5f87504ea5c65f0285ca34a9e" src="https://user-images.githubusercontent.com/58757647/75119753-9d937500-563a-11ea-93a8-3dbc1dab971d.png">

**Comment by royceduong** [comment]
Please update search page copy to say
"Food Oasis has links to food pantries and meals in Los Angeles"
@tina-moh @lvl3jose

**Comment by lvl3jose** [comment]
Here is the update @royceduong 
https://www.figma.com/file/Qs2zKdqZFLyPxc5qaaFCBk/FOLA-v4?node-id=0%3A1
![4134b8154693b0d08dd658e6ca0a9f26](https://user-images.githubusercontent.com/58757647/75125326-70aa8680-5669-11ea-87a7-43ba978cf776.jpg)

**Comment by tina-moh** [comment]
> Food Oasis has links to food pantries and meals in Los Angeles

<img width="1009" alt="p01" src="https://user-images.githubusercontent.com/56663382/75213509-301d3c80-573f-11ea-87fc-f52351bcf514.png">
https://www.figma.com/file/QgM5vS8NhDNXhknnFpu2Hn/Prototyping-in-Figma?node-id=26%3A394

**Comment by tina-moh** [comment]
Hi Everyone, 
Here are new layouts adding "Verified Data" Filter.
Please let me know if you have any thoughts. 
Thanks, Be safe and Healthy :)
@jpmikesell @lucas-homer @Telos8840 @lvl3jose
https://www.figma.com/file/QgM5vS8NhDNXhknnFpu2Hn/Prototyping-in-Figma?node-id=26%3A394

**Comment by tina-moh** [comment]
<img width="990" alt="Adding Verified Data Filter01" src="https://user-images.githubusercontent.com/56663382/78731480-b8712e80-78f4-11ea-9b12-997d31456d26.png">

**Comment by tina-moh** [comment]
<img width="987" alt="Adding Verified Data Filter 02" src="https://user-images.githubusercontent.com/56663382/78731501-c4f58700-78f4-11ea-87e3-0805d505a62c.png">

**Comment by tina-moh** [comment]
<img width="987" alt="Adding Verified Data Filter 03" src="https://user-images.githubusercontent.com/56663382/78731534-d8a0ed80-78f4-11ea-95b8-350e467d2f3a.png">

**Comment by tina-moh** [comment]
Hi everyone, 
Here are the modified layout for verified data icon and content.
Please let me know if you have any thoughts.
Thanks, Be safe and Healthy :)
Tina
@jpmikesell @lucas-homer @Telos8840 @entrotech

**Comment by tina-moh** [comment]
<img width="1050" alt="01" src="https://user-images.githubusercontent.com/56663382/78949730-53970f00-7a81-11ea-9d08-44fbdd6c6df4.png">

**Comment by tina-moh** [comment]
<img width="1054" alt="02" src="https://user-images.githubusercontent.com/56663382/78949736-5eea3a80-7a81-11ea-9640-26aab8e3a6e1.png">

**Comment by tina-moh** [comment]
<img width="1051" alt="03" src="https://user-images.githubusercontent.com/56663382/78949787-8d681580-7a81-11ea-8a40-01174e2afac1.png">
