### ISSUE TITLE
scrape LA Public Library website data

### ISSUE THREAD

**Issue by jpmikesell** [hackforla/food-oasis#254]
### Overview
Scrape website - https://www.lapl.org/homeless-resources-food

### Action Items
Once scraped, place them in csv file in central location with a l[ink here](https://drive.google.com/drive/u/0/folders/1pF7X0Z9S0zh9RL5jHhUFoTgbaQOU9-QQ).

**Comment by alexulven** [comment]
Scraped. Csv is uploaded here: https://drive.google.com/drive/u/0/folders/1pF7X0Z9S0zh9RL5jHhUFoTgbaQOU9-QQ
