### ISSUE TITLE
Migrate PostgreSQL DB hosting from Heroku to AWS

### ISSUE THREAD

**Issue by lucas-homer** [hackforla/food-oasis#265]
### Overview
This issue will track the process of moving our database from being hosted on Heroku to being hosted on AWS. 

### Action Items

- [x] get access to Hack For LA's AWS account

- [x] review documentation on Heroku and AWS re: making the switch

- [x] confirm the scope of the switch --> should we host the app on AWS too while we're at it? Research and document the tradeoffs in this issue

### Resources/Instructions
- [heroku pg cli](https://devcenter.heroku.com/articles/heroku-postgresql#using-the-cli)
- [Importing and Exporting Heroku PG DBs](https://devcenter.heroku.com/articles/heroku-postgres-import-export)
- [PG on RDS](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_PostgreSQL.html)

**Comment by lucas-homer** [comment]
couldn't remember if you wanted me to just ping you here @ExperimentsInHonesty or assign you to the issue too, but anyway here's the created issue as promised!

**Comment by lucas-homer** [comment]
I don't have an update on this, really. I've been doing some reading up on the subject for sure, but since I didn't get this ticket onto @ExperimentsInHonesty 's radar before last Monday (my fault!), we're in a holding pattern before getting the credentials we need. @ExperimentsInHonesty I'll sync up with you on Tuesday!

**Comment by lucas-homer** [comment]
I think the easiest thing right now would be to limit this to migrating the database instance to AWS and keep the app instance hosted on heroku for the time being. The app itself isn't getting so much traffic that it's really necessary now. It IS necessary to move the DB though, so I'd like to do that and then focus on the UI some more. cc @ExperimentsInHonesty any update on me getting access to the Hack for LA AWS account? Or can I press on with my own AWS account for the time being?

**Comment by entrotech** [comment]
Since we were hitting the 10,000 row limit on the heroku-hosted database under the free hobby-dev plan, I had to upgrade to the hobyb-basic plan fo $9.00/ mo (in addition to the $7.00/mo for the web app dyno on heroku.

**Comment by lucas-homer** [comment]
@entrotech should we close this issue for now?

**Comment by entrotech** [comment]
Database is migrated to AWS. Moving the web app will be handled separately
