### ISSUE TITLE
Scrape One Degree

### ISSUE THREAD

**Issue by jpmikesell** [hackforla/food-oasis#272]
Scrape website from One Degree, https://www.1degree.org

Action Items

Put CSV file on google drive with link to [location here](https://drive.google.com/drive/u/0/folders/1zPBkrpQprnB-HUQOF8cjtcUA_QxWrE9i).

**Comment by alexulven** [comment]
First five tabs have been scraped. The csv is uploaded here: https://drive.google.com/drive/u/0/folders/1zPBkrpQprnB-HUQOF8cjtcUA_QxWrE9i
