### ISSUE TITLE
Scrape GET HELP MAP

### ISSUE THREAD

**Issue by jpmikesell** [hackforla/food-oasis#273]
Scrape website from GET HELP MAP, http://ca.gethelpmap.com

Action Items

Put CSV file on google drive with link to[ location here](https://drive.google.com/drive/u/0/folders/1dQLR4NGtRrlmAbvB0z0LvhsHhSKV-kd7).

**Comment by Scott-Larsen** [comment]
Scraped and uploaded to

https://drive.google.com/open?id=1HWpRZ8hu9c5SgFTJdORX3oUTREAUx2Fn
