### ISSUE TITLE
Scrape LA Homeless Resource Wiki 

### ISSUE THREAD

**Issue by jpmikesell** [hackforla/food-oasis#274]
### Overview
Scrape this website https://lahomeless.wikia.org/wiki/Los_Angeles_Homeless_Resource_Wiki

### Action Items
Linking CSV file on our [google drive here.](https://drive.google.com/drive/u/0/folders/1kBohy4WRDJLTZZe5BrIauW1rpIg-LcHz)

**Comment by alexulven** [comment]
Finished. CSV is uploaded to the folder on the google drive. https://drive.google.com/drive/u/0/folders/1kBohy4WRDJLTZZe5BrIauW1rpIg-LcHz
