### ISSUE TITLE
Location Markers on Map Bug

### ISSUE THREAD

**Issue by joshuazrobins** [hackforla/food-oasis#278]
There is currently a bug that does not place location markers at static points on the map. Not only this, but certain location markers do not appear at the correct geocoordinates at certain map-zoom levels. See images for an example:

![screenshot1](https://user-images.githubusercontent.com/1521996/77010812-c6e8ad80-6927-11ea-9678-e614338dd053.png)

![screenshot2](https://user-images.githubusercontent.com/1521996/77010800-c223f980-6927-11ea-83db-9438c481952d.png)

**Comment by entrotech** [comment]
I'm not sure exactly what Joshua is saying, but it might be a problem that we've seen where a user would expect the point at the bottom of the marker to be the exact latitude and longitude of interest, but the markers were being placed such that the top-center of the marker's enclosing rectangle was actually placed on the latitude, longitude of interest. This caused it to look like the marker was moving to  different locationa as the user zoomed in and out. For example, if the map location is Long Beach, all the markers fall on top of each other, but it looks like they are pointing to a spot in the Ocean south of Long Beach. This may have been in an effort to place the pop-up info window such that it would not overlap the marker, as shown here:

![image](https://user-images.githubusercontent.com/9939032/89477081-2f9ebe00-d741-11ea-9e25-372be23ff62f.png)

I modified this to place the marker above the poiint of interest (by adjusting the svg images used in the markers), and then anchoring the pop-up info window such that the top of the window aligns with the point of interest:

![image](https://user-images.githubusercontent.com/9939032/89477231-991ecc80-d741-11ea-8149-d272ea7e5bbb.png)

When zoomed-in:
![image](https://user-images.githubusercontent.com/9939032/89477270-b2277d80-d741-11ea-8965-e1308fbe45af.png)

and zooming in even further, you can see that the marker is on a CSULB building as expected.

**Comment by entrotech** [comment]
Follow-up: Needed to fix a bug introduced where the markers on the results list were out of position. Also made markers a bit smaller, per Tina's request.

**Comment by entrotech** [comment]
PR #642
