### ISSUE TITLE
Allow a user to claim a stakeholder

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#292]
### Overview
We need to have a way for a representative of an Organization to "claim" the organization and essentially take over responsibility for maintaining the correct information about the organization in the application. 

### Action Items

- [ ] - Decide on a procedure for authenticating that a user actually represents the organization. For now, I am assuming that this will be a partially manual process.
- [ ] - Decide on how a user notifies FA that they want to claimn the organization (maybe a "claim this organization" button on the app somewhere/) and implement this feature.
- [ ] - I'm assuming that a user will need to register to claim a business. We need to decide if they need a special security role to claim a business (probably not?)
- [ ] - Implement a feature that allows an admin to assign an existing user to a stakeholder.
- [ ] - When a user is assigned to a stakeholder, they should be able to edit that stakeholder information.
- [ ] - A user may claim multiple organizations, but an organization can have only one claimant?
- [ ] - When a stakeholder is claimed, should we automatically unassign it from a volunteer, but still allow editing by an admin?

### Resources
One example of an app that has this kind of feature is Yelp.

**Comment by entrotech** [comment]
I have started on this by adding claimed_date and claimed_login_id fields to the stakeholder table, and will add a control on the StakeholderEdit component that an admin can use to claim a stakeholder for a user.

**Comment by entrotech** [comment]
Update. The admin can claim an organization for a user by opening the edit page and choosing the user from the claimed by drop-down.  No features are yet in place to process claim requests or allow a used who claimed an organization to be able to edit it.

**Comment by staceyrebekahscott** [comment]
Closing this issue as not planned, as issue #996 deals with the process of having pantries self update their own listings. This issue is also similar to #906 of allowing users to claim a pantry, which is also being closed as 996 deals with this.
