### ISSUE TITLE
Add new fields to the heroku app

### ISSUE THREAD

**Issue by jpmikesell** [hackforla/food-oasis#297]
### Overview
NEW FIELDS TO ADD TO HEROKU APP in response to volunteer feedback and new requirements for partnership with Food Cycle.

### Action Items
FIGMA File to review  
https://www.figma.com/file/5PhElEw8PWEmjqHGkFsKHg/Heroku-App-V2?node-id=0%3A1

**Comment by tina-moh** [comment]
Hi Jenny
I had just two other comments ,
-In introduction : don’t you want to mention we are **non-profit**?
-In eligibility and requirements , can't  they write their notes in the same space provided for Other?  
 please let me know if this needs other modifications 
Thanks
Tina

**Comment by lizagarrison** [comment]
Moving this to V2 milestone to preserve Jenny's comments about information gathering / validation beyond 6 key criteria
