### ISSUE TITLE
Contact Outlet - Recycling Compost

### ISSUE THREAD

**Issue by jpmikesell** [hackforla/food-oasis#30]
Overview

Connecting with orgs to build our database of stakeholders.

Action Items

  Find Hunger Relief Orgs and add to DB
  Find any relevant Coalitions for this subcategory of industry and add to DB
  Contact the organizations you have found and document the information in DB
Resources/Instructions

Outlet Database

**Comment by chombus** [comment]
Closing issue as no longer relevant to project.
