### ISSUE TITLE
Landing Page Usability?

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#304]
### Overview
Issue #266 referred to the visual redesign of the Home page. The Figma file showed that the header background was transparent and the "hamburger" menu was changed from black to a white color, which showed up ok, because the background image on the Figma file happened to be dark in that area. However, I see a few problems with this concept:

- [x] The background image randomly changes, and some of them are a light color behind the hamburger menu icon, making it more or less invisible.
- [x] When a logged-in user goes to the home page, their name is displayed in black and slides over near the hamburger menu. Depending on the background image, this may or may not be visible.
- [x] Likewise, a logged-in user might be able to  see a LOGOUT link in the right-hind side of the header, depending on the background.
- [x] You might say that we should hide the user name and LOGOUT on the home page altogether, but then the user has no idea if they are logged in or not and may or may not be able to see the menu icon.

I think we need to revisit this design concept or make some kind of change for it to be more functional.

### Resources
In this example, the user name "Bonnie" is essentially invisible next to the hamburger icon, and the LOGOUT link is not very visible in the upper-right:

![image](https://user-images.githubusercontent.com/9939032/80011840-461a5580-8481-11ea-8a07-b0381d5eb0f9.png)

In this example, you can see the user name and LOGOUT link, but can't really see the menu icon:

![image](https://user-images.githubusercontent.com/9939032/80012179-c2ad3400-8481-11ea-8cf8-e310cbbb4e1e.png)

**Comment by tina-moh** [comment]
Hi John, 
will update it tonight
Thanks 
Tina

**Comment by tina-moh** [comment]
<img width="1090" alt="L01" src="https://user-images.githubusercontent.com/56663382/80130095-ec7f5d00-854c-11ea-9650-5f56970a5847.png">

**Comment by tina-moh** [comment]
<img width="1091" alt="L02" src="https://user-images.githubusercontent.com/56663382/80130112-f4d79800-854c-11ea-925a-581a6ba011ac.png">

**Comment by tina-moh** [comment]
<img width="1082" alt="L03" src="https://user-images.githubusercontent.com/56663382/80130145-002ac380-854d-11ea-9ddf-1c4d1cb72ca2.png">

**Comment by tina-moh** [comment]
<img width="1084" alt="L04" src="https://user-images.githubusercontent.com/56663382/80130175-0c168580-854d-11ea-816d-d95ce3196c15.png">

**Comment by tina-moh** [comment]
<img width="1087" alt="L05" src="https://user-images.githubusercontent.com/56663382/80130216-19cc0b00-854d-11ea-87ee-db9ade4a2b3f.png">

**Comment by tina-moh** [comment]
<img width="1085" alt="L06" src="https://user-images.githubusercontent.com/56663382/80130502-8941fa80-854d-11ea-899f-43a4b639f9dc.png">

**Comment by tina-moh** [comment]
I have a question  about **Hamburger button**  by now  clicking on it , it refers to down page, are there additional functions in future ? if not is it necessary to keep it?
@entrotech @jpmikesell

**Comment by Telos8840** [comment]
@entrotech I'm going to close this ticket since this was resolved in this PR #344
