### ISSUE TITLE
Decide on UI/UX for Multiple Selection with Optional Description for Each Option

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#316]
### Overview
The figma file Jenny and Gaby created as a concept for the Organization Edit Screen has two data items (Non-Food Items and Eligibility Requirements) where the idea is to be able to:

- Select from a standard list of choices, and
- Be able to free-type additional options that aren't on the list, and
- Enter some sort of note or descripiton about each choice selected.

The screenshots below show their rough ideas of a UI for achieving this, but we should find a better UX that:

- is consistent
- allows for a fairly long list of standard options
- allows for entering an optional note about each option
- is easy for the user to understand and hard (prefereably impossible) for them to use incorrectly
- allows for efficient data entrhy with a minimal number of keystrokes and clicks

### Action Items

- [ ] Conceptualize UX designs
- [ ] Choose a design
- [ ] Implement a React Control
- [ ] Incorporate in the OrganizationEdit screen

### Resources
This is similar to Issue #315, but has the addtional feature of being able to add a note to each selected option

### Resources/Instructions
![image](https://user-images.githubusercontent.com/9939032/80402084-3bd9cc00-8872-11ea-86ee-a1d9b193f2ba.png)

![image](https://user-images.githubusercontent.com/9939032/80402128-4ac07e80-8872-11ea-9b37-bf5659cb64e3.png)

**Comment by staceyrebekahscott** [comment]
@fancyham @sei1122 Is this issue still relevant? It was created in April 2020 and no work has been done on it.

Please advise if this can be closed out.

**Comment by sei1122** [comment]
We can close this since we haven't worked on it for 2 years.

**Comment by staceyrebekahscott** [comment]
As per Seiko's comment, closing this issue.

**Comment by fancyham** [comment]
Adding history here:

Same reasoning as #315.  Do want to eventually create region-specific tagging and Eligibility and Requirements checkboxes are a good place to start in the future.  

Ended up doing freeform text fields for now.

This type of thing would eventually support advanced search in the future though.
