### ISSUE TITLE
Conceptualize how to maintain a log of Data Entry Activity

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#319]
### Overview
Need a mechanism to record the quantity and quality of the work done by Data Entry users. There are several things that we might want to track:
How many stakeholders were edited and/or marked as submitted?
How many of the submitted records were approved / rejected by admin?
How can we gather this data in maningful format? Report of work by individual user, leaderboard ui?

### Action Items

- [ ] Decide what the requirements are...

**Comment by staceyrebekahscott** [comment]
It appears that this issue is being resolved by #368 and #834 

Closing issue as outdated.
