### ISSUE TITLE
Results Page Mapbox Component Enhancement

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#330]
### Overview
Enhance the ResultsMap component to look like the Desktop and Mobile Figma wireframes (linked below).  This is only for the ResultsMap component - the other panels on the page are allocated to different issues. I think the pages labelled Macbook Pro 15, Macbook Pro 16 and Macbook Pro 17 are the wireframes to reference - check with Tina.

### Action Items

- [ ] Study the Figma files below
- [ ] Modify the ResultsMap to mimic the wireframes as closely as possible, including the marker design (the check mark means it's verfied data)
- [ ] There are a few features that aren't shown on the wireframe. For example, clicking on a marker should probably show an pop-up info window near the marker with cursory information about the selected organization. Check with the UX/UI folks about this before proceeding - maybe they don't want this feature, or maybe clicking on a marker highlights the clicked organization on the list in the left-hand panel.
- [ ] Some of the other wireframes show an oversize marker that is the location specified in the serach - I'm not sure if that is still part of the design.
- [ ] The color of the marker should reflect the organization category.

### Resources/Instructions
[Wireframes for Desktop ](https://docs.google.com/document/d/1NaMPWsWJvcTivgS6M6fuJPjdusj8TGMSmw9Pqk3ATbs/edit)

[Wireframe for Mobile](https://docs.google.com/document/d/1NaMPWsWJvcTivgS6M6fuJPjdusj8TGMSmw9Pqk3ATbs/edit)

**Comment by pr1ntr** [comment]
The way I am able to work on the pins is by going to /organization and searching Echo Park. I want to confirm that is the correct view.

**Comment by pr1ntr** [comment]
Which property of the pin data decides the color of the pin?

pin data:
```json
{
    "id": 3218,
    "name": "Echo Park Library",
    "address1": "1410 W Temple Street",
    "address2": "",
    "city": "Los Angeles",
    "state": "CA",
    "zip": "90026",
    "phone": "Victoria Sikora / 213.580.3738",
    "latitude": 33.94,
    "longitude": -118.52,
    "website": "https://www.lafoodbank.org/sfsp/",
    "notes": "Closed 7/4/2017",
    "createdDate": "2019-12-01T08:00:00.000Z",
    "createdLoginId": null,
    "modifiedDate": null,
    "modifiedLoginId": null,
    "verifiedDate": null,
    "verifiedLoginId": null,
    "assignedDate": null,
    "assignedLoginId": null,
    "approvedDate": null,
    "rejectedDate": null,
    "reviewedLoginId": null,
    "claimedDate": "2019-12-01T08:00:00.000Z",
    "claimedLoginId": null,
    "requirements": "",
    "adminNotes": "",
    "inactive": false,
    "createdUser": "",
    "modifiedUser": "",
    "verifiedUser": "",
    "reviewedUser": "",
    "assignedUser": "",
    "claimedUser": "",
    "categories": [
      {
        "id": 6,
        "name": "Summer Lunch for Kids"
      }
    ],
    "hours": [
      {
        "day_of_week": "Fri",
        "open": "12:00:00",
        "close": "12:50:00",
        "week_of_month": 0
      },
      {
        "day_of_week": "Thu",
        "open": "12:00:00",
        "close": "12:50:00",
        "week_of_month": 0
      },
      {
        "day_of_week": "Wed",
        "open": "12:00:00",
        "close": "12:50:00",
        "week_of_month": 0
      },
      {
        "day_of_week": "Tue",
        "open": "12:00:00",
        "close": "12:50:00",
        "week_of_month": 0
      },
      {
        "day_of_week": "Mon",
        "open": "12:00:00",
        "close": "12:50:00",
        "week_of_month": 0
      }
    ],
    "parentOrganization": "",
    "physicalAccess": "",
    "email": "",
    "items": "",
    "services": "",
    "facebook": "",
    "twitter": "",
    "pinterest": "",
    "linkedin": "",
    "description": "",
    "reviewNotes": "",
    "instagram": "",
    "adminContactName": "",
    "adminContactPhone": "",
    "adminContactEmail": "",
    "donationContactName": "",
    "donationContactPhone": "",
    "donationContactEmail": "",
    "donationPickup": false,
    "donationAcceptFrozen": false,
    "donationAcceptRefrigerated": false,
    "donationAcceptPerishable": false,
    "donationSchedule": "",
    "donationDeliveryInstructions": "",
    "donationNotes": "",
    "covidNotes": "",
    "categoryNotes": "",
    "eligibilityNotes": "",
    "foodTypes": "",
    "languages": "English",
    "distance": 17.48251984717587
  }
```
