### ISSUE TITLE
Fixes / Enhancements to Security Admin Screen

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#351]
### Overview
When using the Security Admin Screen, every time you click on a checkbox to grant or remove a permission, it creates a copy of the row representind the acount you clicked on in the table, instead of replacing the existing record.  Also, see other improvements below

### Action Items

- [ ] Fix problem described above. This is all in the SecurityAdminDashboard's handlePermissionChange method. This also causes a duplicate key warning in the console when you run in a dev environment.
- [ ] If the user types in criteria that have no match among the accounts, Display a prominent message that no accounts were found matching the entered criteria.
- [ ] We want to use camelCase variable and property naming convention in javascript. This requires a conversion from snake case column names used in postgres to camelCase - preferable in the code that format the web api response from node.

### Resources/Instructions
Before clicking on a check box:
![image](https://user-images.githubusercontent.com/9939032/80927242-48b65e00-8d51-11ea-8f60-5955ee5277be.png)

After clicking on the Data Entry check box:
![image](https://user-images.githubusercontent.com/9939032/80927265-6b487700-8d51-11ea-8436-b819acf1a175.png)

Follow-up to PR #346  I did fix up some problems with the search, and re-name state variables for clarity, and improve the PropTypes on SecurityTable, but left these issues for Hassen.

**Comment by HassenH1** [comment]
I just pushed up 
let me know if it's good
