### ISSUE TITLE
Hook up the Landing Page to go to the Results Page when submitting

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#360]
### Overview
The home page has a location auto-complete control and a submit button. When a location is pressed and the button is clicked, it currently navigates to the Stakeholders component with query parameters that specify the search criteria. Since the Stakeholders component is being replaced by the ResultsContainer, we need to modify both the ResultsContainer and the Home page to navigate to the Result page and somehow pass the appropriate query parameters.

### Action Items

- [x] Decide on how to pass the parameters (query string parameters, local storage, etc.)
- [x] Implement code on the ResultsContained to recieve the parameters and execute the query immediately.
- [x] Modify the Home page to call the ResultsContainer accordingly.

**Comment by timmalstead** [comment]
having an issue figuring how to pass down location string from Search component to the next render cycle of Search component
