### ISSUE TITLE
Fix bug when user logs out

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#362]
### Overview
The browser show the error displayed in the screenshot below when the user logs out.

### Action Items

- [ ] Fix it

### Resources/Instructions

![image](https://user-images.githubusercontent.com/9939032/81082443-2a16ab00-8ea8-11ea-89cd-7a5f2c49e411.png)

**Comment by Telos8840** [comment]
@entrotech if you haven't started this yet, I can take over since I tried adding this feature. I might know why it's not working but let me know if you're ok with me working on this
