### ISSUE TITLE
Design & Develop UI for Mobile Version of Site

### ISSUE THREAD

**Issue by lizagarrison** [hackforla/food-oasis#366]
### Overview
Food seeker users will need to be able to access the FOLA site via mobile devices; as such, we need to design and develop the responsive version of the end user site (map, search functionality, etc.) to be accessed via mobile web browsers.

### Action Items
- [x] Conceptualize UX/UI design options for mobile browser(s)
- [x] Choose a design
- [x] Realize the design on front end

**Comment by tina-moh** [comment]
https://www.figma.com/file/zeiGomkm313mPgYGd04Qt0/FOLA-MOBILE?node-id=0%3A1
