### ISSUE TITLE
Implement the Coordinator Role

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#369]
### Overview
We need to introduce a new kind of user and a dashboard  for them. It is a "Coordinator", and the idea is that this person would coordinatte the work of volunteers, and have all the authorization of an Admin user except for the abilty to mark stakeholder records as "verified". This issue is to add the coordinator role to the database, allow granting/revonking the role by a Securiyt Admin user, and enable the application features that an Admin currently has (with the excpetion of the the ability to verify organization records).

### Action Items

- [x] Add an "is_coordinator" boolean column to the login table.
- [x] Add this field to the node services that retrieve account information.
- [x] Add this field to the SecurityAdmin React form as a fourth checkbox on each line, and hook it up to grant / revoke the security role from the user.
- [x] Locate the react code that enables buttons and other features for user.isAdmin, and also allow user.isCoordinator to have those same roles, except for the features that allow an admin to verify an organization

### Resources/Instructions
This is what the Security Admin screen looks like. Also re-order the columns so they are Security Admin, then Admin, then Coordinator, then Data Entry.
![image](https://user-images.githubusercontent.com/9939032/81419488-26cb2b80-9103-11ea-9b03-aacc0dc8824d.png)

**Comment by StevenKitzes** [comment]
The PR addressing this issue will include code for both front and back end changes.  Review of front end changes can be assisted by the following images, depicting a Security user's ability to set Coordinator permissions, as well as a Coordinator's *inability* to Approve Verification of an Organization.

![369-1](https://user-images.githubusercontent.com/3070303/82552538-25442f00-9b17-11ea-8147-400db52c36cb.JPG)
![369-3](https://user-images.githubusercontent.com/3070303/82552541-26755c00-9b17-11ea-84b3-f674e100936b.JPG)
![369-2](https://user-images.githubusercontent.com/3070303/82552543-26755c00-9b17-11ea-9616-7a7bb5a19826.JPG)
