### ISSUE TITLE
Move Stakeholder Inserts and Updates into a Stored Procedure

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#373]
### Overview
This is the first in as series of issues that implement a full audit log for organization/stakeholder records. The idea is to perform updates to a stakeholder, it's hours and it's categories in a single stored procedure call. This stored procedure call will evolve in later issues into a full-blown audit log.

### Action Items

- [x] Without changing the schema of the current stakeholder table, implement a stored procedure that updates the stakeholder, stakeholder_schedule and stakeholder_category tables for a single stakeholder in a single stored procedure call.
- [x] Likewise, create a similar stored procedure for inserts of new stakeholders.
- [ ] Modify the PUT and POST web api endpoint implementations to use the stored procedures instead of the current dynamic SQL.

**Comment by Benbaillou** [comment]
Hi - can we label the size please?
