### ISSUE TITLE
Improve appearance of the Registration Verification Email

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#411]
### Overview
The email that gets sent our when you first register looks like the screenshot below

### Action Items

- [ ] Design a more attractive message in HMTL
- [ ] Implmenent the design
- [ ] Test in a few different email clients (gmail, outlook, whatever)

### Resources/Instructions
Very similar to issue #412

![image](https://user-images.githubusercontent.com/9939032/82124679-83f35c80-9755-11ea-9de6-cc22f4385382.png)

**Comment by rblaz001** [comment]
See issue #412.
