### ISSUE TITLE
Improve the Appearance of the Forgot Password Email

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#412]
### Overview
The email that gets sent our when you first register looks like the screenshot below

### Action Items

- [ ] Design a more attractive message in HMTL
- [ ] Implmenent the design
- [ ] Test in a few different email clients (gmail, outlook, whatever)

### Resources/Instructions
Very similar to Issue #411
![image](https://user-images.githubusercontent.com/9939032/82124904-1ea06b00-9757-11ea-9b44-ae012a6400a7.png)

**Comment by rblaz001** [comment]
**Progress Report**
- [x] Design a more attractive message in HMTL
- [x] Implmenent the design
- [ ] Test in a few different email clients (gmail, outlook, whatever)

I still need to figure out how to set up local database environment so I can make sure my implementation is correct.
I also need to continue testing on different email clients, I currently have only verified correctness on gmail client.

**Current Version of Template**
![Screenshot from 2020-08-03 18-10-01](https://user-images.githubusercontent.com/35281980/89242661-f5091a00-d5b6-11ea-8cbb-e1534d22c7b7.png)

**Comment by rblaz001** [comment]
**Progress Report**
- [x] Test on local database to make sure email is being sent properly
- [ ] Test in a few different email clients (gmail, outlook, whatever)

I have finally been able to test that my implementation is working on my local database using the sendgrid service. The only thing that is left is adding the links to the images used in the above template. They are currently svgs so I will need to request pngs for email compatibility sake.

Note there has been a few small changes to the template to better reflect our style guides. Not all email clients support adjusting line height so there will be some styling variation compared to our guides.

![Screenshot from 2020-08-07 13-16-29](https://user-images.githubusercontent.com/35281980/89684984-4fa0bf80-d8b0-11ea-97a8-b8c38b857140.png)

**Comment by rblaz001** [comment]
**Progress Report**
- [x] Test on local database to make sure email is being sent properly
- [x] Obtain png versions of Food Oasis Logo and Icon Spacer
- [x] Test in a few different email clients (gmail, outlook, whatever)
