### ISSUE TITLE
Re-factor the StakeholderEdit component

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#418]
### Overview
This component has grown to over 2000 lines of code and needs to be reafctored

### Action Items

- [ ] Research techniques for breaking a large Formik form into smaller pieces
- [ ] Implement the re-factor without modifying the functionality of the form.

**Comment by staceyrebekahscott** [comment]
@entrotech Issue is from May 2020. Moved it to Icebox. Does this issue need to be rewritten or refreshed considering its age?  Given the Impact Sprints 2022 priorities, is this OK to be in the Icebox for now until after the sprints are completed?
