### ISSUE TITLE
FOLA Style Guide

### ISSUE THREAD

**Issue by lizagarrison** [hackforla/food-oasis#423]
### Overview
Develop Style Guide of standard UI elements to ensure consistency across designs / designers

**Comment by tina-moh** [comment]
[STYLE GIUDE  01.pdf](https://github.com/hackforla/food-oasis/files/4659115/STYLE.GIUDE.01.pdf)

[STYLE GIUDE  01.pptx](https://github.com/hackforla/food-oasis/files/4659119/STYLE.GIUDE.01.pptx)

**Comment by ExperimentsInHonesty** [comment]
@tina-moh, I recommend changing language on slide 5 from 
(After Hamburger Button if there is)
to
(Logo appears to the right of Hamburger menu, when menu is present)

**Comment by tina-moh** [comment]
@ExperimentsInHonesty Noted.
[STYLE GIUDE  02.pdf](https://github.com/hackforla/food-oasis/files/4664937/STYLE.GIUDE.02.pdf)
[STYLE GIUDE  02.pptx](https://github.com/hackforla/food-oasis/files/4664946/STYLE.GIUDE.02.pptx)

**Comment by tina-moh** [comment]
https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/Fola-Design-System?node-id=0%3A1

**Comment by lizagarrison** [comment]
[Final Design Guide](https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/Fola-Design-System?node-id=0%3A1)
