### ISSUE TITLE
Define, Implement and Document a Database Migration Process

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#431]
### Overview
We recently created separate development and production environments. Confuration management for source code is handled through a Git Flow workflow, and publishing code to the web servers from the develop and master branches, respectively.  We need to implement a database migration process for managing the migration of database schema and object changes and reference data changes from one environment to the next.

### Action Items

- [ ] Decide on a database migration tool.
- [ ] Implement a baseline (if necessary) and first migration for PR #425 
- [ ] Document in a migrations.md markedown file in the repo the instructions for developers to follow to add new migrations for database changes.

### Resources/Instructions
Here's one[node-pg-migrate]( https://github.com/salsita/node-pg-migrate) that looks really promising to me, since it uses SQL for the migration (a lot of them use JSON in some tool-specific structure that gets compiled into SQL for execution, which I'm not a fan of). It also fits well with ou node environment. It also seem really straightforward to manage.

Other people have used flyway or other tools that are more generic, and there might bo other options.

**Comment by jafow** [comment]
I'll throw out Sequelize for migrations. It's a nodejs SQL orm but it may be possible to utilize its CLI for creating migration files. 
[https://sequelize.org/v5/manual/migrations.html](https://sequelize.org/v5/manual/migrations.html)

The real benefit of using this would be leveraging the ORM features, defining models in code, and having the DAL be more javascript-y :-) there are plus and minuses for this

**Comment by jafow** [comment]
> Here's onenode-pg-migrate that looks really promising to me

just looked at this and agree it looks like a good choice, especially as it doesn't require an ORM and would work out of the box with `pg`. :+1:
