### ISSUE TITLE
Debug web api request issues from ResultsContainer

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#442]
### Overview
Tim has been expereincing problems with 404 errors on web requests from the ResultsContainer. Investigate. The problems we've seen in recent days are:

### Action Items
- [x] Tim reports 404 errors on web requests that seem to have been working before.
- [x] Pressing the button with the magnifying glass icon results in two web requests, instead of one (this also happens for the similar button on the home page).
- [x] Some web requests are missing the latitude and longitude, and therefore return no results, and position the maps origin at latitude, longitude (0,0)

**Comment by timmalstead** [comment]
This was strictly a local issue with me, now sorted.
