### ISSUE TITLE
Add Search Criteria to Verification Admin dashboard

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#446]
### Overview
MVP Requirements 28 and 36

### Action Items
Search by

- [x] Permanently Closed
- [x] Closed for COVID,
- [x] Organization ID,
- [x] %Complete

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.

**Comment by lizagarrison** [comment]
Note: per call with John on 6/4 -- "neighborhood" filter is being moved to V2 (issue #372)

Volunteer Coordinator can use "search by radius" feature to accomplish this in meantime

**Comment by entrotech** [comment]
PR #498
