### ISSUE TITLE
Use Google Sheet as database to populate static roster page on site

### ISSUE THREAD

**Issue by timmalstead** [hackforla/food-oasis#466]
### Overview
Instead of having to make a frontend change for semi-static information, such as the team roster, we should store the info on a spreadsheet in google drive and have the site make a request for that info when the roster (or other) page is loaded.

This would allow the pm to easily change information without having to open a developer issue.

### Action Items
- [ ] install and implement google sheets api in express
- [ ] set up google sheets api in google console
- [ ] deliver google sheets data to front end as JSON, to be mapped and rendered in React
- [ ] implement JSON caching in express with fs and possibly frontend caching as well.

**Comment by staceyrebekahscott** [comment]
Closing this issue as outdated. We do need to update our listing on the website, but I don't think creating a process for updates that don't happen that often is a good use of our time. HfLA website already has a process for this. 

Current issue: #1269

**Comment by ExperimentsInHonesty** [comment]
Tim wrote an article about how to do this 
https://medium.com/better-programming/make-a-team-roster-with-node-react-and-google-sheets-305b9f9ebbb1
