### ISSUE TITLE
Information Pages Design (MVP)

### ISSUE THREAD

**Issue by lizagarrison** [hackforla/food-oasis#480]
### Overview
There are a few static pages that we want to include on the FOLA site, some of which will be included in MVP and some of which will be introduced as part of V2. 

_MVP Pages:_
1. Donate
2. FAQs
3. About FOLA

_MVP Sitemap:_
![FOLA_MVP_STATIC_PAGES](https://user-images.githubusercontent.com/63373671/83699898-21ee8000-a5ba-11ea-8476-e9e89f61c7f9.png)

### Copywriting Tasks
- [X] Draft copy: "About FOLA" page (@lizagarrison)
- [x] Draft copy: "FAQs" page (@jpmikesell)
- [x] Refine copy: "Donate" page (@wendywong86)
- [x] Refine copy: "FAQs" page (@wendywong86)
- [x] Refine copy: "About FOLA" page (@wendywong86)
- [x] Review copy with Jenny/Liza (@wendywong86)
- [x] Make any necessary edits (@wendywong86)
- [x] Final copy review w/ Bonnie for HfLA lens (@lizagarrison)

### Design Tasks
- [x] Create Figma template for static information pages (@paigelizabeth)
- [x] Provide link to hero images for info pages (@jpmikesell)
- [x] Design "About FOLA" page w/ final copy (@tina-moh)
- [x] Design "Donate" page w/ final copy (@tina-moh)
- [x] Design "FAQs" page w/ final copy (@tina-moh)
- [x] Design team sign-off (in Slack / Figma file)
- [x] Document list of links for CTAs for handoff / develop wireflow (@lizagarrison)
- [x] Coordinate handoff to dev team (@lizagarrison)

### Resources/Instructions
- [Draft Copy (Google Doc)](https://docs.google.com/document/d/19ocQRMumwX_yu3HOaabgJIu6jovaE0RLEY2jVdIlJKs/edit?usp=sharing)
- [Final Copy](https://docs.google.com/document/d/15xvzGx9QeVZ2TgL8pq4phDNb3LmCdxAA9stOaKv_E5E/edit#) - **@ExperimentsInHonesty TO REVIEW**

**Comment by wendywong86** [comment]
@lizagarrison @jpmikesell Let me know if you prefer to make comments in the Google doc (https://docs.google.com/document/d/15xvzGx9QeVZ2TgL8pq4phDNb3LmCdxAA9stOaKv_E5E/edit#)—or on a call. Happy to schedule something for us to go everything. (I'm usually available around 12-2pm M-F depending on my work mtgs.)

**Comment by wendywong86** [comment]
@lizagarrison Reviewed copy with @jpmikesell this evening, and added new content for the Donate and FAQ pages (just the glossary) based on feedback. Here’s a link to the final copy: https://docs.google.com/document/d/15xvzGx9QeVZ2TgL8pq4phDNb3LmCdxAA9stOaKv_E5E/edit#

**Comment by lizagarrison** [comment]
[Design Guide / Sandbox](https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/Fola-Design-System?node-id=0%3A1)

**Comment by wendywong86** [comment]
@lizagarrison Edited one sentence in the About Us + also added a note about a potential workaround for the donation copy.

**Comment by entrotech** [comment]
Should have mobile mock-ups by 6/18/20
