### ISSUE TITLE
Create MVP User Flows

### ISSUE THREAD

**Issue by lizagarrison** [hackforla/food-oasis#485]
### Overview
Create user flows for the (1) Food Seeker, (2) Admin, (3) Data Entry User and (4) Volunteer Coordinator roles. 
Final user flows for "internal users" (i.e. Admin, Data Entry Users & Volunteer Coordinators) should encompass everything from recruiting/onboarding through the volunteer session process and finally review/approval of the updated data.
Final user flows for "external users" (i.e. Food Seekers) should encompass everything from finding the site to searching an address, filtering search results and selecting an organization

### Action Items - Food Seekers
- [X] Perform heuristic evaluation of food seeker flow, document observations (Issue #484)
- [X] Define requirements
- [X] Walk through new requirements with dev team & prioritize
- [ ] Create final Food Seeker user flow based on final MVP process

### Action Items - Admin & Data Entry Users
- [X] Map out user flows for _existing processes_ performed by Admin & Data Entry users (using Webinar / manual recruiting processes)
- [X] Map out user flows for _"to be" processes_ performed by Admin & Data Entry users (using heroku app processes)
- [X] Identify gaps in the "to be" processes, define requirements
- [X] Walk through new requirements with dev team & prioritize
- [ ] Update final Admin user flow based on final MVP process
- [ ] Update final Data Entry user flow based on final MVP process

### Action Items - Volunteer Coordinator Users
- [ ] Map out user flows for "to be" process performed by VC users (using heroku app)
- [ ] Identify gaps in the "to be" processes, define requirements
- [ ] Walk through new requirements with dev team & prioritize
- [ ] Update final Coordinator user flow based on final MVP process

### Resources/Instructions
[Heroku App](https://food-oasis.herokuapp.com/)

**Comment by lizagarrison** [comment]
- [FOLA Existing User Flows - Admin & Data Entry](https://miro.com/app/board/o9J_kt_HV4Q=/)
- [FOLA "To Be" User Flows - Admin & Data Entry (Draft)](https://app.lucidchart.com/invitations/accept/cda00ca9-de11-4aa9-a3ef-122687c4e82f)
- [FOLA Ideal User Flows - Recruiting & Onboarding (Draft)](https://app.lucidchart.com/invitations/accept/b3e355d7-1fd3-43ee-8eab-6c770cb664b6) --> _NOTE: this should be pushed to V2_

**Comment by Benbaillou** [comment]
Work done or in progress as part of the following issues:

- [https://github.com/hackforla/food-oasis/issues/1114]
- [https://github.com/hackforla/food-oasis/issues/1113]
[https://github.com/hackforla/food-oasis/issues/1016]
