### ISSUE TITLE
Update Team Roster for Hack for LA site

### ISSUE THREAD

**Issue by lizagarrison** [hackforla/food-oasis#489]
### Overview
We need to update our team roster in order to update: 
1) the [Hack for LA Project Overview](https://www.hackforla.org/projects/food-oasis) --> MVP
2) the "Project Background" static page on the FOLA site --> V2

### Action Items
- [x] Compile a list of team members (past & present) in a new Google Sheet **or** in framework doc created by Bonnie (if already created)
- [ ] Save Google Sheet in [GDrive for Site Content](https://drive.google.com/drive/folders/1EYFMjBzHhvmLkAMIW4V4JAK8hxUvitHW?usp=sharing)
- [ ] Using LinkedIn, gather images of contributors and label image files with contributor name
- [ ] Upload all image files to the [GDrive for Site Content](https://drive.google.com/drive/folders/1EYFMjBzHhvmLkAMIW4V4JAK8hxUvitHW?usp=sharing) (first creating a new folder specifically for the images)

### Resources
- [Team Roster](https://docs.google.com/spreadsheets/d/1--JQ5WTLpQcBkSC5wbvQKFZ3Mw8OoHK9ToyXrymVGnM/edit?usp=sharing)
- [Existing Team Page on FOLA site](https://foodoasis.la/team/) 
- [Existing Hack for LA Project Overview](https://www.hackforla.org/projects/food-oasis)
- [GDrive for Site Content](https://drive.google.com/drive/folders/1EYFMjBzHhvmLkAMIW4V4JAK8hxUvitHW?usp=sharing)

**Comment by Benbaillou** [comment]
Question: is this issue still needed ?

Observation:
[Hack for LA Project Overview ](url) - the images and the names of the current team members is not updated

**Comment by staceyrebekahscott** [comment]
@fancyham Bryan- can you give some insight as to why you assigned yourself this issue and moved it into In Progress? I'd like to get a sense of what priority this should have at this time.

**Comment by fancyham** [comment]
@staceyrebekahscott, I don’t remember!  Looking at the date it might have been to try to find out how to add someone. Anyway,   I unassigned myself just now.

**Comment by staceyrebekahscott** [comment]
Assigning this issue to myself for now. FOLA needs an update on the HfLA page, the Wiki page, and a few other places. A new issue needs to be planned and I'm keeping this issue open as a reminder for myself to plan it out.

**Comment by staceyrebekahscott** [comment]
Created issue #1269 to address HfLA website update.
