### ISSUE TITLE
Download CSV of verified information for food rescue orgs

### ISSUE THREAD

**Issue by lizagarrison** [hackforla/food-oasis#505]
### Overview
Please pull a CSV file with the following fields for all org records that are currently verified ("approved" status"). This is a one-off request for @jpmikesell to provide this information to food rescue orgs as it currently stands.

Org Name
Org Phone
Org Email
Category
Org Address
Food Donation Hours
Donation Contact Name
Donation Phone
Donation Email
Donation Schedule
Four check boxes: pick up, frozen, refrigerated, perishable
Donations Delivery Instructions
Donation Notes

**Comment by entrotech** [comment]
Uploaded to the /07_DATABASES G-Drive folder as StakeholderDonations20200611.csv

**Comment by jpmikesell** [comment]
I'm sorry I did not mention that I need the COVID closed and the Permanently closed organizations. That's also very valuable to other partners and food rescuers.
