### ISSUE TITLE
Develop Product Roadmap

### ISSUE THREAD

**Issue by lizagarrison** [hackforla/food-oasis#506]
### Overview
Define goals and features for MVP and future product iterations. Powerpoint preferred for roadmap file format

**Comment by lizagarrison** [comment]
[Product Roadmap](https://docs.google.com/presentation/d/1Mmjej5dnPksIlqo_YlSE3j6Tkj_n3dVmlejo6D6xjhY/edit?usp=sharing) -- _IN DRAFT_

**Comment by Benbaillou** [comment]
see https://github.com/hackforla/food-oasis/issues/506 for development
