### ISSUE TITLE
Control what appears when you paste your sites link in social media sites

### ISSUE THREAD

**Issue by lizagarrison** [hackforla/food-oasis#509]
### Overview
When your website is shared on slack, facebook, twitter, etc. It should automatically display with an image and title instead of just the URL.

### Action items
Identify what to put in the following fields:
og:url
g:type
og:title
og:description     
og:image   
og:type (optional)
og:local (option)
using the standards set forth in the instructions.

Add content to header and test with the tool provided in the instructions.

### Instructions
[A Guide to Sharing for Webmasters](https://developers.facebook.com/docs/sharing/webmasters#markup)

**Comment by timmalstead** [comment]
@jpmikesell if you could get an image at 1200 pixels x 627 pixels and a paragraph describing FOLA that would be great
