### ISSUE TITLE
Add Authentication check to appropriate web api endpoints

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#516]
### Overview
Almost all of our web api endpoints with the exception of the /api/stakeholders and some of the /api/accounts endpoints should only be accessed by authenticated (logged in) users. Implement the authentication check.

### Action Items
Account Controller: Most are used by unauthenticated users, except:
/api/accounts GET: requires validated user.
/api/setPermissions POST: requires validated user with securityAdmin role.
/api/resetPassword POST: requires validated user (I think).

Category Controller:
/api/ GET does not require auth
/api/:id GET does not require auth
all others require auth and admin role

Distance Controller: not used
ESRI Controller: does not require auth

FAQ Controller: 
All GET endpoints do not require auth
All others require authenticated user and admin permission

Import Controller:
All require authenticated user and admin permission.

Load Controller:
All require authentication user and admin permission.

Neighborhood Controller:
does not require authenticated user

Stakeholder Controller:
GET /api/stakeholders unauthenticated
GET /api/stakeholders/dashboard auth with dataEntry, coordinator or admin role
GET /api/:id auth with dataEntry, coordinator or admin role
POST /api/csv auth with dataEntry or admin or coordinator role
POST /api auth with admin or coordinator role
PUT /api/:id auth with dataEntry, coordinator, or admin role
PUT /api/stakeholder/:id?needsVerificattion auth with admin or coordinator role
PUT /api/stakeholder/:id?assign auth with admin or  coordinator role
PUT /api/stakeholder/:id?claim auth with admin role
DELETE /api/:id auth with admin role

**Comment by jafow** [comment]
will use this issue to track on #514

**Comment by entrotech** [comment]
PR #514
