### ISSUE TITLE
Fix data persistence issues

### ISSUE THREAD

**Issue by timmalstead** [hackforla/food-oasis#527]
### Overview
we have two React data persistence issues that we are having problems with. Suggestions welcome for both!

### Action Items
- [x] figure out how to make open stakeholder info persistent on site refresh or navigating away from the map component
- [x] figure out how to pass down locationName string as an input value rather than a placeholder.

**Comment by timmalstead** [comment]
I don't have an idea of how to save/reload the stakeholder that is open and don't think figuring it out is the best use of our time, can we skip that step for MVP now that we have the placeholder issue fixed? @entrotech ?

**Comment by djbradleyii** [comment]
Reference [Issue #561](https://github.com/hackforla/food-oasis/issues/561) for updated details
