### ISSUE TITLE
Fix foodseeker ui cosmetic issues

### ISSUE THREAD

**Issue by timmalstead** [hackforla/food-oasis#536]
### Overview
fix minor cosmetic issues in map page and ui landing page

### Action Items
- [x] replace transparent area in split icons with white
- [x] fix filter buttons height on smaller device widths
- [x] add new split icon(s)
- [ ] also, change landing page and search bar tag lines to "Locate free food resources in Los Angeles."
- [x] review with UI/UX team

**Comment by entrotech** [comment]
Need review by UI/UX team

**Comment by tina-moh** [comment]
The tagline on the search 

- [ ] bar is "Your free food directory in Los Angeles" which is already set.
