### ISSUE TITLE
Organization Detail Panel Hours Display

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#538]
### Overview
When an organization's detail data is displayed on the left-hand panel of the food seeker ui, we need to show the week of month, if applicable next to the day of week. For example, if open on the Second Wednesday, the hours line should show "2nd Wed 9:00-12:00" or something similar. Also the hours lines should be sorted in a sensible, consistent order.

### Action Items

- [x] Implement changes
- [x] Get review from UI/UX 

- [x] UX/UI Approved

**Comment by entrotech** [comment]
Deployed on PR #548 for UI review.

**Comment by lizagarrison** [comment]
@motorcykey @entrotech is there an address/location we could search that would show an organization that has hours like this so we can review?

**Comment by entrotech** [comment]
On food-oasis-dev.herokuapp.com, search for 'Watts Labor Community Action Committee (WLCAC), 10956 S Central Ave, Los Angeles, California 90059, United States' and click on the detai for this organization. Back to @tina-moh

**Comment by tina-moh** [comment]
@entrotech Hi John this is what I got
<img width="1388" alt="Screen Shot 2020-07-08 at 11 41 24 AM" src="https://user-images.githubusercontent.com/56663382/86957744-0540ed00-c110-11ea-9a7c-944cedc66fb2.png">

**Comment by entrotech** [comment]
Ah, sorry, there was a data problem in development. Duplicate entries, and the correct one didn't have the right coordinates. This should be fixed in both dev or production site now.

**Comment by tina-moh** [comment]
UX/UI Approved
