### ISSUE TITLE
Make cosmetic changes to Home Page for MVP

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#546]
- [ ] ### Overview

Per meeting with design team on 6/23, we want to make a few minmal changes to the HOme page layout consisten with the home page EX1 from the [System Design Document Figma](https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/Fola-Design-System)

### Action Items

- [x] Subtitle under FOLA logo should be "Your free food directory in Los Angeles". Font Helvetia Neue, 20 pt(?) color Dark Gray
- [x] Caption above the text box should be "Locate free food resources in Los Angeles". Color White, style: Heading 2
- [x] Round the corners on the rectangles by 24px
- [x] Text should be Helvetica Neue
- [x] Get UI/UX review

- [x] UX/UI Approved

**Comment by entrotech** [comment]
Deployed on PR #548 for UI/UX review

**Comment by lizagarrison** [comment]
@entrotech per insights from usability testing, we'd like to **remove the "in Los Angeles" from the tagline** directly below the logo (the text highlighted in the screenshot below) as it's redundant with the reference to the "Los Angeles" in the call-to-action text on the blue background below it. The final tagline **on this page only** will say "Your free food directory". The tagline should not change on the header on any subsequent pages.
![Screen Shot 2020-07-07 at 2 59 43 PM](https://user-images.githubusercontent.com/63373671/86842696-d28ceb00-c062-11ea-8878-977f26113f36.png)

Also, why is "Los Angeles" in the call-to-action text (on the blue background) still showing up on 2 separate lines? Has the PR that fixes this not been deployed yet (I believe Marine was working on it)?

**Comment by entrotech** [comment]
Issue $558 is for the line break, @marinemekhakyan  is working on it.
I removed "in Los Angeles" from the subtitle.  Back to you, @tina-moh

**Comment by tina-moh** [comment]
Hi ,  #550 
iOS safari-MOBILE
https://food-oasis-dev.herokuapp.com/ IT has been updated in the landing page, not on other pages. (it supposed to be the updated) in all headers
https://food-oasis.herokuapp.com/. It has not been updated.

please let me know which address do I have to check.

**Comment by entrotech** [comment]
food-oasis-dev

**Comment by tina-moh** [comment]
UX/UI Approved
