### ISSUE TITLE
Changes to Organization Detail Panel

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#547]
### Overview
For stakeholders that are verified, want the Text "Data Updated on 4/9/2020" to appear as per figma file.

### Action Items

- [x] Add the "Date updated on ..." information to the ResultsSelectedStakeholder component.
- [x] For six required fields alwasys show the caption but print message that information is not provided. For other fields, if no information is available, hide the caption as well as the (empty) data.
- [x] Get UI/UX review

- [x] UX/UI approved

### Resources/Instructions
![image](https://user-images.githubusercontent.com/9939032/85460789-79985f80-b558-11ea-80e2-3e187711087f.png)

This is just for MVP - a more extensive re-design of the layout is slated for V2.

**Comment by entrotech** [comment]
The part about not showing the verfied date was my fault. When I changed the rules about what constitutes a verfiied record, I missed a bit of code that needed to be changed on the detail panel.

**Comment by entrotech** [comment]
There were already rules in place about what to show when various fields are missing. In particular, for the six required fields, it will show someghing like "No E-Mail address on record". For the other fields, like coivd notes, the label is not shown if the data is empty (though there were one or two bugs where that was not implemented right). So, for now I fexed a bug or two and am submitting for UI/UX review.

**Comment by entrotech** [comment]
Deployed on PR #548 for UI/UX review

**Comment by tina-moh** [comment]
AS I got here for Hours should say "information is not provided" ?
<img width="434" alt="Screen Shot 2020-07-02 at 10 31 23 PM" src="https://user-images.githubusercontent.com/56663382/86435111-07d8b800-bcb4-11ea-9b05-9424df717dfc.png">

**Comment by lizagarrison** [comment]
@entrotech see above for tina's comment(s)

**Comment by entrotech** [comment]
Merged PR#592. Available now on food-oasis-dev.herokuiapp.com

**Comment by tina-moh** [comment]
@entrotech UX/UI Approved
