### ISSUE TITLE
Refactor header and footer component

### ISSUE THREAD

**Issue by timmalstead** [hackforla/food-oasis#550]
### Overview
The new header and footer components done by marcello are needed to replace the old components on react

### Action Items
- [x] refactor header component based on marcello's designs
- [x] refactor footer component based on marcello's designs
- [x] remove latitude and longitude from footer
- [x] ui/ux review

- [x] UI/UX approved

**Comment by lizagarrison** [comment]
@tina-moh can you confirm that there are no changes that need to be made to the header/footer that could be considered launch blockers? 

The only thing that was brought up this morning was concerning which side of the screen the hamburger menu panel should come from, but that's now covered in issue #586

**Comment by tina-moh** [comment]
approved

**Comment by lizagarrison** [comment]
Update tagline to be "Your free food directory" in header @timmalstead

**Comment by timmalstead** [comment]
@tina-moh have made change and sent it to john. correct tagline should be reflected soon.

**Comment by timmalstead** [comment]
@tina-moh that has been merged into the dev build. should be available and correct

**Comment by tina-moh** [comment]
@timmalstead  
Hi Tim, iOS safari
https://food-oasis-dev.herokuapp.com/   IT has been updated in landing page, not on other pages. (it supposed to be the updated) in all headers
https://food-oasis.herokuapp.com/.  The same as before

please let me know which address do I have to check.

**Comment by timmalstead** [comment]
@tina-moh sorry, that's my mistake. it hasn't been updated on the dev site and i thought it had. will let you know when it is.

**Comment by timmalstead** [comment]
@tina-moh that has populated to the dev site

**Comment by tina-moh** [comment]
UX/UI Approved
