### ISSUE TITLE
Implement About Page Re-Design

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#551]
### Overview
Issue #480 specifies a re-designed About page. This issue is to implement the static About page based on the Figma File 

### Action Items

- [x] Implement as stand-alone HMTL/CSS to get the styles etc. working (this is for Marcello to get started).
- [x] Integrate with the React Application
- [x] Review design and funcntionality by Marcello and the UI/UX team.
- [ ] Revise, as necessary.

- [x] UX/UI Review

- [ ] UX/UI Approved

### Resources/Instructions
[Design System Figma](https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/Fola-Design-System?node-id=315%3A598)

**Comment by lizagarrison** [comment]
@entrotech @alvaram  it appears there's a bug on the Firefox version of the desktop site that's making the location icons show up really big (this is an issue pointed out / screenshotted by @jpmikesell, we were unable to reproduce it on other browsers, e.g. Chrome) 

![IMG_1484](https://user-images.githubusercontent.com/63373671/86844344-2ac4ec80-c065-11ea-9d8f-f5a259531916.JPG)

**Comment by lizagarrison** [comment]
@jpmikesell to provide updated copy on "contact us" CTA

**Comment by entrotech** [comment]
Just received updated copy from @jpmikesell

**Comment by alvaram** [comment]
![image](https://user-images.githubusercontent.com/3699720/87252411-a806ad80-c427-11ea-8017-b027b8e9aa13.png)
FYI there is double scroll issue happening on the static pages because of a class that's getting applied to the outer container, if you remove then the map gets affected, so I left as is for now
