### ISSUE TITLE
Implement the Donate Page Re-Design

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#552]
### Overview
Issue #480 specifies a re-designed Donate page. This issue is to implement the static Donate page based on the Figma File 

### Action Items

- [x] Implement as stand-alone HMTL/CSS to get the styles etc. working (this is for Marcello to get started).
- [x] Integrate with the React Application
- [ ] Review design and funcntionality by Marcello and the UI/UX team.
- [ ] Revise, as necessary.

### Resources/Instructions
[Design System Figma](https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/Fola-Design-System?node-id=315%3A598)

**Comment by tina-moh** [comment]
CTA Buttons don’t work

**Comment by lizagarrison** [comment]
@alvaram @entrotech please update "Donate" link to https://www.codeforamerica.org/donate

**Comment by entrotech** [comment]
Will work on this when all links are available.

**Comment by lizagarrison** [comment]
Updated - all links are now available

**Comment by entrotech** [comment]
Completed on PR #588 - It's available in food-oasis-dev.herokuapp.com now.
