### ISSUE TITLE
Implement the FAQ Page Re-Design

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#553]
### Overview
Issue #480 specifies a re-designed statuc FAQ page. This issue is to implement the static FAQ page based on the Figma File 

### Action Items

- [x] Implement the re-design
- [x] Review design and funcntionality by Marcello and the UI/UX team.
- [x] Revise, as necessary.

- [x] UX/UI approved

### Resources/Instructions
[Design System Figma](https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/Fola-Design-System?node-id=315%3A598)

**Comment by lizagarrison** [comment]
@tina-moh are there any design changes that need to be made to the "About" page or can we consider this approved?

**Comment by tina-moh** [comment]
I approve other than hamburger menu that is already mentioned in other issue.

**Comment by entrotech** [comment]
Since Tina approves, I'm closing this one.
