### ISSUE TITLE
Make Search Box and Button on the Map page look exactly like Figma File

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#558]
- [ ] ### Overview

Make adjustments to the appearance of the Search Bar on the Map Page. This is just a cleanup for the MVP release, a more significant re-styling is scheduled for the V2 release. We don't have an exact wireframe to work from, This is based on interpolation between the existing Figma file, feedback for usabilitiy testing and an effort to make things consistent.

### Actions
- [ ] Adjust the line break so "Los" and "Angeles" are on the same line.
- [x] For consistency with the Landing Page and other controls, the Location TextBox should not have a border, and should have the left top and left bottom corners rounded, but the right top and bottom corners square.
- [x] The size and aspect ratio of the magnifier button should match its apperance on the Landing Page.
- [x] The vertical size of the distance drop-down, filter buttons and location text box and button should all be the same (at least on wide devices).
- [x] The caption on the Verfied Data button should be changed to Updated Data.
- [x] Review by UI/UX team.
- [ ] UX/UI approved

### Resources/Instructions
Current Appearance:

![image](https://user-images.githubusercontent.com/9939032/85953175-52101100-b923-11ea-847b-4bb5e78e6a23.png)

What it should look like from Figma https://www.figma.com/file/QgM5vS8NhDNXhknnFpu2Hn/FOLA-DESKTOP?node-id=26%3A394 Note that this isn't quite what's specified above.

![image](https://user-images.githubusercontent.com/9939032/85953189-6fdd7600-b923-11ea-85a0-1dfa2e487799.png)

**Comment by tina-moh** [comment]
1. Adjust the line break so "Los" and "Angeles" are on the same line. **Is not adjusted**

**Comment by tina-moh** [comment]
**On "landing page" The  Hamburger menu is located at the top right but the menu opens on the left side**

**Comment by tina-moh** [comment]
3. On the landing page, the search window on top right is not on a straight line
<img width="533" alt="Screen Shot 2020-07-02 at 10 13 27 PM" src="https://user-images.githubusercontent.com/56663382/86434465-6c931300-bcb2-11ea-99d4-2f53d5a9e86c.png">

**Comment by tina-moh** [comment]
4- **Chrome Browser** on landing page the search box is not centered  and the hamburger menu does not show up randomly
<img width="1430" alt="Screen Shot 2020-07-02 at 10 51 24 PM" src="https://user-images.githubusercontent.com/56663382/86436194-a403be80-bcb6-11ea-84bb-5bea7300fd8f.png">

**Comment by tina-moh** [comment]
@entrotech @lizagarrison @marinemekhakyan  I'm checking again now on Mobile Safari 
so the issues are not resolved (7/6/20) 3:40 pm

I added UX/UI approved to check points to separate UX/UI review and resolved and got approved UX/UI
![IMG_EFA55349CDF0-1](https://user-images.githubusercontent.com/56663382/86851735-509fc080-c068-11ea-97d7-e4a2f2a593d5.jpeg)
