### ISSUE TITLE
Fix bug with default filter selection on Map Page

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#561]
### Overview
When you first get to the Map Page, either from the landing page or the main menu, the filter buttons should be set to the default values:
Distance: 5 mi
Food PantriesL off
Meal Programs: off
Updated Data: off
In many cases these are not the default settings when you get to the page - it seems that the filter may be "remembering" past settings somehow.

### Action Items

- [x] Fix.
- [x] Get UI/UX review

- [x] UX/UI approved

**Comment by tina-moh** [comment]
1. when you get to Map Page the "**Food pantries "** Filter button is on

**Comment by tina-moh** [comment]
the issues exist. 6/7/20 2 pm

**Comment by djbradleyii** [comment]
Hi Tina, 

Can you explain what issue you are seeing that still exists?

**Comment by tina-moh** [comment]
Hi Tim, 
these are my screenshots now Mobile iOS Safari/
I tried  https://food-oasis-dev.herokuapp.com/  and https://food-oasis.herokuapp.com/
![IMG_3F9AD8B836A8-1](https://user-images.githubusercontent.com/56663382/86852401-8ee9af80-c069-11ea-818a-ebc4e90b3dfa.jpeg)
![IMG_8391](https://user-images.githubusercontent.com/56663382/86852409-91e4a000-c069-11ea-892d-6bd33611cf4d.PNG)
![IMG_8392](https://user-images.githubusercontent.com/56663382/86852414-94df9080-c069-11ea-9ce5-0e28c448a8af.PNG)

and let me know do I have to check on which address, dev.herukoapp or https://food-oasis.herokuapp.com/
Thanks

**Comment by entrotech** [comment]
@tina-moh  and @djbradleyii I released this change in both the dev environment (food-oasis-dev.herokuapp.com) and production (food-oasis.herokuapp.com) - can you both play with it and make sure it is working the way you want?

**Comment by djbradleyii** [comment]
Will do.

**Comment by djbradleyii** [comment]
Hi John, 

I am sorry to have made this more confusing, but I sent a Pull Request ( https://github.com/hackforla/food-oasis/pull/602 ) because after testing, I noticed that there were a couple of updates that were required. Everything should work as expected after you merge 602. Thank you.

**Comment by tina-moh** [comment]
@entrotech @djbradleyii UX/UI Approved. Thx
