### ISSUE TITLE
Make Adjustment to organization list and detail displays

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#562]
### Overview
Cosmetic changes to the Organization Results list and Organication Detail panels on the Map Page.

### Action Items

- [x] When showing open times, add a space between the minutes and meridian, For example 10:00 AM-12:30 PM, instead of 10:00AM-12:30PM
- [x] When showing a temporarily or permanently closed organization, the categories listed occasionally show up in red or blue, they should always be gray on the list.
- [x] For an open organization, it will sometimes have categories other than Food Pantry or Meal Program, such as Shelter or Other. These categories should be displayed in black (not blue or red), but still italicized.
- [x] Get UI/UX review

- [x] UI/UX approved

**Comment by timmalstead** [comment]
ready for ui/ux review when deployed

**Comment by tina-moh** [comment]
1. When showing open times, add a space between the minutes and meridian, For example 10:00 AM-12:30 PM, instead of 10:00AM-12:30PM " **Not resolved**"
