### ISSUE TITLE
Improve Postgres Connection security

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#563]
### Overview
The postgres connections are connecting to the dev and prod databases using a login with sys admin rights, and a weak password.

### Action Items
For the Production Database:

- [x] Create a postgres role `readwrite` that only has the permissions required by the application. (Not the ability to created or delete databases or schemas, for example).
- [x] Create a user named `appuser` that is granted the above role and the ability to login with a secure password.
- [x] Change the deployed production app to use the appuser user and new password, and store the password in a secure place.
- [x] Change the password for the `postgres` user to a strong one, and stored the password in a secure place.

For the Development Database:

- [x] Create a postgres role `readwrite` that only has the permissions required by the application. (Not the ability to created or delete databases or schemas, for example).
- [x] Create a user named `appuser` that is granted the above role and the ability to login with a secure password.
- [x] Change the deployed development app to use the appuser user and new password, and store the password in a secure place.
- [x] Update the .env file with the updated credentials and notify the developers to updated their .env file.
- [x] Change the password for the `postgres` user to a strong one, and stored the password in a secure place.

### Resources/Instructions
https://aws.amazon.com/blogs/database/managing-postgresql-users-and-roles/

**Comment by jafow** [comment]
@entrotech this looks like a good list. An added layer of security we should work towards would be not exposing the db to the open internet, rather running it in a private VPC. 

when and if we move the fola backend to AWS it would be a sensible time to set that up. 
For now I think the list you've outlined above is great improvement. :+1:
