### ISSUE TITLE
Requested Changes from Usability Testing - Map Page

### ISSUE THREAD

**Issue by lizagarrison** [hackforla/food-oasis#585]
### Overview
The map page takes up too much space on the smaller version of the screen layout (i.e. for mobile phones and smaller desktop windows) and it's unclear to the user that there's a list of results below the map. Can we adjust the size of the map or add a responsive breakpoint so that the viewport shows the first result at the bottom of the screen?

**Screenshot of current viewport on iPhone X / Google Chrome:**
![IMG_1481](https://user-images.githubusercontent.com/63373671/86839441-ab341f00-c05e-11ea-8012-05e30cc31730.PNG)

**Another video demonstrating the confusion around the listing of orgs below the map (as well as some difficulty scrolling to get back to the map location):** [Link to screen recording](https://drive.google.com/file/d/1DCZdZFJYvdQH3-IgqT-oElRTjBxURjIN/view?usp=sharing)

**Proposed idea of adjusted design (@tina-moh):**
![IMG_1483](https://user-images.githubusercontent.com/63373671/86840268-c6ebf500-c05f-11ea-91c4-580cab391ffd.JPG)

### Action Items
- [x] Resize map or add responsive breakpoint on "mobile" version so that the map doesn't take up the entire screen
- [x] Show at least the first result on the map screen without requiring the user to scroll to see it
- [x] Notify design team when changes are ready for review
- [x] Design team approval

**Comment by timmalstead** [comment]
- [ ] At least the first listing needs to be visible on mobile devices and smaller desktop windows
- [ ] hold until pr resolving cosmetic header issues from @marinemekhakyan is merged

**Comment by timmalstead** [comment]
@lizagarrison @entrotech Changed map screen to take up less room in mobile view. Please note this mean we need to rethink the rest of the layout of the mobile page, specifically scroll overflow for the list and/or pan scroll on the map.
Please advise.

**Comment by entrotech** [comment]
@tina-moh @lizagarrison  Need to review.

**Comment by lizagarrison** [comment]
looks great! @entrotech @timmalstead approved
