### ISSUE TITLE
Requested Changes from Usability Testing - Hamburger Menu

### ISSUE THREAD

**Issue by lizagarrison** [hackforla/food-oasis#586]
### Action Items
- [x] Remove "Volunteer Register" link from menu completely (users will now access this screen via the "Register" link on the Volunteer Login page)
- [x] Move "Volunteer Login" to the exact spacing where the "Volunteer Register" link was previously to maintain accurate spacing
- [x] Since hamburger icon is located on the upper right of the screen for both desktop and mobile, **hamburger menu panel should slide out from right instead of left.**

Current design:
![Screen Shot 2020-07-07 at 2 53 47 PM](https://user-images.githubusercontent.com/63373671/86841854-b2106100-c061-11ea-8e33-015461b68af1.png)

**Comment by timmalstead** [comment]
- [ ] At least the first listing needs to be visible on mobile devices and smaller desktop windows
- [ ] hold until pr resolving cosmetic header issues from @marinemekhakyan is merged

**Comment by entrotech** [comment]
@timmalstead I did the first two parts - be sure to merge from the develop branch into yours to get these.

**Comment by timmalstead** [comment]
@entrotech Using the code where you made the first two changes, I have edited the drawer so that it is anchored to the right side of the screen. I think this should close the issue.

**Comment by lizagarrison** [comment]
Hi @timmalstead @entrotech - it looks like these issues were addressed but for some reason now a "Volunteer" link is showing up on the hamburger menu that didn't previously exist --> can this be removed from the menu?

![image](https://user-images.githubusercontent.com/63373671/87486134-cb805280-c5f7-11ea-8474-c341bc9caad9.png)

**Comment by timmalstead** [comment]
@lizagarrison @entrotech that's not too hard a fix, but what i'm also noticing is that on the latest dev build, the volunteer link below donate is missing as well. let's see who touched that last at the meeting tonight and go from there.

**Comment by timmalstead** [comment]
@lizagarrison @entrotech oh, nevermind. i see that was on purpose. quick fix and i'll push that in a moment.

**Comment by lizagarrison** [comment]
@entrotech @timmalstead thanks for the fix! looks good in production
