### ISSUE TITLE
Change Map Page svg images

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#603]
### Overview
On issue #584, @JordanRomanoff provided new graphics for the various icons on the Map page components

### Action Items

- [x] Replace the images with the new ones.
- [x] UI/UX review
- [x] UI/UX approval

### Resources/Instructions
Issue #584 - see comment with link to Jordan's dropbox file with icons.

**Comment by lizagarrison** [comment]
Please also update any red text/components pertaining to meal programs to the new orange color (#E57109)

**Comment by timmalstead** [comment]
the svg map icons provided were a bit too small and also had a transparency in the areas where solid white should be. am also posting on #584

**Comment by JordanRomanoff** [comment]
I've updated the pins that had transparency in them. Did you need the SVGs in a specific size? I'd be happy to scale them up. https://www.dropbox.com/sh/0j0qumwlahhyfgh/AADAo104awh1F8DtD9nShzPda?dl=0

**Comment by timmalstead** [comment]
@JordanRomanoff @paigelizabeth it's design's call. i can make it work either way.

**Comment by entrotech** [comment]
PR #607

**Comment by lizagarrison** [comment]
@timmalstead is there any way we can make the pop-up boxes that appear when you click on an org pin closer to the pin it relates to?

![image](https://user-images.githubusercontent.com/63373671/87490981-39327b80-c604-11ea-997d-ab763e118982.png)

^ e.g. "Ananda Marga of LA Inc." looks like it's showing up above and to the left of the location pin for that org -- can we center it above the pin?

**Comment by timmalstead** [comment]
@lizagarrison huh, that shouldn't be but i think i might know why it is. i will fix that.

**Comment by lizagarrison** [comment]
@timmalstead @entrotech looks good in the dev environment!

**Comment by entrotech** [comment]
PR #611
