### ISSUE TITLE
Fix nested scrolling in mobile results page

### ISSUE THREAD

**Issue by rblaz001** [hackforla/food-oasis#653]
### Overview
Results page on mobile extends beyond view-port size. This means we end up with an outer scroll bar for the page and an inner scroll bar for the list within the page.

### Action Items
- [ ] Modify styling so the outer scroll bar is no longer necessary

Example of current issue

![Screenshot from 2020-08-27 20-58-13](https://user-images.githubusercontent.com/35281980/91520605-8dd74080-e8aa-11ea-9ade-aa81a0b483b0.png)

![Screenshot from 2020-08-27 20-58-19](https://user-images.githubusercontent.com/35281980/91520613-90399a80-e8aa-11ea-91d7-fbf9143ce2e2.png)

**Comment by bbovenzi** [comment]
<img width="388" alt="Screen Shot 2020-10-20 at 9 40 05 PM" src="https://user-images.githubusercontent.com/4600967/96666488-d9dbba00-131c-11eb-9b8c-a699f6adecee.png">

Updated, only happens on mobile list view now.
