### ISSUE TITLE
Implement a California Food Oasis Application

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#656]
### Overview
Enhance Food Oasis to support multiple regions/tenants. The immediate need if to create a separate food-seeker site for all of California (except LA County) that starts with an empty database of organizations. The terms "tenant" and "region" are used interchangeably for now, since the immediate usage is to allow expansion into different geographic regions, but we forsee expansion of the application in other dimensions that do not necessarily correspond to regions (for example, variations that focus on other types of organizations such as homeless shelters, school lunch programs, etc.), where the more generic term "tenant" is more appropriate, if a bit moe abstract. 

To facilitate maintenance and code sharing, the idea is to make Food Oasis a multi-tenant application, where the organization lists for each region  are in the same database, but segregated by a tenantId field that associates each organization with a region. Select components of the UI (such as the logo and the static site pages) also need to be swapped out based on region, as appropriate. Then each region will have it's own url, and code will detect which region to use based on the url accessed and apply the appropriate UI components and execute queries for the food seeker UI for the corresponding tenantId.  

For now (and maybe the long term), the Volunteer and Admin UI will allow viewing organizations from all regions, with an added criterion on the Dashboard criteria to select a Region.  This allows the current corps of admins and volunteers to work on both regions.  This is a variation of a concept we've discussed before where volunteers might be organized by neighborhood councils, but expands the idea that a central team of volunteers can be allowed to validate organizations across the various regions/tenants.

Thsi is an incremental first step in growing Food Oasis into a full-blown multi-tenant application, and many aspects described below will definitely require further refinement.

### Action Items

- [x] Add a tenant table to the database that contains records for the two short-term tenants: Food Oasis LA and California Food Oasis.
- [x] Add a tenant_id column to the stakeholder, stakeholder_log and stekholder_best tables, and set up a foreign key to the tenant table, initializing all existing records to the Food Oasis LA tenant.
- [x] Modify the client application to deduce the applicable tenantId based on either an environment variable (for development) or the hostname (for production).
- [x] Modify the client logo to swap out a different logo for FOCA than for FOLA.
- [x] Create separate copies of the static pages About, Donate and FAQ for FOCA, and swap them in when the tenant is FOCA.
- [x] Modify the Food Seeker web api calls to automatically apply the FOCA tenantId to queries for FOCA.
- [x] Modify the Verification Dashboard to support a "Region" critieria that allows the administrator to selectively query organizations that belong to a specific region or to either region.
- [x] Modify the New Stakeholder feature to add the stakeholder to the effective tenantId when a new stakeholder is created.

**Comment by entrotech** [comment]
@jpmikesell I need a different Logo to use for "California Food Oasis" than the one we are using for FOLA.  I know you have been working on an updated logo for FOLA as well that hasn't made its way into the app. I think you were holding off on the "new FOLA logo, waiting for related design decisions. What would you like to do?

We also need to have slightly different copy for the About page (and maybe the Donate and FAQ pages) for the California region.  Can we get somebody to work on that?

**Comment by jpmikesell** [comment]
Here is the new Logo for CA



I’ll see if I can get our copywriter to work on the static content.



On Aug 29, 2020, at 10:00, John Darragh <notifications@github.com> wrote:


@jpmikesell <https://github.com/jpmikesell> I need a different Logo to use for "California Food Oasis" than the one we are using for FOLA. I know you have been working on an updated logo for FOLA as well that hasn't made its way into the app. I think you were holding off on the "new FOLA logo, waiting for related design decisions. What would you like to do?

We also need to have slightly different copy for the About page (and maybe the Donate and FAQ pages) for the California region. Can we get somebody to work on that?

**Comment by foodoasis** [comment]
[new logo](https://drive.google.com/drive/u/0/folders/1S6NJ9VfQ7uM49-i8XjJpEL0gNguFKzO9)
![Food Oasis CA](https://user-images.githubusercontent.com/70418784/91900083-faf42880-ec52-11ea-8089-49567c0cd339.jpg)

**Comment by entrotech** [comment]
@jpmikesell Do you have this logo in svg format?  The aspect ratio is much more square than the existing FOLA logo was, so it' going to be pretty unreadable in the header and footer unless we make some adjustments to the layout, but will look fine on the landing page.

**Comment by jpmikesell** [comment]
I do but Tina and Jordan want to work on it for a few more hours. :-(



On Sep 1, 2020, at 15:05, John Darragh <notifications@github.com> wrote:


@jpmikesell <https://github.com/jpmikesell> Do you have this logo in svg format? The aspect ratio is much more square than the existing FOLA logo was, so it' going to be pretty unreadable in the header and footer unless we make some adjustments to the layout, but will look fine on the landing page.
