### ISSUE TITLE
Modify Food Seeker UI to switch between Map and List View of results

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#677]
### Overview
The map page currently only uses about 1/3 of the screen to show the map and 1/3 of the screen to simultaneiously show the list on mobile devices. Come up with a way to switch back and forth between list and map views, where the list or map occupies at least 2/3 of the screen. On a Desktop screen width, it should still show the list and map side-by-side.

### Action Items
TBD

### Resources/Instructions
TBD

**Comment by bbovenzi** [comment]
I can take this one.

On everything but desktop sizes we add a button to switch between showing list and map view?
