### ISSUE TITLE
Implement Food Type Checkboxes

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#678]
### Overview
Food types should be entered for an organization as checkboxes for the specific types: 

- Bakery
- Dry Goods
- Produce
- Dairy	
- Prepared Food	
- Meat

We want to change the Organization Edit Form's Food Type input from a free-form text entry field, to a set of six checkboxes for the above food types, then display the food types on the organization detail panel in the Food Seeker UI.

### Action Items

- [x] Add columns to the stakeholder and related tables for these checkboxes
- [x] Modify the stored procedures and trigger accordingly.
- [x] Add the checkboxes to the OrganizationEdit form.
- [x] Modify the Percent Complete metric to include confirmFoodTypes as a 7th critical field.
- [x] Display the Confirm Food types as an additional check box column on the Admin Dashboard.
- [x] Do not need to be able to search by these food types from the dashboard or food seeker UI (yet)

**Comment by bbovenzi** [comment]
@pageignited can you link to where in figma this is?
