### ISSUE TITLE
Implement Page for Admin to View Suggestions

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#679]
### Dependencies
#935 - Map the process
#936 - Design the process

### Overview
A "Suggest an Edit" feature was implemented which records end-user suggestions in a suggestion table.  We need to provide a page for an admin to view and process these suggestions.

### Action Items

- [x] Write a SQL suggestion searxh query that searches the suggestion table by appropriate criteria.
- [x] Make an Express/Node endpoint /apio/suggestions/search that executes this SQL and returns results as JSON, the enpoint should require the calling user to be logged in as a user with the admin role.
- [x] Add a menu item to the main menu that is only available to admin users and have it link to...
- [ ] A page that allows the user to query the suggestions and display them in a list. 
- [ ] The user should be able to select a suggestion and edit the admin note and update the status to indicate whether the issue is "in process" or "closed" and save the change.
- [ ] For saving changes, you will need to provide additional endpoints and sql queries to update the table.

**Comment by crisbnp** [comment]
Hi @entrotech! Is there a visual what the page (suggestion list) should look like?

**Comment by ktjnyc** [comment]
@entrotech do you need an issue created for a page mock-up for this one?

**Comment by ktjnyc** [comment]
Created 2 issues as dependencies for this:
Map out process #935 
Design process #936

I'm going to move this to ice-box so that it waits until the other two are complete.  This will be updated when it's ready for coding.

**Comment by entrotech** [comment]
Checked with @hanapotski on tuesday 9/7/21. She said that she and @webdevangelie were going to start working on this soon.

**Comment by gigicobos** [comment]
@entrotech I tried submitting a Correction (Google Chrome) as a food seeker on the test site and this error message showed up:
![Screen Shot 2021-09-23 at 10 20 36 PM](https://user-images.githubusercontent.com/66035169/134608925-ef173ff1-077c-498f-974f-cee7fcabb154.png)

**Comment by hanapotski** [comment]
@entrotech I have this PR up > https://github.com/hackforla/food-oasis/pull/1035

**Comment by fancyham** [comment]
Hi folks, is this issue completed?  I see it’s in the ‘done’ column of the Project Management [kanban board](https://github.com/hackforla/food-oasis/projects/8) but is still open — is it actually complete?

**Comment by staceyrebekahscott** [comment]
Re-closing this issue as all associated PRs appear to be resolved and closed.
