### ISSUE TITLE
Search text reordering

### ISSUE THREAD

**Issue by pageignited** [hackforla/food-oasis#689]
Acceptance criteria:

Reorder text in the input box so “zip code” is not the last  text

Display text in the input box needs to display in this order “Search by address, zip code, or neighborhood”

See Image:
https://drive.google.com/file/d/1kglzvjupDn5Wat3v6bJEuwMCU_P-4Zk4/view?usp=sharing

**Comment by entrotech** [comment]
@pageignited  Why does it matter that zip code is not listed last?  And why do we include "neighborhood" - the Geocoder may or may not know anything about official neighborhoods, so seraching by neighborhood is hit-or-miss.

**Comment by entrotech** [comment]
The issue was that the text was too long to display on mobile devices, and the last few words were cut off. The location search doesn't search by neighborhood anyway, so I made it "Search by address or zip code".

**Comment by pageignited** [comment]
Perfect thanks
