### ISSUE TITLE
Foodseeker organization list view card

### ISSUE THREAD

**Issue by pageignited** [hackforla/food-oasis#695]
As a foodseeker I want to glance at the highlights of an organization's information so that I know if this place offers what I need.

Acceptance Criteria:

I can view the organization's name

I can see the type of category it is “food pantry, meal program, food bank, etc”

I can see if the location is open or closed

I can see how much time is left before the location closes

I can see a logo icon of the type of service they offer “Meals, Pantry or both”

I can see how many miles I am from the location 

I can see the “Food Types” the location offers

I can click to make a phone call to the organization

I can click to get directions to the location 

I can click to see the full details of the location

Note:

See the  image
https://drive.google.com/file/d/1chNH6edQxBw_7rEwADyiFbE1rJZMcJ9Z/view?usp=sharing

**Comment by bbovenzi** [comment]
Currently we have no validation on phone numbers so the frontend will also have to parse out all valid phone numbers and turn them into separate links and leave any non-phone number data ("and" "ext: 3627", etc) to be plaintext

**Comment by pageignited** [comment]
Yeah, I remember that now. I know I did see some organizations with ("and" "ext: 3627") that's fine if we make it in plaintext.
