### ISSUE TITLE
Display only verified map pin drop icons

### ISSUE THREAD

**Issue by pageignited** [hackforla/food-oasis#697]
As a foodseeker I only want to see verified location on the map so that I don’t waste my time visiting a location that is not correct.

Acceptance Criteria:

When displaying “pantries and  meal location” the pin drops on the map only can  display  if they are verified by the food oasis admin

When any location that has not been fully verified by the food oasis admin.  The pin drops should not display on the map or list view.

Only active fully verified  “Meal Program and Food Pantries” pin drop icons can display on the map view

See Image
https://drive.google.com/file/d/1luYpL0HjLOO5nDwMCIh8GjF4YoJkb_g3/view

**Comment by bbovenzi** [comment]
How about we change the opacity and layering of the pins? (Temporarily closed locations will be transparent and will always show up behind open locations). Therefore we can still show the data we have without distracting food seekers from getting to their destination.

**Comment by pageignited** [comment]
I'm fine with that as long as it will not distract the food seekers.
