### ISSUE TITLE
Display open now locations in list view first

### ISSUE THREAD

**Issue by pageignited** [hackforla/food-oasis#698]
As a foodseeker, I want to see all open locations first in a list view,  so that I do not have a scroll through all the locations to find what is open. 

Acceptance Criteria:

When in the “list view” it needs to display a filtered view of all open locations first

When the “list view” displays it needs to display a filtered view in chronological order of locations closing <= 30 minutes first.

When the location display in chronological order we need to also display the open place closed to a food seeker current location

Need displaying text for locations still open but closing soon  like this  “Closes in XX minutes”

See Image
https://drive.google.com/file/d/1chNH6edQxBw_7rEwADyiFbE1rJZMcJ9Z/view

**Comment by fancyham** [comment]
This is being addressed in 
- #947 

with the ‘open now’ filter
