### ISSUE TITLE
Change map pin colors on map view based on time and active location

### ISSUE THREAD

**Issue by pageignited** [hackforla/food-oasis#699]
As a food seeker, I want to see different color pin colors so at a glance I click on the location based on the color

Acceptance Criteria

When any category i.e “food pantry or meal program” that is still open needs to display on the map as a green pin icon to a food seeker.

When a food seeker clicks on any color map pin icon for that map icon to display as red and it becomes the active location for them.

When the map pin icon of a location that is not active or open to display in the current orange or blue color based on if they are a “food pantry or meal program”

Notes

See image 

https://drive.google.com/file/d/1luYpL0HjLOO5nDwMCIh8GjF4YoJkb_g3/view?usp=sharing - Connect to preview

**Comment by bbovenzi** [comment]
Same suggestion as #697 in terms of opacity and layering

**Comment by pageignited** [comment]
I'm good with that.
