### ISSUE TITLE
Map and List view to display only open location when selected

### ISSUE THREAD

**Issue by pageignited** [hackforla/food-oasis#700]
As a food seeker, I want only to see open locations map or list view when the open button is selected so I get a list of current active open locations.

Acceptance Criteria

When the food seeker selects the  “open” button the  “map view” to  display a filter view of only  green color pin markers for locations currently open

When the food seeker selects the “open” button in the “list view”  to displays a filter view of only locations that are open in chronological order.

Note

See Image
https://drive.google.com/file/d/1luYpL0HjLOO5nDwMCIh8GjF4YoJkb_g3/view

**Comment by entrotech** [comment]
Obsolete
