### ISSUE TITLE
Allow top nav filtering CTA buttons to be turned on or off

### ISSUE THREAD

**Issue by pageignited** [hackforla/food-oasis#701]
As a food seeker, I want to be able to turn on and off the button filter, so I can get back to the default filer setting if I want.  

Acceptance Criteria

When the food seeker selects “Pantry, meals, open” CTA to turn on the filter results it needs to display in the results.

When the food seeker selects “Pantry, meals, open” CTA to turn off the filtered results it needs to return to the default view.

**Comment by bbovenzi** [comment]
We should probably expand this issue to include all the filter changes. Right now we have 2 buttons for meals and pantries, a dropdown for the radius and a button to toggle map/list view on mobile.

We need to add a button to show only open or include temporarily closed locations, right?

I feel like if we update search results when a user modifies the map then the radius dropdown becomes unnecessary. See #710

**Comment by Benbaillou** [comment]
issue solved - feature already available on the website
