### ISSUE TITLE
Map view organization quick view

### ISSUE THREAD

**Issue by pageignited** [hackforla/food-oasis#702]
As a food seeker when I click on a map location pinpoint I need a quick view to display so I see that location basic info.  

Acceptance Criteria

When the food seeker displays the map view for the first time need to display “List View” CTA at bottom of the screen

This “List View” CTA  if selected it will display all location in the list view

**Comment by staceyrebekahscott** [comment]
This issue was marked as Done on in Dec 2020, but it was not properly closed. Labels were added after this point, even though issue was marked Done. Closing issue.
