### ISSUE TITLE
Add Google tag manager script tag on all site pages 

### ISSUE THREAD

**Issue by pageignited** [hackforla/food-oasis#703]
As food oasis admin I need the ability to add tracking pixels to the site when I need to, so I don't rely on devs to do this.

Acceptance Criteria:

Need to add google tag manager  script tags to all pages
Enable the Preview and Debug mode in Google Tag manager to see if script tags are firing
Check Google Tag Assistant to see if tags are firing

Notes
Script tags need to be placed in two spots on all pages. 

1. Paste this code as high in the < head > of the page as possible:

2. Additionally, paste this code immediately after the opening < body > tag:

**Comment by bbovenzi** [comment]
See here to set up: https://firebase.google.com/docs/analytics/get-started?platform=web

**Comment by entrotech** [comment]
Here is an article about deciding between Google Analytics and Firebase: https://www.bounteous.com/insights/2018/02/20/choosing-between-firebase-and-google-analytics-sdks-app-tracking/

**Comment by pageignited** [comment]
@entrotech @bbovenzi  That was a good read. John, you might want to read this one too https://www.webfx.com/internet-marketing/firebase-vs-google.html

So Firebase seems great for mobile apps, where GA is best for the website. Also, if we are looking to capture events, then Firebase is better. GA is more session-oriented to track a user's path through the site and then use that to make a better experience. It seems if we have apps, then Firebase would be better, but since we have just a website, GA seems better.  We can talk about this Tuesday.

**Comment by entrotech** [comment]
PR #775

**Comment by sameergautam** [comment]
@pageignited it looks like there was a PR merged in Dec. What remains in this issue? Does it pass your acceptance criteria or are there any next steps to be carried out? Please define them if there are any.

**Comment by pageignited** [comment]
Hi Sameer,

yes is ticket pass my AC
