### ISSUE TITLE
The button design for "Call, directions and details "is not in the correct style

### ISSUE THREAD

**Issue by pageignited** [hackforla/food-oasis#732]
The current new 3 buttons are not following the design talk about in a prior ticket.  The buttons get too much visibility, they need to have a more visual balance.  You can find the button style here. We need to replace the current blue one for these
<img width="477" alt="buttons" src="https://user-images.githubusercontent.com/22136920/95297923-17761880-0830-11eb-8711-f50ac0b114c3.png">

https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/Fola-Design-System?node-id=0%3A1
@bbovenzi @entrotech

**Comment by bbovenzi** [comment]
If the figma designs are finalized then it's probably worth to do a full design pass on the app.

My only concern here is how much space the icon+text button takes up on mobile. On small screen sizes we should probably drop the logo or the text.

**Comment by pageignited** [comment]
@bbovenzi @entrotech 

Ok, that makes sense. What if for now we just turn those current buttons into text link until the new designs are completed? I'm waiting for Jenny to sign off before you make any changes. Once I hear back I'll let you know the direction.

**Comment by pageignited** [comment]
@bbovenzi So I spoke with Jenny and she is fine with either of these two solutions.

1. What's the lift to remove the blue but keep the same button shape as you have now. Make the button white with gray text and  a gray outline with no  icon inside the button. 
2. Remove the button blue and just make them blue text links until we get the final designs with new button look. 

Let me know your thoughts
