### ISSUE TITLE
Bug: When you type a zip code in the location search text box, then use backspace to delete it, you can't delete the first character.

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#746]
### Overview
REPLACE THIS TEXT -Text here that clearly states the purpose of this issue in 2 sentences or less.

### Action Items
- [ ] Fix

### Resources/Instructions
From here, the backspace key will not delete the "L":

![image](https://user-images.githubusercontent.com/9939032/96655898-7db07000-12f3-11eb-868f-00eb5c8a574c.png)

**Comment by Gautam-Arora24** [comment]
Shall I give a try to this issue?

**Comment by bbovenzi** [comment]
@Gautam-Arora24 sure! feel free to join https://www.hackforla.org/projects/food-oasis and we can set you up with all the environment variables you need to get the project running

**Comment by Gautam-Arora24** [comment]
I need an invitation to your Slack workspace

**Comment by bbovenzi** [comment]
@Gautam-Arora24 Here's the link for slack on the hackforla website. If that doesnt work @entrotech should be able to help you out

**Comment by Gautam-Arora24** [comment]
Sure... I just checked Slack and it showed that the administrator needs to send an invitation to join the workspace

**Comment by entrotech** [comment]
Fixed in PR #749,  @Gautam-Arora24 Do you want to join Hack for LA? If so, use the link @bbovenzi posted above, and we'll get you set up. Thanks!

**Comment by Gautam-Arora24** [comment]
I would love to join Hack for LA

**Comment by bbovenzi** [comment]
@Gautam-Arora24 Oops I forgot to paste the link itself. My bad: https://hackforla.slack.com/?redir=%2Farchives%2FC016CJZ8VTN

**Comment by bbovenzi** [comment]
@Gautam-Arora24
Extra resources:
https://www.hackforla.org/getting-started
https://hackforla-slack.herokuapp.com/
