### ISSUE TITLE
Bug: site won't load at all on Internet Explorer 11.

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#747]
### Overview
Bug: site won't load at all on Internet Explorer 11.

### Action Items
- [ ] Fix

### Resources/Instructions
Reported by John Ritchey and John Darragh able to reproduce on Windows.

**Comment by entrotech** [comment]
@bbovenzi See https://blog.steven266.de/react-blank-screen-on-internet-explorer-11-7b7c5863873a for an explanation of the problem and suggested fix.

**Comment by bbovenzi** [comment]
Unassigning myself. I ran out of credits to test ie11 from a mac...

**Comment by staceyrebekahscott** [comment]
Closing this issue as outdated. 

It has not been worked on since Nov 2020 and has been in the Icebox since Mar 2021. If this was an issue affecting a large number of users, it would have been addressed by now.
