### ISSUE TITLE
Ensure all team members are added to Github

### ISSUE THREAD

**Issue by chombus** [hackforla/food-oasis#75]
### Overview
Find any team members actively working on the project and make sure they are added to Github 

### Action Items
- [x] Get the latest roster info
- [x] Send @ExperimentsInHonesty the list of team members that are on the roster but _**not**_ on GitHub
- [x] Verify the updated list
### Resources/Instructions
[Current team roster](https://docs.google.com/spreadsheets/d/1--JQ5WTLpQcBkSC5wbvQKFZ3Mw8OoHK9ToyXrymVGnM/edit#gid=0)
[Current members on Github team](https://github.com/orgs/hackforla/teams/food-oasis-la/members)

**Comment by chombus** [comment]
@ExperimentsInHonesty The following people are on the roster, but not on the Github project team:

- Natesh Kodancha, @nkodancha
- John Darragh, @entrotech 
- Tina Moh, @tina-moh

Can you add them ?

**Comment by ExperimentsInHonesty** [comment]
Tina is the only one not currently in the org at all.  I added her and invited her to the team.  Can you send her this url so she can accept: https://github.com/hackforla 

John was already an Admin,but I added Natesh the Admin level

**Comment by ExperimentsInHonesty** [comment]
I closed this issue prematurely.  @chombus , you can close it once you verify that Tina has access.
