### ISSUE TITLE
Improve foodseeker feedback on locations

### ISSUE THREAD

**Issue by bbovenzi** [hackforla/food-oasis#750]
Coming from user interviews from @pageignited. The ability to provide some feedback on locations came up as a potentially useful feature.

Adding the ability to like or comment on a place would be quite a complicated change (new endpoints, need to create a login for foodseekers, etc)

Instead a faster and more lightweight approach would be to improve our "Send Correction" form. We could probably condense the entire long form into just a simple multiline text field that volunteers can read and update orgs as needed.

We could probably remove the popup form entirely and make the UI simpler by just including the single text field at the bottom of every "details" page.

**Comment by pageignited** [comment]
@bbovenzi 
I like that approach for now.
- I would change the text from "Send A Correction "to   "Suggest an edit "  and make it a text link, not a button. 
- The food seeker when they click it they would navigate to the bottom of the "details"  page where they can "Suggest an edit " 
- We then have that multiline text field with a post submit button the says "Send Edit"

**Comment by bbovenzi** [comment]
Note: On the "Send Correction" modal. Remove every field other than Other Suggestions , Your Name (optional), Your Phone (optional), Your Email (optional).
