### ISSUE TITLE
Add empty state to list view when there are no results

### ISSUE THREAD

**Issue by bbovenzi** [hackforla/food-oasis#764]
Problem: Currently if you go a to a location without any organizations we show a blank screen for the list view (see below)

Solution: Add some text like "Sorry, we don't have any results for this area. Click here to reset the search". On the reset we can do a search with the `defaultCoordinates`

<img width="1284" alt="Screen Shot 2020-10-28 at 1 37 58 PM" src="https://user-images.githubusercontent.com/4600967/97487755-e49cdd00-1922-11eb-86ac-382fcce49148.png">

**Comment by sasi-jj** [comment]
Hi, i would like to contribute in this work.

**Comment by bbovenzi** [comment]
@sasi-jj go for it!

**Comment by sasi-jj** [comment]
Ok i will do 😁

**Comment by sasi-jj** [comment]
@bbovenzi Need help with **NO_TOKEN_WARNING** issue in dev - changes made for empty state need to test

**Comment by bbovenzi** [comment]
@sasi-jj sent you an email with the `.env` variables
