### ISSUE TITLE
Display Food Types via Badges or equivalent in Food Seeker UI

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#767]
### Overview
Issue #678 implemented Food Type checkboxes, which allow volunteers to check off which of the six standard food types an organization provides.  These need to be shown to food seekers on the result list items panels and/or the organization details panel in the food seeker ui.

### Resources/Instructions
There are new field foodBakery, foodDryGoods, foodProduce, foodDairy, foodPrepared, and foodMeat in the organization object(s) returned by the food seeker UI endpoints to use for this.

**Comment by athya** [comment]
I can work on this!

**Comment by jpmikesell** [comment]
Hi Athya — I noticed you made great progress with the food types. Can you follow the style of the form and put a bounding box around food types? Also the confirm check box needs to read confirm. I attached the look of what I’m referring to. The name field has a bounding box and confirm is a check box just has the word confirm. I like the check boxes out of the drop down (as it is in categories).

![Screen Shot 2020-11-12 at 07 45 56](https://user-images.githubusercontent.com/54608811/98963222-41200080-24bc-11eb-8a92-84f0fbcb4b83.png)
![Screen Shot 2020-11-12 at 07 48 31](https://user-images.githubusercontent.com/54608811/98963228-42512d80-24bc-11eb-804d-36f5ee8052bc.png)
