### ISSUE TITLE
Research the Web API for Yelp to determine what stakeholders we can extract from Yelp.

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#87]
You will need to create a developer account (or use John Darragh's) to get an API key.  Figure out what we are allowed to use from Yelp and what the API capabilties are. Can we use it to import data to our database?  Use it to verify data that we get from other sources?  Link to Yelp from our app? Integrate our app with Yelp listings?

**Comment by entrotech** [comment]
See https://www.yelp.com/developers/documentation/v3/get_started to get started.

**Comment by Telos8840** [comment]
@entrotech so after doing some research, this is the information I was able to find for your above questions:

* Can we use it to import data to our database?
    * No, we’re not allowed to store data for longer than 24 hours 
    * You agree that you will not, and will not assist or enable others to cache, record, pre-fetch, or otherwise store any portion of the Yelp Content for a period longer than twenty-four (24) hours from receipt of the Yelp Content, or attempt or provide a means to execute any scraping or "bulk download" operations, with the exception of using the Yelp Content to perform non-commercial analysis (as further explained below) or storing Yelp business IDs which you may use solely for back-end matching purposes;
* Use it to verify data that we get from other sources?
    * Yes, we could use it to verify data from other sources as long as we’re using it non-commercially 
    * Allowable non-commercial use of the Yelp Content. Notwithstanding the foregoing, you may use the Yelp Content to perform certain analysis for non-commercial uses only, such as creating rich visualizations or exploring trends and correlations over time, so long as the underlying Yelp Content is only displayed in the aggregate as an analytical output, and not individually. For example, this is an acceptable non-commercial analytical use of the Yelp Content. “Non-commercial use” means any use of the Yelp Content which does not generate promotional or monetary value for the creator or the user, or such use does not gain economic value from the use of our content for the creator or user, i.e. you. If you are interested in commercial use of the Yelp Content, please visit [knowledge](www.yelp.com/knowledge)
* Link to Yelp from our app?
    * We’re required to link to Yelp if we display any of their content
    * Link directly to the corresponding Yelp pages whenever you display star ratings, review excerpts, and review counts from Yelp 
    * Make the Yelp logo link to yelp.com or the business’s Yelp page wherever and whenever you use it
* Integrate our app with Yelp listings?
    * Yes, as long as we follow their [display guidelines](https://www.yelp.com/developers/display_requirements)

**Comment by entrotech** [comment]
So some things we could do are:
Have a Stakeholder detail page that has a link to the Yelp listing(with
appropriate Yelp logo, etc.) and/or shows the allowable yelp info about the
organization in a panel on the page.
This could be displayed to end users, or just to someone maintaining our
information about a stakeholder for comparison purposes - though it seems
that this is only allowed if we are not in the business of selling our
information to others.

Nice work!

**Comment by Telos8840** [comment]
Sounds good! Should we create a new ticket to get those implemented or would you rather keep this one open and build on top of it @entrotech?

**Comment by chombus** [comment]
@ExperimentsInHonesty closing issue
