### ISSUE TITLE
Create user research questionnaire

### ISSUE THREAD

**Issue by ktjnyc** [hackforla/food-oasis#870]
### Overview
We need to understand how people use the site so that we can make updates to get users information easier. 

### Action Items

- [x] Create a google doc in the [Food Oasis google drive ](https://drive.google.com/drive/folders/1nVn3v_kD9GJ2IO6A84DZkox9h1eqMeRO?ths=true)
- [ ] Determine what items we need to get user feedback on
- [ ] Write up interview script / scenarios
- [ ] Jenny to identify 3 users 

### Resources/Instructions
Link to [draft questions](https://docs.google.com/document/d/1WBfpWLnfmbYA7OWwu6xFTvUMGKSX2Rym7yuOf3Mjulk/edit)
Link to [foodseeker interview draft](https://docs.google.com/document/d/11NoRFXBI7RZg2__S60qQkdRe0ES5wi3IefPjGnj7XHc/edit#)
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.
[Guerilla UX Research Guide ](https://docs.google.com/document/d/1R1qWuAlws7yZS02sQwDZiVy3ah9NiYqGrf7xT2yUPo8/edit?usp=sharing)

**Comment by ktjnyc** [comment]
Potential question - if you landed on the map of the page would you know what the site is about?

**Comment by baipai** [comment]
Start to write some initial thoughts and questions for the user interview questions under google drive “04_Design & UX”-“research”-“2021 research”. I also write some of my hypotheses and start to collect some competitive studies to better create the user questions, it is also under the 2021 research folder. I know there was one past competitive research, that one is more focused on the website feature, the one I create is more focus on the product value. 
https://drive.google.com/drive/folders/1Sz1fNyGIX871_HN7IsOZ4jcKgVg1vzaD?usp=sharing

**Comment by entrotech** [comment]
Bai's document above contains some preliminary ideas, but we need a solid plan for how to proceed.

Issue #862 is to create an alternative landing page to evaluate

**Comment by erigilg** [comment]
I added the user interview draft for foodseekers in the description of the issue. You can find it here as well. https://docs.google.com/document/d/11NoRFXBI7RZg2__S60qQkdRe0ES5wi3IefPjGnj7XHc/edit#

**Comment by staceyrebekahscott** [comment]
Re-closing issue. One of the current UX researchers will develop a new issue.
