### ISSUE TITLE
Updated Github Action to enable CI/CD into AWS Infra

### ISSUE THREAD

**Issue by darpham** [hackforla/food-oasis#871]
### Overview
We want to add Github Action workflow to enable automated deployment.
This requires updated the pre-existing worflow `.github/workflows/deployToDockerHub.yaml`
We will want to append the workflow to deploy the new Docker Image into AWS.

Use pre-existing branch [aws-deployment](https://github.com/hackforla/food-oasis/tree/aws-deployment) to avoid tainting master branch history/log

### Action Items

1. Document Environment variables currently used for Production in Heroku.
2. Separate the environment variables into  non-sensitive or sensitive (secrets).
3. Terraform Apply with these added in the `terraform.tfvars`
4. Retrieve the new `task-definition.json` post Terraform Apply.
5. Filter out the un-needed sections of the json
6. Update the json in the Repo
7. Add the AWS Keys, find the gh_action user keys via Terraform `terraform output`
8. Update the `.github/workflows/deployToAWS.yaml`
9. Validate, test, update, yaml until it works with no issues. (This might take several iterations, so using the `aws-deployment` branch would be best)

### Resources/Instructions
Example of working workflow that could be picked apart and re-used for the deployment side.
We don't need to Auth for pulling the Image as they're public.

**Comment by darpham** [comment]
Please use branch: https://github.com/hackforla/food-oasis/tree/aws-deployment

**Comment by ktjnyc** [comment]
Hi @darpham or @prashantsingh071993 is there an update on this?  thanks,

**Comment by staceyrebekahscott** [comment]
Issue is 18 months old. Moving to Icebox for later priority assessment. May need to be closed as Stale and rewritten.

**Comment by qiqicodes** [comment]
Closing this issue, because it is dated.
