### ISSUE TITLE
Bug: Buttons misaligned on iPhone SE 2016

### ISSUE THREAD

**Issue by fancyham** [hackforla/food-oasis#887]
### Overview
On the iPhone SE (2016), buttons are overlapping, making some inaccessible.  Looks like map is too tall?

![4E419A5D-8653-4BFA-B2C5-194080DEDF2C](https://user-images.githubusercontent.com/3376957/110039621-98edac00-7ce5-11eb-803c-2a17cad5d40c.jpeg)

**Comment by entrotech** [comment]
@fancyham  I don't have an iPhone, and I'm not able to repro by using web dev tool emulators on MacBook or Windows with Chrome. or on MacBook with Safari when emulating iPhone SE. Not sure how to proceed...

**Comment by fancyham** [comment]
Seems to be fixed.  Can no longer reproduce.  Perhaps related to
- #833 and fixed by #895
