### ISSUE TITLE
Usability Studies

### ISSUE THREAD

**Issue by ktjnyc** [hackforla/food-oasis#892]
### Overview
We need to collect usability feedback so we understand point of friction to update on the website.  

### Action Items

- [x] Heuristic usability studies
- [ ] Studies with actual food seekers
- [x] Studies with volunteers
- [ ] Studies with administrators
- [ ] Studies with social services providers
- [ ] Studies with organizations

### Completed heuristic usability studies of front-end / food seeker experience
[Jess's 2021 UX Audit](https://drive.google.com/file/d/1FyIWm4SGqgopm_LESiChPoWFDP_TI2Z_/view?usp=sharing)
[Bryan's Quick UX thoughts](https://docs.google.com/document/d/1W-gw3zd05hbsxN4TxO-rgNw3Rra6AANZ3MsPihyPBCI/edit?usp=sharing)

### Studies with actual users
[Thy's - Recommendations for how to conduct guerrilla user research, along with possible FOLA-specific questions to ask](https://docs.google.com/document/d/1R1qWuAlws7yZS02sQwDZiVy3ah9NiYqGrf7xT2yUPo8/edit)

**Comment by fancyham** [comment]
@ktjnyc, please update Bryan usability comments link

**Comment by wanderingspoon** [comment]
I have a question about the intended subjects/informants for this research:

- Does this issue refer to volunteers verifying site data? Or food seekers? Or both?

**Comment by ktjnyc** [comment]
@wanderingspoon intention was from the food seeker side.

**Comment by fancyham** [comment]
Three completed heuristic usability studies are linked at top of this issue.  This was done during the covid pandemic, so these were usability reviews, not observations of actual users.

In the future, in-person usability studies would be ideal.

**Comment by fancyham** [comment]
Re-opening because there are additional studies that we can conduct now that there is a vaccine.  May take a while but we should do studies with all our user types (food seekers, volunteers, admin, organizations, social service providers, etc.)

**Comment by fancyham** [comment]
@gigicobos, @sameergautam  Could you find out if we or HfLA have an account at usertesting.com or have access to some other service that would allow one of our usability researchers to conduct simple, remote screen-share + audio recording tests?   If we don't currently have access, could you ask around to see if this is something we/HfLA could procure?  This might be a free, donated, or paid service.

This type of service is useful for running short, targeted tests like: while talking out loud to describe what you're thinking and doing,  "please find a pantry near you" or "show us how you update a record in the database".  

Ideally, we find one that works for mobile users (food seekers), as well as desktop computer users.

From past experience, usertesting.com has a respondents we can screen for, or can send tests to specific people.  Also, the tests are done asynchronously (where the researcher waits for people to submit their recordings).

If we can't do this, then perhaps a HfLA Zoom account (or similar)  that allows screen sharing and recordings that maybe the usability folks are using?  Or perhaps there's a guide HfLA has already created for people doing this type of test?

**Comment by sameergautam** [comment]
@fancyham I reached out to Olivia to know about the services that are used and I got to know that free accounts on usabilityhub (https://usabilityhub.com/) are used.

**Comment by fancyham** [comment]
Thank, @sameergautam — I may have missed it but usabilityhub.com seems to have only a few tools, but none for a more traditional usability testing where we're watching someone actually complete a task, which would be a better (IMO) service to investigate how well our app performs.  (see usertesting.com for comparison)

Seems like there several companies, each that have different tools:  (Please add more if you learn more about good ones.)

- usertesting.com — Screen recordings with audio thought narrations of people completing requested tasks, I believe up to 20 mins each.  I've used this professionally with good results in lieu of in-person usability studies.
- usabilityhub.com — Basic surveys and click maps.  We use their free level of service?
- hotjar.com — Time-based session interaction recordings but no voice and anonymous. Looks like we are currently using this at the free level now.

I've opened an issue #1017 "Add video session recording to the volunteer and admin interface to check usability " to look into session-recording tools like usertesting.com.

**Comment by staceyrebekahscott** [comment]
Closing this issue as outdated, as it was created in Aug 2021. 

The current UX researchers should develop their own plan for how to conduct user research.
