### ISSUE TITLE
Add "By Appointment" feature

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#904]
### Overview
A significant percentage of Food Pantries and Meal Programs require appointments. Add fields to the Organization that support appointments. (See attached email PDF for discussion)

### Action Items
- [x] Discuss what types of input fields need to be recorded to support appointments. (see comments below)
  - [x] How would the food seeker see this information, and what actions could they take?
  - [x] Can they click to make a phone call or send an email to make an appointment - especially on a mobile device
- [x] Create mockups of both volunteer and public website for these changes
- [x] Create issue(s) for developers to implement this feature.

### Resources/Instructions
[VolunteerSuggestions20210316.pdf](https://github.com/hackforla/food-oasis/files/6159960/VolunteerSuggestions20210316.pdf)

**Comment by fancyham** [comment]
@entrotech said: Jenny and Jordan said that about ⅓ of the orgs require an appointment

So we can help people by giving the seekers a phone and email with which they should reach out to the org first.

"No walk-ins.  Please make an appointment by calling (XXX) XXX-XXXX between (days and time) or email (email address)"


Database:
Needs checkbox that says "Requires appointment"
with new fields for phone number and email address

On the front-end:
Display
"No walk-ins.  Please make an appointment at:
Phone number
or email address"

**Comment by fancyham** [comment]
@fancyham 

- [ ] Mockup volunteer screen
- [ ] Mockup public screen

**Comment by fancyham** [comment]
First draft for review — thoughts?

Changes:
- Move eligibility/requirements to top (probably where they should be anyway).  This is where instructions and appointment for email/phone number can go.
  - Automatically turn phone numbers and emails in text fields into clickable links.  No special fields just for those because there are likely too many special cases.
- Add a custom text field note for the Hours, in case there are hours but appointments are required, or no hours and want to say "schedule with organization"

![Issue 904 - Supporting _By Appointment Only_ case for listings](https://user-images.githubusercontent.com/3376957/134579479-14e207a5-cf1e-4464-8673-3b71dad945b0.png)

**Comment by gigicobos** [comment]
Waiting for a development issue.

**Comment by entrotech** [comment]
We discussed in the meeting on 9/30/21 among @fancyham @gigicobos and myself, and agreed that Bryan's idea was enough to move forward with - though we should probably check with Jordan Smith as well. We decided that 

- a "Walk-ins checkbox" could be added to explicitly indicate that walk-ins are welcome
- A fee-form text box in the hours section should be added where the volunteer could indicate any caveats to the hours
- Appointment contact email or phone number could be entered in the eligibility text area, and the food-seeker UI would make phone numbers or emails into links.

**Comment by entrotech** [comment]
@fancyham - This feature is implemented and deployed via Issue #1042. I believe this corresponding UI/UX issue should be closed as well.

**Comment by fancyham** [comment]
Excellent — does this move to QA now?  Any examples we can/should look at, just let us know (perhaps too early since the orgs that require appointments need to be added)

**Comment by entrotech** [comment]
@fancyham Can we close this issue?

**Comment by fancyham** [comment]
@entrotech If there aren’t any examples to QA yet, yeah, let’s close it.  We’ve got eager QA folks :)
