### ISSUE TITLE
Unpublish Listings that can't be verified or don't want to be listed.

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#905]
### Overview
One of the main strengths of Food Oasis LA is that the listings are current - no other site to my knowledge makes as much of an effort to keep their information up-to-date. However, some listings are really unreachable, and volunteer Tommy suggested that maybe the unverifiable listings should drop off of our site after a certain period of time (maybe 6 months or so). This would be very easy to implement, though we might wan to add features for the Admin to manage the old listings as well.

On a related note, apparently some organizations that have been contacted do not want our site to publish their information, and we should have a way to flag such organizations (kind of a "do not call list" for organizations). We still want to keep them in our database (like we do for permanently closed places), so admins know that when we stumble upon a reference to them again in our data collection, we don't waste any time trying to re-verify them.

### Action Items
- [ ] Do we want to "expire" listings?
- [ ] What should the time limit be?
- [ ] How should the "do not call" feature be implemented?
- [ ] Do we need to add features for an admin to manage such listings?
- [ ] Make issues for developers to implement such features

### Resources/Instructions
[VolunteerSuggestions20210316.pdf](https://github.com/hackforla/food-oasis/files/6159993/VolunteerSuggestions20210316.pdf)

**Comment by staceyrebekahscott** [comment]
@rylantalerico I am moving this into the Prioritized Backlog and labeling it as an issue I would like to be addressed as part of the Impact Sprints. Is this something you can work to address within the next 2 weeks?

**Comment by staceyrebekahscott** [comment]
Erin had an idea to do a mail merge to send to the existing pantry database, to verify email/ contact information is current. 

The idea here also serves to see what listings we can remove right away by either determining if they are closed, or do not want to be in our database anymore. Then we can mark them on the listing's page accordingly and keep a record, for the occasion that someone submits them to be listed but the org does not want to. 

Suggested tasks to be completed: 

1. Mail merge to send a message to all emails on our list to verify if listing is current, or if they do not want to be listed (actual wording of email TBD). 
2. Add a feature to the listing that will mark them as wanting to be unlisted. 
3. Confirm that the site no longer shows on the website. 
4. Reassess to see how many listings are left and continue with revising the validation process. 

@itserindean Please confirm this is what you originally intended and if you are ready to move forward with this process.

**Comment by itserindean** [comment]
I think we need to make sure each email has a reasonable ask, my intention was to start ONLY with verifying the email/ contact information is current.

once we have that I think we could reach out with a one click "confirm if this info is correct' (with maybe a link to how to make corrections. And maybe here is also where we have an option to be unlisted.

**Comment by staceyrebekahscott** [comment]
@itserindean Moving this to Up Next, as the UCLA volunteers may run into this. We should come up with criteria for pantries who cannot be verified (re: how many contacts do we make before we remove from our list), or ones that we decide we might not want to list (re: if they only hand out food too infrequently, or only to their church members). Let's discuss at our next PM meeting.

**Comment by itserindean** [comment]
@staceyrebekahscott  Yes let's discuss more at our meeting!

Currently I advise UCLA students to 'flag for removal if they  reach out 6 times (using at least 2 different methods of contact (Ie phone/email/FB messenger/carrier pigeon...) and each contact must be 2 days apart....
