### ISSUE TITLE
Allow Users to "Claim" a Pantry or Meal Program

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#906]
### Overview
The idea is similar to how a business owner can claim their business on Yelp.  If a user or volunteer is willing to take responsibility for maintaining an organization's data in Food Oasis, we need to design a process and UX for doing so. The hope is that we can reduce the workload on volunteers and encourage engagement by food pantry or meal program representatives.

### Action Items
- [ ] Is this is a good idea - what is the priority?
- [ ] What process would need to be in place to verify that users are authorized by the pantry or Food Oasis staff to claim an organization?
- [ ] Would changes need to be reviewed by a Food Oasis admin?
- [ ] Can multiple people claim an organization?
- [ ] What process would we need to remind claimants to re-verify their listings?
- [ ] Create issues for developers to implement.

**Comment by entrotech** [comment]
Needs a business analysis. A related feature is the idea of a way for volunteers to "take ownership" of a set of organizations to maintain.

**Comment by gigicobos** [comment]
Maybe we could first test #996 , see if organizations update their info and then create a feature to "Claim Pantry"

**Comment by fancyham** [comment]
- This seems very similar to #996 
- Does that solve this use case?  If not, perhaps we can add a hidden admin email address for an organization's listing.

**Comment by staceyrebekahscott** [comment]
Closing this issue as not planned, as issue #996 deals with the process of having pantries self update their own listings. This issue is also similar to #292 of allowing users to claim a stakeholder, which is also being closed as 996 deals with this.
