### ISSUE TITLE
Add server-side web api request validation

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#912]
### Overview
The web api request do not currently have any sort of server-side request validation. In node/expressjs this is typically implemented by a middleware package like[ joi](https://github.com/sideway/joi)

### Action Items
- [ ] Follow the suggestions outlined here: https://simonplend.com/how-to-handle-request-validation-in-your-express-api/

**Comment by staceyrebekahscott** [comment]
Moved to Icebox as API work should be considered as part of a long term goal for Food Oasis.
