### ISSUE TITLE
Create reading list on Wiki

### ISSUE THREAD

**Issue by ktjnyc** [hackforla/food-oasis#913]
### Overview
We need to add a reading list to the Wiki to provide volunteers with resources to learn about the issues we are trying to solve. 

### Action Items

- [x] Gather list of helpful reading
- [x] Write paragraph for Wiki section 
- [x] Update Wiki

### Resources/Instructions
[Wiki ](https://github.com/hackforla/food-oasis/wiki)
[Reinventing Food Banks and Pantries: New Tools to End Hunger](https://www.amazon.com/Reinventing-Food-Banks-Pantries-Hunger/dp/1642831530/ref=sr_1_1?crid=23U0YUATD2CRH&dchild=1&keywords=reinventing+food+banks+and+pantries&qid=1616454466&s=books&sprefix=reinventing+food+banks+and+pantries%2Caps%2C238&sr=1-1)

**Comment by wanderingspoon** [comment]
A few sources for introductory context on food insecurity:

**Addressing Food Insecurity in Los Angeles County** (LA Country Public Health, 2019)
http://www.uclaisap.org/slides/psattc/cod/2019/Day%202/Workshop_AA.pdf

**Food Insecurity in California** (CA Food Policy Advocates, 2019) 
https://nourishca.org/GeneralNutrition/CFPAPublications/FoodInsecurity-Factsheet-2019.pdf

**Report Summary: Household Food Security in the United States in 2019** (USDA, 2020)
https://www.ers.usda.gov/webdocs/publications/99282/err275_summary.pdf?v=97.9

**Hunger Relief Organizations**
https://www.nal.usda.gov/fnic/hunger-relief-organizations

**Comment by wanderingspoon** [comment]
Also, if you don't already link to them, Feeding America's website is a great resource for both quantitative scope and qualitative stories.

**Real Stories of Hunger**
https://www.feedingamerica.org/hunger-in-america/real-stories-of-hunger

**Feeding America's Research on Hunger**
https://www.feedingamerica.org/research

**Comment by ktjnyc** [comment]
Progress: Thy added some great resources above, need to draft intro language
Blockers: Availability 
Availability: Limited until next week. 
ETA: Paragraph drafted for next Thursday

**Comment by wanderingspoon** [comment]
Not sure where this resource might live?

It could be useful for FOLA research teams (e.g. creating a screening tool, or gathering background for informational interviews with people working in food insecurity).

This page provides standardized survey tools used by and recommended by the research wing of the USDA for studying food insecurity:
https://www.ers.usda.gov/topics/food-nutrition-assistance/food-security-in-the-us/survey-tools/

**Comment by wanderingspoon** [comment]
Katie, Let me know if you see any gaps in the rss we offer new folks...happy to gather and suggest other links for learning about issues, contexts, communities, stakeholders or related successes.
@ktjnyc

**Comment by ktjnyc** [comment]
Updated wiki reading page with paragraph from the One Sheet and links provided above.  

https://github.com/hackforla/food-oasis/wiki/Recommended-Reading
