### ISSUE TITLE
Identify all current versions of logos

### ISSUE THREAD

**Issue by ktjnyc** [hackforla/food-oasis#917]
### Overview
We need to confirm the current logos so that we can archive the old logos on the Google drive and have everything in one place.  

### Action Items

- [ ] Review resources below
- [ ] Identify current horizontal logo
- [ ] Identify current stacked logo
- [ ] Identify current vertical logo
- [ ] Identify current logo for white backgrounds
- [ ] Identify any other current logos
- [ ] Create new subfolder in google drive to hold recent copies
- [ ] Put all other logos into archive folder

If the resources below don't help with straightening out the current versions, I can point you to someone who may be able to assist.  

### Resources/Instructions
[Current folder with logos](https://drive.google.com/drive/u/0/folders/1FfnmTzjk3JETqVQxAhgrKW-nJ4v6_ikR)
[Current Figma](https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/Fola-Design-System?node-id=2591%3A0)
[Logos from Jenny](https://drive.google.com/drive/u/0/folders/1-JCQleINL0OI7UKndm470yzLFlTLaIYU)

**Comment by staceyrebekahscott** [comment]
Closing this issue as not planned, as it includes outdated links. But it is relevant to #991 so I am adding current logos to the scope of that issue.
