### ISSUE TITLE
Review and update volunteer research process flow

### ISSUE THREAD

**Issue by ktjnyc** [hackforla/food-oasis#920]
### Overview
We need to update the user flow for the volunteer database so that we have an understanding of the current process.  

### Action Items

- [ ] Review existing user flow diagrams
- [ ] Research current user flow
- [ ] Update user flow diagrams to show current process
- [ ] Add updated links to [issue for modifications](https://github.com/hackforla/food-oasis/issues/368)

### Resources/Instructions
[User flow PDF](https://drive.google.com/file/d/1g64nt3S0FgQDp2yHeugPEny481nrKh4R/view?usp=sharing)
[User flow slides](https://docs.google.com/presentation/d/1y6O7ghU-YmCD-oEJBBe2cDcz2cyy5HP1fAmYRP_ouJk/edit?usp=sharing)

**Comment by staceyrebekahscott** [comment]
@rylantalerico I think this issue is redundant to the work you and Gigi are doing with the Research Project and #1143. If so, I recommend this issue be noted and closed. Can you take a look and advise?

**Comment by staceyrebekahscott** [comment]
@rylantalerico @GigiUxR Following up on my question as to whether this is redundant to the work being done in issue #1143 . 

Please confirm if this issue should be closed out. If no response by this week's team meeting, I'll assume it can be closed out.
