### ISSUE TITLE
Create training for admin tasks on volunteer dashboard

### ISSUE THREAD

**Issue by ktjnyc** [hackforla/food-oasis#922]
### Overview
We need to create a training so that we can onboard new admins to help with admin tasks on the volunteer dashboard.  We often have people emailing the general email with data questions/issues that can be quickly resolved with admin access.  Since this access is not only restricted to LA data we need to make sure users are properly trained to make the updates.  

### Action Items

- [ ] Obtain admin access
- [ ] Review admin screen 
- [ ] Identify common tasks needed 
- [ ] Create training outline
- [ ] Create user documentation  

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.

**Comment by staceyrebekahscott** [comment]
Closed as Stale, to be addressed in #1296
