### ISSUE TITLE
Usability: selected map pins aren’t prominent enough

### ISSUE THREAD

**Issue by fancyham** [hackforla/food-oasis#923]
A selected location makes the map pin a tiny bit larger, but very hard to tell if a pin is selected or normal, and which pin is selected.

Recommend trying:

Make selected map pin selected state more obvious. Significantly or perhaps better: a colored outline or something similar.

For example, Google map pins grow about 50-80% and sometimes change shape.

Apple Maps grows selected location pin about 100%

**Comment by fancyham** [comment]
- Take a look at #927 that has some detail about where these SVG files live.

**Comment by entrotech** [comment]
@souronion @fancyham Can we close this issue? It has been deployed to production. I wanted to get one last check that it works as you intended.

**Comment by fancyham** [comment]
@entrotech looks good to me.  Good job everyone!
