### ISSUE TITLE
Mobile view scroll bug

### ISSUE THREAD

**Issue by hanapotski** [hackforla/food-oasis#924]
When checking out a location, it's not very obvious that you need to scroll to see the details.

**Comment by hanapotski** [comment]
closing this issue as it's a duplicate of https://github.com/hackforla/food-oasis/issues/958

**Comment by fancyham** [comment]
This might be related to the Apple's auto-hiding of scrollbars.  By default, they appear briefly (if at all) then disappear.  Can be quite confusing.

Not sure if this is the exact issue but I suspect it's related.

There's some CSS to display the scrollbar (when scrolling is possible) — can we try this?
https://stackoverflow.com/questions/7492062/css-overflow-scroll-always-show-vertical-scroll-bar

**Comment by Benbaillou** [comment]
Hi - could we please size the project with a dedicated label. Thanks
