### ISSUE TITLE
Provide Recommendations on how we use web analytics

### ISSUE THREAD

**Issue by ktjnyc** [hackforla/food-oasis#925]
### Overview
We need to research and evaluate potential web analytics tools so that we can get accurate data for out website.  

### Action Items

- [ ] Research analytics options 
- [ ] Provide Recommendations

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.

**Comment by fancyham** [comment]
Do we also collect GPS / location data of our users when they search the maps, for example, if they 'use my current location' on the map or enter search terms?  Searched locations and search terms/filters would be useful to collect.

**Comment by fancyham** [comment]
To start, I propose that we generate reports for:

**"Successful" searchers** = 
People who have visited 2 or more pantry/meal detail pages AND are NOT volunteers (that is, omit people who have visited the volunteer log-in screen or any of the volunteer-only pages)

Additional sub-reports: 
- Successful searchers that placed phone calls
- Successful searchers that got directions

The reasoning:
- We want to see how many people are using our site to find places to get food.  It's unlikely that they'd look up just one place in their search, hence minimum two places.
- We will adjust what "number of places" is appropriate as new information comes in as we learn more about user behavior.

Questions:
- Can we / do we want to gather the locations that people are searching on / geo-locating at?
- Can we set a cookie to omit FOLA team members?  We need to avoid counting ourselves.

**Comment by pageignited** [comment]
Overview: 

After gathering data from our 3 analytics applications (Stormly, GA, and Cloudflare ), I have determined that the data we are getting from Cloudflare is not accurate. User daily visits are off by some 83%.

We are averaging to Food Oasis about 40 users per day. You can see the chart attached to see the results resulting from 4/7/21 to 4/16/21. This is just over a week time frame but based on these trends I do not see anything to warrant the trend to change. 

Insights:
This leads me to believe that Food Oasis has not found a product-market fit with its users. 

How do we go about finding that product-market fit?
1. We are going to have to do more customer development on organizations, agencies, and food seekers.
2. Need to Iterate on the current product or pivot the product.
3. Develop user persona of a (food seeker and organization).
3. We need to develop some key impacts(s) we are looking to achieve (revenue, customer satisfaction, NPS, etc..)
4. These key impacts will be linked to outcomes.
5. These outcomes will need to be achieved by the product outputs we build. 
6. We then need to measure if these new outputs with KPIs to make sure they meet the output and reach the impacts(s) we look to achieve.
7. We'll need to create some hypotheses and then build and test product features to see if we get the outcomes we are looking for.  If not we keep iterating until we get product-market fit.

[Food Oasis Dalliy User Visits  - Sheet1.pdf](https://github.com/hackforla/food-oasis/files/6337693/Food.Oasis.Dalliy.User.Visits.-.Sheet1.pdf)

Recommendations:

1. We'll setup Analytic dashboards
2. Create Site metrics for (Monthly Active Users (MAU) and Daily Active Users (DAU), Click Thru Rate (CTR), Customer Retention Rate (CRR))
3. Create user funnels for (buttons clicks and organization views and other site pages)
4. Views Usage-based on device type and top referring site

**Comment by entrotech** [comment]
Here is what is instrumented at this point for Stormly:

- You should see a "visitAppComponent" event when the user first navigates to the app, regardless of which "page" they start on.
- A "visitLandingPage" should be raised when the user goes to the Landing (Home) page.  
- A "viewDetail" event is raised whenever the Organization Detail Panel is displayed or it's data changed, regardless of whether it is a result of a Detail button click or clicking on a map marker.  
- The map panel raises the "searchArea" event when the user clicks on the "Search this area" button. 
- A "getDirections" event is raised if the user pushes either of the Get Directions buttons.
- A "dialPhone" event is raies if the user pushes the "Call" button or clicks on the phone number link in the Organization Details panel.

If you want, I can add events like "showList" that would be raised if the results list is displayed and "showMap" if the map is displayed.  Events can be raised for each time a react component is created or re-populated with data, or when buttons or links are clicked.

The application does not really keep a sequential history of events, so I don't think I have a way of only counting showMap events that occur immediately after a "visitLandingPage" event, or raising a special event when the user selects a marker for the third time, or things like that - maybe there is a way to put all this together in Stormly based on the above events.

**Comment by pageignited** [comment]
John,

That would be great if you can create events for
- showList
- showMap

What about events for the "Meal and Pantry " buttons are they these events in Stormly?
TogglePantryFilter
ToggleMealFilter

Do we have the events set up for(about us, find food, donate, FAQ, and suggest a new listing)? If not can we get them set up as well?

Let me know thanks.

**Comment by pageignited** [comment]
@entrotech 

John,

Can tie the 3 events and their attribute to "name"? There are two name attributes currently I see in Stormly but either allow for us to get names of those events. We do need this to get more analytics detailed reporting.
![2021-04-20_13-44-10](https://user-images.githubusercontent.com/22136920/115461726-9a642c80-a1de-11eb-9b8d-de009c044c20.jpg)


1. visitLandingPage | name
2. viewDetail | name
3. searchArea | name

**Comment by fancyham** [comment]
“TogglePantryFilter” is a start but can we capture what filters were in effect when a search happened?

It’d be nice to know how many people were “searching for pantries only”.
