### ISSUE TITLE
Meals/Pantry icons don't match order of filter buttons

### ISSUE THREAD

**Issue by fancyham** [hackforla/food-oasis#927]
The icons on the map / lists don't match up with the filter buttons. 

On the filters, Pantry is on the left, Meals is on the right.

On the List and Map, the icons have Meals on the left, Pantry on the right.

The mismatched order make it harder to visually and intuitively relate buttons to items on map.

<img width="650" alt="2021-04-01 Icons don't match filter order" src="https://user-images.githubusercontent.com/3376957/113376581-c130f080-930d-11eb-8408-b29c26cf05bb.png">

This will also be a problem if we colorize the filter buttons to match the icons.

Some possible solutions:

Simple: Swap the filter buttons so 'Meals' is to the left of 'Pantry'. 
<img width="811" alt="2021-04-01 Swap filter buttons" src="https://user-images.githubusercontent.com/3376957/113377132-29cc9d00-930f-11eb-8f8d-35d629ab8743.png">

More difficult: Swap sides on icons.

Consider:
Which is higher priority to our target users?  Pantries or meals?

**Comment by entrotech** [comment]
Good observation.  We have a lot more pantries in the database, but that doesn't necessarily mean that they are more important to users.  It is easier to swap the position of the fliter buttons than to create new icons for the markers and list items - but that shouldn't be the dirving factor on what we choose to do.

**Comment by dking1342** [comment]
buttons have been swapped and awaiting merge

![Screen Shot 2021-06-22 at 10 44 25 PM](https://user-images.githubusercontent.com/28996149/123032403-8047f580-d3ab-11eb-94ef-42fdecdecfc3.png)

**Comment by fancyham** [comment]
Do we have any stats about what food-seekers are viewing most often? (i.e. getting details on pantry or meal)

I think swapping the buttons could work for the short-term, but long-term we should look at changing the icons.

If someone can point me to the icon files or sources, I might even be able to do the edits myself.

**Comment by dking1342** [comment]
It looks like the js file with the svg is located in the client/src/images folder. I believe it is labelled as the splitPantryMealIcon.  

![Screen Shot 2021-06-22 at 11 15 32 PM](https://user-images.githubusercontent.com/28996149/123034848-f2223e00-d3af-11eb-8a7b-fb16c30e5fbd.png)

**Comment by fancyham** [comment]
@dking1342 I created new 'mixed' icons where I swapped the left and right sides and put them back into the Google Drive where the original files are located (client/src/images).  They're named locator.svg and main.svg

I don't know how to add them to the .js files or make a pull request yet — would you mind putting the svg data into the correct files?

I think that should solve this issue?

https://drive.google.com/drive/folders/1jb3yV4B5Isd8oelQ2DTYUvXhm9e6t5fy

**Comment by dking1342** [comment]
@entrotech  fixed the issue with the data not showing. The icons not show the proper image and the filter buttons have been ordered to match the icon images. It is now ready to be sent for a pull request.
