### ISSUE TITLE
Mark user's current or searched location on map

### ISSUE THREAD

**Issue by fancyham** [hackforla/food-oasis#929]
Place a marker at the user's GPS location or the address the user typed into the map.

This can be done with either two markers or one.

Option 1) Same marker for both GPS-location and user-typed location

My assumption is that GPS-location is not updated continuously, so a static marker should be fine.

Option 2) Different marker.
Google and Apple both use a special pin for user-entered address, but a blue dot and circle for current-GPS-located location.  We could do something similar.  

But the implication here is that the blue dot updates as the user moves (say in a car).  So we'd need to update it live and drain the user's battery while we do that.

There are likely other solutions as well.

Of these two options, I think Option 1 might be better for the user (less battery drain).

**Comment by fancyham** [comment]
@entrotech Could you point us to the specifications / documentation / illustrations / resources for designing these Map markers?  Perhaps the current versions or SVGs?

**Comment by sameergautam** [comment]
@fancyham seems like there's a conflict of estimates. Could you revisit the estimate and keep only what is appropriate?

**Comment by fancyham** [comment]
Hi @sameergautam, I currently see 3pt estimate — could you describe the conflict further?

**Comment by sameergautam** [comment]
@fancyham apologies for the delayed response. Recalling from our past conversation, a `good first issue` is one that's something related to getting the environment ready. Hence, I'm removing that label.

**Comment by fancyham** [comment]
Related to
- #995

**Comment by fancyham** [comment]
Related to
- #926

**Comment by fancyham** [comment]
This has been partially addressed by:
- A red pin appears at the user’s entered location (entered via text or via GPS)
- However, when using GPS, it would be better to use a blue dot.

A blue dot is the user’s location in this design update
- #1874

That design may need to add a different-style pin for user-entered street addresses.
