### ISSUE TITLE
Scrape data from the Homeless Shelter Directory (homelessshelterdirectory.org) into a table called load_homeless_shelter_directory

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#93]
Trigger the import from a web api endpoint in the node app using node js and a scraping library like cheerio.

### Resources
create a folder inside this [folder](https://drive.google.com/drive/u/1/folders/15V2rV3aTLiA16juUUPlUmfsi-t2zW-vc) and place the .csv file for this scrape in it.

**Comment by chrislopez28** [comment]
Update:
* Almost done with scrape. Just need to clean up the output (probably using regular expressions) since a lot of the data is lumped together in one field.

**Comment by jpmikesell** [comment]
Hi Chris -- What is the status of this? Can you let me know where this is on our google drive?

**Comment by alexulven** [comment]
Done. The csv is uploaded in the google drive. https://drive.google.com/drive/u/0/folders/1WYD5r2UeOBO4zO8BGkuKgae4OO4bGXpz
