### ISSUE TITLE
Map Process to View Suggestions on Admin Dashboard

### ISSUE THREAD

**Issue by ktjnyc** [hackforla/food-oasis#935]
### Overview
We need to map the process of the volunteers with admin rights to view suggestions and apply updates so that we can design the pages and implement the changes.  

### Action Items

- [x] Talk to John about process
- [x] Document process
- [x] Review process
- [x] Move #936 out of the icebox when this is complete

### Resources/Instructions
[Link to draft process flow](https://docs.google.com/document/d/10tnUVTn0npewheKBuMH_3byMMmqiyQ_ydEyZNxRO1-8/edit?usp=sharing)

**Comment by entrotech** [comment]
We already have features in the application for a food seeker to "Send Correction" on the Organization Details Panel, and to "Suggest New Listing" on the Hamburger Menu.  When a user fills out these forms, the suggestion is recorded in the database to the suggestion table. This is the data collection part of a simple ticketing system, but we have not built out the part that allows an administrator to review the suggestions and act on them.

I envision a Suggestion Dashboard page, accessible to administrators that would allow them to query all the suggestions by various criteria and disposition them to specific states (maybe "New", "Pending", or "Closed") and add admin notes to each suggestion about what needs to be done, why nothing needs to be done, or how the suggestion was resolved.  The details need to be thought through:

- What are useful filtering and sorting criteria for the Suggestion Dashboard (submission date, disposition status)? Maybe the dashboard should default to just showing New and Pending suggestions.
- What should the dashboard look like? It could be a editable grid, or a view only grid where the admin need to open a form for a ticket to edit it.
- How should the notes be recorded?
- If the user provided their email, can we send them an acknowledgement of their submission, a notification that their suggestion has been incorporated or some other feedback or "thank you"?
- It seems like, of the case of a suggested new listing, it would be helpful to implement a process for an admin to check to see if it's a duplicate, and create a new organization if it's new without having to re-key the information from the fields provided in the suggestion.

**Comment by ktjnyc** [comment]
Progress: Worked on draft/notes for map 
Blockers: Availability 
Availability: Limited until next week
ETA: Draft for review next Thursday

**Comment by ktjnyc** [comment]
Progress: A few additional updates to the document 
Blockers: Availability
Availability: Limited until next week
ETA: Will make some progress by next week
