### ISSUE TITLE
Organize Google Drive

### ISSUE THREAD

**Issue by ktjnyc** [hackforla/food-oasis#938]
###dependencies

- #1087 

### Overview
We need to clean up/rearrange the Google Drive so that we can easily find the most recent documents.  A START-HERE document was started to try and avoid hours of moving files around.  

### Action Items

- [ ] Review google drive
- [ ] Provide recommendations for organizing google drive 

### Resources/Instructions
[START-HERE](https://docs.google.com/spreadsheets/d/1sUro4-Tx97N6tN_eAZpfVnqVmuCN3mYfH9Lq-rke0fQ/edit?usp=sharing)
[Google Drive](https://drive.google.com/drive/u/0/folders/1nVn3v_kD9GJ2IO6A84DZkox9h1eqMeRO)

**Comment by entrotech** [comment]
@Benbaillou Do not re-organize files and folders in old G-Drive folder linked above. We are in the process of moving all the files from that folder to the new G-Drive folder, which requires leaving files in the exact same folder structure, until the move is complete. AFTER we get all the files moved to the new shared drive, we can talk about re-arranging the folders.

**Comment by Benbaillou** [comment]
Understood - Thank you @entrotech

**Comment by staceyrebekahscott** [comment]
As this issue originated in Apr 2021, it is outdated and should be closed. As per comments in issue #1087 , upon completion of that issue we should revisit the need to develop rules on how to manage the nee Drive.
