### ISSUE TITLE
Back button is hard to find when viewing location details

### ISSUE THREAD

**Issue by fancyham** [hackforla/food-oasis#948]
On the desktop version of the site, when viewing the details about a location, the 'back' button is in an unexpected location, floating above the content, and I suspect, is overlooked. (I certainly didn't notice it)

To-do:

- [ ] Change color of back button (quick fix but not great)
- [ ] Change location of back button to above the organization name

![Screen Shot 2021-04-12 at 6 43 04 PM](https://user-images.githubusercontent.com/3376957/114498058-1b0fa100-9bbf-11eb-9d9d-214cfe4ea804.png)

- Change the location of the back button to a more intuitive location — perhaps top left of the detail section.

![Suggested new location for back button](https://user-images.githubusercontent.com/3376957/129514024-db4c853b-8db1-40b2-a6c0-feabb84d38df.png)

**Comment by fancyham** [comment]
Added improved illustration for back button location

**Comment by fancyham** [comment]
If we can't easily change the floating back button's location, let's change the color from Blue to Green (or some other FOLA color that is not blue (which blends in)

If someone can point me to the graphic image, I can change it, or maybe it's easy to change yourself.

**Comment by stdyrm** [comment]
@fancyham per our 10/4 meeting, I can take this ticket if nobody else is assigned

**Comment by fancyham** [comment]
Looks good!  Could the link be bigger, please? :)  It should be pretty visible.  Also, in Safari on my mac, it's appearing in font: "system-ui" rather than the helvetica from the css.

I suggest trying 16px to match the rest of the text on the page, perhaps bold.  Post screenshot if you need feedback.

**Comment by VirginiaWu11** [comment]
![image](https://user-images.githubusercontent.com/79432798/140652730-37208769-9e4d-474e-b2c9-5cf62de5a941.png)

Like this?

**Comment by fancyham** [comment]
Yup!  

Could you also show two additional variation screenshots with it bold and with an outline like the ‘Send Correction” button?

It needs to be really obvious, and also because on the latest Safari, the browser back button doesn’t return to the org list so that’s the only way to get back to the list.

I suspect the button outline might work really well?

**Comment by VirginiaWu11** [comment]
![image](https://user-images.githubusercontent.com/79432798/140657187-4706d3aa-0345-4fc0-9bb3-fe1cc421a940.png)
![image](https://user-images.githubusercontent.com/79432798/140657190-c389d435-f886-412c-924a-4205952296d7.png)

Thoughts?

**Comment by fancyham** [comment]
Thanks! 

My favorites, in order:
- bold
- plain
- outline (looks to similar to other buttons, actually)

Do you have a favorite?

Anyone else, if you have faves, please speak up :) @souronion

My criteria are: something that looks different to indicate it’s navigation, and stands out from the content. 

If you’re feeling the same as me, I’d say let’s go for bold, but we can also wait for other opinions if you like.

 I also looked at it on a smartphone and I think bold would work well there, but the outline one not as much because it looks so similar to the filter buttons, so not differentiated enough.

**Comment by souronion** [comment]
@fancyham Yes, I also vote for bold. 

@VirginiaWu11 Thanks for making the screenshots! :)

**Comment by VirginiaWu11** [comment]
Thanks all!
