### ISSUE TITLE
Update the volunteers presentation 

### ISSUE THREAD

**Issue by erigilg** [hackforla/food-oasis#951]
### Overview
Help Jordan, and the team imparting the volunteers presentation update their resources with new and right information.

### Action Items

- [ ] Include slack channel in their presentation [#foodoasis-research](https://hackforla.slack.com/archives/C01T1EL3TJR) where volunteers can ask questions, build community, etc. 
- [ ] Improve the [google doc](https://docs.google.com/document/d/1p3QplBkcXQYlQeZ_TvhMv-5DO642lEKGaFuPWB_HcxY/edit) that's being shared during the presentation

### Resources/Instructions
[Training script ](https://docs.google.com/document/d/1p3QplBkcXQYlQeZ_TvhMv-5DO642lEKGaFuPWB_HcxY/edit)
Review Volunteer Process #901

**Comment by ktjnyc** [comment]
@erigilg I had previously created #930 to track this same item.  Can you please merge the two and close one of them?
