### ISSUE TITLE
Create prioritization criteria for personas

### ISSUE THREAD

**Issue by ktjnyc** [hackforla/food-oasis#955]
### Overview
We need to define the criteria to evaluate the personas so that we can effectively prioritize the most important groups.  

### Action Items

- [ ] Schedule time to discuss criteria
- [ ] Determine criteria to evaluate which personas are most important
- [ ] Identify framework/tool to evaluate criteria

### Resources/Instructions
#885 - Issue tracking the creation of personas

Examples for potential direction from 100 Automations project
https://miro.com/app/board/o9J_lZziQ3g=/
https://github.com/100Automations/Website/projects/2

**Comment by wanderingspoon** [comment]
Happy to provide some examples of questions that could be answered, if needed, to help guide discussions. Let me know either way.

**Comment by fancyham** [comment]
Hi, I'd love to help with this! @ktjnyc
