### ISSUE TITLE
Calfresh Outreach

### ISSUE THREAD

**Issue by ktjnyc** [hackforla/food-oasis#956]
### Overview
We need to reach out to CalFresh to get information about what kinds of analytics they have on phone usage from their customers they might be able to share.  

### Action Items

- [ ] Connect with Bonnie for contact information of a CalFresh person
- [ ] Identify what we want to know from them
- [ ] Schedule meeting
- [ ] Document findings

### Resources/Instructions
[CalFresh website](http://calfresh.dss.ca.gov/food/)
Code for America Article: [Improving access to food assistance and how benefits are delivered](https://codeforamerica.org/programs/social-safety-net/food-benefits/)

**Comment by staceyrebekahscott** [comment]
A conversation is happening now regarding the possibility of working with CalFresh as a partner with Food Oasis as part of the Impact Sprints work. This issue as is will likely be closed, but I am assigning it to myself for now as a reminder to expand on the Partnership in a new issue.

**Comment by staceyrebekahscott** [comment]
@itserindean FYI, another issue that mentions analytics. The discussion around CalFresh and the Impact Sprints is slightly different from just finding out analytics, so I'll loop you in once I have a clearer idea how we are going to partner with them. The partnership might start with a conversation about analytics, as per the Overview, but I need a bit more time to sort out the specifics.

**Comment by staceyrebekahscott** [comment]
Decided to close as not planned, as the issue's scope is stale and the reason indicated for reaching out is not in line with the current direction of the project.

**Comment by itserindean** [comment]
Agree with your reasons for closing @staceyrebekahscott
