### ISSUE TITLE
Create UI Style guide

### ISSUE THREAD

**Issue by ktjnyc** [hackforla/food-oasis#960]
### Overview
We need to create a UI style guide so that we know what/where the most design items are and can share with external parties how they should style any material for Food Oasis.  

### Action Items

- [x] Review [figma](https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/Fola-Design-System)
- [x] Review [website ](foodoasis.la)
- [x] [Logo folder](https://drive.google.com/drive/u/0/folders/1FfnmTzjk3JETqVQxAhgrKW-nJ4v6_ikR) for comparison 
- [x] Create document style guide

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.

**Comment by ashley-ya** [comment]
Audit current style guide and see if anything needs to be updated

**Comment by ashley-ya** [comment]
Created new page for updated design guide with more context

**Comment by ashley-ya** [comment]
Start on color, type, logo first for handoff to UCLA students

**Comment by ashley-ya** [comment]
Draft of a style guide for external teams: https://docs.google.com/document/d/1hvDP6XI8I7Y0-HEdWLZ3H0tAzi-V_5fsT_aflCfUhxE/edit

**Comment by ashley-ya** [comment]
Left comments on the V2 guide for more clarity

**Comment by ashley-ya** [comment]
almost done with the v2 of the design system: https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/Fola-Design-System?node-id=3046%3A7826

Updated the colors, font, and logos to the live versions on the site. Separated the live and proposed components with the plan of implementing the proposed components as we build new features on the site.

**Comment by fancyham** [comment]
The style guide is in the Figma Document on sheet: "style guide audit v2"
https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/Fola-Design-System?node-id=3046%3A7826

"Current System from 5/18/21" shows elements that are in use today on the public-facing part of the site.

"In Progress" section shows ideas with thinking-in-progress and proposed for the future.

We are using Material UI, and have created a theme within that.
