### ISSUE TITLE
Organizations Interviews

### ISSUE THREAD

**Issue by erigilg** [hackforla/food-oasis#963]
### Overview
In order to understand how we can better help the organizations for assuring their information is updated, we need to work on a draft of interview questions and then go interview the organizations (food pantries, meal plans, etc.)

### Action Items

- [x] Call with Jordan to get to know insights from organization side.
- [x] Draft list of questions 
- [x] Get feedback and comments on the draft 
- [ ] Get final review 
- [ ] Make the interviews 

### Resources/Instructions
Notes on [conversation with Jordan](https://docs.google.com/document/d/1V_AQVQdaSe7dSX6edA_bPfqOIpJ_ZjZFiTaSdBeJ1EQ/edit)
Interview [draft](https://docs.google.com/document/d/1A0Ux4eeB2AA9HyaWBqdKWnatKc1u6TvkOEyIwSTkMrs/edit#heading=h.gjdgxs)

**Comment by ktjnyc** [comment]
@erigilg heres a link to an earlier [conversation with Jordan](https://docs.google.com/document/d/1s15-xkos4LM175a4CjIEr8ZUageov1hqjr1MkarjYtQ/edit?usp=sharing) that might be helpful to review

**Comment by erigilg** [comment]
I've added the draft to the issue, here's the link again. I don't want to move forward with the script without being in line with the goal of the interview. https://docs.google.com/document/d/1A0Ux4eeB2AA9HyaWBqdKWnatKc1u6TvkOEyIwSTkMrs/edit#heading=h.gjdgxs

**Comment by gigicobos** [comment]
Update: requesting access to documents.

**Comment by itserindean** [comment]
Could this be moved to in progress?

**Comment by staceyrebekahscott** [comment]
This issue is outdated, links go to old Drive/ Access Denied message. It may pertain to work being done as part of the Impact Sprints, as figuring out ways to make it easier for orgs to update their own listings has been discussed. Will create a new issue with Impact Sprints label to address this if that objective is going to be addressed.
