### ISSUE TITLE
Food Seekers Interviews 

### ISSUE THREAD

**Issue by erigilg** [hackforla/food-oasis#964]
### Overview
In order to add the most value possible to the food seekers we are looking to make some user interviews with the food seekers to understand what their bigger pain points are. With that information we can make changes to the product to move closer towards product market fit. 

### Action Items

- [x] Create an interview script draft 
- [x] Get comments and feedback from other team members
- [ ] Get a final review from expert in the topic 
- [ ] Determine a plan on how to get food seekers for interviews 
- [ ] Do the interviews 

REPLACE THIS TEXT -If the issue has already been researched, and the course of action is clear, this will describe the steps.  However, if the steps can be divided into tasks for more than one person, we recommend dividing it up into separate issues, or assigning it as a pair programming task.

### Resources/Instructions
[Interview script ](https://docs.google.com/document/d/1WSwMkDPtYXxCMKFKnpYT_bn2GWTIuQ6a/edit#heading=h.gjdgxs)

**Comment by staceyrebekahscott** [comment]
Moving to Icebox. This could be part of Impact Sprints long term goals, and may have a connection to work with Partners.

**Comment by staceyrebekahscott** [comment]
Reprioritizing this issue, as I would like us to start organizing to engage with users for research. May need to rewrite issue as was written in April 2021.

**Comment by GigiUxR** [comment]
This issue is too broad -- an epic?   A related issue with a more narrow scope is the multi language research that is in progress.  And there will be a lot more food seeker research coming along -- perhaps we can continue to attach all of our seeker related research to this epic?

**Comment by itserindean** [comment]
I open to whatever makes the most sense to the researchers re: tracking these. LInking all foodsedeker research to these could be useful for tracking/finding related issues moving forward.d

**Comment by staceyrebekahscott** [comment]
Closing this issue as not planned. Issue #1441 Gather demographics on our food seekers is more relevant to the current state of the project. Note that the link in the Overview is Access Denied.
