### ISSUE TITLE
Bug: Suggestion feature is broken.

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#969]
### Overview
When using the Suggest a new listing or the Send correction feature, you get the below error toast after submitting your suggestion (in production).

### Action Items
- [ ] Fix

### Resources/Instructions
![image](https://user-images.githubusercontent.com/9939032/116119826-b3a02980-a673-11eb-9dbc-890629da8d2a.png)

**Comment by itserindean** [comment]
This is happening again at least as of 1/27/23

**Comment by qiqicodes** [comment]
- Closing this issue, see issue #2064
