### ISSUE TITLE
Bug: Deep linking on the Map Page is broken

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#989]
### Overview
When an organization is selected by clicking on a map pin or selecting it from the results list, the URL changes to indicate the selected organization, e.g. https://foodoasis.la/organizations?org=blood_of_jesus_prayer_and_deliverance_ministry  The intent is that a user could copy that url and sned it to someone else, who could then past the url into the browser and display that organization in the app. However, this does not work now, because the original implementation only partially worked and the code to navigage to the specific organization is commented out.

### Action Items
- [ ] To do this right, the SearchResults component may need to run an initial query to locate the specific organization by name, set the center of the map to that organization and then run the query for the area displayed on the map. It's probably not necessary to set the same zoom level as the original page.

**Comment by fancyham** [comment]
I tried a bunch and it seems okay to me — didn’t do exhaustive testing though

**Comment by sei1122** [comment]
looks good.

**Comment by ryu-jieun** [comment]
Looks good

**Comment by fancyham** [comment]
Yes - it works!  The URL given in the issue description won't work but the new deep link URL does seem to work.

The final deep link URL is something like this:
https://foodoasis.la/organizations?latitude=34.0470527045858&longitude=-118.241670138212&org=little_tokyo_towers&id=4877

Someday, it would be nice to specify an org name query in the URL, but I believe that currently, the most important piece of the URL is the lat/long and id.  The 'org' parameter seems to be optional.
