### ISSUE TITLE
Separate User location from map center.

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#995]
### Overview
Currently, the application considers the current map center as the "users location", which is true when the map is first rendered. However, if the user scrolls or pans the map, and uses the "Search this Location" button, the map center moves, and the application considers the center of the map to be the user's location for puposes of getting directions or displaying the distance to each organization (which affects the sort order of the results list). We really should allow the user's location for directions, distance and sorting purposes to be retained, even when it does not correspond to the map centerpoint.

**Comment by fancyham** [comment]
Related to:
- #926
- #929

**Comment by fancyham** [comment]
This issue may be fixed as the devs are considering loading all the pins at once into the map, which means the ‘search this area’ button may go away

But currently (2023-10), hitting the ‘search this area’ changes the user’s ‘pin’, which works differently from other map apps, and may therefore be confusing to our users.

**Comment by ExperimentsInHonesty** [comment]
Closing this as unplanned because we don't currently have the "search this area" function  We will create a new issue for that.
